"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import ContextPanel from "./context-panel";
type Conversation={id:string;title:string};type Message={id?:string;role:"user"|"assistant";content:string};const actions=["Explain","Summarize","Make quiz","Make flashcards"];

export default function AiAssistant(){
 const[prompt,setPrompt]=useState(""),[context,setContext]=useState(""),[output,setOutput]=useState(""),[loading,setLoading]=useState(false),[conversationId,setConversationId]=useState<string|undefined>(),[conversations,setConversations]=useState<Conversation[]>([]),[history,setHistory]=useState<Message[]>([]),[error,setError]=useState(""),[editing,setEditing]=useState(false),[title,setTitle]=useState("");
 const handleContext=useCallback((v:string)=>setContext(v),[]);
 const loadConversations=useCallback(async()=>{const r=await fetch("/api/ai/conversations");if(r.ok){const d=await r.json();setConversations(d.data||[])}},[]);
 useEffect(()=>{loadConversations().catch(()=>setError("Could not load conversation history."))},[loadConversations]);
 async function openConversation(id:string){if(!id){newChat();return}setError("");const r=await fetch(`/api/ai/conversations/${id}`);if(!r.ok){setError("Could not open that conversation.");return}const d=await r.json();setConversationId(id);setTitle(d.conversation.title);setHistory(d.messages||[]);setOutput("")}
 async function submit(e:FormEvent){e.preventDefault();if(!prompt.trim()||loading)return;const text=prompt.trim();setLoading(true);setOutput("");setError("");try{const r=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:text,context,conversationId})});const d=await r.json();if(!r.ok)throw Error(d.error||"Something went wrong.");setConversationId(d.conversationId);setTitle(t=>t||text.slice(0,60));setHistory(h=>[...h,{role:"user",content:text},{role:"assistant",content:d.answer}]);if(!conversationId)await loadConversations();setPrompt("")}catch(err){setError(err instanceof Error?err.message:"Could not reach the AI service.")}finally{setLoading(false)}}
 function useAction(a:string){setPrompt(`${a}: `)}
 function newChat(){setConversationId(undefined);setHistory([]);setOutput("");setTitle("");setError("")}
 async function rename(){if(!conversationId||!title.trim())return;const r=await fetch(`/api/ai/conversations/${conversationId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:title.trim()})});if(r.ok){setEditing(false);await loadConversations()}else setError("Could not rename conversation.")}
 async function remove(){if(!conversationId)return;const r=await fetch(`/api/ai/conversations/${conversationId}`,{method:"DELETE"});if(r.ok){newChat();await loadConversations()}else setError("Could not delete conversation.")}
 return <div className="max-w-3xl">
  <ContextPanel onContextChange={handleContext}/>
  <div className="mt-5 flex flex-wrap gap-2">{actions.map(a=><button key={a} onClick={()=>useAction(a)} className="rounded-xl border border-slate-800 px-4 py-2 text-sm text-slate-400 hover:text-white">{a}</button>)}<button onClick={newChat} className="rounded-xl border border-slate-700 px-4 py-2 text-sm">New chat</button></div>
  {conversations.length>0&&<div className="mt-4 flex gap-2"><select value={conversationId||""} onChange={e=>openConversation(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-sm"><option value="">Conversation history</option>{conversations.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select>{conversationId&&<><button onClick={()=>setEditing(true)} className="rounded-xl border border-slate-700 px-3 text-sm">Rename</button><button onClick={remove} className="rounded-xl border border-red-900/60 px-3 text-sm text-red-300">Delete</button></>}</div>}
  {editing&&<div className="mt-3 flex gap-2"><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={80} className="min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-950 px-4 py-2 text-sm"/><button onClick={rename} className="rounded-xl bg-white px-4 py-2 text-sm font-semibold text-slate-950">Save</button><button onClick={()=>setEditing(false)} className="rounded-xl border border-slate-700 px-4">Cancel</button></div>}
  {error&&<div className="mt-4 rounded-xl border border-red-900/60 bg-red-950/20 p-4 text-sm text-red-300">{error}</div>}
  <div className="mt-5 space-y-3">{history.length===0&&!loading&&<div className="rounded-2xl border border-dashed border-slate-800 p-8 text-center text-sm text-slate-500">Ask a question to start a conversation.</div>}{history.map((m,i)=><div key={m.id||i} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><p className="text-xs uppercase tracking-widest text-slate-500">{m.role}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-300">{m.content}</p></div>)}{loading&&<div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5 text-sm text-slate-500">Thinking…</div>}</div>
  <form onSubmit={submit} className="mt-5 rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={6} maxLength={4000} placeholder="Ask the AI about your study material..." className="w-full resize-none bg-transparent text-sm leading-6 outline-none"/><div className="mt-4 flex items-center justify-between gap-3"><span className="text-xs text-slate-600">{context?"Saved study material attached":"No notes selected"} · {prompt.length}/4000</span><button disabled={loading||!prompt.trim()} className="rounded-xl bg-white px-5 py-3 text-sm font-semibold text-slate-950 disabled:opacity-30">{loading?"Thinking...":"Ask AI"}</button></div></form>{output&&<section className="mt-5 rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><div className="whitespace-pre-wrap text-sm leading-7 text-slate-300">{output}</div></section>}
 </div>
}
