(()=>{
const AKEY='daily-checklist:advanced:v2';
let adv=(()=>{try{return JSON.parse(localStorage.getItem(AKEY))||{plans:[],snapshots:[],settings:{}}}catch{return{plans:[],snapshots:[],settings:{}}}})();
const saveA=()=>localStorage.setItem(AKEY,JSON.stringify(adv));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const data=()=>window.state||{};
const items=()=>data().lists?.flatMap(l=>l.items||[])||[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const modal=html=>window.openModal(html);
const close=()=>document.querySelector('#modal').classList.add('hidden');
function pct(){const a=items(),d=a.filter(i=>i.done).length;return a.length?Math.round(d/a.length*100):0}
function streak(){const h=data().history||{},keys=Object.keys(h).sort().reverse();let n=0;for(const k of keys){const diff=Math.floor((Date.now()-new Date(k+'T12:00:00'))/86400000);if(diff===n)n++;else if(diff>n)break}return n}
function insight(){const a=items(),done=a.filter(i=>i.done).length,over=a.filter(i=>i.due&&i.due<new Date().toLocaleDateString('en-CA')&&!i.done).length,steps=a.flatMap(i=>i.subtasks||[]),stepDone=steps.filter(s=>s.done).length,h=data().history||{},days=Object.keys(h).sort().slice(-21);modal(`<h2>Checklist Intelligence</h2><p class="muted">Private, deterministic analytics calculated only from local data.</p><div class="insight-grid"><div class="stat"><strong>${pct()}%</strong><span>completion</span></div><div class="stat"><strong>${streak()}</strong><span>active-day streak</span></div><div class="stat"><strong>${over}</strong><span>overdue</span></div><div class="stat"><strong>${stepDone}/${steps.length||0}</strong><span>sub-steps complete</span></div></div><h3>Activity</h3><div class="heatmap">${days.map(k=>`<span title="${k}: ${h[k]||0} checks" class="heat ${h[k]?'on':''}">${new Date(k+'T12:00:00').getDate()}</span>`).join('')||'<span class="muted">No activity yet.</span>'}</div><h3>Guidance</h3><ul><li>${over?'Review overdue items and reschedule anything that is still relevant.':'Your due queue is clear.'}</li><li>${a.length-done?`${a.length-done} open items remain.`:'Everything currently listed is complete.'}</li><li>${steps.length?`${steps.length} sub-steps make larger items easier to execute.`:'Use sub-steps when a checklist item contains several actions.'}</li></ul>`)}
function planManager(){modal(`<h2>Reusable plans</h2><p class="muted">Repeatable checklist blueprints keep recurring processes consistent.</p><div class="form"><label>Plan name<input id="planName" placeholder="e.g. School morning"></label><label>Repeat<select id="planFreq"><option value="daily">Daily</option><option value="weekdays">Weekdays</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label>Items<textarea id="planItems" rows="5" placeholder="One item per line"></textarea></label><button class="primary" onclick="savePlan()">Save plan</button></div><hr><div class="stack">${adv.plans.length?adv.plans.map(p=>`<div class="stat"><strong>${esc(p.name)}</strong><span>${esc(p.freq)} · ${p.items.length} items</span><div><button class="mini" onclick="runPlan('${p.id}')">Run now</button><button class="mini danger" onclick="deletePlan('${p.id}')">Delete</button></div></div>`).join(''):'<p class="muted">No saved plans yet.</p>'}</div>`)}
function savePlan(){const name=document.querySelector('#planName').value.trim(),list=(document.querySelector('#planItems').value||'').split('\n').map(x=>x.trim()).filter(Boolean),freq=document.querySelector('#planFreq').value;if(!name||!list.length)return;adv.plans.push({id:uid(),name,freq,items:list,created:new Date().toISOString()});saveA();planManager()}
function runPlan(pid){const p=adv.plans.find(x=>x.id===pid);if(!p)return;data().lists.push({id:uid(),name:p.name,items:p.items.map(text=>({id:uid(),text,done:false,priority:3,tags:[],subtasks:[]}))});localStorage.setItem('daily-checklist:v2',JSON.stringify(data()));close();location.reload()}
function deletePlan(pid){adv.plans=adv.plans.filter(p=>p.id!==pid);saveA();planManager()}
function snapshot(){adv.snapshots.unshift({id:uid(),at:new Date().toISOString(),data:JSON.parse(JSON.stringify(data()))});adv.snapshots=adv.snapshots.slice(0,12);saveA();alert('Restore point saved locally.')}
function restoreManager(){modal(`<h2>Restore points</h2><p class="muted">Snapshots stay in this browser.</p>${adv.snapshots.length?adv.snapshots.map(s=>`<div class="stat"><strong>${new Date(s.at).toLocaleString()}</strong><span>${s.data.lists?.length||0} checklists</span><button class="mini" onclick="restorePoint('${s.id}')">Restore</button></div>`).join(''):'<p class="muted">No restore points yet.</p>'}`)}
function restorePoint(id){const s=adv.snapshots.find(x=>x.id===id);if(s&&confirm('Restore this local snapshot?')){localStorage.setItem('daily-checklist:v2',JSON.stringify(s.data));location.reload()}}
function cell(v){return `"${String(v??'').replace(/"/g,'""')}"`}
function exportCSV(){const rows=['Checklist,Item,Completed,Priority,Due,Repeat,Tags,Note'];data().lists.forEach(l=>(l.items||[]).forEach(i=>rows.push([l.name,i.text,i.done?'yes':'no',i.priority||3,i.due||'',i.repeat||'',(i.tags||[]).join('; '),i.note||''].map(cell).join(','))));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));a.download='daily-checklist.csv';a.click()}
function fullExport(){const payload={version:2,exportedAt:new Date().toISOString(),core:data(),advanced:adv};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='daily-checklist-complete-backup.json';a.click()}
function advancedSettings(){modal(`<h2>Daily Checklist tools</h2><div class="form"><button class="secondary" onclick="insight()">Checklist Intelligence</button><button class="secondary" onclick="planManager()">Reusable plans</button><button class="secondary" onclick="snapshot()">Save restore point</button><button class="secondary" onclick="restoreManager()">Restore points</button><button class="secondary" onclick="exportCSV()">Export CSV</button><button class="secondary" onclick="fullExport()">Complete JSON backup</button><button class="secondary" onclick="basicSettings()">Basic settings</button></div>`)}
const oldSettings=window.settings;const basicSettings=()=>oldSettings();window.settings=advancedSettings;
const btn=document.createElement('button');btn.className='secondary';btn.textContent='Insights';btn.onclick=insight;document.querySelector('.controlbar').appendChild(btn);
window.planManager=planManager;window.savePlan=savePlan;window.runPlan=runPlan;window.deletePlan=deletePlan;window.snapshot=snapshot;window.restoreManager=restoreManager;window.restorePoint=restorePoint;window.exportCSV=exportCSV;window.fullExport=fullExport;window.insight=insight;window.basicSettings=basicSettings;saveA();
})();