(()=>{
const AKEY='daily-checklist:advanced:v1';
let adv=(()=>{try{return JSON.parse(localStorage.getItem(AKEY))||{plans:[],snapshots:[],settings:{autoReset:true}}}catch{return{plans:[],snapshots:[],settings:{autoReset:true}}}})();
function asave(){localStorage.setItem(AKEY,JSON.stringify(adv))}
function advId(){return Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function data(){try{return JSON.parse(localStorage.getItem('daily-checklist:v1'))||{lists:[]}}catch{return{lists:[]}}}
function openA(html){document.querySelector('#modalBody').innerHTML=html;document.querySelector('#modal').classList.remove('hidden')}
function intelligence(){const d=data(),items=d.lists.flatMap(l=>l.items||[]),done=items.filter(i=>i.done).length;const incomplete=items.length-done;openA(`<h2>Checklist Intelligence</h2><p class="muted">Private, deterministic insights based only on your local checklist history.</p><div class="insight-grid"><div class="stat"><strong>${items.length}</strong><span>current items</span></div><div class="stat"><strong>${done}</strong><span>completed</span></div><div class="stat"><strong>${incomplete}</strong><span>remaining</span></div></div><hr><h3>Useful actions</h3><ul><li>Turn repeated lists into reusable plans.</li><li>Keep recurring checklists short enough to finish consistently.</li><li>Use templates for processes you repeat instead of recreating items.</li></ul><button class="primary" onclick="planManager()">Manage recurring plans</button>`)}
function planManager(){openA(`<h2>Reusable plans</h2><p class="muted">Save a checklist as a repeatable plan. The app keeps your plan definition separate from today's completion state.</p><div class="form"><label>Plan name<input id="planName" placeholder="e.g. School day"></label><label>Repeat<select id="planFreq"><option value="daily">Daily</option><option value="weekdays">Weekdays</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label>Items<textarea id="planItems" rows="5" placeholder="One item per line"></textarea></label><button class="primary" onclick="savePlan()">Save plan</button></div><hr><div>${adv.plans.length?adv.plans.map(p=>`<div class="stat"><strong>${escA(p.name)}</strong><span>${p.freq} · ${p.items.length} items</span><button class="mini" onclick="runPlan('${p.id}')">Run today</button><button class="mini" onclick="deletePlan('${p.id}')">Delete</button></div>`).join(''):'<p class="muted">No saved plans yet.</p>'}</div>`)}
function savePlan(){const name=document.querySelector('#planName').value.trim(),items=document.querySelector('#planItems').value.split('\n').map(x=>x.trim()).filter(Boolean),freq=document.querySelector('#planFreq').value;if(!name||!items.length)return;adv.plans.push({id:advId(),name,freq,items,created:new Date().toISOString()});asave();planManager()}
function runPlan(pid){const p=adv.plans.find(x=>x.id===pid),d=data();d.lists.push({id:advId(),name:p.name,items:p.items.map(text=>({id:advId(),text,done:false,note:''}))});localStorage.setItem('daily-checklist:v1',JSON.stringify(d));document.querySelector('#modal').classList.add('hidden');location.reload()}
function deletePlan(pid){adv.plans=adv.plans.filter(x=>x.id!==pid);asave();planManager()}
function snapshot(){const d=data();adv.snapshots.unshift({id:advId(),at:new Date().toISOString(),data:d});adv.snapshots=adv.snapshots.slice(0,8);asave();alert('Local restore point saved.')}
function restoreManager(){openA(`<h2>Restore points</h2>${adv.snapshots.length?adv.snapshots.map(s=>`<div class="stat"><strong>${new Date(s.at).toLocaleString()}</strong><span>Local snapshot</span><button class="mini" onclick="restorePoint('${s.id}')">Restore</button></div>`).join(''):'<p class="muted">No restore points yet.</p>'}`)}
function restorePoint(id){const s=adv.snapshots.find(x=>x.id===id);if(s&&confirm('Restore this local snapshot?')){localStorage.setItem('daily-checklist:v1',JSON.stringify(s.data));location.reload()}}
function exportCSV(){const d=data(),rows=['Checklist,Item,Completed'];d.lists.forEach(l=>(l.items||[]).forEach(i=>rows.push(`"${csv(l.name)}","${csv(i.text)}",${i.done?'yes':'no'}`)));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));a.download='daily-checklist.csv';a.click()}
function csv(s){return String(s).replace(/"/g,'""')}function escA(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
const oldSettings=window.settings;window.settings=()=>{openA(`<h2>Advanced settings</h2><div class="form"><button class="secondary" onclick="snapshot()">Save restore point</button><button class="secondary" onclick="restoreManager()">Restore points</button><button class="secondary" onclick="exportCSV()">Export CSV</button><button class="secondary" onclick="planManager()">Reusable plans</button><button class="secondary" onclick="intelligence()">Checklist intelligence</button><button class="secondary" onclick="oldSettings()">Basic settings</button></div>`)};
const btn=document.createElement('button');btn.className='secondary';btn.textContent='Insights';btn.onclick=intelligence;document.querySelector('.toolbar').appendChild(btn);
window.planManager=planManager;window.savePlan=savePlan;window.runPlan=runPlan;window.deletePlan=deletePlan;window.snapshot=snapshot;window.restoreManager=restoreManager;window.restorePoint=restorePoint;window.exportCSV=exportCSV;window.intelligence=intelligence;asave();
})();