const KEY='daily-checklist:v2';
const seed={lists:[{id:'daily',name:'Daily essentials',color:'',items:[{id:'i1',text:'Review today’s priorities',done:false,priority:2},{id:'i2',text:'Drink water',done:false,priority:3},{id:'i3',text:'Check important messages',done:false,priority:3},{id:'i4',text:'Plan tomorrow before finishing',done:false,priority:2}]},{id:'personal',name:'Personal',color:'',items:[]}],active:'daily',history:{},activity:[],settings:{theme:'system',defaultPriority:3,showCompleted:true,notifications:false}};
let state=load(),filter='today',query='',sort='manual',selected=new Set(),undoStack=[];
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{const raw=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('daily-checklist:v1')||'null');if(!raw)return clone(seed);const s={...clone(seed),...raw,lists:(raw.lists||[]).map(l=>({...l,items:(l.items||[]).map(normalize)}))};s.settings={...seed.settings,...(raw.settings||{})};return s}catch{return clone(seed)}}
function normalize(i){return {...i,id:i.id||id(),text:String(i.text||''),done:!!i.done,note:i.note||'',priority:Number(i.priority||3),due:i.due||'',repeat:i.repeat||'',tags:Array.isArray(i.tags)?i.tags:[],subtasks:Array.isArray(i.subtasks)?i.subtasks.map(s=>({...s,id:s.id||id(),text:String(s.text||''),done:!!s.done})):[],created:i.created||new Date().toISOString(),completedAt:i.completedAt||''}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function dateKey(d=new Date()){return new Date(d).toLocaleDateString('en-CA')}
function allItems(){return state.lists.flatMap(l=>l.items.map(i=>({...i,listId:l.id,listName:l.name})))}
function isDue(i){return i.due&&i.due<=dateKey()&&!i.done}
function matches(i){const q=query.toLowerCase();if(q&&!`${i.text} ${i.note} ${(i.tags||[]).join(' ')}`.toLowerCase().includes(q))return false;if(filter==='done')return i.done;if(filter==='due')return isDue(i);if(filter==='today')return !i.done||i.due===dateKey()||!i.due;return true}
function render(){const d=new Date(),items=allItems(),done=items.filter(i=>i.done).length,total=items.length,pct=total?Math.round(done/total*100):0;document.querySelector('#dateLabel').textContent=d.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});document.querySelector('#greeting').textContent=d.getHours()<12?'Good morning':d.getHours()<18?'Good afternoon':'Good evening';document.querySelector('#percent').textContent=pct+'%';document.querySelector('#ring').style.setProperty('--progress',pct*3.6+'deg');const overdue=items.filter(isDue).length;document.querySelector('#summary').textContent=overdue?`${done} of ${total} complete · ${overdue} due`:`${done} of ${total} items complete`;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));const lists=document.querySelector('#lists');lists.innerHTML='';let shown=0;state.lists.forEach(list=>{let its=list.items.filter(matches);if(sort==='priority')its.sort((a,b)=>(a.priority||3)-(b.priority||3));if(sort==='due')its.sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'));if(sort==='name')its.sort((a,b)=>a.text.localeCompare(b.text));if(!its.length)return;shown++;const el=document.createElement('section');el.className='list';el.innerHTML=`<div class="list-head"><div><div class="list-title">${esc(list.name)}</div><div class="list-meta">${list.items.filter(i=>i.done).length}/${list.items.length} complete</div></div><div class="list-actions"><button class="mini" onclick="addToList('${list.id}')">+ Item</button><button class="mini" onclick="renameList('${list.id}')">Rename</button><button class="mini" onclick="deleteList('${list.id}')">Delete</button></div></div><div class="items">${its.map(i=>itemHTML(list,i)).join('')}</div></section>`;lists.appendChild(el)});if(!shown)lists.innerHTML='<div class="empty"><strong>Nothing here yet.</strong><br><span>Try another filter, clear the search, or add an item.</span></div>';renderInsights();applyTheme();updateBulk()}
function itemHTML(list,i){const subs=i.subtasks||[],subDone=subs.filter(s=>s.done).length,pri=['','P1','P2','P3','P4'][i.priority||3];return `<div class="item ${i.done?'done':''} ${isDue(i)?'overdue':''}"><input class="select" type="checkbox" ${selected.has(i.id)?'checked':''} onchange="selectItem('${i.id}',this.checked)"><button class="check ${i.done?'done':''}" onclick="toggle('${list.id}','${i.id}')">${i.done?'✓':''}</button><div class="item-text"><div>${esc(i.text)} ${pri!=='P3'?`<span class="priority p${i.priority}">${pri}</span>`:''}</div><div class="meta-row">${i.due?`<span>Due ${esc(i.due)}</span>`:''}${i.repeat?`<span>↻ ${esc(i.repeat)}</span>`:''}${i.tags?.length?`<span>#${esc(i.tags.join(' #'))}</span>`:''}${subs.length?`<span>${subDone}/${subs.length} steps</span>`:''}</div>${i.note?`<div class="item-note">${esc(i.note)}</div>`:''}</div><div class="item-actions"><button class="mini" onclick="editItem('${list.id}','${i.id}')">Edit</button><button class="mini" onclick="removeItem('${list.id}','${i.id}')">×</button></div></div>`}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toggle(lid,iid){const i=find(lid,iid);if(!i)return;undoStack.push(clone(state));i.done=!i.done;i.completedAt=i.done?new Date().toISOString():'';if(i.done){const k=dateKey();state.history[k]=(state.history[k]||0)+1;activity('completed',i)}else activity('reopened',i);if(i.done&&i.repeat){const l=state.lists.find(x=>x.id===lid);l.items.push({...clone(i),id:id(),done:false,completedAt:'',due:nextDue(i.repeat,i.due||dateKey())})}save()}
function nextDue(rule,from){const d=new Date((from||dateKey())+'T12:00:00');if(rule==='daily')d.setDate(d.getDate()+1);else if(rule==='weekdays'){do d.setDate(d.getDate()+1);while(d.getDay()===0||d.getDay()===6)}else if(rule==='weekly')d.setDate(d.getDate()+7);else if(rule==='monthly')d.setMonth(d.getMonth()+1);else return '';return dateKey(d)}
function find(lid,iid){const l=state.lists.find(x=>x.id===lid);return l?.items.find(x=>x.id===iid)}
function add(text,listId=state.active,opts={}){if(!text.trim())return;const l=state.lists.find(x=>x.id===listId)||state.lists[0];l.items.push(normalize({id:id(),text:text.trim(),done:false,priority:Number(opts.priority||state.settings.defaultPriority||3),created:new Date().toISOString(),...opts}));activity('added',{text:text.trim()});save()}
function addToList(lid){const text=prompt('Checklist item');if(text)add(text,lid)}
function removeItem(lid,iid){const l=state.lists.find(x=>x.id===lid);if(!l)return;undoStack.push(clone(state));l.items=l.items.filter(i=>i.id!==iid);selected.delete(iid);activity('deleted',{id:iid});save()}
function editItem(lid,iid){const i=find(lid,iid);if(!i)return;openModal(`<h2>Edit item</h2><div class="form"><label>Item<input id="editText" value="${esc(i.text)}"></label><div class="form-grid"><label>Priority<select id="editPriority"><option value="1" ${i.priority===1?'selected':''}>P1 — High</option><option value="2" ${i.priority===2?'selected':''}>P2</option><option value="3" ${i.priority===3?'selected':''}>P3 — Normal</option><option value="4" ${i.priority===4?'selected':''}>P4 — Low</option></select></label><label>Due date<input id="editDue" type="date" value="${esc(i.due)}"></label></div><label>Repeat<select id="editRepeat"><option value="">No repeat</option><option value="daily" ${i.repeat==='daily'?'selected':''}>Daily</option><option value="weekdays" ${i.repeat==='weekdays'?'selected':''}>Weekdays</option><option value="weekly" ${i.repeat==='weekly'?'selected':''}>Weekly</option><option value="monthly" ${i.repeat==='monthly'?'selected':''}>Monthly</option></select></label><label>Tags<input id="editTags" value="${esc((i.tags||[]).join(', '))}" placeholder="school, health, personal"></label><label>Note<textarea id="editNote">${esc(i.note||'')}</textarea></label><label>Steps<textarea id="editSubs" rows="4" placeholder="One step per line">${esc((i.subtasks||[]).map(s=>(s.done?'[x] ':'')+s.text).join('\n'))}</textarea></label><button class="primary" onclick="saveItem('${lid}','${iid}')">Save item</button></div>`)}
function saveItem(lid,iid){const i=find(lid,iid);if(!i)return;i.text=document.querySelector('#editText').value.trim()||i.text;i.priority=Number(document.querySelector('#editPriority').value);i.due=document.querySelector('#editDue').value;i.repeat=document.querySelector('#editRepeat').value;i.tags=document.querySelector('#editTags').value.split(',').map(x=>x.trim()).filter(Boolean);i.note=document.querySelector('#editNote').value.trim();i.subtasks=document.querySelector('#editSubs').value.split('\n').map(x=>x.trim()).filter(Boolean).map((x,n)=>({id:i.subtasks[n]?.id||id(),text:x.replace(/^\[x\]\s*/i,''),done:/^\[x\]/i.test(x)||!!i.subtasks[n]?.done}));closeModal();save()}
function renameList(lid){const l=state.lists.find(x=>x.id===lid),name=prompt('Checklist name',l.name);if(name?.trim()){l.name=name.trim();save()}}
function deleteList(lid){if(state.lists.length===1)return alert('Keep at least one checklist.');if(confirm('Delete this checklist and its items?')){state.lists=state.lists.filter(x=>x.id!==lid);if(state.active===lid)state.active=state.lists[0].id;save()}}
function newList(){openModal('<h2>New checklist</h2><div class="form"><label>Name<input id="listName" placeholder="e.g. School morning"></label><label>Color<select id="listColor"><option value="">Default</option><option value="blue">Blue</option><option value="green">Green</option><option value="purple">Purple</option></select></label><button class="primary" onclick="createList()">Create</button></div>')}
function createList(){const n=document.querySelector('#listName').value.trim();if(!n)return;state.lists.push({id:id(),name:n,color:document.querySelector('#listColor').value,items:[]});state.active=state.lists.at(-1).id;closeModal();save()}
function openModal(html){document.querySelector('#modalBody').innerHTML=html;document.querySelector('#modal').classList.remove('hidden')}
function closeModal(){document.querySelector('#modal').classList.add('hidden')}
function templates(){const t=[['Morning start',['Get ready','Drink water','Review priorities','Start first important task']],['Evening reset',['Clear workspace','Review completed items','Prepare for tomorrow','Wind down']],['Study session',['Open materials','Choose one focus topic','Study in a focused block','Write a short recap']],['Leaving home',['Keys','Phone','Wallet','Bag','Final door check']],['Room reset',['Put things away','Clear desk','Take out trash','Prepare tomorrow']]];openModal('<h2>Checklist templates</h2><p class="muted">Reusable starting points for common routines and processes.</p><div class="template-grid">'+t.map(x=>`<button class="template" onclick='useTemplate(${JSON.stringify(x[1])})'><strong>${x[0]}</strong><br><span class="muted">${x[1].length} items</span></button>`).join('')+'</div>')}
function useTemplate(items){const n=prompt('Checklist name','My checklist');if(!n)return;state.lists.push({id:id(),name:n,items:items.map(text=>normalize({id:id(),text,done:false,priority:3}))});closeModal();save()}
function selectItem(iid,on){if(on)selected.add(iid);else selected.delete(iid);updateBulk()}
function updateBulk(){const b=document.querySelector('#bulkbar');b.classList.toggle('hidden',selected.size===0);document.querySelector('#selectedCount').textContent=`${selected.size} selected`}
function bulkDone(v){state.lists.forEach(l=>l.items.forEach(i=>{if(selected.has(i.id))i.done=v}));selected.clear();save()}
function bulkDelete(){if(!confirm('Delete selected items?'))return;state.lists.forEach(l=>l.items=l.items.filter(i=>!selected.has(i.id)));selected.clear();save()}
function activity(type,item){state.activity=(state.activity||[]).slice(-499);state.activity.push({at:new Date().toISOString(),type,text:item?.text||''})}
function renderInsights(){const items=allItems(),done=items.filter(i=>i.done).length,overdue=items.filter(isDue).length,history=state.history||{},days=Object.keys(history).length,last7=Object.entries(history).filter(([k])=>{const d=new Date(k+'T12:00:00');return (Date.now()-d)/86400000<7}).reduce((a,[,v])=>a+v,0);document.querySelector('#insights').innerHTML=`<div class="insight-grid"><div class="stat"><strong>${done}/${items.length}</strong><span>completed</span></div><div class="stat"><strong>${last7}</strong><span>checks in 7 days</span></div><div class="stat"><strong>${overdue}</strong><span>overdue</span></div><div class="stat"><strong>${days}</strong><span>active days</span></div></div>`}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='daily-checklist-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importData(){const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=()=>{const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.lists))throw Error();state={...clone(seed),...x,lists:x.lists.map(l=>({...l,items:(l.items||[]).map(normalize)}))};save();alert('Backup imported.')}catch{alert('That file is not a valid Daily Checklist backup.')}};r.readAsText(input.files[0])};input.click()}
function settings(){openModal(`<h2>Settings</h2><div class="form"><button class="secondary" onclick="exportData()">Export JSON backup</button><button class="secondary" onclick="importData()">Import JSON backup</button><button class="secondary" onclick="requestNotifications()">Enable browser reminders</button><button class="secondary" onclick="clearCompleted()">Clear completed items</button><button class="secondary danger" onclick="resetAll()">Reset all data</button><p class="muted">Local-first and private. Browser notifications work only when permission is granted and the browser supports them.</p></div>`)}
function requestNotifications(){if(!('Notification'in window))return alert('Notifications are not supported in this browser.');Notification.requestPermission().then(p=>{state.settings.notifications=p==='granted';save();alert(p==='granted'?'Browser reminders enabled.':'Notification permission was not granted.')})}
function clearCompleted(){state.lists.forEach(l=>l.items=l.items.filter(i=>!i.done));save();closeModal()}
function resetAll(){if(confirm('Reset all Daily Checklist data?')){state=clone(seed);localStorage.setItem(KEY,JSON.stringify(state));closeModal();render()}}
function applyTheme(){const t=state.settings?.theme||'system';document.body.classList.toggle('dark',t==='dark'||(t==='system'&&matchMedia('(prefers-color-scheme: dark)').matches))}
function cycleTheme(){const t=state.settings?.theme||'system';state.settings.theme=t==='system'?'light':t==='light'?'dark':'system';save()}
function undo(){const previous=undoStack.pop();if(previous){state=previous;save()}}
document.querySelector('#quickAdd').addEventListener('keydown',e=>{if(e.key==='Enter'){add(e.target.value);e.target.value=''}});document.querySelector('#addBtn').onclick=()=>{const e=document.querySelector('#quickAdd');add(e.value);e.value=''};document.querySelector('#newListBtn').onclick=newList;document.querySelector('#templateBtn').onclick=templates;document.querySelector('#settingsBtn').onclick=settings;document.querySelector('#themeBtn').onclick=cycleTheme;document.querySelector('#closeModal').onclick=closeModal;document.querySelector('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});document.querySelector('#search').oninput=e=>{query=e.target.value;render()};document.querySelector('#sort').onchange=e=>{sort=e.target.value;render()};document.querySelector('#bulkDone').onclick=()=>bulkDone(true);document.querySelector('#bulkUndone').onclick=()=>bulkDone(false);document.querySelector('#bulkDelete').onclick=bulkDelete;window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector('#search').focus()}});window.addEventListener('storage',()=>{state=load();render()});window.addEventListener('online',()=>render());if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});window.state=state;window.render=render;window.openModal=openModal;window.closeModal=closeModal;render();