const KEY='daily-checklist:v1';
const seed={lists:[{id:'daily',name:'Daily essentials',color:'',items:[{id:'i1',text:'Review today’s priorities',done:false},{id:'i2',text:'Drink water',done:false},{id:'i3',text:'Check important messages',done:false},{id:'i4',text:'Plan tomorrow before finishing',done:false}]},{id:'personal',name:'Personal',items:[]}],active:'daily',history:{},settings:{theme:'system'}};
let state=load(),filter='today';
function load(){try{return {...seed,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function today(){return new Date().toISOString().slice(0,10)}
function allItems(){return state.lists.flatMap(l=>l.items.map(i=>({...i,listId:l.id,listName:l.name})))}
function visibleItems(){let items=allItems();if(filter==='done')items=items.filter(i=>i.done);return items}
function render(){
 const d=new Date(),date=d.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});document.querySelector('#dateLabel').textContent=date;document.querySelector('#greeting').textContent=d.getHours()<12?'Good morning':d.getHours()<18?'Good afternoon':'Good evening';
 const items=allItems(),done=items.filter(i=>i.done).length,total=items.length,pct=total?Math.round(done/total*100):0;document.querySelector('#percent').textContent=pct+'%';document.querySelector('#ring').style.setProperty('--progress',(pct*3.6)+'deg');document.querySelector('#summary').textContent=total?`${done} of ${total} items complete`:'Add your first item';
 document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));
 const lists=document.querySelector('#lists');lists.innerHTML='';let shown=0;
 state.lists.forEach(list=>{let its=list.items.filter(i=>filter!=='done'||i.done);if(!its.length)return;shown++;const el=document.createElement('section');el.className='list';el.innerHTML=`<div class="list-head"><div><div class="list-title">${esc(list.name)}</div><div class="list-meta">${list.items.filter(i=>i.done).length}/${list.items.length} complete</div></div><div><button class="mini" onclick="renameList('${list.id}')">Rename</button><button class="mini" onclick="deleteList('${list.id}')">Delete</button></div></div><div class="items">${its.map(i=>`<div class="item ${i.done?'done':''}"><button class="check ${i.done?'done':''}" onclick="toggle('${list.id}','${i.id}')">${i.done?'✓':''}</button><div class="item-text">${esc(i.text)}${i.note?`<div class="item-note">${esc(i.note)}</div>`:''}</div><div class="item-actions"><button class="mini" onclick="editItem('${list.id}','${i.id}')">Edit</button><button class="mini" onclick="removeItem('${list.id}','${i.id}')">×</button></div></div>`).join('')}</div>`;lists.appendChild(el)});
 if(!shown)lists.innerHTML='<div class="empty"><strong>Nothing here yet.</strong><br><span>Everything is clear, or this filter has no items.</span></div>';renderInsights();applyTheme();
}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toggle(lid,iid){const l=state.lists.find(x=>x.id===lid),i=l.items.find(x=>x.id===iid);i.done=!i.done;if(i.done){const k=today();state.history[k]=(state.history[k]||0)+1}save()}
function add(text,listId=state.active){if(!text.trim())return;const l=state.lists.find(x=>x.id===listId)||state.lists[0];l.items.push({id:id(),text:text.trim(),done:false,note:''});save()}
function removeItem(lid,iid){const l=state.lists.find(x=>x.id===lid);l.items=l.items.filter(i=>i.id!==iid);save()}
function editItem(lid,iid){const l=state.lists.find(x=>x.id===lid),i=l.items.find(x=>x.id===iid);openModal(`<h2>Edit item</h2><div class="form"><label>Item<input id="editText" value="${esc(i.text)}"></label><label>Note<textarea id="editNote">${esc(i.note||'')}</textarea></label><button class="primary" onclick="saveItem('${lid}','${iid}')">Save</button></div>`)}
function saveItem(lid,iid){const l=state.lists.find(x=>x.id===lid),i=l.items.find(x=>x.id===iid);i.text=document.querySelector('#editText').value.trim()||i.text;i.note=document.querySelector('#editNote').value.trim();closeModal();save()}
function renameList(lid){const l=state.lists.find(x=>x.id===lid),name=prompt('Checklist name',l.name);if(name&&name.trim()){l.name=name.trim();save()}}
function deleteList(lid){if(state.lists.length===1)return alert('Keep at least one checklist.');if(confirm('Delete this checklist and its items?')){state.lists=state.lists.filter(x=>x.id!==lid);if(state.active===lid)state.active=state.lists[0].id;save()}}
function newList(){openModal('<h2>New checklist</h2><div class="form"><label>Name<input id="listName" placeholder="e.g. School morning"></label><button class="primary" onclick="createList()">Create</button></div>')}
function createList(){const n=document.querySelector('#listName').value.trim();if(!n)return;state.lists.push({id:id(),name:n,items:[]});state.active=state.lists.at(-1).id;closeModal();save()}
function openModal(html){document.querySelector('#modalBody').innerHTML=html;document.querySelector('#modal').classList.remove('hidden')}
function closeModal(){document.querySelector('#modal').classList.add('hidden')}
function templates(){const t=[['Morning start',['Get ready','Drink water','Review priorities','Start first important task']],['Evening reset',['Clear workspace','Review completed items','Prepare for tomorrow','Wind down']],['Study session',['Open materials','Choose one focus topic','Study in a focused block','Write a short recap']],['Leaving home',['Keys','Phone','Wallet','Bag','Final door check']]];openModal('<h2>Checklist templates</h2><p class="muted">Start with a reusable set of items.</p><div class="template-grid">'+t.map(x=>`<button class="template" onclick='useTemplate(${JSON.stringify(x[1])})'><strong>${x[0]}</strong><br><span class="muted">${x[1].length} items</span></button>`).join('')+'</div>')}
function useTemplate(items){const n=prompt('Checklist name','My checklist');if(!n)return;state.lists.push({id:id(),name:n,items:items.map(text=>({id:id(),text,done:false,note:''}))});closeModal();save()}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='daily-checklist-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importData(){const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=()=>{const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.lists))throw Error();state=x;save();alert('Backup imported.')}catch{alert('That file is not a valid Daily Checklist backup.')}};r.readAsText(input.files[0])};input.click()}
function settings(){openModal(`<h2>Settings</h2><div class="form"><button class="secondary" onclick="exportData()">Export JSON backup</button><button class="secondary" onclick="importData()">Import JSON backup</button><button class="secondary" onclick="clearCompleted()">Clear completed items</button><button class="secondary danger" onclick="resetAll()">Reset all data</button><p class="muted">Your data is stored locally in this browser. No account or server is required.</p></div>`)}
function clearCompleted(){state.lists.forEach(l=>l.items=l.items.filter(i=>!i.done));closeModal();save()}
function resetAll(){if(confirm('Reset all Daily Checklist data?')){state=structuredClone(seed);closeModal();save()}}
function applyTheme(){const t=state.settings?.theme||'system';document.body.classList.toggle('dark',t==='dark'||(t==='system'&&matchMedia('(prefers-color-scheme: dark)').matches))}
function cycleTheme(){const t=state.settings?.theme||'system';state.settings.theme=t==='system'?'light':t==='light'?'dark':'system';save()}
function renderInsights(){const items=allItems(),done=items.filter(i=>i.done).length,days=Object.keys(state.history||{}).length,week=Object.entries(state.history||{}).slice(-7).reduce((a,[,v])=>a+v,0);document.querySelector('#insights').innerHTML=`<div class="insight-grid"><div class="stat"><strong>${done}</strong><span>completed items</span></div><div class="stat"><strong>${week}</strong><span>checks logged recently</span></div><div class="stat"><strong>${days}</strong><span>active days</span></div></div>`}
document.querySelector('#quickAdd').addEventListener('keydown',e=>{if(e.key==='Enter'){add(e.target.value);e.target.value=''}});document.querySelector('#addBtn').onclick=()=>{const e=document.querySelector('#quickAdd');add(e.value);e.value=''};document.querySelector('#newListBtn').onclick=newList;document.querySelector('#templateBtn').onclick=templates;document.querySelector('#settingsBtn').onclick=settings;document.querySelector('#themeBtn').onclick=cycleTheme;document.querySelector('#closeModal').onclick=closeModal;document.querySelector('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});window.addEventListener('storage',()=>{state=load();render()});render();
