(() => {
'use strict';
const KEY='routinecraft:v1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const iso=d=>{const x=new Date(d);return new Date(x.getTime()-x.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const today=()=>iso(new Date());
const uid=()=>Math.random().toString(36).slice(2,10)+Date.now().toString(36).slice(-4);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaults={theme:'system',weekStart:1,defaultMode:'timer',countdown:3};
const templates=[
 {name:'Morning Reset',area:'Personal',time:'morning',steps:[['Wake & hydrate',5,'Start gently.'],['Wash up',10,'Get ready for the day.'],['Move your body',10,'Stretch or take a short walk.'],['Plan the day',5,'Choose the important few.']]},
 {name:'Study Launch',area:'Study',time:'morning',steps:[['Clear desk',3,'Remove distractions.'],['Review goals',5,'Pick one concrete outcome.'],['Deep work',30,'Focus on one task.'],['Break & reset',5,'Stand up and reset.']]},
 {name:'Evening Wind-down',area:'Personal',time:'evening',steps:[['Tidy the space',10,'Reset your environment.'],['Prepare tomorrow',10,'Pack and plan ahead.'],['Reflect',5,'Write one win and one lesson.'],['Screen-free wind-down',20,'Give your attention room to slow down.']]},
 {name:'Weekly Reset',area:'Home',time:'any',steps:[['Review the week',15,'Notice what worked.'],['Plan priorities',15,'Choose the next week focus.'],['Reset spaces',20,'Restore the basics.']]}
];
function load(){try{const d=JSON.parse(localStorage.getItem(KEY)||'null');if(d&&Array.isArray(d.routines))return {...d,settings:{...defaults,...d.settings}}}catch{}return {routines:[],runs:[],settings:{...defaults}}}
let state=load();let selectedWeek=new Date();let runner=null, timer=null, remaining=0, paused=false;
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function activeRoutines(){return state.routines.filter(r=>!r.archived&&!r.paused)}
function daysFor(r){return r.days?.length?r.days:[1,2,3,4,5,6,0]}
function scheduled(r,date){const d=new Date(date),dow=d.getDay(); if(r.repeat==='weekdays')return dow>=1&&dow<=5;if(r.repeat==='weekends')return dow===0||dow===6;if(r.repeat==='custom')return daysFor(r).includes(dow);if(r.repeat==='weekly')return true;if(r.repeat==='interval'){const start=new Date(r.created||today());start.setHours(0,0,0,0);return Math.floor((d-start)/86400000)%Math.max(2,+r.interval||2)===0}return true}
function weekTarget(r){return r.repeat==='weekly'?Math.max(1,+r.weekly||1):1}
function runsFor(id,from,to){return state.runs.filter(x=>x.routineId===id&&x.date>=from&&x.date<=to)}
function routineRate(r,days=30){const end=new Date(),start=new Date(end);start.setDate(end.getDate()-days+1);let due=0,done=0;for(let i=0;i<days;i++){const d=new Date(start);d.setDate(start.getDate()+i);if(scheduled(r,d)){if(r.repeat==='weekly'){/* weekly quotas below */}else due++;const hit=state.runs.find(x=>x.routineId===r.id&&x.date===iso(d)&&x.status==='done');if(hit)done++}}if(r.repeat==='weekly'){const weeks=Math.max(1,Math.ceil(days/7));due=weeks*weekTarget(r);const first=iso(start),last=iso(end);done=state.runs.filter(x=>x.routineId===r.id&&x.date>=first&&x.date<=last&&x.status==='done').length;return Math.round(Math.min(1,done/due)*100)}return due?Math.round(Math.min(1,done/due)*100):0}
function streak(r){let n=0,d=new Date();for(let i=0;i<365;i++){const key=iso(d);const hit=state.runs.some(x=>x.routineId===r.id&&x.date===key&&x.status==='done');if(hit)n++;else if(scheduled(r,d))break;d.setDate(d.getDate()-1)}return n}
function totalMinutes(r){return r.steps.reduce((a,s)=>a+(+s.minutes||0),0)}
function runForDate(r,date){return state.runs.find(x=>x.routineId===r.id&&x.date===date)}
function statusLabel(r,date=today()){const x=runForDate(r,date);return x?.status||'due'}
function card(r){const rate=routineRate(r),st=streak(r),mins=totalMinutes(r),stt=statusLabel(r);return `<article class="routine-card"><div class="routine-top"><span class="pill">${esc(r.time||'any')}</span><span class="status ${stt}">${stt}</span></div><h3>${esc(r.name)}</h3><p class="muted">${esc(r.area||'General')} · ${r.steps.length} steps · ${mins} min</p><div class="bar"><span style="width:${rate}%"></span></div><div class="routine-meta"><span>${rate}% / 30d</span><span>${st} day streak</span></div><div class="card-actions"><button data-run="${r.id}" class="primary">${stt==='done'?'Run again':'Start'}</button><button data-edit="${r.id}">Edit</button><button data-more="${r.id}" class="ghost">⋯</button></div></article>`}
function render(){renderToday();renderRoutines();renderPlanner();renderInsights();renderTemplates();renderArchive();applyTheme();}
function renderToday(){const d=new Date();$('#dateTitle').textContent=d.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});const rs=activeRoutines().filter(r=>scheduled(r,d));const done=rs.filter(r=>runForDate(r,today())?.status==='done').length;const score=rs.length?Math.round(done/rs.length*100):0;$('#todayScore').textContent=score+'%';$('#todayStats').innerHTML=[['Due',rs.length],['Done',done],['Minutes',rs.reduce((a,r)=>a+totalMinutes(r),0)],['Streak',Math.max(0,...activeRoutines().map(streak))]].map(x=>`<div class="metric"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('');$('#todayRoutines').innerHTML=rs.length?rs.map(card).join('<div class="divider"></div>'):'<div class="empty">No routines scheduled today. Use the planner to add structure.</div>';$('#quickRoutines').innerHTML=rs.slice(0,4).map(card).join('')||'<div class="empty">Create a routine to get started.</div>';let arr=[];for(let i=6;i>=0;i--){const x=new Date();x.setDate(x.getDate()-i);const key=iso(x),due=activeRoutines().filter(r=>scheduled(r,x)).length,hit=activeRoutines().filter(r=>runForDate(r,key)?.status==='done').length;arr.push(`<div class="day-dot"><span>${x.toLocaleDateString(undefined,{weekday:'short'}).slice(0,2)}</span><i class="level-${due?Math.min(3,Math.ceil(hit/due*3)):0}"></i><small>${hit}/${due}</small></div>`)}$('#weekStrip').innerHTML=arr.join('')}
function renderRoutines(){const q=($('#routineSearch')?.value||'').toLowerCase(),f=$('#routineFilter')?.value||'all',sort=$('#routineSort')?.value||'due';let rs=state.routines.filter(r=>f==='archived'?r.archived:f==='paused'?r.paused&&!r.archived:f==='active'?!r.archived&&!r.paused:true).filter(r=>(r.name+' '+(r.area||'')+' '+(r.tags||[]).join(' ')).toLowerCase().includes(q));rs.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='streak'?streak(b)-streak(a):sort==='completion'?routineRate(b)-routineRate(a):a.name.localeCompare(b.name));$('#routineGrid').innerHTML=rs.length?rs.map(card).join(''):'<div class="empty">No routines match this view.</div>'}
function weekStart(d){const x=new Date(d);const n=state.settings.weekStart===0?x.getDay():(x.getDay()+6)%7;x.setDate(x.getDate()-n);x.setHours(0,0,0,0);return x}
function renderPlanner(){const start=weekStart(selectedWeek),days=[];for(let i=0;i<7;i++){const d=new Date(start);d.setDate(start.getDate()+i);days.push(d)}$('#plannerTitle').textContent=`${start.toLocaleDateString(undefined,{month:'short',day:'numeric'})} – ${days[6].toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}`;const due=days.reduce((a,d)=>a+activeRoutines().filter(r=>scheduled(r,d)).length,0),done=days.reduce((a,d)=>a+activeRoutines().filter(r=>runForDate(r,iso(d))?.status==='done').length,0);$('#plannerSummary').textContent=`${done} completed of ${due} scheduled`;$('#plannerGrid').innerHTML=days.map(d=>{const rs=activeRoutines().filter(r=>scheduled(r,d));return `<article class="day-column"><div class="day-head"><strong>${d.toLocaleDateString(undefined,{weekday:'short'})}</strong><span>${d.getDate()}</span></div>${rs.length?rs.map(r=>`<div class="plan-item ${statusLabel(r,iso(d))}" data-run="${r.id}" data-date="${iso(d)}"><b>${esc(r.name)}</b><small>${totalMinutes(r)} min · ${statusLabel(r,iso(d))}</small></div>`).join(''):'<div class="empty small">Free</div>'}</article>`}).join('')}
function renderInsights(){const rs=activeRoutines(),rates=rs.map(routineRate),avg=rs.length?Math.round(rates.reduce((a,b)=>a+b,0)/rs.length):0,total=state.runs.length,done=state.runs.filter(x=>x.status==='done').length,mins=state.runs.reduce((a,x)=>a+(+x.actualMinutes||0),0);$('#insightCards').innerHTML=[['30d consistency',avg+'%'],['Completed runs',done],['Total runs',total],['Minutes tracked',mins]].map(x=>`<div class="metric"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('');$('#leaderboard').innerHTML=rs.sort((a,b)=>routineRate(b)-routineRate(a)).slice(0,8).map(r=>`<div class="leader"><div><b>${esc(r.name)}</b><small>${streak(r)} day streak · ${totalMinutes(r)} min</small></div><strong>${routineRate(r)}%</strong></div>`).join('')||'<div class="empty">Run a routine to see patterns.</div>';const now=new Date(),cells=[];for(let i=29;i>=0;i--){const d=new Date(now);d.setDate(now.getDate()-i);const key=iso(d),due=rs.filter(r=>scheduled(r,d)).length,hit=rs.filter(r=>runForDate(r,key)?.status==='done').length;cells.push(`<i class="heat-${due?Math.min(4,Math.ceil(hit/due*4)):0}" title="${key}: ${hit}/${due}"></i>`)}$('#heatmap').innerHTML=cells.join('');const advice=avg>=80?'Your routines are stable. Protect what is working and refine one step at a time.':avg>=50?'Your rhythm is forming. Look for routines with a high miss rate and simplify their first step.':'Your system may be too ambitious. Shorten routines, reduce frequency, or add recovery days.';$('#weeklyReview').innerHTML=`<div class="review"><strong>${esc(advice)}</strong><p>Best next move: review the lowest-consistency routine and make its first step easy to start.</p><button class="ghost" id="reviewOpen">Open routine library</button></div>`}
function renderTemplates(){$('#templateGrid').innerHTML=templates.map((t,i)=>`<article class="template-card"><span class="pill">${esc(t.time)}</span><h3>${esc(t.name)}</h3><p class="muted">${t.steps.length} steps · ${t.steps.reduce((a,s)=>a+s[1],0)} minutes · ${esc(t.area)}</p><ol>${t.steps.map(s=>`<li>${esc(s[0])}<small>${s[1]} min</small></li>`).join('')}</ol><button class="primary" data-template="${i}">Use template</button></article>`).join('')}
function renderArchive(){const rs=state.routines.filter(r=>r.archived);$('#archiveGrid').innerHTML=rs.length?rs.map(card).join(''):'<div class="empty">Nothing archived.</div>'}
function openModal(id){const m=$('#'+id);m.setAttribute('aria-hidden','false');m.classList.add('open')}
function closeModal(id){const m=$('#'+id);m.setAttribute('aria-hidden','true');m.classList.remove('open')}
function blankRoutine(){return {id:uid(),name:'',area:'Personal',time:'morning',start:'',repeat:'daily',weekly:3,interval:2,reminder:'',tags:[],notes:'',days:[1,2,3,4,5],steps:[{id:uid(),name:'First step',minutes:5,note:'',mode:state.settings.defaultMode||'timer'}],created:today()}}
function fillRoutine(r){$('#routineId').value=r.id;$('#routineModalTitle').textContent=r.name?'Edit routine':'New routine';['routineName','routineArea','routineTime','routineStart','routineRepeat','routineWeekly','routineInterval','routineReminder','routineColor','routineNotes'].forEach(id=>{const el=$('#'+id);if(el)el.value=id==='routineTags'?(r.tags||[]).join(', '):(id==='routineName'?r.name:id==='routineArea'?r.area||'Personal':id==='routineTime'?r.time||'any':id==='routineStart'?r.start||'':id==='routineRepeat'?r.repeat||'daily':id==='routineWeekly'?r.weekly||3:id==='routineInterval'?r.interval||2:id==='routineReminder'?r.reminder||'':id==='routineColor'?r.color||'indigo':r.notes||'')});$('#routineTags').value=(r.tags||[]).join(', ');renderDayPicker(r.days||[1,2,3,4,5]);renderSteps(r.steps||[])}
function renderDayPicker(days){const names=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];$('#routineDays').innerHTML=names.map((n,i)=>`<label class="day-check"><input type="checkbox" value="${i}" ${days.includes(i)?'checked':''}>${n}</label>`).join('')}
function renderSteps(steps){$('#stepEditor').innerHTML=steps.map((s,i)=>`<div class="step-row" data-step="${s.id}"><span class="drag">${i+1}</span><input class="step-name" value="${esc(s.name)}" placeholder="Step name"><input class="step-min" type="number" min="0" step="1" value="${+s.minutes||0}" title="minutes"><select class="step-mode"><option value="timer" ${s.mode==='timer'?'selected':''}>Timer</option><option value="check" ${s.mode==='check'?'selected':''}>Check</option></select><button type="button" class="remove-step">×</button><input class="step-note full" value="${esc(s.note||'')}" placeholder="Optional instruction"></div>`).join('')}
function readSteps(){return $$('.step-row').map(row=>({id:row.dataset.step||uid(),name:$('.step-name',row).value.trim()||'Untitled step',minutes:Math.max(0,+$('.step-min',row).value||0),mode:$('.step-mode',row).value,note:$('.step-note',row).value.trim()}))}
function openRoutine(id){const r=id?state.routines.find(x=>x.id===id):blankRoutine();if(!r)return;fillRoutine(r);openModal('routineModal')}
function saveRoutine(e){e.preventDefault();const id=$('#routineId').value||uid(),old=state.routines.find(r=>r.id===id),r={...(old||blankRoutine()),id,name:$('#routineName').value.trim(),area:$('#routineArea').value.trim()||'Personal',time:$('#routineTime').value, start:$('#routineStart').value,repeat:$('#routineRepeat').value,weekly:+$('#routineWeekly').value||1,interval:+$('#routineInterval').value||2,reminder:$('#routineReminder').value,tags:$('#routineTags').value.split(',').map(s=>s.trim()).filter(Boolean),notes:$('#routineNotes').value.trim(),days:$$('#routineDays input:checked').map(x=>+x.value),steps:readSteps(),updated:today()};if(!r.name){toast('Give the routine a name.');return}if(!r.steps.length){toast('Add at least one step.');return}const idx=state.routines.findIndex(x=>x.id===id);if(idx<0)state.routines.push(r);else state.routines[idx]=r;save();closeModal('routineModal');render();toast('Routine saved')}
function startRunner(id,date=today()){const r=state.routines.find(x=>x.id===id);if(!r||!r.steps.length)return;runner={routine:r.id,date,step:0,started:Date.now(),actual:[],status:'running'};paused=false;renderRunner();openModal('runnerModal');startTimer()}
function currentStep(){const r=state.routines.find(x=>x.id===runner?.routineId)||state.routines.find(x=>x.id===runner?.routine);return r?.steps[runner.step]}
function runnerRoutine(){return state.routines.find(x=>x.id===runner.routine)||null}
function renderRunner(){const r=runnerRoutine();if(!r)return;const s=r.steps[runner.step];$('#runnerTitle').textContent=r.name;$('#runnerProgress').textContent=`${runner.step+1} of ${r.steps.length}`;$('#runnerStepCount').textContent=`STEP ${runner.step+1}`;$('#runnerStepName').textContent=s.name;$('#runnerStepNote').textContent=s.note||'Focus on the next small action.';$('#runnerIcon').textContent=runner.step+1;$('#runnerChecklist').innerHTML=r.steps.map((x,i)=>`<div class="runner-list ${i===runner.step?'current':''} ${runner.actual[i]?.status||''}"><span>${i+1}</span><b>${esc(x.name)}</b><small>${x.minutes} min</small></div>`).join('');$('#runnerPause').textContent=paused?'Resume':'Pause';$('#runnerNext').textContent=runner.step===r.steps.length-1?'Finish':'Done & next';if(s.mode==='check'){$('#timerValue').textContent='Checklist';$('#timerProgress').style.width='100%'}else updateTimer()}
function startTimer(){clearInterval(timer);const s=currentStep();if(!s||s.mode==='check'){renderRunner();return}remaining=Math.max(0,+s.minutes||0)*60;paused=false;renderRunner();if(remaining<=0)return;timer=setInterval(()=>{if(paused)return;remaining--;updateTimer();if(remaining<=0){clearInterval(timer);toast('Step time is up');}},1000)}
function updateTimer(){const s=currentStep();if(!s)return;const total=Math.max(1,(+s.minutes||0)*60);const sec=Math.max(0,remaining),m=String(Math.floor(sec/60)).padStart(2,'0'),ss=String(sec%60).padStart(2,'0');$('#timerValue').textContent=`${m}:${ss}`;$('#timerProgress').style.width=Math.max(0,Math.min(100,(1-sec/total)*100))+'%'}
function finishRunner(status='done'){clearInterval(timer);const r=runnerRoutine();if(!r)return;const actualMinutes=Math.max(0,Math.round((Date.now()-runner.started)/60000));state.runs=state.runs.filter(x=>!(x.routineId===r.id&&x.date===runner.date));state.runs.push({id:uid(),routineId:r.id,date:runner.date,status,actualMinutes,stepsCompleted:runner.actual.filter(x=>x.status==='done').length,started:new Date(runner.started||Date.now()).toISOString(),finished:new Date().toISOString()});save();closeModal('runnerModal');runner=null;render();toast(status==='done'?'Routine completed':'Routine logged')}
function nextStep(status='done'){if(!runner)return;runner.actual[runner.step]={status,minutes:currentStep()?.minutes||0};if(runner.step>=runnerRoutine().steps.length-1){finishRunner(status==='done'?'done':'partial');return}runner.step++;startTimer()}
function applyTheme(){const t=state.settings.theme;document.documentElement.dataset.theme=t==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):t}
function exportFile(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportJson(){exportFile('routinecraft-backup.json',JSON.stringify(state,null,2))}
function exportCsv(){const rows=[['date','routine','status','actualMinutes','stepsCompleted']];state.runs.forEach(x=>{const r=state.routines.find(y=>y.id===x.routineId);rows.push([x.date,r?.name||'Unknown',x.status,x.actualMinutes||0,x.stepsCompleted||0])});exportFile('routinecraft-runs.csv',rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv')}
function importJson(e){const f=e.target.files?.[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const d=JSON.parse(rd.result);if(!Array.isArray(d.routines)||!Array.isArray(d.runs))throw Error();state={...d,settings:{...defaults,...d.settings}};save();render();toast('Backup restored')}catch{toast('That backup is not valid.')}};rd.readAsText(f);e.target.value=''}
function showView(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===id));if(id==='insights')renderInsights()}
function installTemplate(i){const t=templates[i];state.routines.push({id:uid(),name:t.name,area:t.area,time:t.time,start:'',repeat:'daily',weekly:3,interval:2,reminder:'',tags:[t.area.toLowerCase()],notes:'',days:[1,2,3,4,5],steps:t.steps.map(s=>({id:uid(),name:s[0],minutes:s[1],note:s[2],mode:'timer'})),created:today()});save();render();toast(`${t.name} added`)}
function bind(){document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){showView(nav.dataset.view);return}const run=e.target.closest('[data-run]');if(run){startRunner(run.dataset.run,run.dataset.date||today());return}const edit=e.target.closest('[data-edit]');if(edit){openRoutine(edit.dataset.edit);return}const temp=e.target.closest('[data-template]');if(temp){installTemplate(+temp.dataset.template);return}if(e.target.id==='newRoutine'||e.target.id==='addRoutine2')openRoutine();if(e.target.id==='quickStart'){$('.routine-card [data-run]')?.click()}if(e.target.id==='reviewOpen')showView('routines');if(e.target.matches('[data-close]'))closeModal(e.target.dataset.close);if(e.target.id==='closeRunner'){clearInterval(timer);closeModal('runnerModal');runner=null}if(e.target.id==='runnerNext')nextStep('done');if(e.target.id==='runnerSkip')nextStep('skipped');if(e.target.id==='runnerPrev'&&runner){runner.step=Math.max(0,runner.step-1);startTimer()}if(e.target.id==='runnerPause'){paused=!paused;renderRunner()}if(e.target.classList.contains('remove-step')){e.target.closest('.step-row').remove();renumberSteps()}});
$('#routineForm').addEventListener('submit',saveRoutine);$('#addStep').addEventListener('click',()=>{const steps=readSteps();steps.push({id:uid(),name:'New step',minutes:5,note:'',mode:state.settings.defaultMode});renderSteps(steps);renumberSteps()});['routineSearch','routineFilter','routineSort'].forEach(id=>$('#'+id).addEventListener('input',renderRoutines));
$('#prevWeek').onclick=()=>{selectedWeek.setDate(selectedWeek.getDate()-7);renderPlanner()};$('#nextWeek').onclick=()=>{selectedWeek.setDate(selectedWeek.getDate()+7);renderPlanner()};$('#thisWeek').onclick=()=>{selectedWeek=new Date();renderPlanner()};$('#startFocus').onclick=()=>{const r=activeRoutines().find(x=>scheduled(x,new Date()));if(r)startRunner(r.id);else toast('No routine due today')};$('#theme').onchange=e=>{state.settings.theme=e.target.value;save();applyTheme()};$('#weekStart').onchange=e=>{state.settings.weekStart=+e.target.value;save();renderPlanner();renderToday()};$('#defaultMode').onchange=e=>{state.settings.defaultMode=e.target.value;save()};$('#countdown').onchange=e=>{state.settings.countdown=+e.target.value;save()};$('#exportJson').onclick=exportJson;$('#exportCsv').onclick=exportCsv;$('#importJson').onclick=()=>$('#importFile').click();$('#importFile').onchange=importJson;$('#resetData').onclick=()=>{if(confirm('Delete all local routines and run history?')){state={routines:[],runs:[],settings:{...defaults}};save();render();toast('Local data reset')}};$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openRoutine()}if(e.key==='Escape'){closeModal('routineModal');if(runner){clearInterval(timer);closeModal('runnerModal');runner=null}}});render();
$('#storageHealth').innerHTML=`<p><b>${state.routines.length}</b> routines · <b>${state.runs.length}</b> run records · localStorage ${(new Blob([JSON.stringify(state)]).size/1024).toFixed(1)} KB</p>`;$('#theme').value=state.settings.theme;$('#weekStart').value=state.settings.weekStart;$('#defaultMode').value=state.settings.defaultMode;$('#countdown').value=state.settings.countdown;renderDayPicker([1,2,3,4,5]);
}
function renumberSteps(){ $$('.step-row').forEach((x,i)=>x.querySelector('.drag').textContent=i+1) }
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
window.Routinecraft={state,save,render,startRunner};
})();