const KEY='tv-show-tracker:v1',AKEY='tv-show-tracker:advanced:v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],uid=()=>crypto.randomUUID(),now=()=>new Date().toISOString(),today=()=>new Date().toISOString().slice(0,10),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const blank={theme:'system',shows:[],lists:[],settings:{yearGoal:300,defaultView:'home'},savedFilters:[]};
const advDefault={journal:[],challenges:[],snapshots:[],preferences:{defaultService:'',notifications:false},version:1};
function normalizeEpisode(e,i){return {id:e.id||uid(),season:+e.season||1,number:+e.number||i+1,title:e.title||`Episode ${i+1}`,airDate:e.airDate||'',runtime:+e.runtime||null,status:e.status||'Unwatched',watchedAt:e.watchedAt||'',watchDates:Array.isArray(e.watchDates)?e.watchDates:(e.watchedAt?[e.watchedAt]:[]),rating:e.rating===''?null:(e.rating??null),review:e.review||'',notes:e.notes||'',favorite:!!e.favorite,addedAt:e.addedAt||now()};}
function normalizeShow(s){let seasons=Array.isArray(s.seasons)?s.seasons:[],eps=[];seasons.forEach((sea,si)=>(sea.episodes||[]).forEach((e,i)=>eps.push({...normalizeEpisode(e,i),season:+sea.number||si+1})));if(Array.isArray(s.episodes))eps=s.episodes.map(normalizeEpisode);return {id:s.id||uid(),title:s.title||'Untitled Show',year:+s.year||null,status:s.status||'Watchlist',seasons:+s.seasonsCount||seasons.length||1,seasonsCount:+s.seasonsCount||seasons.length||1,episodes:eps,genres:s.genres||'',creator:s.creator||'',cast:s.cast||'',network:s.network||'',country:s.country||'',language:s.language||'',tags:s.tags||'',notes:s.notes||'',review:s.review||'',poster:s.poster||'',backdrop:s.backdrop||'',trailer:s.trailer||'',source:s.source||'',service:s.service||'',priority:+s.priority||3,rating:s.rating===''?null:(s.rating??null),favorite:!!s.favorite,progressMode:s.progressMode||'episode',startedAt:s.startedAt||'',completedAt:s.completedAt||'',addedAt:s.addedAt||now(),updatedAt:now(),rewatchCount:+s.rewatchCount||0};}
function load(){let s={...blank};try{s={...blank,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{}s.shows=(s.shows||[]).map(normalizeShow);s.lists=s.lists||[];let a=advDefault;try{a={...advDefault,...JSON.parse(localStorage.getItem(AKEY)||'{}')}}catch{}localStorage.setItem(KEY,JSON.stringify(s));return [s,a]}
let [state,adv]=load(),view=state.settings.defaultView||'home',selected=new Set();
function save(){state.shows.forEach(s=>s.updatedAt=now());localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(AKEY,JSON.stringify(adv))}
function allEpisodes(){return state.shows.flatMap(s=>s.episodes.map(e=>({...e,showId:s.id,show:s})))}
function watchedEpisodes(s){return s.episodes.filter(e=>e.status==='Watched')}
function progress(s){return s.episodes.length?Math.round(watchedEpisodes(s).length/s.episodes.length*100):0}
function genreList(s){return String(s.genres||'').split(',').map(x=>x.trim()).filter(Boolean)}
function matches(s,q){return !q||[s.title,s.creator,s.cast,s.genres,s.tags,s.network,s.country,s.language,s.notes,s.review,s.service].join(' ').toLowerCase().includes(q)}
function filterShows(arr){let q=($('#search')?.value||'').trim().toLowerCase(),f=$('#filter')?.value||'all',sort=$('#sort')?.value||'added';arr=arr.filter(s=>matches(s,q));if(f==='Favorite')arr=arr.filter(s=>s.favorite);else if(f==='Unrated')arr=arr.filter(s=>!s.rating);else if(f!=='all')arr=arr.filter(s=>s.status===f);arr.sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):sort==='progress'?progress(b)-progress(a):sort==='rating'?(b.rating||0)-(a.rating||0):sort==='priority'?(b.priority||0)-(a.priority||0):sort==='year'?(b.year||0)-(a.year||0):sort==='runtime'?watchMinutes(b)-watchMinutes(a):String(b.addedAt).localeCompare(String(a.addedAt)));return arr}
function watchMinutes(s){return s.episodes.reduce((n,e)=>n+(+e.runtime||0),0)}
function cover(s){return s.poster?`<img src="${esc(s.poster)}" alt="" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><div class="posterFallback" style="display:none">${esc((s.title||'?')[0])}</div>`:`<div class="posterFallback">${esc((s.title||'?')[0])}</div>`}
function showCard(s){let p=progress(s),next=s.episodes.find(e=>e.status!=='Watched');return `<article class="show ${selected.has(s.id)?'selected':''}"><input class="pick" type="checkbox" ${selected.has(s.id)?'checked':''} aria-label="Select ${esc(s.title)}" onchange="toggleSelect('${s.id}')"><div class="poster">${cover(s)}</div><div class="showbody"><div class="row"><div><h3>${esc(s.title)}</h3><p class="muted">${esc(s.year||'')}${s.creator?' · '+esc(s.creator):''}${s.network?' · '+esc(s.network):''}</p></div><button class="ghost" onclick="openShow('${s.id}')">Open</button></div><p class="muted">${esc(s.genres||'')}${s.service?' · '+esc(s.service):''}</p><div class="progress"><i style="width:${p}%"></i></div><div class="chips"><span>${esc(s.status)}</span><span>${watchedEpisodes(s).length}/${s.episodes.length||0} episodes</span>${s.rating?`<span>★ ${s.rating}</span>`:''}${s.favorite?'<span>Favorite</span>':''}${s.priority>=4?'<span>High priority</span>':''}</div>${next?`<p class="next">Next: S${next.season}E${next.number} · ${esc(next.title)}</p>`:''}</div></article>`}
function empty(t){return `<div class="empty">${esc(t)}</div>`}
function bulkBar(){return `<div class="bulk"><b>${selected.size} selected</b><button onclick="bulkStatus('Watching')">Watching</button><button onclick="bulkStatus('Completed')">Completed</button><button onclick="bulkStatus('Watchlist')">Watchlist</button><button onclick="bulkFavorite()">Toggle favorite</button><button onclick="bulkDelete()">Delete</button><button onclick="selected.clear();render()">Clear</button></div>`}
function shell(title,sub,body){$('#view').innerHTML=`<div class="sectionHead"><div><span class="eyebrow">${esc(title.toUpperCase())}</span><h2>${esc(title)}</h2><p class="muted">${esc(sub)}</p></div></div>${body}${selected.size?bulkBar():''}`}
function home(){let active=state.shows.filter(s=>['Watching','Paused'].includes(s.status)).sort((a,b)=>b.priority-a.priority).slice(0,6),queue=state.shows.filter(s=>s.status==='Watchlist').sort((a,b)=>b.priority-a.priority).slice(0,6),eps=allEpisodes().filter(x=>x.status!=='Watched').sort((a,b)=>String(a.airDate||'9999').localeCompare(String(b.airDate||'9999'))).slice(0,8),ws=allEpisodes().filter(x=>x.status==='Watched'),year=new Date().getFullYear(),yw=ws.filter(x=>(x.watchedAt||'').startsWith(year));shell('Home','Your private control center for current shows, the next episode and your viewing history.',`<div class="hero"><div><span class="eyebrow">YOUR TV YEAR</span><div class="heroStat">${yw.length}<small> / ${state.settings.yearGoal} episodes</small></div><p class="muted">${state.shows.length} shows · ${state.shows.filter(s=>s.status==='Watching').length} watching · ${state.shows.filter(s=>s.status==='Completed').length} completed · ${Math.round(ws.reduce((n,e)=>n+(+e.runtime||0),0)/60)}h watched</p></div><div class="heroActions"><button class="primary" onclick="pickNext()">Pick next</button><button onclick="openAddShow()">Quick add</button></div></div><div class="grid"><div class="card"><div class="row"><h3>Continue watching</h3><button class="ghost" onclick="setView('shows')">See all</button></div>${active.map(showCard).join('')||empty('No active shows yet.')}</div><div class="card"><div class="row"><h3>Watchlist</h3><button class="ghost" onclick="setView('watchlist')">Queue</button></div>${queue.map(showCard).join('')||empty('Add shows you want to watch.')}</div></div><div class="grid"><div class="card"><h3>Next episodes</h3>${eps.map(x=>`<div class="episodeRow"><time>${esc(x.airDate||'No date')}</time><button class="link" onclick="openShow('${x.showId}')">${esc(x.show.title)}</button><span>S${x.season}E${x.number} · ${esc(x.title)}</span></div>`).join('')||empty('Add episode air dates to build your release queue.')}</div><div class="card"><h3>Smart picks</h3><p class="muted">Local-only decision helpers. No account or recommendation API.</p><div class="tools"><button onclick="smartPick('short')">Shortest remaining</button><button onclick="smartPick('priority')">Highest priority</button><button onclick="smartPick('favorite')">Favorite show</button><button onclick="smartPick('fresh')">Least watched</button></div></div></div>`)}
function library(mode){let arr=filterShows(state.shows.filter(s=>mode==='watchlist'?s.status==='Watchlist':true));if(mode==='watchlist')arr=arr.filter(s=>s.status==='Watchlist');shell(mode==='watchlist'?'Watchlist':'My Shows',mode==='watchlist'?'Shows waiting in your queue.':'Your complete show library and current progress.',`<div class="libraryMeta"><span>${arr.length} shows</span><button onclick="openAddShow()">+ Add show</button></div><div class="card list">${arr.map(showCard).join('')||empty('Nothing matches your current filters.')}</div>`)}
function episodes(){let eps=allEpisodes().filter(x=>{let q=($('#search')?.value||'').toLowerCase();return !q||[x.show.title,x.title,x.show.genres].join(' ').toLowerCase().includes(q)}).sort((a,b)=>String(b.watchedAt||b.airDate||'').localeCompare(String(a.watchedAt||a.airDate||'')));let pending=eps.filter(e=>e.status!=='Watched');shell('Episodes','Episode-level progress, ratings, notes and watch dates.',`<div class="statGrid"><div class="card"><span class="label">TOTAL</span><div class="stat">${eps.length}</div></div><div class="card"><span class="label">WATCHED</span><div class="stat">${eps.filter(e=>e.status==='Watched').length}</div></div><div class="card"><span class="label">REMAINING</span><div class="stat">${pending.length}</div></div><div class="card"><span class="label">UNRATED</span><div class="stat">${eps.filter(e=>!e.rating).length}</div></div></div><div class="card">${eps.map(e=>`<div class="episodeRow detailed"><div><button class="link" onclick="openShow('${e.showId}')">${esc(e.show.title)}</button><b>S${e.season}E${e.number}</b><span>${esc(e.title)}</span></div><span>${esc(e.airDate||'')}</span><span>${e.status==='Watched'?'✓ Watched':'Unwatched'}</span><button onclick="toggleEpisode('${e.showId}','${e.id}')">${e.status==='Watched'?'Undo':'Watch'}</button></div>`).join('')||empty('No episodes yet. Add a show and episode data.')}</div>`)}
function diary(){let rows=allEpisodes().filter(e=>e.status==='Watched'&&e.watchedAt).sort((a,b)=>String(b.watchedAt).localeCompare(String(a.watchedAt))),months={};rows.forEach(e=>(months[e.watchedAt.slice(0,7)]??=[]).push(e));shell('Diary','A chronological log of every episode you watched, rated and reviewed.',`<div class="card diaryGrid">${Object.entries(months).sort((a,b)=>b[0].localeCompare(a[0])).map(([m,es])=>`<section><h3>${esc(m)}</h3>${es.map(e=>`<div class="diaryRow"><time>${esc(e.watchedAt)}</time><button class="link" onclick="openShow('${e.showId}')">${esc(e.show.title)}</button><span>S${e.season}E${e.number}</span><span>${e.rating?`★ ${e.rating}`:''}</span><span>${e.favorite?'Favorite':''}</span></div>`).join('')}</section>`).join('')||empty('Your diary appears here after you mark episodes watched.')}</div>`)}
function lists(){let html=state.lists.map(l=>{let ss=l.showIds.map(id=>state.shows.find(s=>s.id===id)).filter(Boolean);return `<div class="card"><div class="row"><div><h3>${esc(l.name)}</h3><p class="muted">${ss.length} shows · ${l.private===false?'Shared':'Private'}</p></div><button onclick="manageList('${l.id}')">Manage</button></div><div class="chips">${ss.slice(0,18).map(s=>`<span>${esc(s.title)}</span>`).join('')||'<span>Empty list</span>'}</div></div>`}).join('');shell('Lists','Private collections for genres, marathons, moods, franchises or anything else.',`<div class="libraryMeta"><span>${state.lists.length} lists</span><button class="primary" onclick="newList()">+ New list</button></div>${html||empty('Create your first custom list.')}`)}
function stats(){let eps=allEpisodes(),w=eps.filter(e=>e.status==='Watched'),year=new Date().getFullYear(),yw=w.filter(e=>(e.watchedAt||'').startsWith(year)),mins=w.reduce((n,e)=>n+(+e.runtime||0),0),rs=w.filter(e=>e.rating),avg=rs.length?(rs.reduce((n,e)=>n+e.rating,0)/rs.length).toFixed(1):'—',gs={};state.shows.forEach(s=>genreList(s).forEach(g=>gs[g]=(gs[g]||0)+watchedEpisodes(s).length));let max=Math.max(1,...Object.values(gs)),months=Array.from({length:12},(_,i)=>{let k=`${year}-${String(i+1).padStart(2,'0')}`;return[k,w.filter(e=>(e.watchedAt||'').startsWith(k)).length]});shell('Stats','Your private TV history, habits, streaks and year review.',`<div class="statGrid"><div class="card"><span class="label">EPISODES</span><div class="stat">${w.length}</div></div><div class="card"><span class="label">AVERAGE RATING</span><div class="stat">${avg}</div></div><div class="card"><span class="label">WATCH TIME</span><div class="stat">${Math.floor(mins/60)}h ${mins%60}m</div></div><div class="card"><span class="label">THIS YEAR</span><div class="stat">${yw.length}/${state.settings.yearGoal}</div></div></div><div class="grid"><div class="card"><h3>${year} viewing</h3><div class="bars">${months.map(([k,n])=>`<div class="barItem"><span>${k.slice(5)}</span><i style="height:${Math.max(4,n*8)}px"></i><b>${n}</b></div>`).join('')}</div></div><div class="card"><h3>Genre profile</h3>${Object.entries(gs).sort((a,b)=>b[1]-a[1]).map(([g,n])=>`<div class="meter"><div><span>${esc(g)}</span><b>${n}</b></div><i><em style="width:${n/max*100}%"></em></i></div>`).join('')||empty('Watch episodes to build your profile.')}</div></div><div class="grid"><div class="card"><h3>Viewing streak</h3><div class="stat">${streak()} days</div><p class="muted">Consecutive days with at least one watched episode.</p></div><div class="card"><h3>Year in review</h3><p class="muted">${yw.length} episodes across ${new Set(yw.map(e=>e.show.title)).size} shows, ${Math.round(yw.reduce((n,e)=>n+(+e.runtime||0),0)/60)} hours.</p><button onclick="copyYearReview()">Copy summary</button></div></div>`)}
function streak(){let days=new Set(allEpisodes().filter(e=>e.status==='Watched'&&e.watchedAt).map(e=>e.watchedAt));let d=new Date();let n=0;while(days.has(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return n}
function render(){document.body.dataset.theme=state.theme==='system'?'':state.theme;$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='home')home();else if(view==='shows')library('shows');else if(view==='watchlist')library('watchlist');else if(view==='episodes')episodes();else if(view==='diary')diary();else if(view==='lists')lists();else stats()}
function setView(v){view=v;state.settings.defaultView=v;selected.clear();render()}function toggleTheme(){state.theme=state.theme==='dark'?'light':state.theme==='light'?'system':'dark';save();render()}function clearFilters(){if($('#search'))$('#search').value='';if($('#filter'))$('#filter').value='all';if($('#sort'))$('#sort').value='added';render()}
function openModal(html){$('#modalBody').innerHTML=html;$('#modal').showModal()}function closeModal(){if($('#modal').open)$('#modal').close()}
function showFields(s={}){return `<label>Show title *<input name="title" required value="${esc(s.title||'')}"></label><div class="two"><label>Year<input name="year" type="number" min="1900" max="2200" value="${s.year||''}"></label><label>Status<select name="status">${['Watchlist','Watching','Paused','Completed','Dropped'].map(x=>`<option ${s.status===x?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="two"><label>Seasons<input name="seasonsCount" type="number" min="1" value="${s.seasonsCount||''}></label><label>Rating<select name="rating"><option value="">Unrated</option>${Array.from({length:10},(_,i)=>(i+1)/2).map(x=>`<option value="${x}" ${s.rating==x?'selected':''}>${x}/5</option>`).join('')}</select></label></div><div class="two"><label>Genres<input name="genres" placeholder="Drama, Comedy" value="${esc(s.genres||'')}"></label><label>Tags<input name="tags" placeholder="comfort, mystery" value="${esc(s.tags||'')}"></label></div><div class="two"><label>Creator<input name="creator" value="${esc(s.creator||'')}"></label><label>Cast<input name="cast" placeholder="Actor 1, Actor 2" value="${esc(s.cast||'')}"></label></div><div class="two"><label>Network<input name="network" value="${esc(s.network||'')}"></label><label>Service<input name="service" placeholder="Optional" value="${esc(s.service||'')}"></label></div><div class="two"><label>Country<input name="country" value="${esc(s.country||'')}"></label><label>Language<input name="language" value="${esc(s.language||'')}"></label></div><label>Poster URL<input name="poster" type="url" value="${esc(s.poster||'')}"></label><div class="two"><label>Trailer URL<input name="trailer" type="url" value="${esc(s.trailer||'')}"></label><label>Source URL<input name="source" type="url" value="${esc(s.source||'')}"></label></div><label>Notes<textarea name="notes">${esc(s.notes||'')}</textarea></label><label>Review<textarea name="review">${esc(s.review||'')}</textarea></label><div class="formActions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save show</button></div>`}
function openAddShow(){openModal(`<span class="eyebrow">LIBRARY</span><h2>Add a TV show</h2><p class="muted">Enter the metadata you care about. Episode data can be added after saving.</p><form id="showForm" onsubmit="saveShow(event)">${showFields()}</form>`)}
function saveShow(e){e.preventDefault();let f=new FormData(e.target),s=normalizeShow(Object.fromEntries(f.entries()));s.seasonsCount=+f.get('seasonsCount')||1;s.episodes=[];state.shows.unshift(s);save();closeModal();openShow(s.id)}
function openShow(id){let s=state.shows.find(x=>x.id===id);if(!s)return;let seasons=[...new Set(s.episodes.map(e=>e.season))].sort((a,b)=>a-b);openModal(`<div class="detailHead"><div class="detailPoster">${cover(s)}</div><div><span class="eyebrow">${esc(s.status)}</span><h2>${esc(s.title)}</h2><p class="muted">${esc(s.year||'')}${s.creator?' · '+esc(s.creator):''}${s.network?' · '+esc(s.network):''}</p><div class="chips"><span>${progress(s)}% complete</span>${s.rating?`<span>★ ${s.rating}</span>`:''}${s.favorite?'<span>Favorite</span>':''}</div></div></div><div class="detailActions"><button class="primary" onclick="markNext('${s.id}')">Mark next watched</button><button onclick="addEpisode('${s.id}')">+ Episode</button><button onclick="editShow('${s.id}')">Edit</button><button onclick="toggleFavorite('${s.id}')">${s.favorite?'Unfavorite':'Favorite'}</button><button onclick="deleteShow('${s.id}')">Delete</button></div><div class="progress large"><i style="width:${progress(s)}%"></i></div><p class="muted">${watchedEpisodes(s).length} of ${s.episodes.length} episodes watched · ${Math.round(watchMinutes(s)/60)}h total episode runtime</p><div class="showMeta"><span>${esc(s.genres||'No genres')}</span><span>${esc(s.service||'No service')}</span><span>Priority ${s.priority}</span></div><div class="episodeEditor"><div class="row"><h3>Episodes</h3><button onclick="seedEpisodes('${s.id}')">Generate empty season grid</button></div>${seasons.map(sea=>`<section><h4>Season ${sea}</h4>${s.episodes.filter(e=>e.season===sea).sort((a,b)=>a.number-b.number).map(e=>episodeEditor(s,e)).join('')}</section>`).join('')||empty('No episode records yet. Add one or generate a season grid.')}</div><div class="card inset"><h3>Journal</h3><p>${esc(s.review||'No show review yet.')}</p><p class="muted">${esc(s.notes||'No notes.')}</p></div>`)}
function episodeEditor(s,e){return `<div class="episodeEdit"><div><b>S${e.season}E${e.number}</b><span>${esc(e.title)}</span><small>${esc(e.airDate||'No air date')}</small></div><div class="chips"><span>${e.status}</span>${e.rating?`<span>★ ${e.rating}</span>`:''}</div><div class="episodeBtns"><button onclick="toggleEpisode('${s.id}','${e.id}')">${e.status==='Watched'?'Undo watched':'Watched'}</button><button onclick="editEpisode('${s.id}','${e.id}')">Edit</button></div></div>`}
function editShow(id){let s=state.shows.find(x=>x.id===id);openModal(`<span class="eyebrow">EDIT</span><h2>${esc(s.title)}</h2><form id="showForm" onsubmit="updateShow(event,'${id}')">${showFields(s)}</form>`)}
function updateShow(e,id){e.preventDefault();let s=state.shows.find(x=>x.id===id),f=new FormData(e.target);Object.assign(s,{title:f.get('title'),year:+f.get('year')||null,status:f.get('status'),seasonsCount:+f.get('seasonsCount')||1,rating:f.get('rating')===''?null:+f.get('rating'),genres:f.get('genres'),tags:f.get('tags'),creator:f.get('creator'),cast:f.get('cast'),network:f.get('network'),service:f.get('service'),country:f.get('country'),language:f.get('language'),poster:f.get('poster'),trailer:f.get('trailer'),source:f.get('source'),notes:f.get('notes'),review:f.get('review')});save();closeModal();openShow(id)}
function addEpisode(showId){openModal(`<span class="eyebrow">EPISODE</span><h2>Add episode</h2><form id="epForm" onsubmit="saveEpisode(event,'${showId}')"><div class="two"><label>Season<input name="season" type="number" min="0" value="1" required></label><label>Episode<input name="number" type="number" min="1" value="1" required></label></div><label>Title<input name="title" required></label><div class="two"><label>Air date<input name="airDate" type="date"></label><label>Runtime<input name="runtime" type="number" min="1"></label></div><div class="two"><label>Rating<select name="rating"><option value="">Unrated</option>${Array.from({length:10},(_,i)=>(i+1)/2).map(x=>`<option value="${x}">${x}/5</option>`).join('')}</select></label><label>Watched date<input name="watchedAt" type="date"></label></div><label>Review<textarea name="review"></textarea></label><label>Notes<textarea name="notes"></textarea></label><div class="formActions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save episode</button></div></form>`)}
function saveEpisode(e,id){e.preventDefault();let f=new FormData(e.target),s=state.shows.find(x=>x.id===id),ep=normalizeEpisode(Object.fromEntries(f.entries()),s.episodes.length);ep.season=+f.get('season');ep.number=+f.get('number');ep.runtime=+f.get('runtime')||null;ep.rating=f.get('rating')===''?null:+f.get('rating');ep.watchedAt=f.get('watchedAt')||'';ep.status=ep.watchedAt?'Watched':'Unwatched';if(ep.watchedAt)ep.watchDates=[ep.watchedAt];s.episodes.push(ep);save();closeModal();openShow(id)}
function editEpisode(showId,id){let s=state.shows.find(x=>x.id===showId),e=s.episodes.find(x=>x.id===id);openModal(`<span class="eyebrow">EPISODE</span><h2>S${e.season}E${e.number} · ${esc(e.title)}</h2><form id="epForm" onsubmit="updateEpisode(event,'${showId}','${id}')"><div class="two"><label>Season<input name="season" type="number" min="0" value="${e.season}"></label><label>Episode<input name="number" type="number" min="1" value="${e.number}"></label></div><label>Title<input name="title" value="${esc(e.title)}" required></label><div class="two"><label>Air date<input name="airDate" type="date" value="${e.airDate}"></label><label>Runtime<input name="runtime" type="number" min="1" value="${e.runtime||''}"></label></div><div class="two"><label>Rating<select name="rating"><option value="">Unrated</option>${Array.from({length:10},(_,i)=>(i+1)/2).map(x=>`<option value="${x}" ${e.rating==x?'selected':''}>${x}/5</option>`).join('')}</select></label><label>Watched date<input name="watchedAt" type="date" value="${e.watchedAt||''}"></label></div><label>Review<textarea name="review">${esc(e.review)}</textarea></label><label>Notes<textarea name="notes">${esc(e.notes)}</textarea></label><div class="formActions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save episode</button></div></form>`)}
function updateEpisode(e,showId,id){e.preventDefault();let s=state.shows.find(x=>x.id===showId),ep=s.episodes.find(x=>x.id===id),f=new FormData(e.target),wd=f.get('watchedAt')||'';Object.assign(ep,{season:+f.get('season'),number:+f.get('number'),title:f.get('title'),airDate:f.get('airDate'),runtime:+f.get('runtime')||null,rating:f.get('rating')===''?null:+f.get('rating'),watchedAt:wd,review:f.get('review'),notes:f.get('notes'),status:wd?'Watched':'Unwatched'});if(wd&&!ep.watchDates.includes(wd))ep.watchDates.push(wd);save();closeModal();openShow(showId)}
function toggleEpisode(showId,id){let s=state.shows.find(x=>x.id===showId),e=s.episodes.find(x=>x.id===id);if(e.status==='Watched'){e.status='Unwatched';e.watchedAt=''}else{e.status='Watched';e.watchedAt=today();if(!e.watchDates.includes(e.watchedAt))e.watchDates.push(e.watchedAt)};if(s.episodes.length&&s.episodes.every(x=>x.status==='Watched'))s.status='Completed';else if(s.status==='Completed')s.status='Watching';save();render()}
function markNext(id){markNextSilent(id);save();closeModal();openShow(id)}function markNextSilent(id){let s=state.shows.find(x=>x.id===id),e=s?.episodes.find(x=>x.status!=='Watched');if(e){e.status='Watched';e.watchedAt=today();if(!e.watchDates.includes(e.watchedAt))e.watchDates.push(e.watchedAt);s.status=s.episodes.every(x=>x.status==='Watched')?'Completed':'Watching'}}
function seedEpisodes(id){let s=state.shows.find(x=>x.id===id);if(s.episodes.length){alert('This show already has episode records.');return}let count=Math.min(50,Math.max(1,s.seasonsCount||1)*10);for(let i=0;i<count;i++)s.episodes.push(normalizeEpisode({season:Math.floor(i/10)+1,number:i%10+1,title:`Episode ${i%10+1}`},i));save();openShow(id)}
function toggleFavorite(id){let s=state.shows.find(x=>x.id===id);s.favorite=!s.favorite;save();openShow(id)}
function deleteShow(id){if(!confirm('Delete this show and its episode history?'))return;state.shows=state.shows.filter(s=>s.id!==id);state.lists.forEach(l=>l.showIds=l.showIds.filter(x=>x!==id));save();closeModal();render()}
function toggleSelect(id){selected.has(id)?selected.delete(id):selected.add(id);render()}
function bulkStatus(status){state.shows.filter(s=>selected.has(s.id)).forEach(s=>s.status=status);save();selected.clear();render()}
function bulkFavorite(){state.shows.filter(s=>selected.has(s.id)).forEach(s=>s.favorite=!s.favorite);save();selected.clear();render()}
function bulkDelete(){if(!confirm(`Delete ${selected.size} shows?`))return;state.shows=state.shows.filter(s=>!selected.has(s.id));state.lists.forEach(l=>l.showIds=l.showIds.filter(id=>!selected.has(id)));save();selected.clear();render()}
function pickNext(){let a=state.shows.filter(s=>['Watching','Watchlist','Paused'].includes(s.status)&&s.episodes.some(e=>e.status!=='Watched'));if(!a.length){alert('No show with remaining episodes.');return}a.sort((x,y)=>y.priority-x.priority||progress(x)-progress(y));openShow(a[0].id)}
function smartPick(type){let a=state.shows.filter(s=>s.episodes.some(e=>e.status!=='Watched'));if(type==='short')a.sort((x,y)=>watchMinutes(x)-watchMinutes(y));if(type==='priority')a.sort((x,y)=>y.priority-x.priority);if(type==='favorite')a=a.filter(s=>s.favorite);if(type==='fresh')a.sort((x,y)=>progress(x)-progress(y));if(a[0])openShow(a[Math.floor(Math.random()*Math.min(a.length,3))].id);else alert('No matching show found.')}
function markNextFromHome(id){markNextSilent(id);save();render()}
function newList(){openModal(`<span class="eyebrow">COLLECTION</span><h2>New list</h2><form onsubmit="saveList(event)"><label>Name<input name="name" required placeholder="Weekend binge"></label><label>Description<textarea name="description"></textarea></label><div class="formActions"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Create list</button></div></form>`)}
function saveList(e){e.preventDefault();let f=new FormData(e.target);state.lists.push({id:uid(),name:f.get('name'),description:f.get('description'),showIds:[],private:true,createdAt:now()});save();closeModal();render()}
function manageList(id){let l=state.lists.find(x=>x.id===id);openModal(`<span class="eyebrow">LIST</span><h2>${esc(l.name)}</h2><p class="muted">${esc(l.description||'Private collection')}</p><div class="checkList">${state.shows.map(s=>`<label><input type="checkbox" ${l.showIds.includes(s.id)?'checked':''} onchange="toggleListShow('${id}','${s.id}')">${esc(s.title)}</label>`).join('')}</div><div class="formActions"><button onclick="deleteList('${id}')">Delete list</button><button class="primary" onclick="closeModal();render()">Done</button></div>`)}
function toggleListShow(lid,sid){let l=state.lists.find(x=>x.id===lid);l.showIds.includes(sid)?l.showIds=l.showIds.filter(x=>x!==sid):l.showIds.push(sid);save()}
function deleteList(id){state.lists=state.lists.filter(l=>l.id!==id);save();closeModal();render()}
function copyYearReview(){let y=new Date().getFullYear(),w=allEpisodes().filter(e=>e.status==='Watched'&&(e.watchedAt||'').startsWith(y));let text=`TV Year Review ${y}\n${w.length} episodes across ${new Set(w.map(e=>e.show.title)).size} shows\n${Math.round(w.reduce((n,e)=>n+(+e.runtime||0),0)/60)} hours watched`;navigator.clipboard?.writeText(text);alert(text)}
render();
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search')?.focus()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='n'){e.preventDefault();openAddShow()}if(e.key==='Escape')closeModal()});
