const PKEY='tv-show-tracker:advanced:v1';
function openPower(){openModal(`<span class="eyebrow">POWER SUITE</span><h2>TV Power Tools</h2><p class="muted">Advanced features stay local in this browser. No account, server or tracking required.</p><div class="powerGrid"><section class="card"><h3>Smart list builder</h3><p class="muted">Build a temporary collection from your own data.</p><div class="ruleRow"><select id="ruleStatus"><option value="">Any status</option><option>Watching</option><option>Watchlist</option><option>Paused</option><option>Completed</option><option>Dropped</option></select><select id="ruleGenre"><option value="">Any genre</option>${[...new Set(state.shows.flatMap(genreList))].sort().map(g=>`<option>${esc(g)}</option>`).join('')}</select><select id="ruleRating"><option value="0">Any rating</option><option value="4">4+</option><option value="3">3+</option><option value="2">2+</option></select><button onclick="runSmartList()">Build</button></div><div id="smartResults"></div></section><section class="card"><h3>Decision engine</h3><p class="muted">Explain why a show is a good next choice.</p><div class="ruleRow"><select id="decisionMode"><option value="balanced">Balanced</option><option value="short">Short commitment</option><option value="priority">Highest priority</option><option value="favorite">Favorite-first</option><option value="fresh">Least watched</option></select><button onclick="explainPick()">Decide</button></div><div id="decisionResults"></div></section><section class="card"><h3>Library audit</h3><button onclick="runAudit()">Scan library</button><div id="auditResults"></div></section><section class="card"><h3>Viewing calendar</h3><div id="powerCalendar" class="powerCalendar">${powerCalendar()}</div></section><section class="card"><h3>Taste profile</h3><div id="tasteResults">${tasteProfile()}</div></section><section class="card"><h3>Data center</h3><p class="muted">Portable backups and local restore points.</p><div class="dataActions"><button onclick="exportJSON()">JSON backup</button><button onclick="exportCSV()">CSV export</button><button onclick="importJSON()">Restore JSON</button><button onclick="encryptedBackup()">Encrypted backup</button><button onclick="restoreSnapshot()">Restore snapshot</button></div><p class="powerNote">Encrypted backups use AES-GCM in your browser. The passphrase is never uploaded.</p></section></div>`)}
function runSmartList(){let status=$('#ruleStatus').value,genre=$('#ruleGenre').value,rating=+$('#ruleRating').value||0,a=state.shows.filter(s=>(!status||s.status===status)&&(!genre||genreList(s).includes(genre))&&(!rating||+(s.rating||0)>=rating));$('#smartResults').innerHTML=`<div class="powerResults">${a.map(s=>`<button onclick="closeModal();openShow('${s.id}')">${esc(s.title)} · ${progress(s)}%</button>`).join('')||empty('No matches.')}</div>`}
function explainPick(){let mode=$('#decisionMode').value,a=state.shows.filter(s=>['Watching','Watchlist','Paused'].includes(s.status)&&s.episodes.some(e=>e.status!=='Watched'));if(mode==='short')a.sort((x,y)=>remainingMinutes(x)-remainingMinutes(y));if(mode==='priority')a.sort((x,y)=>y.priority-x.priority);if(mode==='favorite')a.sort((x,y)=>Number(y.favorite)-Number(x.favorite)||y.priority-x.priority);if(mode==='fresh')a.sort((x,y)=>progress(x)-progress(y));if(mode==='balanced')a.sort((x,y)=>score(y)-score(x));let s=a[0];$('#decisionResults').innerHTML=s?`<div class="decisionCard"><h4>${esc(s.title)}</h4><p>${explain(s,mode)}</p><button onclick="closeModal();openShow('${s.id}')">Open show</button></div>`:empty('No unfinished shows.')}
function remainingMinutes(s){return s.episodes.filter(e=>e.status!=='Watched').reduce((n,e)=>n+(+e.runtime||0),0)}
function score(s){return (s.priority||3)*20+(s.favorite?20:0)+(100-progress(s))*0.3-(remainingMinutes(s)/30)}
function explain(s,mode){let reasons=[];if(s.favorite)reasons.push('it is one of your favorites');if(s.priority>=4)reasons.push('you marked it high priority');if(progress(s)>0)reasons.push(`you are already ${progress(s)}% through it`);if(remainingMinutes(s)>0)reasons.push(`${Math.round(remainingMinutes(s)/60)}h of episodes remain`);if(mode==='short')reasons.push('it has the smallest remaining runtime among the candidates');return reasons.length?`Picked because ${reasons.join(', ')}.`:'It is an available unfinished show in your library.'}
function runAudit(){let dup={};state.shows.forEach(s=>(dup[s.title.toLowerCase()]=dup[s.title.toLowerCase()]||[]).push(s));let duplicates=Object.values(dup).filter(a=>a.length>1),incomplete=state.shows.filter(s=>!s.genres||!s.year||!s.episodes.length),stale=state.shows.filter(s=>s.status==='Watchlist'&&(Date.now()-new Date(s.addedAt).getTime())>1000*60*60*24*180);$('#auditResults').innerHTML=`<div class="audit"><b>${duplicates.length}</b> duplicate title groups · <b>${incomplete.length}</b> incomplete records · <b>${stale.length}</b> watchlist items older than 180 days${duplicates.length?`<details><summary>Duplicate groups</summary>${duplicates.map(a=>`<p>${a.map(s=>esc(s.title)).join(' · ')}</p>`).join('')}</details>`:''}</div>`}
function powerCalendar(){let w=allEpisodes().filter(e=>e.status==='Watched'&&e.watchedAt),days={};w.forEach(e=>days[e.watchedAt]=(days[e.watchedAt]||0)+1);let keys=Object.keys(days).sort().slice(-35);return keys.length?keys.map(d=>`<div title="${d}: ${days[d]} episode${days[d]>1?'s':''}"><span>${d.slice(5)}</span><b style="opacity:${Math.min(1,.25+days[d]/4)}">${days[d]}</b></div>`).join(''):'No viewing dates yet.'}
function tasteProfile(){let genres={},years={},langs={};state.shows.forEach(s=>{let n=watchedEpisodes(s).length;genreList(s).forEach(g=>genres[g]=(genres[g]||0)+n);if(s.year)years[Math.floor(s.year/10)*10]=(years[Math.floor(s.year/10)*10]||0)+n;if(s.language)langs[s.language]=(langs[s.language]||0)+n});let top=o=>Object.entries(o).sort((a,b)=>b[1]-a[1]).slice(0,6);return `<div class="taste"><p><b>Genres:</b> ${top(genres).map(x=>esc(x[0])).join(', ')||'—'}</p><p><b>Decades:</b> ${top(years).map(x=>x[0]+'s').join(', ')||'—'}</p><p><b>Languages:</b> ${top(langs).map(x=>esc(x[0])).join(', ')||'—'}</p></div>`}
function downloadText(name,text,type='text/plain'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportJSON(){downloadText(`tv-show-tracker-${today()}.json`,JSON.stringify({state,advanced:adv},null,2),'application/json')}
function exportCSV(){let rows=[['Show','Year','Status','Progress','Rating','Genres','Creator','Network','Service','Episode','Season','Episode Number','Watched Date','Episode Rating']];allEpisodes().forEach(e=>rows.push([e.show.title,e.show.year||'',e.show.status,progress(e.show),e.show.rating||'',e.show.genres,e.show.creator,e.show.network,e.show.service,e.title,e.season,e.number,e.watchedAt,e.rating||'']));downloadText(`tv-show-tracker-${today()}.csv`,rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv')}
function importJSON(){let i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=()=>{let f=i.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!d.state?.shows)throw Error('Invalid backup');state={...blank,...d.state};state.shows=(state.shows||[]).map(normalizeShow);adv={...advDefault,...(d.advanced||{})};save();render();alert('Backup restored.')}catch(e){alert('Could not restore this file.')}};r.readAsText(f)};i.click()}
async function encryptedBackup(){let pass=prompt('Create a passphrase for this encrypted backup:');if(!pass)return;let enc=new TextEncoder(),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),base=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:150000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt']);let data=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify({state,advanced:adv})));let pack={version:1,salt:[...salt],iv:[...iv],data:[...new Uint8Array(data)]};downloadText(`tv-show-tracker-encrypted-${today()}.json`,JSON.stringify(pack),'application/json')}
function restoreSnapshot(){let raw=localStorage.getItem(PKEY);if(!raw){adv.snapshots=[];save()}let s=adv.snapshots?.[0];if(!s){alert('No snapshot available.');return}if(!confirm('Restore the most recent local snapshot?'))return;state=s.state;adv=s.advanced;save();render();alert('Snapshot restored.')}
function snapshot(){adv.snapshots=[{createdAt:now(),state:JSON.parse(JSON.stringify(state)),advanced:JSON.parse(JSON.stringify(adv))},...(adv.snapshots||[])].slice(0,5);localStorage.setItem(PKEY,JSON.stringify(adv))}
snapshot();
