const ADV='gratitude-journal:advanced:v3';
let adv=JSON.parse(localStorage.getItem(ADV)||'null')||{reflections:[],prompts:[],favoritePrompts:[],goals:[],letters:[],acts:[],rituals:{morning:true,evening:false},snapshots:[],settings:{graceDays:1,reminder:false,reminderTime:'20:00'}};
const A$=s=>document.querySelector(s),A$$=s=>[...document.querySelectorAll(s)];function advSave(){localStorage.setItem(ADV,JSON.stringify(adv))}function entries(){return window.gratitudeState.get().entries}function avg(es){return es.length?es.reduce((a,e)=>a+Number(e.mood||0),0)/es.length:0}function practiceDays(es){return new Set(es.map(e=>day(e.date))).size}function consistency(es){const p=window.gratitudeState.get().settings.period==='all'?365:Number(window.gratitudeState.get().settings.period);return Math.min(100,Math.round(practiceDays(es)/Math.max(1,p)*100))}
function weekly(es){const out=[];for(let i=11;i>=0;i--){const end=new Date();end.setDate(end.getDate()-i*7);const start=new Date(end);start.setDate(start.getDate()-6);const x=es.filter(e=>{const d=new Date(e.date);return d>=start&&d<=end});out.push({label:new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric'}).format(start),count:x.length})}return out}
function heat(){const all=entries(),now=new Date();return Array.from({length:365},(_,i)=>{const d=new Date(now);d.setDate(d.getDate()-(364-i));const n=all.filter(e=>day(e.date)===day(d)).length;return `<i class="l${Math.min(4,n)}" title="${day(d)} · ${n} gratitude notes"></i>`}).join('')}
function categories(es){const m=new Map();es.forEach(e=>m.set(e.category||'Other',(m.get(e.category||'Other')||0)+1));return [...m].sort((a,b)=>b[1]-a[1])}function people(es){const m=new Map();es.forEach(e=>(e.people||'').split(',').map(x=>x.trim()).filter(Boolean).forEach(p=>m.set(p,(m.get(p)||0)+1)));return [...m].sort((a,b)=>b[1]-a[1]).slice(0,8)}
function badges(){const n=entries().length,s=window.gratitudeStreak();return [['First note',n>=1],['7-day practice',s>=7],['30-day practice',s>=30],['100 notes',n>=100],['50 memories',entries().filter(e=>e.favorite).length>=50],['Three-good-things',entries().some(e=>(e.threeGood||[]).filter(Boolean).length>=3)]].filter(x=>x[1]).map(x=>x[0])}
function renderGratitudeInsights(){const es=rangeEntries(),weeks=weekly(es),cats=categories(es),ppl=people(es);A$('#view').innerHTML=`<div class="panel"><h2>Gratitude insights</h2><p>These describe your practice, not your worth or wellbeing. Associations are observations, not proof of cause.</p><div class="stats"><div><b>${es.length}</b><small>notes</small></div><div><b>${practiceDays(es)}</b><small>days noticed</small></div><div><b>${consistency(es)}%</b><small>practice consistency</small></div><div><b>${avg(es)?avg(es).toFixed(1):'—'}</b><small>logged mood / 5</small></div></div></div><div class="panel"><h3>12-week practice rhythm</h3>${weeks.map(x=>`<div class="metric"><span>${x.label}</span><strong>${x.count} notes</strong></div>`).join('')}</div><div class="panel"><h3>Gratitude themes</h3>${cats.map(x=>`<div class="metric"><span>${esc(x[0])}</span><strong>${x[1]}</strong></div>`).join('')||'<p class="sub">Categories appear as you write.</p>'}</div><div class="panel"><h3>People you appreciate most often</h3>${ppl.map(x=>`<div class="metric"><span>${esc(x[0])}</span><strong>${x[1]}</strong></div>`).join('')||'<p class="sub">Add people to entries to build this private view.</p>'}</div><div class="panel"><h3>365-day gratitude map</h3><div class="heat">${heat()}</div></div>`}
function openGratitudeStudio(){A$('#studioDialog').showModal();renderStudio('overview')}
function renderStudio(tab){A$$('[data-studio]').forEach(b=>b.classList.toggle('active',b.dataset.studio===tab));const s=window.gratitudeState.get(),es=rangeEntries();let html='';
if(tab==='overview')html=`<div class="studio-grid"><div class="studio-card"><span>All notes</span><b>${s.entries.length}</b></div><div class="studio-card"><span>Practice streak</span><b>${window.gratitudeStreak()} days</b></div><div class="studio-card"><span>Saved memories</span><b>${s.entries.filter(e=>e.favorite).length}</b></div><div class="studio-card"><span>Consistency</span><b>${consistency(es)}%</b></div></div><div class="panel"><h3>Gentle review</h3><p>${review(es)}</p><button class="secondary" id="reflectionBtn">Write reflection</button></div><div class="panel"><h3>Milestones</h3><div class="tags">${badges().map(x=>`<span class="tag">✦ ${esc(x)}</span>`).join('')||'<span class="sub">Your first milestone starts with one note.</span>'}</div></div>`;
if(tab==='prompts'){const list=[...new Set([...prompts,...adv.prompts])];html=`<div class="panel"><div class="entry-head"><div><h3>Prompt library</h3><p class="sub">Rotate, favorite and add prompts that feel natural to you.</p></div><button class="secondary" id="addPrompt">+ Prompt</button></div>${list.map((p,i)=>`<div class="metric"><span>${esc(p)}</span><span><button class="secondary" data-fav-prompt="${i}">${adv.favoritePrompts.includes(p)?'★':'☆'}</button> <button class="secondary" data-use-prompt="${i}">Use</button></span></div>`).join('')}</div>`}
if(tab==='rituals')html=`<div class="panel"><h3>Gentle rituals</h3><p>Choose a rhythm without turning gratitude into a performance.</p><label class="check"><input id="morningRitual" type="checkbox" ${adv.rituals.morning?'checked':''}> Morning: one thing I appreciate</label><label class="check"><input id="eveningRitual" type="checkbox" ${adv.rituals.evening?'checked':''}> Evening: one moment worth remembering</label><button class="primary" id="runRitual">Start ritual</button></div><div class="panel"><h3>Reminder preference</h3><label class="check"><input id="reminderToggle" type="checkbox" ${adv.settings.reminder?'checked':''}> Ask for a browser reminder when this app is open</label><label>Preferred time<input id="reminderTime" type="time" value="${adv.settings.reminderTime}"></label><button class="secondary" id="notifyPermission">Enable notification permission</button><p class="sub">GitHub Pages cannot guarantee background notifications after the browser is closed.</p></div>`;
if(tab==='insights')html=`<div class="panel"><h3>Practice profile</h3><div class="metric"><span>Average notes per active day</span><strong>${practiceDays(es)?(es.length/practiceDays(es)).toFixed(1):'—'}</strong></div><div class="metric"><span>Most common category</span><strong>${categories(es)[0]?.[0]||'—'}</strong></div><div class="metric"><span>Most appreciated person</span><strong>${people(es)[0]?.[0]||'—'}</strong></div><div class="metric"><span>Three-good-things entries</span><strong>${es.filter(e=>(e.threeGood||[]).filter(Boolean).length>=3).length}</strong></div></div><div class="panel"><h3>Keep it gentle</h3><p>Missing a day is not failure. The goal is noticing and savoring, not maintaining a perfect streak.</p></div>`;
if(tab==='letters')html=`<div class="panel"><div class="entry-head"><div><h3>Appreciation letters</h3><p class="sub">Write a private thank-you letter. Nothing is sent automatically.</p></div><button class="secondary" id="newLetter">+ Letter</button></div>${adv.letters.slice().reverse().map(l=>`<article class="entry"><div class="entry-head"><b>${esc(l.to||'Someone')}</b><small>${new Date(l.date).toLocaleDateString()}</small></div><p>${esc(l.text)}</p><button class="secondary" data-copy-letter="${l.id}">Copy</button></article>`).join('')||'<p class="sub">No letters yet.</p>'}</div><div class="panel"><h3>Acts of appreciation</h3><button class="secondary" id="newAct">Log an act</button>${adv.acts.slice().reverse().map(a=>`<div class="metric"><span>${esc(a.text)}</span><small>${new Date(a.date).toLocaleDateString()}</small></div>`).join('')}</div>`;
if(tab==='goals')html=`<div class="panel"><div class="entry-head"><h3>Practice goals</h3><button class="secondary" id="newGoal">+ Goal</button></div>${adv.goals.map(g=>{const n=s.entries.filter(e=>new Date(e.date)>=new Date(g.start)).length,p=Math.min(100,Math.round(n/g.target*100));return `<div class="goal"><div class="goal-head"><b>${esc(g.name)}</b><span>${n}/${g.target}</span></div><div class="bar"><i style="width:${p}%"></i></div></div>`}).join('')||'<p class="sub">Set a note-count goal for a personal journey.</p>'}</div>`;
if(tab==='data')html=`<div class="panel"><h3>Private data tools</h3><p>Journal text stays in this browser. Media attachments stay in IndexedDB on this device. Encrypted exports protect the journal database, but browser-local media is not included in that encrypted file.</p><div class="data-buttons"><button class="secondary" id="exportJson">JSON backup</button><button class="secondary" id="exportCsv">CSV export</button><button class="secondary" id="exportHtml">HTML archive</button><button class="secondary" id="encryptedExport">Encrypted backup</button><button class="secondary" id="snapshot">Create restore point</button><button class="secondary" id="restore">Restore point</button><button class="danger" id="importJson">Import JSON</button><button class="danger" id="encryptedImport">Import encrypted</button></div><small class="sub">AES-256-GCM + PBKDF2-SHA-256. Passwords are never stored.</small></div>`;
A$('#studioContent').innerHTML=html;bindStudio(tab)}
function review(es){if(!es.length)return'Start with one small observation. A meaningful gratitude practice can be brief.';return `You recorded ${es.length} gratitude notes across ${practiceDays(es)} days in this period. Look for specific, ordinary details that you want to notice again.`}
function bindStudio(tab){if(tab==='overview')A$('#reflectionBtn').onclick=reflection;if(tab==='prompts'){const list=[...new Set([...prompts,...adv.prompts])];A$('#addPrompt').onclick=addPrompt;A$$('[data-fav-prompt]').forEach(b=>b.onclick=()=>{const p=list[+b.dataset.favPrompt];adv.favoritePrompts=adv.favoritePrompts.includes(p)?adv.favoritePrompts.filter(x=>x!==p):[...adv.favoritePrompts,p];advSave();renderStudio('prompts')});A$$('[data-use-prompt]').forEach(b=>b.onclick=()=>{window.gratitudeState.openEntry(null,null,{note:list[+b.dataset.usePrompt]+'\n\n'});A$('#studioDialog').close()})}if(tab==='rituals'){A$('#morningRitual').onchange=e=>{adv.rituals.morning=e.target.checked;advSave()};A$('#eveningRitual').onchange=e=>{adv.rituals.evening=e.target.checked;advSave()};A$('#runRitual').onclick=()=>{const p=adv.rituals.evening?'What moment from today is worth remembering?':'What is one thing you appreciate right now?';window.gratitudeState.openEntry(null,null,{note:p+'\n\n'});A$('#studioDialog').close()};A$('#reminderToggle').onchange=e=>{adv.settings.reminder=e.target.checked;advSave();toast(e.target.checked?'Reminder preference saved':'Reminder preference off')};A$('#reminderTime').onchange=e=>{adv.settings.reminderTime=e.target.value;advSave()};A$('#notifyPermission').onclick=async()=>{if('Notification'in window){const p=await Notification.requestPermission();toast(p==='granted'?'Notifications enabled':'Notification permission not enabled')}else toast('Notifications are not supported here')}}if(tab==='letters'){A$('#newLetter').onclick=newLetter;A$('#newAct').onclick=newAct;A$$('[data-copy-letter]').forEach(b=>b.onclick=()=>{const l=adv.letters.find(x=>x.id===b.dataset.copyLetter);navigator.clipboard?.writeText(l?.text||'');toast('Letter copied')})}if(tab==='goals')A$('#newGoal').onclick=goal;if(tab==='data'){A$('#exportJson').onclick=exportJSON;A$('#exportCsv').onclick=exportCSV;A$('#exportHtml').onclick=exportHTML;A$('#encryptedExport').onclick=encryptedExport;A$('#importJson').onclick=importJSON;A$('#encryptedImport').onclick=encryptedImport;A$('#snapshot').onclick=snapshot;A$('#restore').onclick=restore}}
A$$('[data-studio]').forEach(b=>b.onclick=()=>renderStudio(b.dataset.studio));
function reflection(){const text=prompt('What are you noticing or appreciating lately?');if(!text)return;adv.reflections.push({id:crypto.randomUUID(),date:new Date().toISOString(),text});advSave();toast('Reflection saved')}
function addPrompt(){const p=prompt('Write your own gratitude prompt');if(!p?.trim())return;adv.prompts.push(p.trim());advSave();renderStudio('prompts');toast('Prompt added')}
function newLetter(){const to=prompt('Who is this appreciation for?','Someone I appreciate');if(!to)return;const text=prompt('Write your private thank-you letter');if(!text)return;adv.letters.push({id:crypto.randomUUID(),date:new Date().toISOString(),to,text});advSave();renderStudio('letters');toast('Letter saved privately')}
function newAct(){const text=prompt('What act of appreciation did you do or want to remember?');if(!text)return;adv.acts.push({id:crypto.randomUUID(),date:new Date().toISOString(),text});advSave();renderStudio('letters');toast('Act logged')}
function goal(){const name=prompt('Goal name','Notice 20 good moments');if(!name)return;const target=Math.max(1,Number(prompt('How many notes?','20'))||20);adv.goals.push({id:crypto.randomUUID(),name,target,start:new Date().toISOString()});advSave();renderStudio('goals');toast('Goal created')}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportJSON(){download('gratitude-journal-backup.json',JSON.stringify({app:window.gratitudeState.get(),advanced:adv},null,2));toast('JSON backup exported')}
function exportCSV(){const rows=[['date','note','people','place','category','mood','why','impact','tags','favorite']];entries().forEach(e=>rows.push([e.date,e.note,e.people,e.place,e.category,e.mood,e.why,e.impact,(e.tags||[]).join('|'),e.favorite]));download('gratitude-journal.csv',rows.map(r=>r.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv');toast('CSV exported')}
function exportHTML(){const body=entries().map(e=>`<article><h2>${esc(new Date(e.date).toLocaleString())}</h2><p>${esc(e.note)}</p>${e.why?`<p><b>Why:</b> ${esc(e.why)}</p>`:''}${e.impact?`<p><b>Savor / pass forward:</b> ${esc(e.impact)}</p>`:''}<small>${esc(e.category)}${e.people?' · '+esc(e.people):''}${e.place?' · '+esc(e.place):''}</small></article>`).join('');download('gratitude-journal-archive.html',`<!doctype html><meta charset="utf-8"><title>Gratitude Journal</title><style>body{font:16px system-ui;max-width:760px;margin:40px auto;padding:0 16px}article{padding:20px 0;border-bottom:1px solid #ddd}</style>${body}`,'text/html');toast('HTML archive exported')}
function snapshot(){const s=window.gratitudeState.get();adv.snapshots.push({at:new Date().toISOString(),state:JSON.parse(JSON.stringify(s)),advanced:JSON.parse(JSON.stringify(adv))});adv.snapshots=adv.snapshots.slice(-12);advSave();toast('Restore point created')}
function restore(){if(!adv.snapshots.length)return toast('No restore points');const lines=adv.snapshots.map((x,i)=>`${i+1}. ${new Date(x.at).toLocaleString()}`).join('\n');const n=Number(prompt('Choose restore point:\n'+lines));if(!n||!adv.snapshots[n-1])return;const x=adv.snapshots[n-1];localStorage.setItem(KEY,JSON.stringify(x.state));Object.assign(window.gratitudeState.get(),x.state);adv=x.advanced;advSave();A$('#studioDialog').close();window.gratitudeState.render();toast('Restored')}
async function derive(password,salt){return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']),{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptedExport(){const p=prompt('Create a password for this backup');if(!p)return;const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await derive(p,salt),data=new TextEncoder().encode(JSON.stringify({app:window.gratitudeState.get(),advanced:adv}));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,data);download('gratitude-journal-encrypted.mjenc',JSON.stringify({version:1,algorithm:'AES-256-GCM',kdf:'PBKDF2-SHA-256',iterations:120000,salt:[...salt],iv:[...iv],data:[...new Uint8Array(cipher)]}),'application/json');toast('Encrypted backup exported')}
function pick(cb){const i=document.createElement('input');i.type='file';i.accept='.json,.mjenc';i.onchange=()=>{const r=new FileReader();r.onload=()=>cb(r.result);r.readAsText(i.files[0])};i.click()}
function importJSON(){pick(txt=>{try{const p=JSON.parse(txt);if(!p.app?.entries)throw Error();localStorage.setItem(KEY,JSON.stringify(p.app));Object.assign(window.gratitudeState.get(),p.app);Object.assign(adv,p.advanced||{});advSave();window.gratitudeState.render();toast('Backup imported')}catch{toast('Invalid backup')}})}
async function encryptedImport(){pick(async txt=>{try{const p=JSON.parse(txt),pass=prompt('Enter backup password');if(!pass)return;const key=await derive(pass,new Uint8Array(p.salt)),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(p.iv)},key,new Uint8Array(p.data)),x=JSON.parse(new TextDecoder().decode(plain));if(!x.app?.entries)throw Error();Object.assign(window.gratitudeState.get(),x.app);Object.assign(adv,x.advanced||{});localStorage.setItem(KEY,JSON.stringify(x.app));advSave();window.gratitudeState.render();toast('Encrypted backup restored')}catch{toast('Could not decrypt backup')}})}
window.openGratitudeStudio=openGratitudeStudio;window.renderGratitudeInsights=renderGratitudeInsights;window.exportGratitudeJSON=exportJSON;window.importGratitudeJSON=importJSON;