const KEY='gratitude-journal:v1';
const prompts=[
 'What is something small that made today better?','Who made a difference in your life recently?','What ordinary comfort are you glad to have?','What part of your body or health are you thankful for?','What did you learn that you appreciate knowing?','What place makes you feel at ease?','What is a recent moment you wish you could replay?','What challenge taught you something valuable?','What simple pleasure deserves more attention?','What quality in yourself are you learning to appreciate?','What in nature caught your attention?','What made you laugh or smile recently?'
];
const defaults={version:1,theme:'system',entries:[],settings:{period:'30'},promptIndex:0};
let state=load(),view='today',query='';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const day=d=>new Date(d).toLocaleDateString('en-CA');
const today=()=>day(new Date());
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return {...defaults,...x,settings:{...defaults.settings,...(x?.settings||{})}}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));window.gratitudeState=state;render()}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),1800)}
function entries(){return [...state.entries].sort((a,b)=>new Date(b.date)-new Date(a.date))}
function rangeEntries(){const p=state.settings.period;if(p==='all')return entries();const cut=Date.now()-Number(p)*86400000;return entries().filter(e=>new Date(e.date)>=cut)}
function streak(){const days=new Set(state.entries.map(e=>day(e.date)));let n=0,d=new Date();while(days.has(day(d))){n++;d.setDate(d.getDate()-1)}return n}
function render(){document.body.classList.toggle('dark',state.theme==='dark'||(state.theme==='system'&&matchMedia('(prefers-color-scheme:dark)').matches));$('#dateLabel').textContent=new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric'}).format(new Date());$('#streak').textContent=streak();const t=entries().find(e=>day(e.date)===today());$('#heroTitle').textContent=t?'What are you grateful for today?':'What are you grateful for today?';renderView();renderStats()}
function filtered(){let es=rangeEntries();if(query){const q=query.toLowerCase();es=es.filter(e=>[e.note,e.people,e.place,e.category,(e.tags||[]).join(' ')].join(' ').toLowerCase().includes(q))}return es}
function renderView(){syncTabs();if(view==='calendar')return calendar();if(view==='insights')return window.renderGratitudeInsights?.();if(view==='memories')return memories();const es=view==='today'?filtered().filter(e=>day(e.date)===today()):filtered();$('#view').innerHTML=es.length?es.map(card).join(''):`<div class="empty"><h3>${view==='today'?'Begin with one small thing.':'Nothing found'}</h3><p>${view==='today'?'Gratitude can be one sentence. No perfect wording needed.':'Try a different search or time period.'}</p><button class="primary" id="emptyNew">+ Gratitude</button></div>`;$('#emptyNew')?.addEventListener('click',()=>openEntry());$$('[data-edit]').forEach(b=>b.onclick=()=>openEntry(b.dataset.edit));$$('[data-fav]').forEach(b=>b.onclick=()=>{const e=find(b.dataset.fav);e.favorite=!e.favorite;save()})}
function card(e){return `<article class="entry"><div class="entry-head"><div><h3>${esc(e.note.split('\n')[0].slice(0,90))}</h3><div class="entry-meta">${new Date(e.date).toLocaleString([], {weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})} · ${esc(e.category)}${e.people?' · '+esc(e.people):''}${e.place?' · '+esc(e.place):''}</div></div><div class="entry-actions"><button data-fav="${e.id}">${e.favorite?'★':'☆'}</button><button data-edit="${e.id}">Edit</button></div></div><p>${esc(e.note)}</p><div class="tags">${(e.tags||[]).map(x=>`<span class="tag">#${esc(x)}</span>`).join('')}</div></article>`}
function memories(){const es=entries().filter(e=>e.favorite);$('#view').innerHTML=`<div class="panel"><h2>Memories worth keeping</h2><p class="sub">Your saved moments, gathered in one quiet place.</p>${es.length?es.map(card).join(''):'<div class="empty"><h3>No saved memories yet</h3><p>Tap ☆ on a gratitude entry to keep it here.</p></div>'}</div>`;$$('[data-edit]').forEach(b=>b.onclick=()=>openEntry(b.dataset.edit));$$('[data-fav]').forEach(b=>b.onclick=()=>{const e=find(b.dataset.fav);e.favorite=!e.favorite;save()})}
function calendar(){const now=window.calMonth||new Date(),y=now.getFullYear(),m=now.getMonth(),start=(new Date(y,m,1).getDay()+6)%7,last=new Date(y,m+1,0).getDate();let h=`<div class="panel"><div class="entry-head"><button class="secondary" id="calPrev">←</button><h2>${new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(now)}</h2><button class="secondary" id="calNext">→</button></div><div class="calendar">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="cal-head">${x}</div>`).join('')}`;for(let i=0;i<42;i++){const n=i-start+1,d=new Date(y,m,n),k=day(d),es=state.entries.filter(e=>day(e.date)===k);h+=`<button class="cal-day ${n<1||n>last?'muted':''} ${es.length?'has':''}" data-day="${k}"><strong>${d.getDate()}</strong>${es.length?`<small>✦ ${es.length}</small>`:''}</button>`}h+='</div></div>';$('#view').innerHTML=h;$('#calPrev').onclick=()=>{window.calMonth=new Date(y,m-1,1);render()};$('#calNext').onclick=()=>{window.calMonth=new Date(y,m+1,1);render()};$$('[data-day]').forEach(b=>b.onclick=()=>{const es=state.entries.filter(e=>day(e.date)===b.dataset.day);if(es.length){view='timeline';query='';render()}else openEntry(null,b.dataset.day)})}
function renderStats(){const es=rangeEntries(),days=new Set(es.map(e=>day(e.date)));$('#stats').innerHTML=`<div><b>${es.length}</b><small>gratitude notes</small></div><div><b>${days.size}</b><small>days noticed</small></div><div><b>${state.entries.filter(e=>e.favorite).length}</b><small>memories</small></div><div><b>${window.gratitudeStreak?.()??streak()}</b><small>day practice</small></div>`}
function find(id){return state.entries.find(e=>e.id===id)}
function localISO(d){const x=new Date(d),p=n=>String(n).padStart(2,'0');return `${x.getFullYear()}-${p(x.getMonth()+1)}-${p(x.getDate())}T${p(x.getHours())}:${p(x.getMinutes())}`}
function openEntry(id=null,date=null,preset=null){const e=id?find(id):null;$('#entryForm').reset();$('#entryId').value=e?.id||'';$('#modalTitle').textContent=e?'Edit gratitude':'New gratitude';$('#entryDate').value=localISO(e?.date||(date?new Date(date+'T12:00'):new Date()));$('#note').value=e?.note||preset?.note||'';$('#people').value=e?.people||preset?.people||'';$('#place').value=e?.place||preset?.place||'';$('#category').value=e?.category||preset?.category||'Moments';$('#mood').value=e?.mood||preset?.mood||'5';$('#tags').value=(e?.tags||preset?.tags||[]).join(', ');$('#favorite').checked=!!e?.favorite;const p=prompts[state.promptIndex%prompts.length];$('#promptBox').innerHTML=`<b>Prompt</b> · ${esc(p)} <button type="button" id="usePrompt">Use</button>`;$('#usePrompt').onclick=()=>{$('#note').value=p+'\n\n';$('#note').focus()};$('#deleteEntry').style.display=e?'block':'none';$('#entryDialog').showModal()}
function formData(){const id=$('#entryId').value||uid(),old=find(id);return{id,date:new Date($('#entryDate').value).toISOString(),note:$('#note').value.trim(),people:$('#people').value.trim(),place:$('#place').value.trim(),category:$('#category').value,mood:+$('#mood').value,tags:$('#tags').value.split(',').map(x=>x.trim()).filter(Boolean),favorite:$('#favorite').checked,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()}}
$('#entryForm').onsubmit=e=>{e.preventDefault();const d=formData();if(!d.note)return toast('Write one small thing first');const old=find(d.id);if(old)Object.assign(old,d);else state.entries.push(d);state.promptIndex++;save();$('#entryDialog').close();toast(old?'Gratitude updated':'Gratitude saved')};$('#deleteEntry').onclick=()=>{const id=$('#entryId').value;if(id&&confirm('Delete this gratitude?')){state.entries=state.entries.filter(e=>e.id!==id);save();$('#entryDialog').close();toast('Deleted')}};
$('#newBtn').onclick=()=>openEntry();$('#studioBtn').onclick=()=>window.openGratitudeStudio?.();$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':state.theme==='light'?'system':'dark';save()};$('#search').oninput=e=>{query=e.target.value;renderView()};$('#period').value=state.settings.period;$('#period').onchange=e=>{state.settings.period=e.target.value;save()};$('#randomBtn').onclick=()=>{const es=state.entries.filter(e=>e.note);if(!es.length)return toast('Write a few memories first');openEntry(es[Math.floor(Math.random()*es.length)].id)};$$('#tabs button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});$$('.quick').forEach(b=>b.onclick=()=>quick(b.dataset.quick));
function quick(type){const p={tiny:{},people:{category:'People'},moment:{category:'Moments'},prompt:{note:prompts[state.promptIndex%prompts.length]+'\n\n'}}[type]||{};openEntry(null,null,p)}
function syncTabs(){$$('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
window.gratitudeState={get:()=>state,save,render,openEntry,exportJSON:()=>window.exportGratitudeJSON?.(),importJSON:()=>window.importGratitudeJSON?.()};window.state=state;window.gratitudeStreak=streak;render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});