const MEDIA_DB='gratitude-journal-media-v1';
let mediaDbPromise=null;
function mediaDb(){if(mediaDbPromise)return mediaDbPromise;mediaDbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open(MEDIA_DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('files',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return mediaDbPromise}
const mediaUid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();
async function mediaPut(entryId,file){const db=await mediaDb();return new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite'),o=tx.objectStore('files'),id=mediaUid();o.put({id,entryId,name:file.name,type:file.type,size:file.size,createdAt:new Date().toISOString(),blob:file});tx.oncomplete=()=>resolve(id);tx.onerror=()=>reject(tx.error)})}
async function mediaList(entryId){const db=await mediaDb();return new Promise((resolve,reject)=>{const tx=db.transaction('files','readonly'),r=tx.objectStore('files').getAll();r.onsuccess=()=>resolve(r.result.filter(x=>x.entryId===entryId));r.onerror=()=>reject(r.error)})}
async function mediaDelete(id){const db=await mediaDb();return new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function renderMedia(entryId){const box=document.querySelector('#existingMedia');if(!box)return;const items=await mediaList(entryId);box.innerHTML=items.length?items.map(x=>`<div class="media-item"><span>${x.type.startsWith('image/')?'Image':x.type.startsWith('audio/')?'Audio':x.type.startsWith('video/')?'Video':'File'} · ${esc(x.name)}</span><button type="button" class="secondary" data-media-delete="${x.id}">Remove</button></div>`).join(''):'<span class="sub">No attachments yet.</span>';box.querySelectorAll('[data-media-delete]').forEach(b=>b.onclick=async()=>{await mediaDelete(b.dataset.mediaDelete);renderMedia(entryId);toast('Attachment removed')})}
async function saveGratitudeMedia(entryId){const input=document.querySelector('#mediaFiles');if(!input?.files?.length)return;for(const file of input.files){if(file.size>15*1024*1024){toast('Attachment skipped: 15 MB limit');continue}await mediaPut(entryId,file)}input.value='';await renderMedia(entryId);toast('Attachment saved')}
window.gratitudeMedia={list:mediaList,remove:mediaDelete,render:renderMedia,save:saveGratitudeMedia};