const AKEY='personal-journal:advanced:v1';
const ADEFAULT={promptsEnabled:true,weeklyGoal:3,reflectionHistory:[],snapshots:[],templates:[{id:'gratitude',name:'Gratitude',body:'## Three things I’m grateful for\n\n1. \n2. \n3. \n\nWhat made them meaningful?'},{id:'daily',name:'Daily reflection',body:'## Today\n\nWhat happened?\n\n## How I felt\n\n\n## What I learned\n\n\n## Tomorrow\n\n'}]};
let advanced=(()=>{try{return {...ADEFAULT,...JSON.parse(localStorage.getItem(AKEY))}}catch{return {...ADEFAULT}}})();
function saveAdvanced(){localStorage.setItem(AKEY,JSON.stringify(advanced));window.render?.()}
function stats(){const s=window.state||{};const entries=s.entries||[];const dates=new Set(entries.map(e=>e.date));const now=new Date();let week=0;for(let i=0;i<7;i++){const d=new Date(now);d.setDate(d.getDate()-i);if(dates.has(dayKey(d)))week++}const recent=entries.filter(e=>Date.now()-new Date(e.created).getTime()<30*864e5);const avg=recent.length?Math.round(recent.reduce((n,e)=>n+wordCount(e),0)/recent.length):0;return{entries:entries.length,days:dates.size,week,avg,rate:Math.round((week/7)*100)}}
function dayKey(d){const x=new Date(d);return x.getFullYear()+'-'+String(x.getMonth()+1).padStart(2,'0')+'-'+String(x.getDate()).padStart(2,'0')}
function wordCount(e){const x=document.createElement('div');x.innerHTML=e.body||'';return(x.textContent||'').trim().split(/\s+/).filter(Boolean).length}
function openAdvanced(){document.querySelector('#smallTitle').textContent='Journal Studio';document.querySelector('#smallBody').innerHTML=`<div class="grid"><div class="stat-card"><b>${stats().entries}</b><span>Entries</span></div><div class="stat-card"><b>${stats().days}</b><span>Writing days</span></div><div class="stat-card"><b>${stats().week}/${advanced.weeklyGoal}</b><span>This week</span></div><div class="stat-card"><b>${stats().avg}</b><span>Avg words / recent entry</span></div></div><div class="insight-card"><h3>Reflection tools</h3><p class="muted">Reusable templates, guided prompts and lightweight weekly reflection — all stored locally.</p><div class="card-actions"><button id="studioPrompt" class="primary">Prompt me</button><button id="templateList">Templates</button><button id="snapshotBtn">Create restore point</button></div></div><div class="insight-card"><h3>Data tools</h3><div class="card-actions"><button id="backupAll">Full JSON backup</button><button id="csvAdvanced">Enriched CSV</button><button id="manageSnapshots">Restore points (${advanced.snapshots.length})</button></div></div><div class="insight-card"><h3>Weekly reflection</h3><textarea id="reflection" style="width:100%;min-height:100px;border:1px solid var(--line);border-radius:10px;padding:10px;background:var(--bg);color:var(--text)" placeholder="What do you want to carry forward from this week?"></textarea><div class="dialog-actions"><button id="saveReflection" class="primary">Save reflection</button></div></div>`;document.querySelector('#smallModal').classList.remove('hidden');document.querySelector('#studioPrompt').onclick=()=>{closeModals();showPromptAdvanced()};document.querySelector('#templateList').onclick=templates;document.querySelector('#snapshotBtn').onclick=createSnapshot;document.querySelector('#backupAll').onclick=fullBackup;document.querySelector('#csvAdvanced').onclick=enrichedCSV;document.querySelector('#manageSnapshots').onclick=manageSnapshots;document.querySelector('#saveReflection').onclick=()=>{const text=document.querySelector('#reflection').value.trim();if(text){advanced.reflectionHistory.unshift({date:dayKey(new Date()),text});advanced.reflectionHistory=advanced.reflectionHistory.slice(0,52);saveAdvanced();toast('Reflection saved')}}}
function showPromptAdvanced(){const p=prompts[Math.floor(Math.random()*prompts.length)];document.querySelector('#smallTitle').textContent='Guided prompt';document.querySelector('#smallBody').innerHTML=`<div class="prompt">${esc(p)}</div><div class="dialog-actions"><button id="promptWrite" class="primary">Write about this</button><button data-close>Later</button></div>`;document.querySelector('#smallModal').classList.remove('hidden');document.querySelector('#promptWrite').onclick=()=>{closeModals();openEditor();setTimeout(()=>document.querySelector('#entryTitle').value='Reflection · '+new Date().toLocaleDateString(),50)}}
function templates(){document.querySelector('#smallTitle').textContent='Journal templates';document.querySelector('#smallBody').innerHTML=`<div class="timeline">${advanced.templates.map(t=>`<div class="entry-card"><h3>${esc(t.name)}</h3><div class="excerpt">${esc(t.body)}</div><div class="card-actions"><button data-template="${esc(t.id)}" class="primary">Use template</button></div></div>`).join('')}<button id="newTemplate">+ Create template</button></div>`;document.querySelector('#smallModal').classList.remove('hidden');document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>{const t=advanced.templates.find(x=>x.id===b.dataset.template);closeModals();openEditor();setTimeout(()=>document.querySelector('#entryBody').innerHTML=esc(t.body).replace(/\n/g,'<br>'),50)});document.querySelector('#newTemplate').onclick=()=>{const name=prompt('Template name');const body=prompt('Template text');if(name&&body){advanced.templates.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name,body});saveAdvanced();templates()}}}
function createSnapshot(){const s=window.state||{};advanced.snapshots.unshift({id:Date.now(),at:new Date().toISOString(),entries:JSON.parse(JSON.stringify(s.entries||[])),journals:[...(s.journals||[])]});advanced.snapshots=advanced.snapshots.slice(0,12);saveAdvanced();toast('Restore point created')}
function manageSnapshots(){document.querySelector('#smallTitle').textContent='Restore points';document.querySelector('#smallBody').innerHTML=advanced.snapshots.length?advanced.snapshots.map((x,i)=>`<div class="setting-row"><div><b>${new Date(x.at).toLocaleString()}</b><small>${x.entries.length} entries</small></div><button data-restore="${i}">Restore</button></div>`).join(''):'<div class="empty">No restore points yet.</div>';document.querySelector('#smallModal').classList.remove('hidden');document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{const x=advanced.snapshots[+b.dataset.restore];if(confirm('Restore this point? Current entries will be replaced.')){window.state.entries=x.entries;window.state.journals=x.journals;window.save();closeModals();toast('Restore complete')}})}
function fullBackup(){const payload={version:1,exportedAt:new Date().toISOString(),core:window.state,advanced};download('personal-journal-full-backup.json','application/json',JSON.stringify(payload,null,2));toast('Full backup exported')}
function enrichedCSV(){const entries=window.state?.entries||[];const rows=[['date','time','title','mood','weather','location','tags','journal','favorite','private','words'],...entries.map(e=>[e.date,e.time,e.title,e.mood,e.weather,e.location,e.tags.join('|'),e.journal,e.favorite,e.private,wordCount(e)])].map(r=>r.map(x=>'"'+String(x??'').replace(/"/g,'""')+'"').join(','));download('personal-journal-enriched.csv','text/csv',rows.join('\n'));toast('Enriched CSV exported')}
function installStudio(){const s=document.querySelector('#settingsBtn');if(!s||document.querySelector('#studioBtn'))return;const b=document.createElement('button');b.id='studioBtn';b.textContent='Studio';b.title='Journal intelligence and restore tools';s.parentElement.insertBefore(b,s);b.onclick=openAdvanced}
const originalSettings=window.settings;window.settings=()=>{if(originalSettings)originalSettings();setTimeout(installStudio,0)};
const originalRender=window.render;window.render=()=>{originalRender();installStudio()};installStudio();