const KEY='personal-journal:v1';
const prompts=['What made you smile today?','What are you grateful for right now?','What did you learn today?','What felt difficult, and what helped?','What is one thing you want to remember about today?','What are you looking forward to?','Describe a small moment you usually overlook.','What would you tell your future self about today?','What gave you energy today?','What would make tomorrow a little better?'];
const uid=()=>crypto.randomUUID?crypto.randomUUID():'e-'+Date.now()+'-'+Math.random().toString(36).slice(2);
const dayKey=d=>{const x=new Date(d);return x.getFullYear()+'-'+String(x.getMonth()+1).padStart(2,'0')+'-'+String(x.getDate()).padStart(2,'0')};
const today=()=>dayKey(new Date());
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[m]));
const strip=s=>{const t=document.createElement('div');t.innerHTML=s||'';return t.textContent||''};
const defaults={theme:'system',defaultJournal:'Personal',promptIndex:0,lock:false,pinHash:'',sort:'newest'};
let state=load(); let editingId=null; let activeView='timeline';
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x&&Array.isArray(x.entries))return {...{journals:['Personal'],templates:[],settings:defaults,history:[]},...x,settings:{...defaults,...x.settings}}}catch{}return{journals:['Personal'],entries:[],templates:[],settings:{...defaults},history:[]}}
function save(){window.state=state;localStorage.setItem(KEY,JSON.stringify(state));render()}
function toast(m){const e=document.querySelector('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function fmtDate(s){return new Date(s+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}
function fmtTime(s){return new Date(s).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}
function wordCount(e){return strip(e.body).trim().split(/\s+/).filter(Boolean).length}
function activeEntries(){const q=document.querySelector('#search').value.trim().toLowerCase();const jf=document.querySelector('#journalFilter').value;const tf=document.querySelector('#tagFilter').value;const mf=document.querySelector('#moodFilter').value;let a=state.entries.filter(e=>(jf==='all'||e.journal===jf)&&(tf==='all'||e.tags.includes(tf))&&(mf==='all'||e.mood===mf));if(q)a=a.filter(e=>(e.title+' '+strip(e.body)+' '+e.tags.join(' ')+' '+e.mood).toLowerCase().includes(q));if(activeView==='favorites')a=a.filter(e=>e.favorite);if(activeView==='onthisday'){const md=new Date().toISOString().slice(5,10);a=a.filter(e=>e.date.slice(5)===md)}return a.sort((a,b)=>new Date(b.date+'T'+b.time)-new Date(a.date+'T'+a.time))}
function render(){document.querySelector('#todayLabel').textContent=new Date().toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});const words=state.entries.reduce((n,e)=>n+wordCount(e),0);document.querySelector('#entryStat').textContent=state.entries.length;document.querySelector('#wordStat').textContent=words.toLocaleString();document.querySelector('#streakStat').textContent=streak();fillFilters();document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===activeView));const v=document.querySelector('#view');if(activeView==='calendar')renderCalendar(v);else if(activeView==='insights')renderInsights(v);else renderTimeline(v)}
function fillFilters(){const j=document.querySelector('#journalFilter'),t=document.querySelector('#tagFilter'),m=document.querySelector('#moodFilter');const jv=j.value,tv=t.value,mv=m.value;j.innerHTML='<option value="all">All journals</option>'+state.journals.map(x=>`<option>${esc(x)}</option>`).join('');j.value=state.journals.includes(jv)?jv:'all';const tags=[...new Set(state.entries.flatMap(e=>e.tags))].sort();t.innerHTML='<option value="all">All tags</option>'+tags.map(x=>`<option>${esc(x)}</option>`).join('');t.value=tags.includes(tv)?tv:'all';const moods=[...new Set(state.entries.map(e=>e.mood).filter(Boolean))];m.innerHTML='<option value="all">All moods</option>'+moods.map(x=>`<option>${esc(x)}</option>`).join('');m.value=moods.includes(mv)?mv:'all'}
function renderTimeline(v){const a=activeEntries();v.innerHTML=`<div class="timeline">${a.length?a.map(card).join(''):`<div class="empty"><h3>${activeView==='onthisday'?'No memories for this date yet.':'Your journal is waiting.'}</h3><p>Write a few lines, capture a moment, or start with a prompt.</p><button class="primary" id="emptyNew">Write an entry</button></div>`}</div>`;document.querySelector('#emptyNew')?.addEventListener('click',()=>openEditor())}
function card(e){const excerpt=strip(e.body);return`<article class="entry-card"><div class="date"><span>${fmtDate(e.date)} · ${fmtTime(e.created)}</span><span>${e.favorite?'★ ':''}${e.mood?`<span class="mood">${esc(e.mood)}</span>`:''}</span></div><h3>${esc(e.title||'Untitled entry')}</h3><div class="excerpt">${esc(excerpt||'No text yet.')}</div>${e.tags.length?`<div class="chips">${e.tags.map(t=>`<span class="chip">#${esc(t)}</span>`).join('')}</div>`:''}<div class="card-actions"><button data-edit="${e.id}">Open</button><button data-dup="${e.id}">Duplicate</button><button data-fav="${e.id}">${e.favorite?'Unfavorite':'Favorite'}</button></div></article>`}
function renderCalendar(v){const base=new Date();base.setDate(1);const y=base.getFullYear(),m=base.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate();let h='<div class="calendar">';['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].forEach(x=>h+=`<div class="cal-head">${x}</div>`);for(let i=0;i<42;i++){const n=i-first+1;let num=n,mm=m,yy=y,muted=false;if(n<1){num=prev+n;mm=m-1;muted=true}else if(n>days){num=n-days;mm=m+1;muted=true}const key=dayKey(new Date(yy,mm,num));const count=state.entries.filter(e=>e.date===key).length;h+=`<div class="cal-day ${muted?'muted':''} ${count?'has-entry':''}" data-date="${key}"><strong>${num}</strong>${count?`<div class="dots">● ${count} ${count===1?'entry':'entries'}</div>`:''}</div>`}h+='</div>';v.innerHTML=h;v.querySelectorAll('.cal-day').forEach(d=>d.onclick=()=>{openEditor(null,d.dataset.date)})}
function renderInsights(v){const total=state.entries.length,words=state.entries.reduce((n,e)=>n+wordCount(e),0),fav=state.entries.filter(e=>e.favorite).length;const moods={};state.entries.forEach(e=>{if(e.mood)moods[e.mood]=(moods[e.mood]||0)+1});const top=Object.entries(moods).sort((a,b)=>b[1]-a[1])[0];const days=[];for(let i=20;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const c=state.entries.filter(e=>e.date===dayKey(d)).length;days.push(`<span class="heat l${Math.min(4,c)}" title="${dayKey(d)}: ${c} entries"></span>`)}v.innerHTML=`<div class="grid"><div class="stat-card"><b>${total}</b><span>Total entries</span></div><div class="stat-card"><b>${words.toLocaleString()}</b><span>Total words</span></div><div class="stat-card"><b>${streak()}</b><span>Current streak</span></div><div class="stat-card"><b>${fav}</b><span>Favorites</span></div><div class="stat-card"><b>${top?esc(top[0]):'—'}</b><span>Most logged mood</span></div><div class="stat-card"><b>${avgWords()}</b><span>Average words / entry</span></div></div><div class="insight-card"><h3>Recent activity</h3><div class="heatmap">${days.join('')}</div><p class="muted">Each square represents one day. Darker means more entries.</p></div><div class="insight-card"><h3>Journaling rhythm</h3><p>${rhythmText()}</p></div>`}
function avgWords(){return state.entries.length?Math.round(state.entries.reduce((n,e)=>n+wordCount(e),0)/state.entries.length):0}
function rhythmText(){if(!state.entries.length)return'Start with one honest sentence today.';const s=streak();return s>=7?`You have a ${s}-day writing streak. Keep it gentle and sustainable.`:`You have written on ${new Set(state.entries.map(e=>e.date)).size} different days. Consistency matters more than length.`}
function streak(){let d=new Date();let s=0;while(state.entries.some(e=>e.date===dayKey(d))){s++;d.setDate(d.getDate()-1)}return s}
function openEditor(id=null,date=today()){editingId=id;const e=id?state.entries.find(x=>x.id===id):null;document.querySelector('#editorTitle').textContent=e?'Edit entry':'New entry';document.querySelector('#entryDate').value=e?.date||date;document.querySelector('#entryTime').value=e?.time||new Date().toTimeString().slice(0,5);document.querySelector('#entryTitle').value=e?.title||'';document.querySelector('#entryMood').value=e?.mood||'';document.querySelector('#entryWeather').value=e?.weather||'';document.querySelector('#entryLocation').value=e?.location||'';document.querySelector('#entryBody').innerHTML=e?.body||'';document.querySelector('#entryTags').value=e?.tags?.join(', ')||'';document.querySelector('#entryFavorite').checked=!!e?.favorite;document.querySelector('#entryPrivate').checked=!!e?.private;document.querySelector('#deleteEntry').classList.toggle('hidden',!e);document.querySelector('#editor').classList.remove('hidden');setTimeout(()=>document.querySelector('#entryBody').focus(),50)}
function closeModals(){document.querySelectorAll('.modal').forEach(x=>x.classList.add('hidden'))}
function saveEntry(){const body=document.querySelector('#entryBody').innerHTML.trim();if(!body&& !document.querySelector('#entryTitle').value.trim()){toast('Write something first');return}const now=new Date();const e={id:editingId||uid(),date:document.querySelector('#entryDate').value||today(),time:document.querySelector('#entryTime').value||now.toTimeString().slice(0,5),created:editingId?(state.entries.find(x=>x.id===editingId)?.created||now.toISOString()):now.toISOString(),updated:now.toISOString(),title:document.querySelector('#entryTitle').value.trim(),body,mood:document.querySelector('#entryMood').value,weather:document.querySelector('#entryWeather').value.trim(),location:document.querySelector('#entryLocation').value.trim(),tags:document.querySelector('#entryTags').value.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),favorite:document.querySelector('#entryFavorite').checked,private:document.querySelector('#entryPrivate').checked,journal:state.settings.defaultJournal};if(editingId)state.entries=state.entries.map(x=>x.id===editingId?e:x);else state.entries.unshift(e);state.history.unshift({type:editingId?'edit':'create',id:e.id,at:now.toISOString()});state.history=state.history.slice(0,200);closeModals();save();toast(editingId?'Entry updated':'Entry saved')}
function duplicate(id){const e=state.entries.find(x=>x.id===id);if(!e)return;state.entries.unshift({...e,id:uid(),created:new Date().toISOString(),updated:new Date().toISOString(),title:e.title?e.title+' (copy)':'Untitled (copy)'});save();toast('Entry duplicated')}
function deleteEntry(){if(!editingId)return;if(!confirm('Delete this journal entry?'))return;state.entries=state.entries.filter(e=>e.id!==editingId);closeModals();save();toast('Entry deleted')}
function showPrompt(){const p=prompts[state.settings.promptIndex++%prompts.length];save();document.querySelector('#smallTitle').textContent='Today’s prompt';document.querySelector('#smallBody').innerHTML=`<div class="prompt">${esc(p)}</div><div class="dialog-actions"><button id="usePrompt" class="primary">Use in new entry</button></div>`;document.querySelector('#smallModal').classList.remove('hidden');document.querySelector('#usePrompt').onclick=()=>{closeModals();openEditor();setTimeout(()=>document.querySelector('#entryBody').insertAdjacentText('afterbegin',p+'\n\n'),50)}}
function settings(){document.querySelector('#smallTitle').textContent='Journal settings';document.querySelector('#smallBody').innerHTML=`<div class="setting-row"><div><b>Default journal</b><small>New entries are saved here.</small></div><select id="defaultJournal">${state.journals.map(j=>`<option>${esc(j)}</option>`).join('')}</select></div><div class="setting-row"><div><b>Journal name</b><small>Create another private journal.</small></div><button id="addJournal">Add journal</button></div><div class="setting-row"><div><b>App lock</b><small>Lock this browser session with a local PIN.</small></div><button id="lockBtn">${state.settings.lock?'Change / disable':'Set PIN'}</button></div><div class="setting-row"><div><b>Backup</b><small>Export or restore your journal data.</small></div><div><button id="exportBtn">Export JSON</button><button id="importBtn">Import</button></div></div><div class="setting-row"><div><b>Appearance</b><small>Choose light, dark or system.</small></div><select id="themeSelect"><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></div><div class="dialog-actions"><button id="csvBtn">Export CSV</button><button id="mdBtn">Export Markdown</button><button id="wipeBtn" class="danger">Delete all data</button></div>`;document.querySelector('#defaultJournal').value=state.settings.defaultJournal;document.querySelector('#themeSelect').value=state.settings.theme;document.querySelector('#smallModal').classList.remove('hidden');document.querySelector('#defaultJournal').onchange=e=>{state.settings.defaultJournal=e.target.value;save()};document.querySelector('#themeSelect').onchange=e=>{state.settings.theme=e.target.value;applyTheme();save()};document.querySelector('#addJournal').onclick=()=>{const n=prompt('New journal name');if(n?.trim()&&!state.journals.includes(n.trim())){state.journals.push(n.trim());save();settings()}};document.querySelector('#exportBtn').onclick=exportJSON;document.querySelector('#importBtn').onclick=importJSON;document.querySelector('#csvBtn').onclick=exportCSV;document.querySelector('#mdBtn').onclick=exportMarkdown;document.querySelector('#wipeBtn').onclick=()=>{if(confirm('Delete every journal entry and template?')){state={journals:['Personal'],entries:[],templates:[],settings:{...defaults},history:[]};window.state=state;save();closeModals()}};document.querySelector('#lockBtn').onclick=pinSetup}
function pinSetup(){const p=prompt(state.settings.lock?'Enter a new PIN, or leave blank to disable:':'Choose a PIN (4+ characters):');if(p===null)return;if(!p){state.settings.lock=false;state.settings.pinHash='';save();toast('App lock disabled');return}crypto.subtle.digest('SHA-256',new TextEncoder().encode(p)).then(buf=>{state.settings.lock=true;state.settings.pinHash=Array.from(new Uint8Array(buf)).map(x=>x.toString(16).padStart(2,'0')).join('');save();toast('PIN saved')})}
async function verifyLock(){if(!state.settings.lock||sessionStorage.getItem('journal-unlocked')==='1')return true;const p=prompt('Personal Journal is locked. Enter your PIN:');if(p===null)return false;const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(p));const h=Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('');if(h===state.settings.pinHash){sessionStorage.setItem('journal-unlocked','1');return true}alert('Incorrect PIN');return false}
function download(name,type,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportJSON(){download('personal-journal-backup.json','application/json',JSON.stringify(state,null,2));toast('JSON backup exported')}
function exportCSV(){const head=['date','time','title','mood','weather','location','tags','favorite','words'];const rows=[head,...state.entries.map(e=>[e.date,e.time,e.title,e.mood,e.weather,e.location,e.tags.join('|'),e.favorite,wordCount(e)])].map(r=>r.map(x=>'"'+String(x??'').replace(/"/g,'""')+'"').join(','));download('personal-journal.csv','text/csv',rows.join('\n'))}
function exportMarkdown(){const s=[...state.entries].sort((a,b)=>a.date.localeCompare(b.date)).map(e=>`# ${e.title||'Untitled entry'}\n\n**${e.date} ${e.time}**${e.mood?' · '+e.mood:''}${e.location?' · '+e.location:''}\n\n${strip(e.body)}\n\n${e.tags.map(t=>'#'+t).join(' ')}`).join('\n\n---\n\n');download('personal-journal.md','text/markdown',s)}
function importJSON(){const i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=()=>{const f=i.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.entries))throw Error('Invalid backup');state={...state,...x,settings:{...defaults,...x.settings}};window.state=state;save();toast('Backup imported')}catch(e){alert('Could not import that backup.')}};r.readAsText(f)};i.click()}
function applyTheme(){const t=state.settings.theme;if(t==='dark'||(t==='system'&&matchMedia('(prefers-color-scheme:dark)').matches))document.body.classList.add('dark');else document.body.classList.remove('dark')}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.matches('[data-close]'))return closeModals();if(b.dataset.edit)return verifyLock().then(ok=>ok&&openEditor(b.dataset.edit));if(b.dataset.dup)return duplicate(b.dataset.dup);if(b.dataset.fav){const x=state.entries.find(x=>x.id===b.dataset.fav);if(x){x.favorite=!x.favorite;save()}}});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{activeView=b.dataset.view;render()});document.querySelector('#newBtn').onclick=()=>openEditor();document.querySelector('#promptBtn').onclick=showPrompt;document.querySelector('#settingsBtn').onclick=settings;document.querySelector('#themeBtn').onclick=()=>{state.settings.theme=document.body.classList.contains('dark')?'light':'dark';applyTheme();save()};document.querySelector('#saveEntry').onclick=saveEntry;document.querySelector('#deleteEntry').onclick=deleteEntry;['search','journalFilter','tagFilter','moodFilter'].forEach(id=>document.querySelector('#'+id).addEventListener('input',render));document.querySelector('#clearSearch').onclick=()=>{document.querySelector('#search').value='';render()};document.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>{document.execCommand(b.dataset.cmd,false,b.dataset.value||null);document.querySelector('#entryBody').focus()});
window.render=render;window.state=state;window.openEditor=openEditor;window.save=save;window.download=download;window.exportJSON=exportJSON;window.exportCSV=exportCSV;window.exportMarkdown=exportMarkdown;applyTheme();render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
