(() => {
  'use strict';
  const KEY='personal-notes-app:v1';
  const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
  const now=()=>new Date().toISOString();
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{"version":1,"notes":[],"folders":[]}')}catch{return{version:1,notes:[],folders:[]}}};
  const write=d=>localStorage.setItem(KEY,JSON.stringify(d));
  const currentId=()=>document.querySelector('.note-card.active')?.dataset.id||null;
  const current=()=>{const d=read();return d.notes.find(n=>n.id===currentId())||null};
  const refresh=()=>{location.reload()};

  const style=document.createElement('style');
  style.textContent='.advanced-actions{display:flex;gap:6px;align-items:center}.advanced-btn{border:1px solid var(--border,#ddd);background:var(--panel,#fff);color:inherit;border-radius:10px;padding:7px 10px;cursor:pointer;font:inherit}.advanced-btn:hover{background:var(--soft,#f4f4f5)}.advanced-modal{width:min(960px,94vw);max-height:90vh;border:1px solid var(--border,#ddd);border-radius:18px;padding:0;background:var(--panel,#fff);color:inherit}.advanced-modal::backdrop{background:rgba(0,0,0,.5)}.advanced-head{display:flex;align-items:center;justify-content:space-between;padding:16px 18px;border-bottom:1px solid var(--border,#ddd)}.advanced-head h2{margin:0;font-size:18px}.advanced-body{padding:18px;overflow:auto}.template-grid,.advanced-grid,.stats-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px}.template-card,.tool-card{display:block;text-align:left;border:1px solid var(--border,#ddd);border-radius:14px;padding:14px;background:transparent;color:inherit;cursor:pointer;font:inherit}.template-card:hover,.tool-card:hover{border-color:#6758e8}.template-card strong,.tool-card strong{display:block;margin-bottom:5px}.template-card span,.tool-card span{font-size:13px;opacity:.72}.graph-wrap{background:radial-gradient(circle at 50% 50%,rgba(103,88,232,.08),transparent 58%);border-radius:14px;overflow:hidden}.graph-svg{width:100%;height:520px;display:block}.graph-node{cursor:pointer}.graph-node circle{stroke:var(--panel,#fff);stroke-width:3}.graph-node text{font-size:11px;fill:currentColor;pointer-events:none}.graph-edge{stroke:currentColor;opacity:.22}.outline-block{border-top:1px solid var(--border,#ddd);padding-top:14px;margin-top:14px}.outline-list{display:flex;flex-direction:column;gap:5px}.outline-item{background:none;border:0;text-align:left;color:inherit;padding:4px 0;cursor:pointer}.property-grid{display:grid;grid-template-columns:130px 1fr;gap:8px;align-items:center}.find-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.find-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.storage-meter{height:8px;background:var(--soft,#eee);border-radius:99px;overflow:hidden}.storage-meter i{display:block;height:100%;background:#6758e8}.stat{padding:12px;border:1px solid var(--border,#ddd);border-radius:12px}.stat b{display:block;font-size:20px}.stat span{font-size:12px;opacity:.7}@media(max-width:680px){.advanced-actions .advanced-btn span{display:none}.graph-svg{height:430px}.find-grid,.property-grid{grid-template-columns:1fr}}';
  document.head.appendChild(style);

  function modal(id,title,html){
    let d=document.getElementById(id);
    if(!d){d=document.createElement('dialog');d.id=id;d.className='advanced-modal';d.innerHTML='<div class="advanced-head"><h2></h2><button class="icon-btn" aria-label="Close">×</button></div><div class="advanced-body"></div>';d.querySelector('.icon-btn').onclick=()=>d.close();document.body.appendChild(d)}
    d.querySelector('h2').textContent=title;d.querySelector('.advanced-body').innerHTML=html;return d;
  }
  function insertText(text){const ta=document.getElementById('noteBody');if(!ta)return;const s=ta.selectionStart,e=ta.selectionEnd;ta.setRangeText(text,s,e,'end');ta.dispatchEvent(new Event('input',{bubbles:true}));ta.focus()}
  function createNote(title,body){const d=read();d.notes.unshift({id:uid(),title,body,tags:['template'],folder:'',pinned:false,favorite:false,archived:false,deleted:false,daily:false,createdAt:now(),updatedAt:now(),history:[]});write(d);refresh()}

  const templatesList=[
    ['Meeting notes','Agenda, decisions, action items','# Meeting notes\n\n**Date:** DATE\n\n## Agenda\n- \n\n## Decisions\n- \n\n## Action items\n- [ ] '],
    ['Project brief','Scope, goals, milestones','# Project brief\n\n## Goal\n\n## Scope\n- \n\n## Milestones\n- [ ] \n\n## Risks\n- '],
    ['Study notes','Concepts, examples, questions','# Study notes\n\n## Topic\n\n## Key concepts\n- \n\n## Examples\n- \n\n## Questions\n- '],
    ['Daily journal','Reflection and highlights','# Daily journal\n\n## Highlights\n- \n\n## What I learned\n- \n\n## Tomorrow\n- '],
    ['Book / article','Summary and takeaways','# Reading notes\n\n**Source:** \n\n## Summary\n\n## Key ideas\n- \n\n## Takeaways\n- \n\n## Questions\n- '],
    ['Decision record','Context, options, decision','# Decision record\n\n## Context\n\n## Options\n- \n\n## Decision\n\n## Consequences\n- '],
    ['How-to','Repeatable procedure','# How-to\n\n## Goal\n\n## Steps\n1. \n2. \n3. \n\n## Notes\n'],
    ['Idea canvas','Problem, insight, next step','# Idea\n\n## Problem\n\n## Insight\n\n## Possible solution\n\n## Next step\n- [ ] '],
    ['Weekly review','Wins, lessons, priorities','# Weekly review\n\n## Wins\n- \n\n## Lessons\n- \n\n## Priorities\n- [ ] '],
    ['Research note','Question, evidence, conclusion','# Research note\n\n**Question:** \n\n## Evidence\n- \n\n## Analysis\n\n## Conclusion\n\n## Sources\n- ']
  ];
  function templates(){const d=modal('templatesDialog','Templates','<p class="muted">Structured starting points for common note workflows.</p><div class="template-grid" id="templateGrid"></div>');const grid=d.querySelector('#templateGrid');grid.innerHTML=templatesList.map((x,i)=>'<button class="template-card" data-i="'+i+'"><strong>'+esc(x[0])+'</strong><span>'+esc(x[1])+'</span></button>').join('');grid.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const x=templatesList[+b.dataset.i];createNote(x[0],x[2].replace('DATE',new Date().toLocaleDateString()));d.close()});d.showModal()}

  function addOutline(){const c=document.getElementById('connections');if(!c||document.getElementById('advancedOutline'))return;const s=document.createElement('section');s.className='outline-block';s.id='advancedOutline';s.innerHTML='<h3>Outline</h3><div class="outline-list" id="outlineList"></div>';c.parentNode.insertBefore(s,c);renderOutline()}
  function renderOutline(){const list=document.getElementById('outlineList'),ta=document.getElementById('noteBody');if(!list||!ta)return;let pos=0,items=[];ta.value.split('\n').forEach(line=>{const m=line.match(/^(#{1,6})\s+(.+)$/);if(m)items.push({level:m[1].length,text:m[2],pos});pos+=line.length+1});list.innerHTML=items.length?items.map(x=>'<button class="outline-item" style="padding-left:'+(x.level-1)*12+'px" data-pos="'+x.pos+'">'+esc(x.text)+'</button>').join(''):'<span class="muted">Add headings to build an outline.</span>';list.querySelectorAll('[data-pos]').forEach(b=>b.onclick=()=>{ta.focus();ta.setSelectionRange(+b.dataset.pos,+b.dataset.pos)})}

  function graph(){const notes=read().notes.filter(n=>!n.deleted).slice(0,100),d=modal('graphDialog','Knowledge graph','<div class="graph-wrap"><svg class="graph-svg" id="graphSvg" viewBox="0 0 900 520" role="img" aria-label="Note relationship graph"></svg></div><p class="muted">Lines represent wiki links. Click a node to open it.</p>');const svg=d.querySelector('#graphSvg'),W=900,H=520,cx=W/2,cy=H/2,r=Math.max(90,Math.min(210,35*notes.length/8)),by=new Map(notes.map(n=>[String(n.title||'').trim().toLowerCase(),n])),pts=new Map(notes.map((n,i)=>{const a=i/Math.max(1,notes.length)*Math.PI*2-Math.PI/2;return[n.id,{x:cx+r*Math.cos(a),y:cy+r*Math.sin(a)}]})),edges=[];notes.forEach(n=>{const re=/\[\[([^\]|#]+)/g;let m;while((m=re.exec(n.body||''))){const t=by.get(m[1].trim().toLowerCase());if(t&&t.id!==n.id)edges.push([n.id,t.id])}});svg.innerHTML=edges.map(e=>{const a=pts.get(e[0]),b=pts.get(e[1]);return'<line class="graph-edge" x1="'+a.x+'" y1="'+a.y+'" x2="'+b.x+'" y2="'+b.y+'"/>'}).join('')+notes.map(n=>{const p=pts.get(n.id);return'<g class="graph-node" data-id="'+esc(n.id)+'"><circle cx="'+p.x+'" cy="'+p.y+'" r="'+(n.pinned?10:7)+'" fill="'+(n.favorite?'#6758e8':'#8b83d9')+'"/><text x="'+(p.x+12)+'" y="'+(p.y+4)+'">'+esc((n.title||'Untitled').slice(0,26))+'</text></g>'}).join('');svg.querySelectorAll('[data-id]').forEach(g=>g.onclick=()=>{const card=[...document.querySelectorAll('.note-card')].find(x=>x.dataset.id===g.dataset.id);if(card){d.close();card.click()}});d.showModal()}

  function properties(){const n=current();if(!n)return;n.properties=n.properties||{};const keys=['status','type','source','author','date','priority'];const html='<p class="muted">Structured metadata stored with this note.</p><div class="property-grid">'+keys.map(k=>'<label>'+k+'</label><input id="prop-'+k+'" value="'+esc(n.properties[k]||'')+'" placeholder="'+k+'">').join('')+'</div><div class="find-actions"><button class="primary-btn" id="saveProperties">Save</button></div>';const d=modal('propertiesDialog','Note properties',html);keys.forEach(k=>{d.querySelector('#prop-'+k).value=n.properties[k]||''});d.querySelector('#saveProperties').onclick=()=>{const data=read(),x=data.notes.find(v=>v.id===n.id);x.properties=x.properties||{};keys.forEach(k=>{const v=d.querySelector('#prop-'+k).value.trim();if(v)x.properties[k]=v;else delete x.properties[k]});x.updatedAt=now();write(data);d.close();refresh()};d.showModal()}

  function duplicate(){const n=current();if(!n)return;const d=read(),copy=JSON.parse(JSON.stringify(n));copy.id=uid();copy.title=(n.title||'Untitled')+' copy';copy.createdAt=now();copy.updatedAt=now();copy.history=[];d.notes.unshift(copy);write(d);refresh()}
  function randomNote(){const a=read().notes.filter(n=>!n.deleted&&!n.archived);if(!a.length)return;const n=a[Math.floor(Math.random()*a.length)],card=[...document.querySelectorAll('.note-card')].find(x=>x.dataset.id===n.id);if(card)card.click()}
  function noteStats(){const n=current();if(!n)return;const b=n.body||'',w=b.trim()?b.trim().split(/\s+/).length:0,l=(b.match(/\[\[[^\]]+\]\]/g)||[]).length,h=(b.match(/^#{1,6}\s+/gm)||[]).length,m=Math.max(1,Math.ceil(w/200));const d=modal('statsDialog','Note analytics','<div class="stats-grid"><div class="stat"><b>'+w+'</b><span>words</span></div><div class="stat"><b>'+b.length+'</b><span>characters</span></div><div class="stat"><b>'+m+' min</b><span>reading time</span></div><div class="stat"><b>'+l+'</b><span>wiki links</span></div><div class="stat"><b>'+h+'</b><span>headings</span></div></div>');d.showModal()}
  function findReplace(){const n=current();if(!n)return;const d=modal('findReplaceDialog','Find & replace','<div class="find-grid"><input id="findText" placeholder="Find text"><input id="replaceText" placeholder="Replace with"></div><div class="find-actions"><button class="secondary-btn" id="replaceAll">Replace all</button></div>');d.querySelector('#replaceAll').onclick=()=>{const f=d.querySelector('#findText').value;if(!f)return;const r=d.querySelector('#replaceText').value,data=read(),x=data.notes.find(v=>v.id===n.id);x.body=x.body.split(f).join(r);x.updatedAt=now();write(data);d.close();refresh()};d.showModal()}
  function storage(){const bytes=new Blob([JSON.stringify(read())]).size;const show=e=>{const used=e?.usage||bytes,q=e?.quota||0,p=q?Math.min(100,used/q*100):0,d=modal('storageDialog','Storage health','<p>Notes are stored locally in this browser profile. Keep periodic backups.</p><div class="storage-meter"><i style="width:'+p+'%"></i></div><p class="muted">Approximate origin usage: '+(used/1024).toFixed(1)+' KB'+(q?' · estimated quota '+(q/1024/1024).toFixed(1)+' MB':'')+'</p><div class="find-actions"><button class="secondary-btn" id="persistBtn">Request persistent storage</button><button class="secondary-btn" id="backupBtn">Export backup</button></div>');d.querySelector('#persistBtn').onclick=async()=>{alert(navigator.storage?.persist&&await navigator.storage.persist()?'Persistent storage granted.':'Persistent storage was not granted.');};d.querySelector('#backupBtn').onclick=()=>document.getElementById('exportJsonBtn')?.click();d.showModal()};navigator.storage?.estimate?navigator.storage.estimate().then(show):show(null)}
  function exportAllMarkdown(){const text=read().notes.filter(n=>!n.deleted).map(n=>'# '+(n.title||'Untitled')+'\n\n'+(n.body||'')+'\n\n---\n').join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/markdown'}));a.download='notes-export.md';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function importMarkdown(){const input=document.createElement('input');input.type='file';input.accept='.md,.markdown,text/markdown';input.multiple=true;input.onchange=async()=>{const d=read();for(const f of input.files){d.notes.unshift({id:uid(),title:f.name.replace(/\.(md|markdown)$/i,''),body:await f.text(),tags:['imported'],folder:'',pinned:false,favorite:false,archived:false,deleted:false,daily:false,createdAt:now(),updatedAt:now(),history:[]})}write(d);refresh()};input.click()}

  function toolbar(){const bar=document.getElementById('formatToolbar');if(!bar||bar.dataset.advanced)return;bar.dataset.advanced='1';const add=(text,title,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=text;b.title=title;b.onclick=fn;bar.insertBefore(b,bar.querySelector('#previewBtn'))};add('▦','Insert table',()=>insertText('\n| Column 1 | Column 2 | Column 3 |\n| --- | --- | --- |\n| Value | Value | Value |\n'));add('—','Insert divider',()=>insertText('\n---\n'));add('[]','Insert checklist',()=>insertText('- [ ] '))}
  function buttons(){const top=document.querySelector('.top-actions');if(top&&!document.getElementById('advancedTools')){const w=document.createElement('div');w.id='advancedTools';w.className='advanced-actions';w.innerHTML='<button class="advanced-btn" id="templatesBtn">▦ <span>Templates</span></button><button class="advanced-btn" id="graphBtn">◎ <span>Graph</span></button>';top.insertBefore(w,top.firstChild);document.getElementById('templatesBtn').onclick=templates;document.getElementById('graphBtn').onclick=graph}const sb=document.querySelector('#settingsDialog .settings-body');if(sb&&!document.getElementById('advancedSettings')){const s=document.createElement('div');s.id='advancedSettings';s.innerHTML='<hr><h3>Advanced workspace</h3><div class="advanced-grid"><button class="secondary-btn" id="propertiesBtn">Note properties</button><button class="secondary-btn" id="statsBtn">Note analytics</button><button class="secondary-btn" id="storageBtn">Storage health</button><button class="secondary-btn" id="duplicateBtn">Duplicate note</button><button class="secondary-btn" id="findBtn">Find & replace</button><button class="secondary-btn" id="randomBtn">Random note</button><button class="secondary-btn" id="templates2">Templates</button><button class="secondary-btn" id="exportMdAll">Export all Markdown</button><button class="secondary-btn" id="importMd">Import Markdown</button></div>';sb.appendChild(s);document.getElementById('propertiesBtn').onclick=properties;document.getElementById('statsBtn').onclick=noteStats;document.getElementById('storageBtn').onclick=storage;document.getElementById('duplicateBtn').onclick=duplicate;document.getElementById('findBtn').onclick=findReplace;document.getElementById('randomBtn').onclick=randomNote;document.getElementById('templates2').onclick=templates;document.getElementById('exportMdAll').onclick=exportAllMarkdown;document.getElementById('importMd').onclick=importMarkdown}}
  function shortcuts(){if(window.__advancedShortcuts)return;window.__advancedShortcuts=true;document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.altKey){const k=e.key.toLowerCase();if(k==='g'){e.preventDefault();graph()}if(k==='t'){e.preventDefault();templates()}if(k==='r'){e.preventDefault();randomNote()}if(k==='p'){e.preventDefault();properties()}if(k==='h'){e.preventDefault();findReplace()}}})}
  function observe(){buttons();toolbar();addOutline();shortcuts();const ta=document.getElementById('noteBody');if(ta&&!ta.dataset.advanced){ta.dataset.advanced='1';ta.addEventListener('input',renderOutline)}if(!window.__advancedObserver){window.__advancedObserver=true;new MutationObserver(()=>{buttons();toolbar();addOutline();renderOutline()}).observe(document.body,{childList:true,subtree:true})}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',observe);else observe();
})();
