(() => {
  'use strict';
  const KEY = 'personal-notes-app:v1';
  const read = () => { try { return JSON.parse(localStorage.getItem(KEY) || '{"version":1,"notes":[],"folders":[]}'); } catch { return {version:1,notes:[],folders:[]}; } };
  const write = data => localStorage.setItem(KEY, JSON.stringify(data));
  const uid = () => crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36) + Math.random().toString(36).slice(2);
  const now = () => new Date().toISOString();
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const getCurrentId = () => document.querySelector('.note-card.active')?.dataset.id || null;
  const currentNote = () => { const d=read(); return d.notes.find(n=>n.id===getCurrentId()) || null; };
  const saveCurrentBody = body => { const d=read(), id=getCurrentId(), n=d.notes.find(x=>x.id===id); if(!n) return false; n.body=body; n.updatedAt=now(); write(d); return true; };
  const style = document.createElement('style');
  style.textContent = `.advanced-actions{display:flex;gap:6px;align-items:center}.advanced-btn{border:1px solid var(--border,#ddd);background:var(--panel,#fff);color:inherit;border-radius:10px;padding:7px 10px;cursor:pointer;font:inherit}.advanced-btn:hover{background:var(--soft,#f4f4f5)}.advanced-modal{width:min(900px,94vw);max-height:88vh;border:1px solid var(--border,#ddd);border-radius:18px;padding:0;background:var(--panel,#fff);color:inherit}.advanced-modal::backdrop{background:rgba(0,0,0,.48)}.advanced-head{display:flex;align-items:center;justify-content:space-between;padding:16px 18px;border-bottom:1px solid var(--border,#ddd)}.advanced-head h2{margin:0;font-size:18px}.advanced-body{padding:18px;overflow:auto}.template-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px}.template-card{text-align:left;border:1px solid var(--border,#ddd);border-radius:14px;padding:14px;background:transparent;color:inherit;cursor:pointer}.template-card:hover{transform:translateY(-1px);border-color:#6758e8}.template-card strong{display:block;margin-bottom:5px}.template-card span{font-size:13px;opacity:.72}.graph-wrap{position:relative;min-height:500px;background:radial-gradient(circle at 50% 50%,rgba(103,88,232,.08),transparent 58%);border-radius:14px;overflow:hidden}.graph-svg{width:100%;height:500px;display:block}.graph-node{cursor:pointer}.graph-node circle{stroke:var(--panel,#fff);stroke-width:3}.graph-node text{font-size:11px;fill:currentColor;pointer-events:none}.graph-edge{stroke:currentColor;opacity:.22}.graph-legend{font-size:12px;opacity:.7;margin-top:8px}.outline-block{border-top:1px solid var(--border,#ddd);padding-top:14px;margin-top:14px}.outline-list{display:flex;flex-direction:column;gap:5px}.outline-item{background:none;border:0;text-align:left;color:inherit;padding:4px 0;cursor:pointer;opacity:.82}.outline-item:hover{opacity:1;text-decoration:underline}.storage-meter{height:8px;background:var(--soft,#eee);border-radius:99px;overflow:hidden}.storage-meter>i{display:block;height:100%;background:#6758e8;width:0}.find-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.find-grid input{min-width:0}.find-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}@media(max-width:680px){.find-grid{grid-template-columns:1fr}.advanced-actions .advanced-btn span{display:none}.graph-svg{height:430px}.graph-wrap{min-height:430px}}`;
  document.head.appendChild(style);
  function dialog(id,title,content){ let d=document.getElementById(id); if(d) return d; d=document.createElement('dialog'); d.id=id; d.className='advanced-modal'; d.innerHTML=`<div class="advanced-head"><h2>${esc(title)}</h2><button class="icon-btn" data-adv-close aria-label="Close">×</button></div><div class="advanced-body">${content}</div>`; d.querySelector('[data-adv-close]').onclick=()=>d.close(); document.body.appendChild(d); return d; }
  function addToolbarFeatures(){ const bar=document.getElementById('formatToolbar'); if(!bar || bar.dataset.advanced)return; bar.dataset.advanced='1'; const sep=document.createElement('span'); bar.insertBefore(sep,bar.querySelector('#previewBtn')); const table=document.createElement('button'); table.textContent='▦'; table.title='Insert table'; table.type='button'; table.onclick=()=>insertTable(); bar.insertBefore(table,bar.querySelector('#previewBtn')); const hr=document.createElement('button'); hr.textContent='—'; hr.title='Insert divider'; hr.type='button'; hr.onclick=()=>insertText('\n---\n'); bar.insertBefore(hr,bar.querySelector('#previewBtn')); }
  function insertText(text){const ta=document.getElementById('noteBody');if(!ta)return;const s=ta.selectionStart,e=ta.selectionEnd;ta.setRangeText(text,s,e,'end');ta.dispatchEvent(new Event('input',{bubbles:true}));ta.focus();}
  function insertTable(){insertText('\n| Column 1 | Column 2 | Column 3 |\n| --- | --- | --- |\n| Value | Value | Value |\n| Value | Value | Value |\n');}
  function addOutline(){ const c=document.getElementById('connections'); if(!c || document.getElementById('advancedOutline'))return; const section=document.createElement('section'); section.className='outline-block'; section.id='advancedOutline'; section.innerHTML='<h3>Outline</h3><div class="outline-list" id="outlineList"></div>'; c.parentNode.insertBefore(section,c); renderOutline(); }
  function renderOutline(){ const list=document.getElementById('outlineList'), ta=document.getElementById('noteBody'); if(!list||!ta)return; const lines=ta.value.split('\n'), items=[]; let pos=0; lines.forEach(line=>{const m=line.match(/^(#{1,6})\s+(.+)$/);if(m)items.push({level:m[1].length,text:m[2].trim(),pos});pos+=line.length+1;}); list.innerHTML=items.length?items.map(x=>`<button class="outline-item" style="padding-left:${(x.level-1)*12}px" data-pos="${x.pos}">${esc(x.text)}</button>`).join(''):'<span class="muted">Add Markdown headings to build an outline.</span>'; list.querySelectorAll('[data-pos]').forEach(b=>b.onclick=()=>{ta.focus();ta.setSelectionRange(+b.dataset.pos,+b.dataset.pos);ta.scrollTop=ta.scrollHeight*(+b.dataset.pos/Math.max(1,ta.value.length));}); }
  function templates(){ const d=dialog('templatesDialog','Templates',`<p class="muted">Start faster with structured note types. Templates create normal editable Markdown notes.</p><div class="template-grid" id="templateGrid"></div>`); const list=[['Meeting notes','Agenda, decisions, action items','# Meeting notes\n\n**Date:** ${new Date().toLocaleDateString()}\n\n## Agenda\n- \n\n## Decisions\n- \n\n## Action items\n- [ ] \n'],['Project brief','Scope, goals, milestones','# Project brief\n\n## Goal\n\n## Scope\n- \n\n## Milestones\n- [ ] \n\n## Risks\n- \n'],['Study notes','Concepts, examples, questions','# Study notes\n\n## Topic\n\n## Key concepts\n- \n\n## Examples\n- \n\n## Questions\n- \n'],['Daily journal','Reflection and highlights','# ${new Date().toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'})}\n\n## Highlights\n- \n\n## What I learned\n- \n\n## Tomorrow\n- \n'],['Book / article','Summary and takeaways','# Reading notes\n\n**Source:** \n\n## Summary\n\n## Key ideas\n- \n\n## Takeaways\n- \n\n## Questions\n- \n'],['Decision record','Context, options, decision','# Decision record\n\n## Context\n\n## Options\n- \n\n## Decision\n\n## Consequences\n- \n'],['How-to','Repeatable procedure','# How-to\n\n## Goal\n\n## Steps\n1. \n2. \n3. \n\n## Notes\n'],['Idea canvas','Problem, insight, next step','# Idea\n\n## Problem\n\n## Insight\n\n## Possible solution\n\n## Next step\n- [ ] \n']]; const grid=d.querySelector('#templateGrid'); grid.innerHTML=list.map((x,i)=>`<button class="template-card" data-template="${i}"><strong>${esc(x[0])}</strong><span>${esc(x[1])}</span></button>`).join(''); grid.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>{const x=list[+b.dataset.template];createFromTemplate(x[0],x[2]);d.close();}); d.showModal(); }
  function createFromTemplate(title,body){const d=read();const n={id:uid(),title,body,tags:['template'],folder:'',pinned:false,favorite:false,archived:false,deleted:false,daily:false,createdAt:now(),updatedAt:now(),history:[]};d.notes.unshift(n);write(d);location.reload();}
  function graph(){ const d=read(), notes=d.notes.filter(n=>!n.deleted); const modal=dialog('graphDialog','Knowledge graph',`<div class="graph-wrap"><svg class="graph-svg" id="graphSvg" viewBox="0 0 900 500" role="img" aria-label="Note relationship graph"></svg></div><div class="graph-legend">Circles are notes; lines are [[wiki links]]. Click a note to open it.</div>`); renderGraph(modal,notes); modal.showModal(); }
  function renderGraph(modal,notes){ const svg=modal.querySelector('#graphSvg'); if(!svg)return; const W=900,H=500,cx=W/2,cy=H/2; const nodes=notes.slice(0,80); const byTitle=new Map(nodes.map(n=>[n.title.trim().toLowerCase(),n])); const r=Math.max(100,Math.min(205,45*nodes.length/8)); const points=new Map(nodes.map((n,i)=>{const a=(i/Math.max(1,nodes.length))*Math.PI*2-Math.PI/2;return[n.id,{x:cx+r*Math.cos(a),y:cy+r*Math.sin(a)}]})); const edges=[]; nodes.forEach(n=>{const re=/\[\[([^\]|#]+)(?:\|[^\]]+)?(?:#[^\]]+)?\]\]/g;let m;while((m=re.exec(n.body))){const t=byTitle.get(m[1].trim().toLowerCase());if(t&&t.id!==n.id)edges.push([n.id,t.id]);}}); svg.innerHTML=edges.map(([a,b])=>{const p=points.get(a),q=points.get(b);return`<line class="graph-edge" x1="${p.x}" y1="${p.y}" x2="${q.x}" y2="${q.y}"/>`}).join('')+nodes.map(n=>{const p=points.get(n.id),label=(n.title||'Untitled').slice(0,24);return`<g class="graph-node" data-id="${esc(n.id)}"><circle cx="${p.x}" cy="${p.y}" r="${n.pinned?10:7}" fill="${n.favorite?'#6758e8':'#8b83d9'}"/><text x="${p.x+12}" y="${p.y+4}">${esc(label)}</text></g>`}).join(''); svg.querySelectorAll('[data-id]').forEach(g=>g.onclick=()=>{const card=[...document.querySelectorAll('.note-card')].find(x=>x.dataset.id===g.dataset.id);if(card){modal.close();card.click();}}); }
  function duplicate(){const n=currentNote();if(!n)return;const d=read(),copy=JSON.parse(JSON.stringify(n));copy.id=uid();copy.title=(n.title||'Untitled')+' copy';copy.createdAt=now();copy.updatedAt=now();copy.history=[];d.notes.unshift(copy);write(d);location.reload();}
  function storage(){ const d=read(), bytes=new Blob([JSON.stringify(d)]).size; let estimate=null; const render=()=>{const used=estimate?.usage||bytes,quota=estimate?.quota||0,pct=quota?Math.min(100,used/quota*100):0;const modal=dialog('storageDialog','Storage & resilience',`<p>Your notes stay on this device. Indexed browser storage is the modern direction for larger structured offline datasets; this app also keeps a portable JSON backup path.</p><div class="storage-meter"><i style="width:${pct}%"></i></div><p class="muted">Approximate notes data: ${(used/1024).toFixed(1)} KB${quota?` · browser quota ${(quota/1024/1024).toFixed(1)} MB`:''}</p><div class="find-actions"><button class="secondary-btn" id="persistStorageBtn">Request persistent storage</button><button class="secondary-btn" id="storageBackupBtn">Export backup now</button></div>`);modal.querySelector('#persistStorageBtn').onclick=async()=>{if(navigator.storage?.persist){const ok=await navigator.storage.persist();alert(ok?'Persistent storage granted by the browser.':'The browser did not grant persistent storage.');}else alert('Persistent storage is not available in this browser.');};modal.querySelector('#storageBackupBtn').onclick=()=>document.getElementById('exportJsonBtn')?.click();modal.showModal();}; if(navigator.storage?.estimate) navigator.storage.estimate().then(x=>{estimate=x;render()}); else render(); }
  function findReplace(){const n=currentNote();if(!n)return;const modal=dialog('findReplaceDialog','Find & replace',`<div class="find-grid"><input id="findText" placeholder="Find text"><input id="replaceText" placeholder="Replace with"></div><div class="find-actions"><button class="secondary-btn" id="replaceAllBtn">Replace all</button></div>`);modal.querySelector('#replaceAllBtn').onclick=()=>{const f=modal.querySelector('#findText').value;if(!f)return;const r=modal.querySelector('#replaceText').value;const ta=document.getElementById('noteBody');const body=ta.value.split(f).join(r);if(saveCurrentBody(body)){ta.value=body;ta.dispatchEvent(new Event('input',{bubbles:true}));modal.close();}};modal.showModal();}
  function addButtons(){ const top=document.querySelector('.top-actions'); if(top&&!document.getElementById('graphBtn')){const wrap=document.createElement('div');wrap.className='advanced-actions';wrap.innerHTML='<button class="advanced-btn" id="templatesBtn" title="Templates">▦ <span>Templates</span></button><button class="advanced-btn" id="graphBtn" title="Knowledge graph">◎ <span>Graph</span></button>';top.insertBefore(wrap,top.firstChild);document.getElementById('templatesBtn').onclick=templates;document.getElementById('graphBtn').onclick=graph;} const settingsBody=document.querySelector('#settingsDialog .settings-body'); if(settingsBody&&!document.getElementById('advancedSettings')){const sec=document.createElement('div');sec.id='advancedSettings';sec.innerHTML='<hr><h3>Advanced</h3><div class="settings-grid"><button class="secondary-btn" id="storageBtn">Storage health</button><button class="secondary-btn" id="duplicateBtn">Duplicate current note</button><button class="secondary-btn" id="templatesSettingsBtn">Browse templates</button><button class="secondary-btn" id="findReplaceBtn">Find & replace</button></div>';settingsBody.appendChild(sec);document.getElementById('storageBtn').onclick=storage;document.getElementById('duplicateBtn').onclick=duplicate;document.getElementById('templatesSettingsBtn').onclick=templates;document.getElementById('findReplaceBtn').onclick=findReplace;} }
  function shortcuts(){document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,[contenteditable="true"]') && !(e.ctrlKey||e.metaKey))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='h'){e.preventDefault();findReplace();}if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate();}if((e.ctrlKey||e.metaKey)&&e.altKey&&e.key.toLowerCase()==='g'){e.preventDefault();graph();}if((e.ctrlKey||e.metaKey)&&e.altKey&&e.key.toLowerCase()==='t'){e.preventDefault();templates();}});}
  function observe(){ addButtons();addToolbarFeatures();addOutline(); const ta=document.getElementById('noteBody'); if(ta&&!ta.dataset.advanced){ta.dataset.advanced='1';ta.addEventListener('input',renderOutline);} const mo=new MutationObserver(()=>{addButtons();addToolbarFeatures();addOutline();renderOutline();});mo.observe(document.body,{childList:true,subtree:true}); shortcuts(); }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',observe);else observe();
})();
