(() => {
  'use strict';
  const KEY = 'personal-notes-app:v1';
  const SETTINGS_KEY = 'personal-notes-app:settings:v1';
  const today = () => new Date().toISOString().slice(0, 10);
  const uid = () => crypto.randomUUID ? crypto.randomUUID() : Date.now().toString(36) + Math.random().toString(36).slice(2);
  const now = () => new Date().toISOString();
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const saveDebounced = (() => { let t; return fn => { clearTimeout(t); t=setTimeout(fn,220); }; })();

  const seedNotes = [
    {id:uid(),title:'Welcome to Notes',body:'# Welcome\n\nThis is your private, local-first notes workspace.\n\n- Write with **Markdown**\n- Add #tags to organize ideas\n- Connect notes with [[wiki links]]\n- Pin or favorite important notes\n\n## Quick start\n\nCreate a new note, type a title, and start writing. Your changes are saved automatically in this browser.',tags:['welcome','guide'],folder:'Personal',pinned:true,favorite:true,archived:false,deleted:false,createdAt:now(),updatedAt:now(),history:[]},
    {id:uid(),title:'Ideas',body:'## Ideas\n\nCapture anything worth remembering here.\n\n#ideas',tags:['ideas'],folder:'Personal',pinned:false,favorite:false,archived:false,deleted:false,createdAt:now(),updatedAt:now(),history:[]}
  ];
  let data = load();
  let settings = loadSettings();
  let state = {view:'all', folder:'', tag:'', search:'', sort:'updated', selectedId:data.notes[0]?.id || null, preview:false};

  function load(){
    try { const raw=localStorage.getItem(KEY); if(raw){const x=JSON.parse(raw); if(x && Array.isArray(x.notes)) return x;} } catch(e) { console.warn(e); }
    const x={version:1,notes:seedNotes,folders:['Personal','Work','Study'],createdAt:now()}; localStorage.setItem(KEY,JSON.stringify(x)); return x;
  }
  function persist(){ try{localStorage.setItem(KEY,JSON.stringify(data));}catch(e){toast('Storage is full — export a backup and remove large notes.');} }
  function loadSettings(){ try{return {...{theme:'system',fontSize:17,compact:false},...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch{return {theme:'system',fontSize:17,compact:false}} }
  function persistSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings)); applySettings();}
  function applySettings(){
    document.body.classList.toggle('dark',settings.theme==='dark'||(settings.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches));
    document.body.classList.toggle('compact',!!settings.compact); document.documentElement.style.setProperty('--editor-font',settings.fontSize+'px');
    const s=document.getElementById('themeSelect'); if(s)s.value=settings.theme; const r=document.getElementById('fontSizeRange'); if(r)r.value=settings.fontSize; const fv=document.getElementById('fontSizeValue'); if(fv)fv.textContent=settings.fontSize+'px'; const c=document.getElementById('compactMode'); if(c)c.checked=settings.compact;
    document.getElementById('themeBtn').textContent=document.body.classList.contains('dark')?'☀':'☾';
  }
  const byId=id=>document.getElementById(id);
  function activeNotes(){ return data.notes.filter(n=>!n.deleted && !n.archived); }
  function visibleNotes(){
    let a=data.notes.filter(n=> state.view==='trash'?n.deleted:true);
    if(state.view!=='trash') a=a.filter(n=>!n.deleted);
    if(state.view==='archive') a=a.filter(n=>n.archived); else if(state.view!=='trash') a=a.filter(n=>!n.archived);
    if(state.view==='favorites') a=a.filter(n=>n.favorite); if(state.view==='pinned') a=a.filter(n=>n.pinned); if(state.view==='daily') a=a.filter(n=>n.daily);
    if(state.folder) a=a.filter(n=>n.folder===state.folder); if(state.tag) a=a.filter(n=>n.tags.includes(state.tag));
    const q=state.search.trim().toLowerCase(); if(q) a=a.filter(n=>(n.title+' '+n.body+' '+n.tags.join(' ')).toLowerCase().includes(q));
    a.sort((x,y)=>{if(state.sort==='title')return x.title.localeCompare(y.title);if(state.sort==='created')return y.createdAt.localeCompare(x.createdAt);return y.updatedAt.localeCompare(x.updatedAt)}); return a;
  }
  function current(){return data.notes.find(n=>n.id===state.selectedId)||null}
  function render(){renderSidebar();renderList();renderEditor();renderCounts();applySettings();}
  function renderCounts(){
    const live=data.notes.filter(n=>!n.deleted&&!n.archived); byId('allCount').textContent=live.length; byId('favoriteCount').textContent=live.filter(n=>n.favorite).length; byId('pinnedCount').textContent=live.filter(n=>n.pinned).length; byId('dailyCount').textContent=live.filter(n=>n.daily).length; byId('archiveCount').textContent=data.notes.filter(n=>n.archived&&!n.deleted).length; byId('trashCount').textContent=data.notes.filter(n=>n.deleted).length;
  }
  function renderSidebar(){
    document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view && !state.folder&&!state.tag));
    const folders=[...new Set(data.folders.concat(data.notes.map(n=>n.folder).filter(Boolean)))]; byId('folderList').innerHTML=folders.map(f=>`<button class="folder-item ${state.folder===f?'active':''}" data-folder="${esc(f)}">▱ ${esc(f)} <b>${data.notes.filter(n=>!n.deleted&&n.folder===f).length}</b></button>`).join('')||'<div class="muted" style="padding:8px">No folders yet</div>';
    const counts={}; data.notes.filter(n=>!n.deleted).forEach(n=>n.tags.forEach(t=>counts[t]=(counts[t]||0)+1)); const tags=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,18);
    byId('tagList').innerHTML=tags.map(([t,c])=>`<button class="tag-item ${state.tag===t?'active':''}" data-tag="${esc(t)}"><i class="tag-dot"></i>#${esc(t)} <span style="margin-left:auto">${c}</span></button>`).join('')||'<div class="muted" style="padding:8px">Add #tags to notes</div>';
    byId('folderList').querySelectorAll('[data-folder]').forEach(b=>b.onclick=()=>{state.folder=b.dataset.folder;state.tag='';state.view='all';render()}); byId('tagList').querySelectorAll('[data-tag]').forEach(b=>b.onclick=()=>{state.tag=b.dataset.tag;state.folder='';state.view='all';render()});
    byId('viewLabel').textContent=labelForView(); byId('selectedFolderLabel').textContent=state.folder||state.tag? (state.folder||('#'+state.tag)):'';
  }
  function labelForView(){return ({all:'All notes',favorites:'Favorites',pinned:'Pinned',daily:'Daily notes',archive:'Archive',trash:'Trash'})[state.view]||'All notes'}
  function renderList(){
    const notes=visibleNotes(); byId('listTitle').textContent=state.folder||state.tag? (state.folder||('#'+state.tag)):labelForView(); byId('listSubtitle').textContent=state.view==='trash'?'Deleted notes stay here until you remove them.':state.view==='daily'?'Your journal-style notes, one per day.':'Your private notes, stored on this device.';
    byId('searchInput').value=state.search; byId('noteList').innerHTML=notes.map(noteCard).join(''); byId('emptyList').classList.toggle('hidden',notes.length>0); byId('noteList').classList.toggle('hidden',notes.length===0);
    document.querySelectorAll('.note-card').forEach(c=>c.onclick=()=>select(c.dataset.id));
  }
  function noteCard(n){const excerpt=n.body.replace(/[#*_`\[\]]/g,'').replace(/\s+/g,' ').trim()||'Empty note';const tags=n.tags.slice(0,3).map(t=>`<span class="mini-tag">#${esc(t)}</span>`).join('');return `<div class="note-card ${n.id===state.selectedId?'active':''} ${n.pinned?'pinned':''}" data-id="${n.id}"><h3>${n.favorite?'★ ':''}${esc(n.title||'Untitled')}</h3><p>${esc(excerpt)}</p><div class="card-meta"><span>${relative(n.updatedAt)}</span>${tags}</div></div>`}
  function relative(iso){const d=Date.now()-new Date(iso).getTime(),m=Math.round(d/60000);if(m<1)return'just now';if(m<60)return m+'m ago';const h=Math.round(m/60);if(h<24)return h+'h ago';const days=Math.round(h/24);if(days<7)return days+'d ago';return new Date(iso).toLocaleDateString(undefined,{month:'short',day:'numeric',year:new Date(iso).getFullYear()===new Date().getFullYear()?undefined:'numeric'})}
  function renderEditor(){const n=current(), has=!!n;byId('editorEmpty').classList.toggle('hidden',has);byId('editorContent').classList.toggle('hidden',!has);if(!has)return;byId('editorPanel').classList.toggle('mobile-open',innerWidth<=680);byId('noteTitle').value=n.title;byId('noteBody').value=n.body;byId('noteTags').value=n.tags.join(', ');const sel=byId('noteFolder');sel.innerHTML='<option value="">No folder</option>'+data.folders.map(f=>`<option value="${esc(f)}">${esc(f)}</option>`).join('');sel.value=n.folder||'';byId('pinBtn').classList.toggle('active',n.pinned);byId('favoriteBtn').classList.toggle('active',n.favorite);byId('favoriteBtn').textContent=n.favorite?'★':'☆';updateStats();renderConnections();if(state.preview)renderPreview();else{byId('noteBody').classList.remove('hidden');byId('preview').classList.add('hidden')} }
  function updateStats(){const n=current();if(!n)return;const words=n.body.trim()?n.body.trim().split(/\s+/).length:0;byId('wordCount').textContent=words+' words';byId('charCount').textContent=n.body.length+' characters';byId('linkCount').textContent=(n.body.match(/\[\[[^\]]+\]\]/g)||[]).length+' links'}
  function select(id){state.selectedId=id;state.preview=false;render();if(innerWidth<=680)byId('editorPanel').classList.add('mobile-open');}
  function createNote(opts={}){const n={id:uid(),title:opts.title||'',body:opts.body||'',tags:opts.tags||[],folder:opts.folder||state.folder||'',pinned:false,favorite:false,archived:false,deleted:false,daily:!!opts.daily,createdAt:now(),updatedAt:now(),history:[]};data.notes.unshift(n);state.selectedId=n.id;state.view='all';state.search='';state.tag='';persist();render();setTimeout(()=>byId('noteTitle').focus(),50);return n}
  function updateCurrent(){const n=current();if(!n)return;const oldBody=n.body, oldTitle=n.title; n.title=byId('noteTitle').value.trim();n.body=byId('noteBody').value;n.tags=parseTags(byId('noteTags').value);n.folder=byId('noteFolder').value;n.updatedAt=now();if(oldBody!==n.body||oldTitle!==n.title){if(!n.history)n.history=[]; if(oldBody!==n.body||oldTitle!==n.title){n.history.push({title:oldTitle,body:oldBody,at:now()});n.history=n.history.slice(-20)}}saveDebounced(()=>persist());byId('saveStatus').textContent='Saved locally';updateStats();renderConnections();renderList();renderSidebar();renderCounts()}
  function parseTags(v){return [...new Set(v.split(',').map(x=>x.trim().replace(/^#/,'').toLowerCase()).filter(Boolean))].slice(0,30)}
  function renderConnections(){const n=current();if(!n)return;const links=[...n.body.matchAll(/\[\[([^\]|#]+)(?:\|[^\]]+)?(?:#[^\]]+)?\]\]/g)].map(x=>x[1].trim());byId('outlinks').innerHTML=links.length?[...new Set(links)].map(t=>`<span class="connection-link" data-open-title="${esc(t)}">→ ${esc(t)}</span>`).join(''):'No note links yet.';const back=data.notes.filter(x=>x.id!==n.id&&!x.deleted&&x.body.includes('[['+n.title+']]'));byId('backlinks').innerHTML=back.length?back.map(x=>`<span class="connection-link" data-open-id="${x.id}">← ${esc(x.title||'Untitled')}</span>`).join(''):'No backlinks yet.';byId('outlinks').querySelectorAll('[data-open-title]').forEach(el=>el.onclick=()=>openOrCreateByTitle(el.dataset.openTitle));byId('backlinks').querySelectorAll('[data-open-id]').forEach(el=>el.onclick=()=>select(el.dataset.openId))}
  function openOrCreateByTitle(title){let n=data.notes.find(x=>!x.deleted&&x.title.toLowerCase()===title.toLowerCase());if(!n)n=createNote({title});select(n.id)}
  function renderPreview(){const n=current();if(!n)return;byId('noteBody').classList.add('hidden');byId('preview').classList.remove('hidden');byId('preview').innerHTML=markdown(n.body);byId('preview').querySelectorAll('[data-wikilink]').forEach(e=>e.onclick=()=>openOrCreateByTitle(e.dataset.wikilink));}
  function markdown(src){let s=esc(src);const blocks=[];s=s.replace(/```([\s\S]*?)```/g,(_,x)=>{blocks.push('<pre><code>'+x.trim()+'</code></pre>');return'@@BLOCK'+(blocks.length-1)+'@@'});s=s.replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>');s=s.replace(/^&gt; (.+)$/gm,'<blockquote>$1</blockquote>');s=s.replace(/^[-*] (.+)$/gm,'<li>$1</li>').replace(/(<li>.*<\/li>\n?)+/g,m=>'<ul>'+m+'</ul>');s=s.replace(/^\d+\. (.+)$/gm,'<li>$1</li>');s=s.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g,(_,a,b)=>`<span class="wikilink" data-wikilink="${esc(a.trim())}">${esc(b||a.trim())}</span>`);s=s.replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');s=s.split(/\n{2,}/).map(p=>/^<(h|ul|blockquote|pre)/.test(p.trim())?p:p.replace(/\n/g,'<br>')).join('\n\n');s=s.replace(/@@BLOCK(\d+)@@/g,(_,i)=>blocks[+i]);return s}
  function newDaily(){const key=today(),found=data.notes.find(n=>n.daily&&n.title===key&&!n.deleted);if(found)return select(found.id);return createNote({title:key,body:`# ${new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}\n\n## Today\n\n- \n\n## Notes\n\n`,daily:true,tags:['daily']})}
  function togglePreview(){state.preview=!state.preview;byId('previewBtn').textContent=state.preview?'Edit':'Preview';state.preview?renderPreview():renderEditor()}
  function format(type){const ta=byId('noteBody'),start=ta.selectionStart,end=ta.selectionEnd,sel=ta.value.slice(start,end)||'text';const map={bold:['**','**'],italic:['*','*'],heading:['# ',''],bullet:['- ',''],check:['- [ ] ',''],quote:['> ',''],code:['`','`'],link:['[','](https://)']};const p=map[type];if(!p)return;ta.setRangeText(p[0]+sel+p[1],start,end,'select');ta.dispatchEvent(new Event('input',{bubbles:true}));ta.focus()}
  function download(name,text,type='application/octet-stream'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function exportJson(){download('personal-notes-backup-'+today()+'.json',JSON.stringify({version:1,exportedAt:now(),...data},null,2),'application/json');toast('Backup exported')}
  function exportMarkdown(){const n=current();if(!n)return;download((n.title||'untitled').replace(/[^a-z0-9-_]+/gi,'-').toLowerCase()+'.md',n.body,'text/markdown');toast('Markdown exported')}
  function importJson(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.notes))throw Error();const incoming=x.notes.map(n=>({...n,id:n.id||uid(),history:Array.isArray(n.history)?n.history:[]}));const existing=new Set(data.notes.map(n=>n.id));incoming.forEach(n=>{if(existing.has(n.id)){const i=data.notes.findIndex(x=>x.id===n.id);data.notes[i]=n}else data.notes.push(n)});data.folders=[...new Set(data.folders.concat(x.folders||[],incoming.map(n=>n.folder).filter(Boolean)))];persist();render();toast('Backup imported')}catch{toast('That file is not a valid Notes backup.')}};r.readAsText(file)}
  function confirm(title,text,ok){byId('confirmTitle').textContent=title;byId('confirmText').textContent=text;const d=byId('confirmDialog');d.showModal();byId('confirmOk').onclick=()=>{d.close();ok()};byId('confirmCancel').onclick=()=>d.close()}
  function deleteCurrent(){const n=current();if(!n)return;if(n.deleted){confirm('Delete permanently?','This note cannot be restored after permanent deletion.',()=>{data.notes=data.notes.filter(x=>x.id!==n.id);state.selectedId=data.notes.find(x=>!x.deleted)?.id||null;persist();render();toast('Note permanently deleted')})}else{n.deleted=true;n.archived=false;n.updatedAt=now();state.selectedId=data.notes.find(x=>!x.deleted)?.id||null;persist();render();toast('Moved to trash')}}
  function emptyTrash(){const count=data.notes.filter(n=>n.deleted).length;if(!count)return toast('Trash is already empty');confirm('Empty trash?',`Permanently delete ${count} note${count===1?'':'s'}?`,()=>{data.notes=data.notes.filter(n=>!n.deleted);state.selectedId=data.notes[0]?.id||null;persist();render();toast('Trash emptied')})}
  function addFolder(){const name=prompt('Folder name');if(!name)return;const n=name.trim();if(!n||data.folders.includes(n))return toast('Folder already exists');data.folders.push(n);persist();render();toast('Folder created')}
  function showHistory(){const n=current();if(!n)return;const list=byId('historyList');list.innerHTML=n.history?.length?n.history.slice().reverse().map((h,i)=>`<div class="history-item"><div><strong>${esc(h.title||'Untitled')}</strong><small>${new Date(h.at).toLocaleString()} · ${h.body.length} characters</small></div><button class="secondary-btn" data-restore="${n.history.length-1-i}">Restore</button></div>`).join(''):'<p class="muted" style="padding:12px">No saved versions yet. Changes are captured automatically as you edit.</p>';list.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{const h=n.history[+b.dataset.restore];confirm('Restore this version?','Your current content will be saved in history before restoring.',()=>{n.history.push({title:n.title,body:n.body,at:now()});n.title=h.title;n.body=h.body;n.updatedAt=now();persist();byId('historyDialog').close();render();toast('Version restored')})});byId('historyDialog').showModal()}
  const commands=[['New note','Create a blank note','new'],['Daily note','Open today’s journal note','daily'],['Search','Search your notes','search'],['Preview note','Toggle Markdown preview','preview'],['Export backup','Download a complete JSON backup','export'],['Focus mode','Hide navigation for distraction-free writing','focus'],['Settings','Open app settings','settings']];
  function openCommands(){renderCommands('');byId('commandDialog').showModal();byId('commandSearch').focus()}
  function renderCommands(q){const a=commands.filter(c=>(c[0]+' '+c[1]).toLowerCase().includes(q.toLowerCase()));byId('commandList').innerHTML=a.map(c=>`<button class="command-item" data-cmd="${c[2]}"><strong>${c[0]}</strong><span>${c[1]}</span></button>`).join('');byId('commandList').querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>runCommand(b.dataset.cmd))}
  function runCommand(c){byId('commandDialog').close();({new:()=>createNote(),daily:newDaily,search:()=>{byId('searchWrap').scrollIntoView();byId('searchInput').focus()},preview:togglePreview,export:exportJson,focus:toggleFocus,settings:()=>byId('settingsDialog').showModal()})[c]?.()}
  function toggleFocus(){document.body.classList.toggle('focus-mode')}
  function toast(msg){const t=byId('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}

  document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.folder='';state.tag='';render();});
  byId('newNoteBtn').onclick=()=>createNote();byId('emptyNewBtn').onclick=()=>createNote();byId('editorNewBtn').onclick=()=>createNote();byId('addFolderBtn').onclick=addFolder;
  byId('noteTitle').oninput=updateCurrent;byId('noteBody').oninput=()=>{byId('saveStatus').textContent='Saving…';updateCurrent()};byId('noteTags').oninput=updateCurrent;byId('noteFolder').onchange=updateCurrent;
  byId('pinBtn').onclick=()=>{const n=current();if(n){n.pinned=!n.pinned;persist();render()}};byId('favoriteBtn').onclick=()=>{const n=current();if(n){n.favorite=!n.favorite;persist();render()}};byId('historyBtn').onclick=showHistory;
  byId('moreBtn').onclick=()=>{const n=current();if(!n)return;const choices=n.deleted?['Restore','Delete permanently']:['Archive','Move to trash','Export Markdown'];const pick=prompt('Actions:\n'+choices.map((x,i)=>(i+1)+'. '+x).join('\n')+'\n\nEnter a number');if(pick==='1'){if(n.deleted)n.deleted=false;else n.archived=!n.archived;persist();render()}else if(pick==='2'){if(n.deleted)deleteCurrent();else deleteCurrent()}else if(pick==='3'&&!n.deleted)exportMarkdown()};
  byId('searchInput').oninput=e=>{state.search=e.target.value;byId('clearSearch').style.display=state.search?'block':'none';renderList()};byId('clearSearch').onclick=()=>{state.search='';renderList();byId('searchInput').focus()};byId('searchBtn').onclick=()=>{byId('searchWrap').scrollIntoView();byId('searchInput').focus()};
  byId('sortBtn').onclick=()=>{state.sort=state.sort==='updated'?'title':state.sort==='title'?'created':'updated';byId('sortBtn').textContent={updated:'Recently edited ▾',title:'Title A–Z ▾',created:'Recently created ▾'}[state.sort];renderList()};
  byId('themeBtn').onclick=()=>{settings.theme=document.body.classList.contains('dark')?'light':'dark';persistSettings()};byId('focusBtn').onclick=toggleFocus;byId('previewBtn').onclick=togglePreview;document.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>format(b.dataset.format));
  byId('settingsBtn').onclick=()=>byId('settingsDialog').showModal();byId('helpBtn').onclick=()=>byId('helpDialog').showModal();byId('themeSelect').onchange=e=>{settings.theme=e.target.value;persistSettings()};byId('fontSizeRange').oninput=e=>{settings.fontSize=+e.target.value;persistSettings()};byId('compactMode').onchange=e=>{settings.compact=e.target.checked;persistSettings()};byId('exportJsonBtn').onclick=exportJson;byId('exportMdBtn').onclick=exportMarkdown;byId('clearTrashBtn').onclick=emptyTrash;byId('importJsonBtn').onclick=()=>byId('importFile').click();byId('importFile').onchange=e=>{if(e.target.files[0])importJson(e.target.files[0]);e.target.value=''};
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>byId(b.dataset.close).close());byId('openSidebar').onclick=()=>byId('appShell').querySelector('.sidebar').classList.add('open');byId('closeSidebar').onclick=()=>byId('appShell').querySelector('.sidebar').classList.remove('open');byId('backToList').onclick=()=>byId('editorPanel').classList.remove('mobile-open');
  byId('commandSearch').oninput=e=>renderCommands(e.target.value);
  document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommands()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();persist();toast('Saved locally')}else if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='p'){e.preventDefault();togglePreview()}else if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();byId('searchInput').focus()}else if(e.key.toLowerCase()==='n'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();createNote()}else if(e.key==='Escape'){document.querySelectorAll('dialog[open]').forEach(d=>d.close())}});
  matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>settings.theme==='system'&&applySettings());
  window.addEventListener('beforeunload',persist);
  if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});
  render();
})();
