(() => {
  'use strict';
  const DB='personal-notes-attachments:v1', STORE='files';
  let dbPromise;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const openDB=()=>dbPromise||(dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE)){const s=r.result.createObjectStore(STORE,{keyPath:'id'});s.createIndex('noteId','noteId')}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}));
  const noteId=()=>document.querySelector('.note-card.active')?.dataset.id||null;
  const tx=(mode,fn)=>openDB().then(db=>new Promise((resolve,reject)=>{const t=db.transaction(STORE,mode),s=t.objectStore(STORE);let out;try{out=fn(s)}catch(e){reject(e);return}t.oncomplete=()=>resolve(out);t.onerror=()=>reject(t.error)}));
  async function addFiles(files){const id=noteId();if(!id||!files.length)return;const db=await openDB();for(const file of files){await new Promise((resolve,reject)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put({id:crypto.randomUUID(),noteId,name:file.name,type:file.type||'application/octet-stream',size:file.size,createdAt:new Date().toISOString(),blob:file});t.oncomplete=resolve;t.onerror=()=>reject(t.error)})}render();}
  async function list(){const id=noteId();if(!id)return[];return tx('readonly',s=>new Promise((resolve,reject)=>{const r=s.index('noteId').getAll(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}));}
  async function remove(id){await tx('readwrite',s=>s.delete(id));render();}
  async function get(id){return tx('readonly',s=>new Promise((resolve,reject)=>{const r=s.get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}));}
  const size=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB';
  async function download(id){const f=await get(id);if(!f)return;const url=URL.createObjectURL(f.blob),a=document.createElement('a');a.href=url;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  async function preview(id){const f=await get(id);if(!f)return;const url=URL.createObjectURL(f.blob);const d=document.createElement('dialog');d.className='attachment-preview';d.innerHTML='<div class="attachment-preview-head"><strong>'+esc(f.name)+'</strong><button class="icon-btn">×</button></div><div class="attachment-preview-body"></div>';d.querySelector('button').onclick=()=>{d.close();URL.revokeObjectURL(url);d.remove()};const body=d.querySelector('.attachment-preview-body');if(f.type.startsWith('image/'))body.innerHTML='<img alt="'+esc(f.name)+'" src="'+url+'">';else if(f.type==='application/pdf')body.innerHTML='<iframe title="'+esc(f.name)+'" src="'+url+'"></iframe>';else body.innerHTML='<p>This file type has no inline preview.</p><button class="primary-btn" id="downloadAttachment">Download</button>';if(body.querySelector('#downloadAttachment'))body.querySelector('#downloadAttachment').onclick=()=>download(id);document.body.appendChild(d);d.showModal()}
  async function render(){const host=document.getElementById('attachmentList');if(!host)return;try{const files=await list();host.innerHTML=files.length?files.map(f=>'<div class="attachment-item"><button class="attachment-main" data-preview="'+f.id+'"><span class="attachment-icon">'+(f.type.startsWith('image/')?'IMG':f.type==='application/pdf'?'PDF':'FILE')+'</span><span><strong>'+esc(f.name)+'</strong><small>'+size(f.size)+'</small></span></button><button class="icon-btn" data-download="'+f.id+'" aria-label="Download '+esc(f.name)+'">↓</button><button class="icon-btn" data-remove="'+f.id+'" aria-label="Delete '+esc(f.name)+'">×</button></div>').join(''):'<p class="muted">No attachments. Images, PDFs and other files stay in this browser.</p>';host.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>preview(b.dataset.preview));host.querySelectorAll('[data-download]').forEach(b=>b.onclick=()=>download(b.dataset.download));host.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>remove(b.dataset.remove))}catch(e){host.textContent='Attachments are unavailable in this browser.'}}
  function setup(){if(document.getElementById('attachmentsSection'))return;const c=document.getElementById('connections');if(!c)return;const s=document.createElement('section');s.id='attachmentsSection';s.className='outline-block';s.innerHTML='<div class="attachment-head"><div><h3>Attachments</h3><p class="muted">Stored locally with IndexedDB, separate from note text.</p></div><button class="secondary-btn" id="addAttachmentBtn">Add files</button></div><input id="attachmentInput" type="file" multiple hidden><div id="attachmentList"></div>';c.parentNode.appendChild(s);s.querySelector('#addAttachmentBtn').onclick=()=>s.querySelector('#attachmentInput').click();s.querySelector('#attachmentInput').onchange=()=>addFiles([...s.querySelector('#attachmentInput').files]);const ta=document.getElementById('noteBody');if(ta){['dragover','drop'].forEach(ev=>ta.addEventListener(ev,e=>{if(ev==='dragover'){e.preventDefault();ta.classList.add('drop-target')}else{e.preventDefault();ta.classList.remove('drop-target');if(e.dataTransfer?.files?.length)addFiles([...e.dataTransfer.files])}}));}render()}
  const style=document.createElement('style');style.textContent='.attachment-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.attachment-head h3{margin-bottom:2px}.attachment-item{display:flex;align-items:center;gap:8px;border:1px solid var(--border,#ddd);border-radius:10px;padding:8px;margin-top:7px}.attachment-main{display:flex;align-items:center;gap:10px;flex:1;text-align:left;border:0;background:none;color:inherit;cursor:pointer}.attachment-main strong,.attachment-main small{display:block}.attachment-main small{opacity:.65}.attachment-icon{font-size:10px;font-weight:700;border:1px solid var(--border,#ddd);border-radius:6px;padding:4px}.attachment-preview{width:min(900px,92vw);height:min(760px,88vh);padding:0;border:1px solid var(--border,#ddd);border-radius:16px;background:var(--panel,#fff);color:inherit}.attachment-preview-head{display:flex;justify-content:space-between;align-items:center;padding:12px 16px;border-bottom:1px solid var(--border,#ddd)}.attachment-preview-body{height:calc(100% - 58px);display:grid;place-items:center;padding:12px;overflow:auto}.attachment-preview-body img{max-width:100%;max-height:100%;object-fit:contain}.attachment-preview-body iframe{width:100%;height:100%;border:0}.drop-target{outline:2px dashed #6758e8;outline-offset:4px}';document.head.appendChild(style);
  const mo=new MutationObserver(setup);mo.observe(document.body,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();
