(() => {
  'use strict';

  const KEY = 'dayflow:v1';
  const $ = id => document.getElementById(id);
  const qs = s => document.querySelector(s);
  const uid = prefix => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
  const pad = n => String(n).padStart(2, '0');
  const iso = d => `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
  const parseDate = s => { const [y,m,d] = s.split('-').map(Number); return new Date(y,m-1,d); };
  const today = () => iso(new Date());
  const addDays = (s,n) => { const d=parseDate(s); d.setDate(d.getDate()+n); return iso(d); };
  const startOfWeek = s => { const d=parseDate(s); const day=(d.getDay()+6)%7; d.setDate(d.getDate()-day); return iso(d); };
  const fmtDate = s => parseDate(s).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});
  const fmtLong = s => parseDate(s).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});
  const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const timeToMin = t => { if(!t) return null; const [h,m]=t.split(':').map(Number); return h*60+m; };
  const minToTime = n => `${pad(Math.floor(n/60)%24)}:${pad(n%60)}`;
  const priorityRank = {high:0,medium:1,low:2};
  const defaultState = () => ({
    tasks: [], habits: [
      {id:uid('habit'),name:'Plan the day',days:'daily',icon:'★',logs:{}},
      {id:uid('habit'),name:'Read for 20 minutes',days:'daily',icon:'◆',logs:{}}
    ],
    routines: [], reviews:{}, settings:{theme:'system',focusMinutes:25,compact:false,notifications:false}, selectedDate:today(), weekAnchor:startOfWeek(today())
  });
  let state = load();
  let activeView = 'day';
  let editingId = null;
  let focus = {taskId:null,seconds:0,running:false,timer:null};
  let deferredInstall = null;

  function load(){
    try { const raw=localStorage.getItem(KEY); if(!raw) return defaultState(); const data=JSON.parse(raw); const base=defaultState(); return {...base,...data,settings:{...base.settings,...(data.settings||{})},reviews:data.reviews||{},habits:data.habits||base.habits,routines:data.routines||[],tasks:(data.tasks||[]).map(t=>({id:uid('fix'),completed:false,priority:'medium',duration:30,date:today(),tags:[],notes:'',start:'',repeat:'',createdAt:Date.now(),...t,id:t.id||uid('task')}))}; } catch { return defaultState(); }
  }
  function save(){ localStorage.setItem(KEY,JSON.stringify(state)); }
  function toast(msg){ const el=$('toast'); el.textContent=msg; el.classList.add('show'); clearTimeout(toast.t); toast.t=setTimeout(()=>el.classList.remove('show'),2200); }
  function setTheme(theme){ document.documentElement.dataset.theme = theme==='system' ? (matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light') : theme; }
  function refreshTheme(){ setTheme(state.settings.theme); }
  function isDoneOn(t,date){ return t.completed && t.completedDate===date; }
  function taskMatchesDate(t,date){ return t.date===date || (!t.date && !t.completed); }
  function parseQuickTitle(raw){
    let title=raw.trim(), date=null, start=null, duration=null, priority=null, tags=[];
    const tagMatches=[...title.matchAll(/(^|\s)#([\w-]+)/g)]; tags=tagMatches.map(m=>m[2].toLowerCase()); title=title.replace(/(^|\s)#([\w-]+)/g,' ').trim();
    const p=title.match(/(^|\s)!p([123])\b/i); if(p){priority={1:'high',2:'medium',3:'low'}[p[2]];title=title.replace(p[0],' ').trim();}
    const dm=title.match(/\b(today|tomorrow|mon|tue|wed|thu|fri|sat|sun)\b/i);
    if(dm){ const word=dm[1].toLowerCase(); if(word==='today') date=state.selectedDate; else if(word==='tomorrow') date=addDays(state.selectedDate,1); else { const map={sun:0,mon:1,tue:2,wed:3,thu:4,fri:5,sat:6}; const d=parseDate(state.selectedDate); const target=map[word]; let diff=(target-d.getDay()+7)%7; if(diff===0) diff=7; date=addDays(state.selectedDate,diff); } title=title.replace(dm[0],' ').trim(); }
    const tm=title.match(/\b([01]?\d|2[0-3])(?::([0-5]\d))?\s*(am|pm)\b/i); if(tm){let h=Number(tm[1]),m=Number(tm[2]||0);const ap=tm[3].toLowerCase();if(ap==='pm'&&h<12)h+=12;if(ap==='am'&&h===12)h=0;start=`${pad(h)}:${pad(m)}`;title=title.replace(tm[0],' ').trim();}
    const dur=title.match(/\b(\d{1,3})\s*(m|min|mins|minutes|h|hr|hours)\b/i); if(dur){duration=Number(dur[1])*(/h|hr|hours/i.test(dur[2])?60:1);title=title.replace(dur[0],' ').trim();}
    return {title:title.replace(/\s+/g,' ').trim(),date,start,duration,priority,tags};
  }
  function createTask(data){
    const t={id:uid('task'),title:data.title,notes:'',date:data.date||state.selectedDate,start:data.start||'',duration:Number(data.duration)||30,priority:data.priority||'medium',tags:data.tags||[],completed:false,completedDate:'',repeat:data.repeat||'',createdAt:Date.now()};
    state.tasks.push(t); save(); renderAll(); return t;
  }
  function removeTask(id){ const t=state.tasks.find(x=>x.id===id); if(!t) return; state.tasks=state.tasks.filter(x=>x.id!==id); save(); renderAll(); toast(`Deleted “${t.title}”`); }
  function toggleTask(id){ const t=state.tasks.find(x=>x.id===id); if(!t)return; t.completed=!t.completed; t.completedDate=t.completed?state.selectedDate:''; if(t.completed && t.repeat){ const next=nextRepeatDate(t.date,t.repeat); if(next) state.tasks.push({...t,id:uid('task'),date:next,completed:false,completedDate:'',createdAt:Date.now()}); } save(); renderAll(); }
  function nextRepeatDate(date,repeat){ if(!date)return null; if(repeat==='daily')return addDays(date,1); if(repeat==='weekdays'){let d=addDays(date,1);while([0,6].includes(parseDate(d).getDay()))d=addDays(d,1);return d;} if(repeat==='weekly')return addDays(date,7); if(repeat==='monthly'){const d=parseDate(date);d.setMonth(d.getMonth()+1);return iso(d);} return null; }
  function sortedTasks(tasks){ const sort=activeView==='tasks'?($('sortBy')?.value||'due'):'due'; return [...tasks].sort((a,b)=>{if(a.completed!==b.completed)return a.completed?1:-1;if(sort==='priority')return priorityRank[a.priority]-priorityRank[b.priority];if(sort==='created')return b.createdAt-a.createdAt;if(sort==='title')return a.title.localeCompare(b.title);const ad=(a.date||'9999')+' '+(a.start||'99:99'),bd=(b.date||'9999')+' '+(b.start||'99:99');return ad.localeCompare(bd)||priorityRank[a.priority]-priorityRank[b.priority];}); }
  function renderAll(){ refreshTheme(); renderHeader(); renderDay(); renderWeek(); renderTasks(); renderHabits(); renderReview(); updateNav(); }
  function renderHeader(){ $('dateLabel').textContent=fmtLong(state.selectedDate); $('dayTitle').textContent=state.selectedDate===today()?'Today':fmtDate(state.selectedDate); $('taskDate').value=state.selectedDate; $('todayBadge').textContent=state.tasks.filter(t=>t.date===state.selectedDate&&!t.completed).length; $('taskBadge').textContent=state.tasks.filter(t=>!t.completed).length; }
  function renderDay(){
    const date=state.selectedDate; const tasks=sortedTasks(state.tasks.filter(t=>t.date===date)); const active=tasks.filter(t=>!t.completed), done=tasks.filter(t=>t.completed).length; const planned=active.reduce((s,t)=>s+(Number(t.duration)||0),0); const scheduled=active.filter(t=>t.start).length;
    $('daySummary').innerHTML=`<div class="summary-card"><strong>${active.length}</strong><span>open tasks</span></div><div class="summary-card"><strong>${done}</strong><span>completed</span></div><div class="summary-card"><strong>${Math.round(planned/60*10)/10}h</strong><span>planned time</span></div><div class="summary-card"><strong>${scheduled}/${active.length||0}</strong><span>time-blocked</span></div>`;
    renderBig3(tasks); renderInbox(state.tasks.filter(t=>!t.completed&&!t.start&&(t.date===date||!t.date))); renderTimeline(tasks);
  }
  function renderBig3(tasks){ const chosen=tasks.filter(t=>t.big3); const candidates=tasks.filter(t=>!t.completed&&!t.big3).slice(0,3-chosen.length); const list=[...chosen,...candidates]; $('big3Count').textContent=`${chosen.length}/3`; $('big3List').innerHTML=list.length?list.map(t=>`<div class="big3-item"><input class="check" type="checkbox" ${t.completed?'checked':''} data-toggle="${t.id}"><div class="item-text"><div class="item-title">${escapeHtml(t.title)}</div><div class="item-sub">${t.start||'Unscheduled'} · ${t.duration||30}m</div></div><button class="mini-btn" data-big3="${t.id}" title="Toggle Big 3">${t.big3?'★':'☆'}</button></div>`).join(''):'<div class="muted" style="padding:16px">Add a few tasks, then star your Big 3.</div>'; }
  function renderInbox(tasks){ $('inboxList').innerHTML=tasks.length?tasks.slice(0,8).map(t=>`<div class="inbox-item"><input class="check" type="checkbox" data-toggle="${t.id}"><div class="item-text"><div class="item-title">${escapeHtml(t.title)}</div><div class="item-sub">${t.duration||30}m · ${t.priority.toUpperCase()}</div></div><button class="mini-btn" data-edit="${t.id}">Plan</button></div>`).join(''):'<div class="muted" style="padding:16px">Inbox is clear.</div>'; }
  function renderTimeline(tasks){
    const scheduled=tasks.filter(t=>t.start); const unscheduled=tasks.filter(t=>!t.start); let html='';
    for(let hour=6;hour<=22;hour++){
      const blocks=scheduled.filter(t=>Math.floor(timeToMin(t.start)/60)===hour);
      html+=`<div class="time-row"><div class="time-label">${hour===12?'12 PM':hour>12?hour-12+' PM':hour+' AM'}</div><div class="time-lane">${blocks.map(t=>blockHtml(t)).join('')}</div></div>`;
    }
    if(unscheduled.length) html+=`<div class="time-row"><div class="time-label">Inbox</div><div class="time-lane">${unscheduled.map(t=>blockHtml(t,true)).join('')}</div></div>`;
    $('timeline').innerHTML=html||'<div class="muted" style="padding:25px;text-align:center">Nothing planned. Add a task above to shape your day.</div>';
  }
  function blockHtml(t,unscheduled=false){return `<article class="time-block ${t.completed?'completed':''} ${unscheduled?'unscheduled':''}" data-edit="${t.id}" draggable="true"><div class="block-main"><div class="block-title"><span class="priority-${t.priority}">${t.priority==='high'?'●':t.priority==='medium'?'•':'○'}</span> ${escapeHtml(t.title)}</div><div class="block-meta">${t.start?`${t.start} · `:''}${t.duration||30} min${t.tags?.length?' · '+escapeHtml(t.tags.map(x=>'#'+x).join(' ')):''}</div></div><div class="block-actions"><button class="mini-btn" data-focus="${t.id}" title="Focus">▶</button><button class="mini-btn" data-toggle="${t.id}" title="Complete">${t.completed?'↩':'✓'}</button></div></article>`;}
  function renderWeek(){ const start=state.weekAnchor; $('weekRange').textContent=`${fmtDate(start)} — ${fmtDate(addDays(start,6))}`; $('weekGrid').innerHTML=Array.from({length:7},(_,i)=>{const d=addDays(start,i), ts=sortedTasks(state.tasks.filter(t=>t.date===d));return `<div class="week-day ${d===today()?'today':''}"><div class="week-day-head"><strong>${parseDate(d).toLocaleDateString(undefined,{weekday:'short'})}</strong><span>${parseDate(d).toLocaleDateString(undefined,{month:'short',day:'numeric'})} · ${ts.filter(t=>!t.completed).length} open</span></div>${ts.slice(0,10).map(t=>`<div class="week-task ${t.completed?'done':''}" data-edit="${t.id}">${t.start?`<b>${t.start}</b> `:''}${escapeHtml(t.title)}</div>`).join('')}</div>`;}).join(''); }
  function renderTasks(){ if(!$('taskList'))return; let ts=state.tasks; const q=($('search')?.value||'').trim().toLowerCase(); const status=$('statusFilter')?.value||'active'; const p=$('priorityFilter')?.value||'all'; if(status==='active')ts=ts.filter(t=>!t.completed); if(status==='completed')ts=ts.filter(t=>t.completed); if(p!=='all')ts=ts.filter(t=>t.priority===p); if(q)ts=ts.filter(t=>[t.title,t.notes,(t.tags||[]).join(' ')].join(' ').toLowerCase().includes(q)); ts=sortedTasks(ts); $('taskList').innerHTML=ts.map(t=>`<div class="task-row ${t.completed?'completed':''}"><input class="check" type="checkbox" ${t.completed?'checked':''} data-toggle="${t.id}"><div class="task-details"><div class="task-name">${escapeHtml(t.title)}</div><div class="task-sub"><span class="priority-${t.priority}">${t.priority.toUpperCase()}</span> · ${t.date?fmtDate(t.date):'No date'}${t.start?' · '+t.start:''} · ${t.duration||30}m${t.tags?.length?' · '+escapeHtml(t.tags.map(x=>'#'+x).join(' ')):''}</div></div><div class="task-actions"><button class="mini-btn" data-big3="${t.id}">${t.big3?'★':'☆'}</button><button class="mini-btn" data-edit="${t.id}">Edit</button></div></div>`).join('')||'<div class="panel" style="padding:25px;text-align:center">No tasks match these filters.</div>'; }
  function renderHabits(){ const days=['M','T','W','T','F','S','S']; $('habitGrid').innerHTML=state.habits.map(h=>{const start=startOfWeek(state.selectedDate);return `<article class="habit-card"><div class="habit-icon">${escapeHtml(h.icon)}</div><h3>${escapeHtml(h.name)}</h3><p>${h.days==='daily'?'Every day':h.days==='weekdays'?'Weekdays':'Weekends'} · ${habitStreak(h)} day streak</p><div class="habit-days">${days.map((d,i)=>{const date=addDays(start,i);return `<button class="day-dot ${h.logs?.[date]?'done':''}" data-habit="${h.id}" data-habit-date="${date}" title="${date}">${d}</button>`}).join('')}</div><button class="btn ghost" data-delete-habit="${h.id}">Delete</button></article>`;}).join(''); }
  function habitStreak(h){let count=0,d=state.selectedDate;for(let i=0;i<365;i++){if(h.logs?.[d]){count++;d=addDays(d,-1)}else break;}return count;}
  function renderReview(){ const r=state.reviews[state.selectedDate]||{}; const ts=state.tasks.filter(t=>t.date===state.selectedDate); const done=ts.filter(t=>t.completed).length; const planned=ts.reduce((s,t)=>s+(t.duration||0),0); $('reviewStats').innerHTML=`<h2>Day at a glance</h2><div class="day-summary" style="margin-top:14px"><div class="summary-card"><strong>${done}</strong><span>done</span></div><div class="summary-card"><strong>${ts.length?Math.round(done/ts.length*100):0}%</strong><span>completion</span></div><div class="summary-card"><strong>${Math.round(planned/60*10)/10}h</strong><span>planned</span></div><div class="summary-card"><strong>${ts.filter(t=>t.big3&&t.completed).length}/3</strong><span>Big 3 done</span></div></div>`; $('reviewWins').value=r.wins||'';$('reviewLearnings').value=r.learnings||'';$('reviewTomorrow').value=r.tomorrow||''; }
  function updateNav(){document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===activeView));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active-view',v.id===`${activeView}View`));}
  function openTask(id){ const t=state.tasks.find(x=>x.id===id);if(!t)return; editingId=id; $('editTitle').value=t.title;$('editNotes').value=t.notes||'';$('editDate').value=t.date||'';$('editStart').value=t.start||'';$('editDuration').value=t.duration||30;$('editPriority').value=t.priority;$('editRepeat').value=t.repeat||'';$('editTags').value=(t.tags||[]).join(', ');$('taskDialog').showModal(); }
  function saveEdited(){ const t=state.tasks.find(x=>x.id===editingId);if(!t)return;t.title=$('editTitle').value.trim();t.notes=$('editNotes').value.trim();t.date=$('editDate').value||state.selectedDate;t.start=$('editStart').value;t.duration=Math.max(5,Number($('editDuration').value)||30);t.priority=$('editPriority').value;t.repeat=$('editRepeat').value;t.tags=$('editTags').value.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);save();renderAll();toast('Task updated'); }
  function toggleBig3(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;if(!t.big3 && state.tasks.filter(x=>x.date===state.selectedDate&&x.big3&&!x.completed).length>=3){toast('Big 3 is full — complete or unstar one first');return;}t.big3=!t.big3;save();renderAll();}
  function chooseFocus(id){const t=state.tasks.find(x=>x.id===id);if(!t)return;focus.taskId=id;focus.seconds=(state.settings.focusMinutes||25)*60;focus.running=false;clearInterval(focus.timer);renderFocus();}
  function renderFocus(){const t=state.tasks.find(x=>x.id===focus.taskId);$('focusClock').textContent=minToTime(Math.ceil(focus.seconds/60)).replace(':',' : ');if(focus.seconds<3600)$('focusClock').textContent=`${pad(Math.floor(focus.seconds/60))}:${pad(focus.seconds%60)}`;$('focusTask').textContent=t?t.title:'Choose a task to focus.';$('startFocus').textContent=focus.running?'Pause':'Start';}
  function tickFocus(){if(focus.seconds<=0){clearInterval(focus.timer);focus.running=false;renderFocus();toast('Focus session complete');return;}focus.seconds--;renderFocus();}
  function startFocus(){if(!focus.taskId){const t=state.tasks.find(x=>x.date===state.selectedDate&&!x.completed);if(t)chooseFocus(t.id);else return toast('Add an open task first');}focus.running=!focus.running;if(focus.running)focus.timer=setInterval(tickFocus,1000);else clearInterval(focus.timer);renderFocus();}
  function saveSettings(){state.settings.theme=$('settingsTheme').value;state.settings.focusMinutes=Math.max(5,Number($('focusMinutes').value)||25);state.settings.compact=$('compactToggle').checked;state.settings.notifications=$('notificationToggle').checked;document.body.classList.toggle('compact',state.settings.compact);save();refreshTheme();toast('Settings saved');}
  async function requestNotifications(){if(!('Notification'in window))return toast('Notifications are not supported here');const p=await Notification.requestPermission();state.settings.notifications=p==='granted';save();$('notificationToggle').checked=state.settings.notifications;toast(p==='granted'?'Reminders enabled':'Reminders not enabled');}
  function checkReminders(){if(!state.settings.notifications||Notification.permission!=='granted')return;const now=new Date(), date=iso(now), tm=`${pad(now.getHours())}:${pad(now.getMinutes())}`;state.tasks.filter(t=>t.date===date&&t.start===tm&&!t.completed).forEach(t=>new Notification('Dayflow reminder',{body:t.title}));}
  async function showStorage(){if(!navigator.storage?.estimate){$('storageStats').textContent='Browser storage information is not available.';return;}const e=await navigator.storage.estimate();const used=e.usage||0,quota=e.quota||0;$('storageStats').textContent=`Using ${(used/1024/1024).toFixed(1)} MB of an estimated ${(quota/1024/1024).toFixed(0)} MB browser quota.`;}
  function exportData(){const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`dayflow-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href);}
  function importData(file){const r=new FileReader();r.onload=()=>{try{const incoming=JSON.parse(r.result);if(!Array.isArray(incoming.tasks))throw new Error('Invalid backup');state={...defaultState(),...incoming,settings:{...defaultState().settings,...(incoming.settings||{})}};save();renderAll();toast('Backup imported');}catch{toast('Import failed: invalid Dayflow backup');}};r.readAsText(file);}
  function shiftDay(n){state.selectedDate=addDays(state.selectedDate,n);save();renderAll();}
  function shiftWeek(n){state.weekAnchor=addDays(state.weekAnchor,n*7);save();renderWeek();}

  $('taskForm').addEventListener('submit',e=>{e.preventDefault();const parsed=parseQuickTitle($('taskTitle').value);const data={...parsed,date:$('taskDate').value||parsed.date||state.selectedDate,start:$('taskStart').value||parsed.start,duration:Number($('taskDuration').value)||parsed.duration||30,priority:parsed.priority||$('taskPriority').value};if(!data.title)return;createTask(data);e.target.reset();$('taskDate').value=state.selectedDate;$('taskTitle').focus();});
  $('prevDay').onclick=()=>shiftDay(-1);$('nextDay').onclick=()=>shiftDay(1);$('todayBtn').onclick=()=>{state.selectedDate=today();renderAll();};$('prevWeek').onclick=()=>shiftWeek(-1);$('nextWeek').onclick=()=>shiftWeek(1);
  $('fitDayBtn').onclick=()=>toast('Timeline shows the full planning window from 6 AM to 10 PM');
  $('addTaskNav').onclick=()=>{$('taskTitle').focus();window.scrollTo({top:0,behavior:'smooth'});};
  document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.onclick=()=>{activeView=b.dataset.view;updateNav();renderAll();});
  document.addEventListener('click',e=>{const toggle=e.target.closest('[data-toggle]');if(toggle){toggleTask(toggle.dataset.toggle);return;}const edit=e.target.closest('[data-edit]');if(edit){openTask(edit.dataset.edit);return;}const big=e.target.closest('[data-big3]');if(big){toggleBig3(big.dataset.big3);return;}const f=e.target.closest('[data-focus]');if(f){chooseFocus(f.dataset.focus);return;}const hb=e.target.closest('[data-habit]');if(hb){const h=state.habits.find(x=>x.id===hb.dataset.habit);if(h){h.logs=h.logs||{};if(h.logs[hb.dataset.habitDate])delete h.logs[hb.dataset.habitDate];else h.logs[hb.dataset.habitDate]=true;save();renderHabits();}return;}const dh=e.target.closest('[data-delete-habit]');if(dh){state.habits=state.habits.filter(x=>x.id!==dh.dataset.deleteHabit);save();renderHabits();toast('Habit deleted');}});
  $('taskEditForm').addEventListener('submit',e=>{e.preventDefault();saveEdited();$('taskDialog').close();});$('deleteTaskBtn').onclick=()=>{removeTask(editingId);$('taskDialog').close();};
  $('search').addEventListener('input',renderTasks);$('statusFilter').onchange=renderTasks;$('priorityFilter').onchange=renderTasks;$('sortBy').onchange=renderTasks;
  $('addHabitBtn').onclick=()=>{$('habitForm').reset();$('habitDialog').showModal();};$('habitForm').addEventListener('submit',e=>{e.preventDefault();state.habits.push({id:uid('habit'),name:$('habitName').value.trim(),days:$('habitDays').value,icon:$('habitIcon').value,logs:{}});save();$('habitDialog').close();renderHabits();toast('Habit added');});
  $('routineBtn').onclick=()=>{$('routineList').innerHTML=state.routines.length?state.routines.map(r=>`<div class="task-row"><div class="task-details"><div class="task-name">${escapeHtml(r.name)}</div><div class="task-sub">${r.tasks.length} tasks</div></div><button class="mini-btn" data-use-routine="${r.id}">Add today</button></div>`).join(''):'<p class="muted">No routines yet. Create a routine for a reusable sequence.</p>';$('routineDialog').showModal();};
  $('newRoutine').onclick=()=>{const name=prompt('Routine name (for example: Morning setup)');if(!name)return;const items=prompt('Task names separated by commas');if(!items)return;state.routines.push({id:uid('routine'),name:name.trim(),tasks:items.split(',').map(x=>x.trim()).filter(Boolean)});save();$('routineBtn').click();toast('Routine created');};
  $('routineList').addEventListener('click',e=>{const b=e.target.closest('[data-use-routine]');if(!b)return;const r=state.routines.find(x=>x.id===b.dataset.useRoutine);r.tasks.forEach(title=>createTask({title,date:state.selectedDate,duration:30,priority:'medium'}));$('routineDialog').close();toast('Routine added to today');});
  $('saveReview').onclick=()=>{state.reviews[state.selectedDate]={wins:$('reviewWins').value,learnings:$('reviewLearnings').value,tomorrow:$('reviewTomorrow').value,savedAt:new Date().toISOString()};save();toast('Review saved');};
  $('startFocus').onclick=startFocus;$('resetFocus').onclick=()=>{clearInterval(focus.timer);focus.running=false;focus.seconds=(state.settings.focusMinutes||25)*60;renderFocus();};
  $('themeBtn').onclick=()=>{const next=state.settings.theme==='system'?'light':state.settings.theme==='light'?'dark':'system';state.settings.theme=next;save();refreshTheme();};$('settingsBtn').onclick=()=>{$('settingsTheme').value=state.settings.theme;$('focusMinutes').value=state.settings.focusMinutes;$('compactToggle').checked=state.settings.compact;$('notificationToggle').checked=state.settings.notifications;showStorage();$('settingsDialog').showModal();};$('saveSettings').onclick=saveSettings;$('notifyBtn').onclick=requestNotifications;$('notificationToggle').onchange=requestNotifications;$('persistStorage').onclick=async()=>{if(navigator.storage?.persist){const ok=await navigator.storage.persist();toast(ok?'Persistent storage requested':'Browser did not grant persistent storage');}};
  $('exportBtn').onclick=exportData;$('importInput').onchange=e=>{if(e.target.files[0])importData(e.target.files[0]);e.target.value='';};
  document.addEventListener('keydown',e=>{const tag=(e.target.tagName||'').toLowerCase();if(e.key.toLowerCase()==='n'&&!['input','textarea','select'].includes(tag)&&!e.metaKey&&!e.ctrlKey){e.preventDefault();$('taskTitle').focus();}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();activeView='tasks';updateNav();$('search').focus();}});
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('installBtn').classList.remove('hidden');});$('installBtn').onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('installBtn').classList.add('hidden');};
  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
  setInterval(checkReminders,30000);setInterval(()=>{if(activeView==='day')renderDay();},60000);
  renderAll();renderFocus();
})();