/* Advanced local-first Game Backlog Tracker feature layer. */
(function(){
  const KEY='game-backlog-tracker:v1';
  const get=()=>JSON.parse(localStorage.getItem(KEY)||'{"games":[],"logs":[],"lists":[],"snapshots":[],"theme":"dark"}');
  const put=db=>localStorage.setItem(KEY,JSON.stringify(db));
  const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
  const modal=document.getElementById('modal'), body=document.getElementById('modalBody');
  function open(html){body.innerHTML=html;modal.showModal()}
  window.openAdvanced=function(){
    const db=get(); const gs=db.games; const logs=db.logs;
    const totalHours=gs.reduce((n,g)=>n+(+g.hours||0),0);
    const completed=gs.filter(g=>g.status==='Completed').length;
    const backlog=gs.filter(g=>g.status==='Backlog');
    const stale=backlog.filter(g=>Date.now()-new Date(g.added||Date.now())>180*864e5).length;
    const platforms=[...new Set(gs.flatMap(g=>String(g.platform||'').split(',').map(x=>x.trim()).filter(Boolean)))];
    open(`<h2 class="modalTitle">Advanced Game Planner</h2><div class="grid">
      <button onclick="advancedRecommend()"><b>Smart recommendation</b><small>Score backlog by priority, length, rating, freshness and variety.</small></button>
      <button onclick="backlogHealth()"><b>Backlog health</b><small>Find stale, unrated, missing-data and oversized backlog entries.</small></button>
      <button onclick="gamingGoals()"><b>Gaming goals</b><small>Create yearly/monthly hour or completion targets.</small></button>
      <button onclick="importGamesCSV()"><b>CSV import</b><small>Bring a spreadsheet library into the tracker.</small></button>
      <button onclick="exportEnhancedCSV()"><b>Enhanced CSV export</b><small>Export games plus useful planning fields.</small></button>
      <button onclick="manageTaxonomy()"><b>Taxonomy & tags</b><small>Inspect genres, platforms, series and tags.</small></button>
      <button onclick="releasePlanner()"><b>Release planner</b><small>See upcoming games in your wishlist and backlog.</small></button>
      <button onclick="backupPackage()"><b>Full backup package</b><small>Export library, sessions, lists and settings together.</small></button>
    </div><div class="grid"><div class="card"><span class="muted">Games</span><b>${gs.length}</b></div><div class="card"><span class="muted">Backlog</span><b>${backlog.length}</b></div><div class="card"><span class="muted">Completed</span><b>${completed}</b></div><div class="card"><span class="muted">Logged hours</span><b>${totalHours.toFixed(1)}</b></div><div class="card"><span class="muted">Sessions</span><b>${logs.length}</b></div><div class="card"><span class="muted">Platforms</span><b>${platforms.length}</b></div></div><p class="muted">Backlog aging currently flags ${stale} entries older than 180 days.</p>`);
  };
  window.advancedRecommend=function(){const db=get(); const now=Date.now(); const candidates=db.games.filter(g=>['Backlog','Wishlist'].includes(g.status)); if(!candidates.length){open('<h2 class="modalTitle">Smart recommendation</h2><div class="empty">No backlog or wishlist games available.</div>');return;} const scores=candidates.map(g=>{const age=Math.min(20,Math.floor((now-new Date(g.added||now))/864e5/30)); const short=+g.hours>0?Math.max(0,20-Math.min(20,+g.hours)):8; const rating=(+g.rating||0)*5; const priority=(+g.priority||0)*10; const freshness=g.status==='Wishlist'?4:0; return {g,score:priority+rating+short+age+freshness};}).sort((a,b)=>b.score-a.score); open(`<h2 class="modalTitle">Smart recommendation</h2><p class="muted">Transparent score: priority + rating + reasonable commitment + backlog age + wishlist freshness.</p><div class="timeline">${scores.slice(0,8).map((x,i)=>`<div class="entry"><b>#${i+1} ${esc(x.g.title)}</b><span class="pill">Score ${x.score.toFixed(0)}</span><div class="muted">${esc(x.g.platform||'Platform unknown')} · ${x.g.hours||'unknown'}h · priority ${x.g.priority||0}/5 · rating ${x.g.rating||'—'}/5</div><button onclick="window.__advancedPick('${x.g.id}')">Start this game</button></div>`).join('')}</div>`);};
  window.__advancedPick=function(id){const db=get(),g=db.games.find(x=>x.id===id);if(!g)return;g.status='Playing';g.updated=new Date().toISOString();put(db);modal.close();if(window.render)render();};
  window.backlogHealth=function(){const db=get(),gs=db.games, issues=[]; gs.forEach(g=>{const missing=[]; if(!g.platform)missing.push('platform'); if(!g.genres)missing.push('genre'); if(!g.year)missing.push('release year'); if(!g.cover)missing.push('cover'); if(!g.rating&&g.status==='Completed')missing.push('rating'); if(missing.length)issues.push(`<div class="entry"><b>${esc(g.title)}</b><div class="muted">Missing: ${missing.join(', ')}</div></div>`);}); const stale=gs.filter(g=>g.status==='Backlog'&&Date.now()-new Date(g.added||Date.now())>180*864e5); open(`<h2 class="modalTitle">Backlog health</h2><div class="grid"><div class="card"><b>${gs.filter(g=>g.status==='Backlog').length}</b><span class="muted">backlog games</span></div><div class="card"><b>${stale.length}</b><span class="muted">stale 180d+</span></div><div class="card"><b>${issues.length}</b><span class="muted">metadata audits</span></div><div class="card"><b>${gs.filter(g=>g.status==='Abandoned').length}</b><span class="muted">abandoned</span></div></div><h3>Metadata audit</h3><div class="timeline">${issues.slice(0,30).join('')||'<div class="empty">Your library has no obvious metadata gaps.</div>'}</div>`);};
  window.gamingGoals=function(){const db=get();db.goals=db.goals||[]; const goals=db.goals; open(`<h2 class="modalTitle">Gaming goals</h2><form class="form" onsubmit="saveGoal(event)"><div class="two"><label>Goal name<input id="goalName" required placeholder="Finish 12 games"></label><label>Target<input id="goalTarget" type="number" min="1" required value="12"></label></div><div class="two"><label>Type<select id="goalType"><option value="completed">Completed games</option><option value="hours">Hours played</option><option value="sessions">Play sessions</option></select></label><label>Deadline<input id="goalDate" type="date"></label></div><div class="dialogActions"><button type="button" onclick="openAdvanced()">Cancel</button><button class="primary">Create goal</button></div></form><h3>Current goals</h3>${goals.map((g,i)=>`<div class="entry"><b>${esc(g.name)}</b><span class="pill">${g.type}: ${g.target}</span><button onclick="deleteGoal(${i})">Delete</button></div>`).join('')||'<div class="empty">No goals yet.</div>'>`)};
  window.saveGoal=function(e){e.preventDefault();const db=get();db.goals=db.goals||[];db.goals.push({id:uid(),name:document.getElementById('goalName').value,target:+document.getElementById('goalTarget').value,type:document.getElementById('goalType').value,deadline:document.getElementById('goalDate').value});put(db);gamingGoals()};
  window.deleteGoal=function(i){const db=get();db.goals.splice(i,1);put(db);gamingGoals()};
  window.manageTaxonomy=function(){const db=get(); const groups=(field)=>[...new Set(db.games.flatMap(g=>String(g[field]||'').split(',').map(x=>x.trim()).filter(Boolean)))].sort((a,b)=>a.localeCompare(b)); const rows=(label,a)=>`<div class="card"><b>${label}</b><div class="row">${a.map(x=>`<span class="pill">${esc(x)}</span>`).join('')||'<span class="muted">None</span>'}</div></div>`;open(`<h2 class="modalTitle">Library taxonomy</h2><div class="grid">${rows('Genres',groups('genres'))}${rows('Platforms',groups('platform'))}${rows('Series',groups('series'))}${rows('Tags',groups('tags'))}${rows('Developers',groups('developer'))}${rows('Publishers',groups('publisher'))}</div>`)};
  window.releasePlanner=function(){const db=get();const upcoming=db.games.filter(g=>g.release&&new Date(g.release)>=new Date()).sort((a,b)=>new Date(a.release)-new Date(b.release));open(`<h2 class="modalTitle">Release planner</h2><div class="timeline">${upcoming.map(g=>`<div class="entry"><b>${esc(g.title)}</b><span class="pill">${esc(g.release)}</span><div class="muted">${esc(g.status)} · ${esc(g.platform||'Platform unknown')}</div></div>`).join('')||'<div class="empty">Add an ISO release date to games to use the release planner.</div>'}</div>`)};
  window.importGamesCSV=function(){open(`<h2 class="modalTitle">CSV import</h2><p class="muted">Expected columns: title,status,platform,year,genres,series,developer,publisher,hours,progress,rating,priority,ownership,medium,tags,cover,notes,review,favorite,release</p><textarea id="csvInput" rows="12" placeholder="title,status,platform,year\nMy Game,Backlog,PC,2026"></textarea><div class="dialogActions"><button onclick="closeModal()">Cancel</button><button class="primary" onclick="runCSVImport()">Import</button></div>`)};
  window.runCSVImport=function(){const ta=document.getElementById('csvInput');const lines=ta.value.trim().split(/\r?\n/);if(lines.length<2)return;const parse=line=>{const out=[];let cur='',q=false;for(const c of line){if(c==='\"')q=!q;else if(c===','&&!q){out.push(cur);cur='';}else cur+=c;}out.push(cur);return out.map(x=>x.trim().replace(/^\"|\"$/g,''));};const h=parse(lines[0]).map(x=>x.toLowerCase());const db=get();lines.slice(1).forEach(line=>{const v=parse(line),g={id:uid(),added:new Date().toISOString(),updated:new Date().toISOString()};h.forEach((k,i)=>g[k]=v[i]||'');['year','hours','progress','rating','priority'].forEach(k=>g[k]=+g[k]||0);g.favorite=['true','1','yes'].includes(String(g.favorite).toLowerCase());db.games.push(g);});put(db);modal.close();if(window.render)render();};
  window.exportEnhancedCSV=function(){const db=get(),fields=['title','status','platform','year','genres','series','developer','publisher','hours','progress','rating','priority','ownership','medium','tags','cover','notes','review','favorite','release'];const q=x=>'"'+String(x??'').replace(/"/g,'""')+'"';const csv=[fields.join(','),...db.games.map(g=>fields.map(f=>q(g[f])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='game-backlog-enhanced.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
  window.backupPackage=function(){const db=get();const payload={format:'game-backlog-tracker',version:2,exportedAt:new Date().toISOString(),...db};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='game-backlog-full-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
})();
