function openTools(){openModal(`<h2 class="modalTitle">Power tools</h2><div class="grid"><div class="card"><h3>Library audit</h3><p class="muted">Find duplicates, missing metadata and stale backlog entries.</p><button onclick="audit()">Run audit</button></div><div class="card"><h3>Smart backlog</h3><p class="muted">Rank games using priority, age, progress, rating and time.</p><button onclick="smartBacklog()">Build shortlist</button></div><div class="card"><h3>Backup</h3><p class="muted">Portable JSON plus encrypted browser backup.</p><button onclick="backupJSON()">JSON backup</button> <button onclick="encryptedBackup()">Encrypted</button></div><div class="card"><h3>Restore</h3><p class="muted">Restore a JSON file or return to a saved local snapshot.</p><button onclick="restoreJSON()">Restore JSON</button> <button onclick="snapshot()">Save snapshot</button></div></div>`)}
function audit(){let dup={},missing=[],stale=[];db.games.forEach(g=>{let k=g.title.trim().toLowerCase();(dup[k]??=[]).push(g);if(!g.platform||!g.genres||!g.year)missing.push(g);if(g.status==='Backlog'&&age(g)>180)stale.push(g)});let d=Object.values(dup).filter(a=>a.length>1);openModal(`<h2 class="modalTitle">Library audit</h2><div class="notice">${d.length} duplicate title group${d.length===1?'':'s'} · ${missing.length} incomplete metadata entr${missing.length===1?'y':'ies'} · ${stale.length} backlog games older than 180 days.</div><div class="sectionHead"><h3>Stale backlog</h3></div>${stale.slice(0,20).map(g=>`<div class="entry"><b>${esc(g.title)}</b> · ${age(g)} days</div>`).join('')||'<p class="muted">None.</p>'}<div class="sectionHead"><h3>Duplicates</h3></div>${d.map(a=>`<div class="entry">${a.map(g=>esc(g.title)).join(' · ')}</div>`).join('')||'<p class="muted">None.</p>'}`)}
function smartBacklog(){let a=db.games.filter(g=>g.status==='Backlog').map(g=>({...g,score:((g.priority||0)*24)+(g.favorite?18:0)+(Math.min(age(g),365)/365*20)+(g.progress||0)*.12-(g.hours||0)*.3})).sort((a,b)=>b.score-a.score).slice(0,10);openModal(`<h2 class="modalTitle">Smart backlog shortlist</h2><p class="muted">A transparent local ranking — not a hidden recommendation service.</p>${a.map((g,i)=>`<div class="entry"><b>${i+1}. ${esc(g.title)}</b><div class="muted">Score ${g.score.toFixed(1)} · Priority ${g.priority||0}/5 · ${age(g)} backlog days · ${g.progress||0}% progress</div><button onclick="openGame('${g.id}')">Open</button></div>`).join('')||'<div class="empty">No backlog games.</div>'}`)}
function backupJSON(){let blob=new Blob([JSON.stringify({app:'Game Backlog Tracker',version:1,exported:new Date().toISOString(),data:db},null,2)],{type:'application/json'});download(blob,'game-backlog-backup.json')}
function download(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportCSV(){let rows=[['Title','Status','Platform','Year','Genres','Hours','Progress','Rating','Priority','Ownership','Favorite','Tags']];db.games.forEach(g=>rows.push([g.title,g.status,g.platform,g.year,g.genres,g.hours,g.progress,g.rating,g.priority,g.ownership,g.favorite,g.tags]));let csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');download(new Blob([csv],{type:'text/csv'}),'game-backlog.csv')}
function restoreJSON(){let input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{let o=JSON.parse(await input.files[0].text()),next=o.data||o;if(!next.games||!Array.isArray(next.games))throw Error('Invalid backup');db=next;save();closeModal();alert('Backup restored.')}catch(e){alert('Could not restore: '+e.message)}};input.click()}
async function encryptedBackup(){let pass=prompt('Create a password for this encrypted backup:');if(!pass)return;let enc=new TextEncoder(),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),base=await crypto.subtle.importKey('raw',enc.encode(pass),'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:150000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt']),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(db)));let out={version:1,algorithm:'AES-GCM',kdf:'PBKDF2-SHA-256',iterations:150000,salt:b64(salt),iv:b64(iv),ciphertext:b64(new Uint8Array(cipher))};download(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}),'game-backlog-encrypted.json')}
function b64(a){let s='';a.forEach(x=>s+=String.fromCharCode(x));return btoa(s)}
function snapshot(){db.snapshots=(db.snapshots||[]).filter(Boolean);db.snapshots.unshift({at:new Date().toISOString(),games:db.games,logs:db.logs,lists:db.lists});db.snapshots=db.snapshots.slice(0,5);save();alert('Local snapshot saved.')}
window.openTools=openTools;window.audit=audit;window.smartBacklog=smartBacklog;window.backupJSON=backupJSON;window.restoreJSON=restoreJSON;window.encryptedBackup=encryptedBackup;window.snapshot=snapshot;window.exportCSV=exportCSV;