(()=>{
  const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
  const dayMs=86400000, iso=d=>new Date(d).toISOString().slice(0,10), today=()=>iso(new Date());
  const parseDate=s=>new Date(s+'T12:00:00');
  function weekStart(date,first=1){const d=parseDate(date),day=d.getDay(),diff=(day-first+7)%7;d.setDate(d.getDate()-diff);return iso(d)}
  function logsFor(h){return window.state?.logs?.filter(x=>x.habitId===h.id)||[]}
  function logFor(h,date=today()){return window.state?.logs?.find(x=>x.habitId===h.id&&x.date===date)}
  function scheduled(h,date){const d=parseDate(date),day=d.getDay(),start=h.startDate||'0000-01-01',end=h.endDate||'9999-12-31';if(date<start||date>end)return false;switch(h.frequency){case'daily':return true;case'weekdays':return day>0&&day<6;case'weekends':return day===0||day===6;case'custom':return (h.days||[]).includes(day);case'weekly':return true;case'interval':{const diff=Math.floor((d-parseDate(start))/dayMs);return diff>=0&&diff%Math.max(2,Number(h.interval)||2)===0}default:return true}}
  function expected(h,days=30){const out=[];for(let i=0;i<days;i++){const d=new Date();d.setDate(d.getDate()-i);const s=iso(d);if(scheduled(h,s))out.push(s)}return out}
  function completionRate(h,days=30){if(h.frequency==='weekly'){let good=0,weeks=0;for(let i=0;i<days;i+=7){const d=new Date();d.setDate(d.getDate()-i);const ws=weekStart(iso(d),window.state?.settings?.weekStart??1);const count=logsFor(h).filter(l=>l.date>=ws&&l.date<iso(new Date(parseDate(ws).getTime()+7*dayMs))&&['done','partial'].includes(l.status)).length;good+=Math.min(count,Number(h.weekly)||3);weeks++}return weeks?Math.round(good/(weeks*Math.max(1,Number(h.weekly)||3))*100):0}const ds=expected(h,days);if(!ds.length)return 0;const good=ds.filter(s=>['done','partial'].includes(logFor(h,s)?.status)).length;return Math.round(good/ds.length*100)}
  function streak(h){let n=0,d=new Date();for(let guard=0;guard<400;guard++){const s=iso(d);if(!scheduled(h,s)){d.setDate(d.getDate()-1);continue}const l=logFor(h,s);if(['done','partial'].includes(l?.status)){n++;d.setDate(d.getDate()-1);continue}break}return n}
  function bestStreak(h){let best=0,cur=0;for(const s of expected(h,365).reverse()){if(['done','partial'].includes(logFor(h,s)?.status)){cur++;best=Math.max(best,cur)}else cur=0}return best}
  window.scheduled=scheduled;window.completionRate=completionRate;window.streak=streak;window.bestStreak=bestStreak;
  function health(h){const r7=completionRate(h,7),r30=completionRate(h,30),s=streak(h);let label='Steady',tone='good';if(r7<50){label='Needs a reset';tone='bad'}else if(r7<75){label='Warming up';tone='warn'}else if(s>=7){label='In rhythm';tone='good'}return {r7,r30,s,label,tone}}
  function renderSmart(){
    const active=(window.state?.habits||[]).filter(h=>!h.archived);if(!q('#smartInsights'))return;
    const hs=active.map(h=>({h,x:health(h)})).sort((a,b)=>a.x.r7-b.x.r7);const weakest=hs[0],strongest=hs.slice().sort((a,b)=>b.x.r30-a.x.r30)[0];
    q('#smartInsights').innerHTML=active.length?`<div class="stats-list"><div class="stat"><small>Recovery focus</small><strong>${weakest?esc(weakest.h.name):'—'}</strong><span class="muted">${weakest?weakest.x.r7+'% this week':''}</span></div><div class="stat"><small>Most consistent</small><strong>${strongest?esc(strongest.h.name):'—'}</strong><span class="muted">${strongest?strongest.x.r30+'% / 30d':''}</span></div><div class="stat"><small>Best active streak</small><strong>${Math.max(0,...active.map(streak))} days</strong></div><div class="stat"><small>Today</small><strong>${window.scoreToday?window.scoreToday():'—'}%</strong></div></div><p class="muted">${weakest&&weakest.x.r7<60?`Try making “${esc(weakest.h.name)}” smaller today rather than abandoning the routine.`:'Your recent consistency is balanced. Keep the next action obvious.'}</p>`:'<p class="muted">Add a few habits and this panel will surface useful patterns.</p>';
  }
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function inject(){
    const dash=q('#dashboard');if(dash&&!q('#smartCard')){const card=document.createElement('article');card.id='smartCard';card.className='card';card.innerHTML='<div class="section-head"><div><p class="eyebrow">SMART INSIGHTS</p><h2>Gentle guidance</h2></div><span class="badge">Local & explainable</span></div><div id="smartInsights"></div>';dash.appendChild(card)}
    const top=q('.top-actions');if(top&&!q('#captureBtn')){const b=document.createElement('button');b.id='captureBtn';b.className='ghost';b.textContent='Quick capture';b.title='Ctrl+Shift+A';b.onclick=quickCapture;top.insertBefore(b,top.firstChild)}
    renderSmart();
  }
  function quickCapture(){
    const raw=prompt('Describe a habit, e.g. “Read 20 minutes 4x/week”');if(!raw)return;const m=raw.match(/^(.+?)(?:\s+(\d+(?:\.\d+)?)\s*(minutes?|mins?|hours?|pages?|times?|x))?(?:\s+(?:every\s+)?(\d+)x?\s*(?:per\s+week|\/\s*week|weekly))?$/i);const name=(m?.[1]||raw).trim();const value=Number(m?.[2])||1;let unit='check';const u=(m?.[3]||'').toLowerCase();if(u.includes('min'))unit='minutes';else if(u.includes('hour'))unit='hours';else if(u.includes('page'))unit='pages';else if(u.includes('time')||u==='x')unit='count';const weekly=Number(m?.[4])||0;window.openHabit();setTimeout(()=>{q('#habitName').value=name;q('#habitTarget').value=value;q('#habitUnit').value=unit;if(weekly){q('#habitFrequency').value='weekly';q('#habitWeekly').value=Math.min(7,Math.max(1,weekly))}},0)}
  function addShortcuts(){window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if(e.key==='n')window.openHabit();if(e.key==='t')window.switchView?.('today');if(e.key==='a')window.switchView?.('analytics');if(e.key==='/'){e.preventDefault();window.switchView?.('habits');setTimeout(()=>q('#habitSearch')?.focus(),0)}if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='a'){e.preventDefault();quickCapture()}})}
  function rerender(){renderSmart()}
  setTimeout(()=>{inject();addShortcuts();window.addEventListener('hashchange',inject);const oldRender=window.render;if(oldRender)window.render=function(){oldRender();setTimeout(rerender,0)};},0);
})();