(()=>{
const q=s=>document.querySelector(s),KEY='habitflow:v1',dayMs=86400000,iso=d=>new Date(d).toISOString().slice(0,10),today=()=>iso(new Date()),D=d=>new Date(d+'T12:00:00');
const getState=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{"habits":[],"logs":[],"settings":{"weekStart":1}}')}catch{return {habits:[],logs:[],settings:{weekStart:1}}}};
const log=(h,date)=>getState().logs.find(x=>x.habitId===h.id&&x.date===date);
const start=(date,first=1)=>{const d=D(date),n=(d.getDay()-first+7)%7;d.setDate(d.getDate()-n);return iso(d)};
function scheduled(h,date){const d=D(date),day=d.getDay(),s=h.startDate||'0000-01-01',e=h.endDate||'9999-12-31';if(date<s||date>e)return false;switch(h.frequency){case'daily':return true;case'weekdays':return day>0&&day<6;case'weekends':return day===0||day===6;case'custom':return(h.days||[]).includes(day);case'weekly':return true;case'interval':{const n=Math.floor((d-D(s))/dayMs);return n>=0&&n%Math.max(2,Number(h.interval)||2)===0}default:return true}}
function dates(h,n=30){const a=[];for(let i=0;i<n;i++){const d=new Date();d.setDate(d.getDate()-i);const s=iso(d);if(scheduled(h,s))a.push(s)}return a}
function rate(h,n=30){const st=getState();if(h.frequency==='weekly'){let got=0,weeks=0;for(let i=0;i<n;i+=7){const d=new Date();d.setDate(d.getDate()-i);const ws=start(iso(d),st.settings?.weekStart??1),end=iso(new Date(D(ws).getTime()+7*dayMs));const c=st.logs.filter(l=>l.habitId===h.id&&l.date>=ws&&l.date<end&&['done','partial'].includes(l.status)).length;got+=Math.min(c,Number(h.weekly)||3);weeks++}return weeks?Math.round(got/(weeks*Math.max(1,Number(h.weekly)||3))*100):0}const ds=dates(h,n);return ds.length?Math.round(ds.filter(s=>['done','partial'].includes(log(h,s)?.status)).length/ds.length*100):0}
function streak(h){let n=0,d=new Date();for(let g=0;g<400;g++){const s=iso(d);if(!scheduled(h,s)){d.setDate(d.getDate()-1);continue}if(['done','partial'].includes(log(h,s)?.status)){n++;d.setDate(d.getDate()-1)}else break}return n}
function best(h){let b=0,c=0;for(const s of dates(h,365).reverse()){if(['done','partial'].includes(log(h,s)?.status)){c++;b=Math.max(b,c)}else c=0}return b}
window.scheduled=scheduled;window.completionRate=rate;window.streak=streak;window.bestStreak=best;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function smart(){const st=getState(),hs=st.habits.filter(h=>!h.archived);const box=q('#smartInsights');if(!box)return;if(!hs.length){box.innerHTML='<p class="muted">Add a few habits and this panel will surface useful patterns.</p>';return}const ranked=hs.map(h=>({h,r7:rate(h,7),r30:rate(h,30),s:streak(h)})),weak=ranked.slice().sort((a,b)=>a.r7-b.r7)[0],strong=ranked.slice().sort((a,b)=>b.r30-a.r30)[0],bestSt=Math.max(...ranked.map(x=>x.s));box.innerHTML=`<div class="stats-list"><div class="stat"><small>Recovery focus</small><strong>${esc(weak.h.name)}</strong><span class="muted">${weak.r7}% this week</span></div><div class="stat"><small>Most consistent</small><strong>${esc(strong.h.name)}</strong><span class="muted">${strong.r30}% / 30d</span></div><div class="stat"><small>Best active streak</small><strong>${bestSt} days</strong></div><div class="stat"><small>Active habits</small><strong>${hs.length}</strong></div></div><p class="muted">${weak.r7<60?`Try making “${esc(weak.h.name)}” smaller today rather than abandoning the routine.`:'Your recent consistency is balanced. Keep the next action obvious.'}</p>`}
function capture(){const raw=prompt('Describe a habit, e.g. “Read 20 minutes 4x/week”');if(!raw)return;const m=raw.match(/^(.+?)(?:\s+(\d+(?:\.\d+)?)\s*(minutes?|mins?|hours?|pages?|times?|x))?(?:\s+(\d+)x?\s*(?:per\s+week|\/\s*week|weekly))?$/i);window.openHabit();setTimeout(()=>{q('#habitName').value=(m?.[1]||raw).trim();q('#habitTarget').value=Number(m?.[2])||1;const u=(m?.[3]||'').toLowerCase();q('#habitUnit').value=u.includes('min')?'minutes':u.includes('hour')?'hours':u.includes('page')?'pages':u.includes('time')||u==='x'?'count':'check';if(m?.[4]){q('#habitFrequency').value='weekly';q('#habitWeekly').value=Math.min(7,Math.max(1,Number(m[4])))}},0)}
function inject(){const dash=q('#dashboard');if(dash&&!q('#smartCard')){const c=document.createElement('article');c.id='smartCard';c.className='card';c.innerHTML='<div class="section-head"><div><p class="eyebrow">SMART INSIGHTS</p><h2>Gentle guidance</h2></div><span class="badge">Local & explainable</span></div><div id="smartInsights"></div>';dash.appendChild(c)}const top=q('.top-actions');if(top&&!q('#captureBtn')){const b=document.createElement('button');b.id='captureBtn';b.className='ghost';b.textContent='Quick capture';b.title='Ctrl+Shift+A';b.onclick=capture;top.insertBefore(b,top.firstChild)}smart()}
setTimeout(()=>{inject();window.addEventListener('hashchange',inject);window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if(e.key==='n')window.openHabit();if(e.key==='t')window.switchView?.('today');if(e.key==='a')window.switchView?.('analytics');if(e.key==='/'){e.preventDefault();window.switchView?.('habits');setTimeout(()=>q('#habitSearch')?.focus(),0)}if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='a'){e.preventDefault();capture()}});const r=window.render;if(r)window.render=function(){r();setTimeout(smart,0)}},0);
})();