const KEY='habitflow:v1';
const DEFAULT={habits:[],logs:[],routines:[],settings:{theme:'system',weekStart:1,dailyTarget:.7},meta:{created:new Date().toISOString()}};
let state=load();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const iso=d=>new Date(d).toISOString().slice(0,10);
const today=()=>iso(new Date());
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return {...structuredClone(DEFAULT),...x,settings:{...DEFAULT.settings,...x.settings}}}catch{return structuredClone(DEFAULT)}}
function save(msg){localStorage.setItem(KEY,JSON.stringify(state));render();if(msg)toast(msg)}
function toast(msg){const x=$('#toast');x.textContent=msg;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),1800)}
function applyTheme(){const t=state.settings.theme;document.body.classList.toggle('dark',t==='dark'||(t==='system'&&matchMedia('(prefers-color-scheme:dark)').matches))}
function openModal(id){$('#'+id).classList.add('open');$('#'+id).setAttribute('aria-hidden','false')}
function closeModal(id){$('#'+id).classList.remove('open');$('#'+id).setAttribute('aria-hidden','true')}
function habitLogs(h){return state.logs.filter(x=>x.habitId===h.id)}
function logFor(h,date=today()){return state.logs.find(x=>x.habitId===h.id&&x.date===date)}
function daysSince(date){return Math.floor((new Date(today())-new Date(date||today()))/86400000)}
function scheduled(h,date){const d=new Date(date+'T12:00:00'),day=d.getDay(),start=h.startDate||'0000-01-01',end=h.endDate||'9999-12-31';if(date<start||date>end)return false;switch(h.frequency){case'daily':return true;case'weekdays':return day>0&&day<6;case'weekends':return day===0||day===6;case'custom':return(h.days||[]).includes(day);case'weekly':return true;case'interval':return Math.max(0,Math.floor((d-new Date(start+'T12:00:00'))/86400000))%Math.max(2,Number(h.interval)||2)===0;default:return true}}
function expectedDates(h,days=30){const arr=[];for(let i=0;i<days;i++){const d=new Date();d.setDate(d.getDate()-i);const s=iso(d);if(scheduled(h,s))arr.push(s)}return arr}
function completionRate(h,days=30){if(h.frequency==='weekly'){let good=0,weeks=0;for(let i=0;i<days;i+=7){const d=new Date();d.setDate(d.getDate()-i);const end=new Date(d);end.setDate(end.getDate()+1);const ws=new Date(d);ws.setDate(ws.getDate()-((ws.getDay()-(state.settings.weekStart||1)+7)%7));ws.setHours(12,0,0,0);const we=new Date(ws);we.setDate(we.getDate()+7);const c=state.logs.filter(l=>l.habitId===h.id&&l.date>=iso(ws)&&l.date<iso(we)&&['done','partial'].includes(l.status)).length;good+=Math.min(c,Number(h.weekly)||3);weeks++}return weeks?Math.round(good/(weeks*Math.max(1,Number(h.weekly)||3))*100):0}const dates=expectedDates(h,days);if(!dates.length)return 0;const good=dates.filter(d=>{const l=logFor(h,d);return l&&(l.status==='done'||l.status==='partial')}).length;return Math.round(good/dates.length*100)}
function streak(h){let n=0,d=new Date();for(let guard=0;guard<400;guard++){const s=iso(d);if(!scheduled(h,s)){d.setDate(d.getDate()-1);continue}const l=logFor(h,s);if(l?.status==='done'||l?.status==='partial'){n++;d.setDate(d.getDate()-1)}else break}return n}
function bestStreak(h){let best=0,cur=0;for(const s of expectedDates(h,365).reverse()){const l=logFor(h,s);if(l?.status==='done'||l?.status==='partial'){cur++;best=Math.max(best,cur)}else cur=0}return best}
function scoreToday(){const hs=state.habits.filter(h=>!h.archived&&scheduled(h,today()));if(!hs.length)return 0;const points=hs.reduce((n,h)=>{const l=logFor(h);return n+(l?.status==='done'?1:l?.status==='partial'?.5:0)},0);return Math.round(points/hs.length*100)}
function status(h){const l=logFor(h);if(l)return l.status;return scheduled(h,today())?'pending':'not-due'}
function habitLabel(h){return h.type==='bad'?'Reduce':'Build'}
function unitLabel(h){return h.unit==='check'?'check-in':h.unit==='custom'?'units':h.unit}
function formatTarget(h){return h.unit==='check'?'1 check-in':`${h.target||0} ${unitLabel(h)}`}
function render(){applyTheme();$('#todayLabel').textContent=new Intl.DateTimeFormat(undefined,{weekday:'long',month:'short',day:'numeric'}).format(new Date());$('#dailyScore').textContent=scoreToday()+'%';renderMetrics();renderToday();renderHabits();renderAnalytics();renderRoutines();renderArchive();renderSettings();fillFilters()}
function renderMetrics(){const hs=state.habits.filter(h=>!h.archived),due=hs.filter(h=>scheduled(h,today())),done=due.filter(h=>['done','partial'].includes(status(h))).length,current=hs.filter(h=>streak(h)>0).length,avg=hs.length?Math.round(hs.reduce((n,h)=>n+completionRate(h,30),0)/hs.length):0;$('#metrics').innerHTML=[['Active habits',hs.length],['Due today',due.length],['Completed today',done],['30-day average',avg+'%']].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('#momentum').innerHTML=`<div class="stats-list"><div class="stat"><small>Habits with a streak</small><strong>${current}</strong></div><div class="stat"><small>Daily target</small><strong>${Math.round(state.settings.dailyTarget*100)}%</strong></div></div><p class="muted">${scoreToday()>=state.settings.dailyTarget*100?'You are on pace today.':'Focus on the smallest useful action next.'}</p>`;const counts=[0,0,0,0,0,0,0];for(let i=0;i<7;i++){const d=new Date();d.setDate(d.getDate()-6+i);const s=iso(d);counts[d.getDay()]=hs.filter(h=>scheduled(h,s)&&['done','partial'].includes(logFor(h,s)?.status)).length}const max=Math.max(1,...counts);$('#weeklyRhythm').innerHTML=counts.map((n,i)=>`<div class="daybar"><i style="height:${Math.max(4,n/max*95)}px"></i><span>${['S','M','T','W','T','F','S'][i]}</span></div>`).join('')}
function renderToday(){const hs=state.habits.filter(h=>!h.archived&&scheduled(h,today())).sort((a,b)=>(status(a)==='done')-(status(b)==='done')||streak(b)-streak(a));const html=hs.length?hs.map(h=>journalRow(h)).join(''):'<div class="card empty">Nothing scheduled today. Add a habit or enjoy the space.</div>';$('#todayList').innerHTML=html;$('#journalList').innerHTML=html;$('#journalTitle').textContent=new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric'}).format(new Date());const attention=state.habits.filter(h=>!h.archived).map(h=>({h,rate:completionRate(h,14),s:streak(h)})).filter(x=>x.rate<70).sort((a,b)=>a.rate-b.rate).slice(0,5);$('#attentionList').innerHTML=attention.length?attention.map(x=>`<div class="habit-row"><div><div class="habit-name">${esc(x.h.name)}</div><small class="muted">${x.rate}% in 14 days · ${x.s} day streak</small></div><button onclick="openCheck('${x.h.id}')">Log</button></div>`).join(''):'<p class="muted">Your active habits have a healthy recent rhythm.</p>';const counts={};state.habits.filter(h=>!h.archived).forEach(h=>counts[h.area||'Personal']=(counts[h.area||'Personal']||0)+completionRate(h,30));const vals=Object.entries(counts).map(([a,n])=>[a,Math.round(n/(state.habits.filter(h=>!h.archived&&h.area===a).length||1))]);$('#areaBalance').innerHTML=vals.length?vals.sort((a,b)=>b[1]-a[1]).slice(0,7).map(([a,n])=>`<div class="bar"><span>${esc(a)}</span><div><i style="width:${n}%"></i></div><small>${n}%</small></div>`).join(''):'<p class="muted">Add habits to see area balance.</p>'}
function journalRow(h){const l=logFor(h),st=l?.status||'pending',val=l?.value??'';return `<div class="journal-row"><div><div class="row"><div><span class="badge ${h.type==='bad'?'bad':''}">${habitLabel(h)}</span> <span class="badge">${esc(h.area||'Personal')}</span></div><span class="muted">${st==='done'?'Done':st==='partial'?'Partial':st==='skipped'?'Skipped':st==='missed'?'Missed':'Not logged'}</span></div><div class="habit-name">${esc(h.name)}</div><div class="habit-meta"><span>${formatTarget(h)}</span><span>${streak(h)} day streak</span><span>${completionRate(h,30)}% / 30d</span>${val!==''?`<span>today: ${val}</span>`:''}</div></div><div class="journal-actions"><button class="check-btn ${st==='done'?'done':st==='partial'?'partial':''}" title="Mark done" onclick="quickCheck('${h.id}','done')">✓</button><button onclick="openCheck('${h.id}')">Log</button></div></div>`}
function renderHabits(){const q=($('#habitSearch')?.value||'').toLowerCase(),f=$('#habitFilter')?.value||'all',a=$('#areaFilter')?.value||'all',sort=$('#sortFilter')?.value||'attention';let hs=state.habits.filter(h=>(f==='archived'?h.archived:!h.archived)&&(f==='all'||f==='archived'||h.type===f)&&(!q||[h.name,h.area,h.tags,h.notes].join(' ').toLowerCase().includes(q))&&(a==='all'||h.area===a));hs.sort((x,y)=>sort==='name'?x.name.localeCompare(y.name):sort==='streak'?streak(y)-streak(x):sort==='rate'?completionRate(y,30)-completionRate(x,30):completionRate(x,14)-completionRate(y,14));$('#habitGrid').innerHTML=hs.length?hs.map(habitCard).join(''):'<div class="card empty">No habits match these filters.</div>'}
function habitCard(h){const rate=completionRate(h,30),s=streak(h),l=logFor(h);return `<article class="card"><div class="row"><div><span class="badge ${h.type==='bad'?'bad':'good'}">${habitLabel(h)}</span><h2 style="margin:7px 0">${esc(h.name)}</h2></div><span class="badge">${esc(h.area||'Personal')}</span></div><p class="muted">${esc(h.notes||'No note yet.')}</p><div class="progress"><i style="width:${rate}%"></i></div><div class="habit-meta"><span>${rate}% / 30d</span><span>Streak ${s}</span><span>Best ${bestStreak(h)}</span><span>${formatTarget(h)}</span></div><div class="row" style="margin-top:13px"><span class="badge">${esc(scheduleText(h))}</span><div class="habit-actions">${!h.archived?`<button onclick="quickCheck('${h.id}','done')">${l?.status==='done'?'Done today':'Check in'}</button>`:''}<button onclick="openHabit('${h.id}')">Edit</button><button onclick="archiveHabit('${h.id}')">${h.archived?'Restore':'Archive'}</button></div></div></article>`}
function scheduleText(h){if(h.frequency==='daily')return'Daily';if(h.frequency==='weekdays')return'Weekdays';if(h.frequency==='weekends')return'Weekends';if(h.frequency==='weekly')return`${h.weekly||3}× / week`;if(h.frequency==='interval')return`Every ${h.interval||2} days`;return(h.days||[]).map(Number).sort().map(d=>['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d]).join(' · ')}
function fillFilters(){const areas=[...new Set(state.habits.map(h=>h.area).filter(Boolean))].sort();$('#areaFilter').innerHTML='<option value="all">All areas</option>'+areas.map(a=>`<option value="${esc(a)}">${esc(a)}</option>`).join('');$('#analyticsHabit').innerHTML=state.habits.filter(h=>!h.archived).map(h=>`<option value="${h.id}">${esc(h.name)}</option>`).join('')||'<option value="">No habits</option>'}
function renderAnalytics(){const hs=state.habits.filter(h=>!h.archived),all=hs.length?Math.round(hs.reduce((n,h)=>n+completionRate(h,90),0)/hs.length):0,best=hs.slice().sort((a,b)=>bestStreak(b)-bestStreak(a))[0];$('#analyticsSummary').innerHTML=[['90-day average',all+'%'],['Best current streak',Math.max(0,...hs.map(streak))+' days'],['Best all-time streak',Math.max(0,...hs.map(bestStreak))+' days'],['Strongest habit',best?best.name:'—']].map(x=>`<div class="stat"><small>${x[0]}</small><strong>${esc(x[1])}</strong></div>`).join('');const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((name,i)=>{let n=0,t=0;hs.forEach(h=>{for(const d of expectedDates(h,56)){if(new Date(d+'T12:00:00').getDay()===i){t++;if(['done','partial'].includes(logFor(h,d)?.status))n++}}});return[name,t?Math.round(n/t*100):0]});$('#weekdayChart').innerHTML=days.map(([n,v])=>`<div class="vbar"><i style="height:${Math.max(3,v)}%"></i><span>${n}<br>${v}%</span></div>`).join('');$('#leaderboard').innerHTML=hs.slice().sort((a,b)=>completionRate(b,30)-completionRate(a,30)).slice(0,8).map((h,i)=>`<div class="habit-row"><div><b>${i+1}. ${esc(h.name)}</b><small class="muted">${streak(h)} streak · best ${bestStreak(h)}</small></div><strong>${completionRate(h,30)}%</strong></div>`).join('')||'<p class="muted">No data yet.</p>';renderHeatmap();renderHabitDetail()}
function renderHeatmap(){const hs=state.habits.filter(h=>!h.archived),cells=[];for(let i=89;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const s=iso(d);let total=0,done=0,partial=0,miss=0,skip=0;hs.forEach(h=>{if(!scheduled(h,s))return;total++;const st=logFor(h,s)?.status;if(st==='done')done++;else if(st==='partial')partial++;else if(st==='missed')miss++;else if(st==='skipped')skip++});let cls='';if(total&&done===total)cls='done';else if(done||partial)cls='partial';else if(miss)cls='missed';else if(skip)cls='skipped';cells.push(`<span class="heat ${cls}" title="${s}: ${done}/${total} complete"></span>`)}$('#heatmap').innerHTML=cells.join('')}
function renderHabitDetail(){const id=$('#analyticsHabit')?.value,h=state.habits.find(x=>x.id===id);if(!h){$('#habitDetail').innerHTML='<p class="muted">Create a habit to see detail.</p>';return}const logs=habitLogs(h),last=logs.slice().sort((a,b)=>b.date.localeCompare(a.date))[0];$('#habitDetail').innerHTML=`<div class="stats-list"><div class="stat"><small>30-day completion</small><strong>${completionRate(h,30)}%</strong></div><div class="stat"><small>Current streak</small><strong>${streak(h)}</strong></div><div class="stat"><small>Best streak</small><strong>${bestStreak(h)}</strong></div><div class="stat"><small>Last logged</small><strong>${last?.date||'—'}</strong></div></div><p class="muted">${esc(h.notes||'No notes.')} ${h.tags?` · ${esc(h.tags)}`:''}</p>`}
function renderRoutines(){const el=$('#routineGrid');el.innerHTML=state.routines.length?state.routines.map(r=>{const hs=r.habits.map(id=>state.habits.find(h=>h.id===id)).filter(Boolean);return `<article class="card"><div class="row"><div><span class="badge">${esc(r.time)}</span><h2>${esc(r.name)}</h2></div><button onclick="deleteRoutine('${r.id}')">Delete</button></div>${hs.map(h=>`<div class="habit-row"><span>${esc(h.name)}</span><button onclick="quickCheck('${h.id}','done')">Done</button></div>`).join('')||'<p class="muted">No habits selected.</p>'}</article>`}).join(''):'<div class="card empty">Create a routine to chain a few habits into one repeatable sequence.</div>'}
function renderArchive(){const hs=state.habits.filter(h=>h.archived);$('#archiveList').innerHTML=hs.length?hs.map(h=>`<article class="card"><span class="badge">${esc(h.area||'Personal')}</span><h2>${esc(h.name)}</h2><p class="muted">${completionRate(h,90)}% over last 90 days · best streak ${bestStreak(h)}</p><button onclick="archiveHabit('${h.id}')">Restore</button></article>`).join(''):'<div class="card empty">No archived habits.</div>'}
function renderSettings(){$('#theme').value=state.settings.theme;$('#weekStart').value=state.settings.weekStart;$('#dailyTarget').value=state.settings.dailyTarget;const bytes=new Blob([JSON.stringify(state)]).size;$('#storageHealth').innerHTML=`<div class="stats-list"><div class="stat"><small>Habits</small><strong>${state.habits.length}</strong></div><div class="stat"><small>Check-ins</small><strong>${state.logs.length}</strong></div><div class="stat"><small>Local storage payload</small><strong>${Math.round(bytes/1024)} KB</strong></div><div class="stat"><small>Backup status</small><strong>${localStorage.getItem(KEY)?'Saved':'Empty'}</strong></div></div>`}
function openHabit(id=''){const h=state.habits.find(x=>x.id===id);$('#habitModalTitle').textContent=h?'Edit habit':'New habit';$('#habitId').value=h?.id||'';$('#habitName').value=h?.name||'';$('#habitType').value=h?.type||'good';$('#habitArea').value=h?.area||'Personal';$('#habitUnit').value=h?.unit||'check';$('#habitTarget').value=h?.target??1;$('#habitFrequency').value=h?.frequency||'daily';$('#habitWeekly').value=h?.weekly||3;$('#habitInterval').value=h?.interval||2;$('#habitTime').value=h?.timeOfDay||'any';$('#habitReminder').value=h?.reminder||'';$('#habitStart').value=h?.startDate||today();$('#habitEnd').value=h?.endDate||'';$('#habitTags').value=h?.tags||'';$('#habitNotes').value=h?.notes||'';renderDayPicker(h?.days||[1,2,3,4,5]);openModal('habitModal')}
function renderDayPicker(selected){const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];$('#dayPicker').innerHTML=days.map((d,i)=>`<button type="button" class="day ${selected.includes(i)?'active':''}" data-day="${i}">${d}</button>`).join('')}
function submitHabit(e){e.preventDefault();const old=state.habits.find(h=>h.id===$('#habitId').value),days=$$('#dayPicker .day.active').map(x=>Number(x.dataset.day));const h={id:old?.id||uid(),name:$('#habitName').value.trim(),type:$('#habitType').value,area:$('#habitArea').value.trim()||'Personal',unit:$('#habitUnit').value,target:Number($('#habitTarget').value)||1,frequency:$('#habitFrequency').value,weekly:Number($('#habitWeekly').value)||3,interval:Number($('#habitInterval').value)||2,days,timeOfDay:$('#habitTime').value,reminder:$('#habitReminder').value,startDate:$('#habitStart').value||today(),endDate:$('#habitEnd').value,tags:$('#habitTags').value.trim(),notes:$('#habitNotes').value.trim(),archived:old?.archived||false,created:old?.created||new Date().toISOString(),updated:new Date().toISOString(),anchorDay:old?.anchorDay??new Date().getDay()};if(!h.name)return;if(old)Object.assign(old,h);else state.habits.push(h);save('Habit saved');closeModal('habitModal')}
function openCheck(id){const h=state.habits.find(x=>x.id===id),l=logFor(h);if(!h)return;$('#checkHabitId').value=id;$('#checkTitle').textContent=h.name;$('#checkDate').value=l?.date||today();$('#checkStatus').value=l?.status||'done';$('#checkValue').value=l?.value??(h.unit==='check'?1:'');$('#checkNote').value=l?.note||'';openModal('checkModal')}
function submitCheck(e){e.preventDefault();const id=$('#checkHabitId').value,h=state.habits.find(x=>x.id===id),date=$('#checkDate').value;if(!h||!date)return;const existing=logFor(h,date),entry={id:existing?.id||uid(),habitId:id,date,status:$('#checkStatus').value,value:Number($('#checkValue').value)||0,note:$('#checkNote').value.trim(),updated:new Date().toISOString()};if(existing)Object.assign(existing,entry);else state.logs.push(entry);save('Check-in saved');closeModal('checkModal')}
function quickCheck(id,status='done'){const h=state.habits.find(x=>x.id===id);if(!h)return;const l=logFor(h);if(l?.status===status){state.logs=state.logs.filter(x=>x.id!==l.id);save('Check-in removed');return}const entry={id:l?.id||uid(),habitId:id,date:today(),status,value:h.unit==='check'?1:Number(h.target)||1,note:l?.note||'',updated:new Date().toISOString()};if(l)Object.assign(l,entry);else state.logs.push(entry);save(status==='done'?'Habit completed':'Habit updated')}
function archiveHabit(id){const h=state.habits.find(x=>x.id===id);if(!h)return;h.archived=!h.archived;save(h.archived?'Habit archived':'Habit restored')}
function openRoutine(id=''){const r=state.routines.find(x=>x.id===id);$('#routineId').value=r?.id||'';$('#routineName').value=r?.name||'';$('#routineTime').value=r?.time||'morning';$('#routineHabits').innerHTML=state.habits.filter(h=>!h.archived).map(h=>`<label class="check-item"><input type="checkbox" value="${h.id}" ${r?.habits?.includes(h.id)?'checked':''}>${esc(h.name)}</label>`).join('')||'<span class="muted">Create habits first.</span>';openModal('routineModal')}
function submitRoutine(e){e.preventDefault();const id=$('#routineId').value,old=state.routines.find(r=>r.id===id),r={id:id||uid(),name:$('#routineName').value.trim(),time:$('#routineTime').value,habits:$$('#routineHabits input:checked').map(x=>x.value)};if(!r.name)return;if(old)Object.assign(old,r);else state.routines.push(r);save('Routine saved');closeModal('routineModal')}
function deleteRoutine(id){state.routines=state.routines.filter(x=>x.id!==id);save('Routine deleted')}
function exportJson(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString(),schema:'habitflow.v1'})],{type:'application/json'}));a.download='habitflow-backup.json';a.click();URL.revokeObjectURL(a.href)}
function exportCsv(){const rows=[['habit','type','area','date','status','value','note']];state.logs.forEach(l=>{const h=state.habits.find(x=>x.id===l.habitId);rows.push([h?.name||'Deleted',h?.type||'',h?.area||'',l.date,l.status,l.value,l.note||''])});const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='habitflow-checkins.csv';a.click();URL.revokeObjectURL(a.href)}
function importJson(file){const fr=new FileReader();fr.onload=()=>{try{const x=JSON.parse(fr.result);if(!Array.isArray(x.habits)||!Array.isArray(x.logs))throw Error();state={...structuredClone(DEFAULT),...x,settings:{...DEFAULT.settings,...x.settings}};save('Backup imported')}catch{toast('Invalid Habitflow backup')}};fr.readAsText(file)}
function showTemplates(){const ts=[['Morning reading','Read for 20 minutes','good','minutes',20,'daily'],['Move 3× weekly','Walk, stretch or exercise','good','check',1,'weekly'],['Plan tomorrow','Write tomorrow’s top priorities','good','check',1,'daily'],['Hydrate','Drink water intentionally','good','count',6,'daily'],['Screen-free wind-down','Reduce late-night screen time','bad','check',1,'daily'],['Weekly reflection','Reflect on the week','good','minutes',15,'weekly']];$('#templateList').innerHTML=ts.map((t,i)=>`<article class="template"><span class="badge">${t[5]}</span><h3>${t[0]}</h3><p>${t[1]}</p><button onclick="useTemplate(${i})">Use template</button></article>`).join('');window.templates=ts;openModal('templateModal')}
function useTemplate(i){const t=window.templates[i];closeModal('templateModal');openHabit();$('#habitName').value=t[0];$('#habitNotes').value=t[1];$('#habitType').value=t[2];$('#habitUnit').value=t[3];$('#habitTarget').value=t[4];$('#habitFrequency').value=t[5]}
function switchView(v){if(!$('#'+v))return;$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));location.hash=v;$('#sidebar').classList.remove('open');render()}
function bind(){document.addEventListener('click',e=>{const n=e.target.closest('[data-view]');if(n)switchView(n.dataset.view);const c=e.target.closest('[data-close]');if(c)closeModal(c.dataset.close)});$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#newHabit').onclick=()=>openHabit();$('#focusBtn').onclick=()=>{switchView('today');const first=state.habits.find(h=>!h.archived&&scheduled(h,today())&&status(h)!=='done');if(first)openCheck(first.id)};$('#newRoutine').onclick=()=>openRoutine();$('#templateBtn').onclick=showTemplates;$('#habitForm').onsubmit=submitHabit;$('#checkForm').onsubmit=submitCheck;$('#routineForm').onsubmit=submitRoutine;$('#exportJson').onclick=exportJson;$('#exportCsv').onclick=exportCsv;$('#importJson').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>e.target.files[0]&&importJson(e.target.files[0]);$('#resetData').onclick=()=>{if(confirm('Delete all Habitflow data from this browser?')){localStorage.removeItem(KEY);state=load();render();toast('Data reset')}};['habitSearch','habitFilter','areaFilter','sortFilter'].forEach(id=>$('#'+id).addEventListener('input',renderHabits));$('#analyticsHabit').onchange=renderHabitDetail;$('#theme').onchange=e=>{state.settings.theme=e.target.value;save('Theme updated')};$('#weekStart').onchange=e=>{state.settings.weekStart=Number(e.target.value);save('Week start updated')};$('#dailyTarget').onchange=e=>{state.settings.dailyTarget=Number(e.target.value);save('Daily target updated')};$('#notifyBtn').onclick=enableNotifications;$('#dayPicker').addEventListener('click',e=>{const b=e.target.closest('[data-day]');if(b)b.classList.toggle('active')});window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();openHabit()}if(e.key==='Escape')$$('.modal.open').forEach(x=>closeModal(x.id))})}
async function enableNotifications(){if(!('Notification'in window)){toast('Notifications are not supported');return}const p=await Notification.requestPermission();toast(p==='granted'?'Reminders enabled':'Permission not granted')}
function reminderTick(){if(typeof Notification==='undefined'||Notification.permission!=='granted')return;const now=new Date(),hm=now.toTimeString().slice(0,5);state.habits.filter(h=>!h.archived&&h.reminder===hm&&scheduled(h,today())&&!logFor(h)).forEach(h=>new Notification('Habitflow reminder',{body:`Time for: ${h.name}`}))}
bind();render();setInterval(reminderTick,60000);if(location.hash)switchView(location.hash.slice(1));
Object.assign(window,{openHabit,openCheck,quickCheck,archiveHabit,openRoutine,deleteRoutine,useTemplate,render,switchView,scoreToday});