const AKEY='reading-tracker:advanced:v2';
let adv=JSON.parse(localStorage.getItem(AKEY)||'null')||{prompts:['What idea will you remember from this book?','What changed your mind?','What would you recommend?','What passage deserves another look?'],journal:[],challenges:[],snapshots:[],settings:{dailyMinutes:20,reminderTime:'20:00'}};
function saveAdvanced(){localStorage.setItem(AKEY,JSON.stringify(adv))}
function openStudio(){const modal=document.querySelector('#modal');document.querySelector('#modalBody').innerHTML=`<div class="modal"><div class="row"><div><span class="label">READING STUDIO</span><h2>Your reading practice</h2></div><button onclick="document.querySelector('#modal').close()">Close</button></div><div class="grid" style="margin-top:14px"><div class="card"><span class="label">REFLECTIONS</span><div class="stat">${adv.journal.length}</div></div><div class="card"><span class="label">CHALLENGES</span><div class="stat">${adv.challenges.length}</div></div><div class="card"><span class="label">RESTORE POINTS</span><div class="stat">${adv.snapshots.length}</div></div></div><div class="card" style="margin-top:14px"><h3>Classic tools</h3><div class="list"><button onclick="readingPrompt()">Writing prompt</button><button onclick="readingReflection()">Add reflection</button><button onclick="readingChallenge()">Create challenge</button><button onclick="readingSnapshot()">Save restore point</button><button onclick="readingExport()">Export classic backup</button></div></div></div>`;modal.showModal()}
window.openStudio=openStudio;
function readingPrompt(){const p=adv.prompts[Math.floor(Math.random()*adv.prompts.length)];uiModal(`<span class="label">PROMPT</span><h2>${esc(p)}</h2><textarea id="promptAnswer" rows="6" placeholder="Write privately..."></textarea><div class="row"><button onclick="closeModal()">Close</button><button class="primary" onclick="savePrompt()">Save reflection</button></div>`)}
function savePrompt(){const t=document.querySelector('#promptAnswer').value.trim();if(!t)return;adv.journal.push({id:crypto.randomUUID(),date:new Date().toISOString().slice(0,10),text:t});saveAdvanced();openStudio()}
function readingReflection(){uiModal(`<h2>Reading reflection</h2><textarea id="reflection" rows="7" placeholder="What are you thinking about after reading?"></textarea><div class="row"><button onclick="closeModal()">Cancel</button><button class="primary" onclick="saveReflection()">Save</button></div>`)}
function saveReflection(){const t=document.querySelector('#reflection').value.trim();if(t){adv.journal.push({id:crypto.randomUUID(),date:new Date().toISOString().slice(0,10),text:t});saveAdvanced();openStudio()}}
function readingChallenge(){uiModal(`<h2>Reading challenge</h2><form class="form" id="challenge"><label>Name<input name="name" required></label><label>Target books<input name="target" type="number" min="1" value="5"></label><label>End date<input name="end" type="date"></label><div class="row"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Create</button></div></form>`);document.querySelector('#challenge').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);adv.challenges.push({id:crypto.randomUUID(),name:f.get('name'),target:+f.get('target'),end:f.get('end'),created:new Date().toISOString()});saveAdvanced();openStudio()}}
function readingSnapshot(){adv.snapshots.push({date:new Date().toISOString(),state:JSON.parse(JSON.stringify(state))});adv.snapshots=adv.snapshots.slice(-12);saveAdvanced();alert('Local restore point saved.')}
function readingExport(){const payload={version:2,exportedAt:new Date().toISOString(),state,advanced:adv};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='reading-tracker-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}