const KEY='reading-tracker:v2';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{books:[],sessions:[],goals:{year:12,pages:0,minutes:0},theme:'system'};
let view='dashboard'; const $=s=>document.querySelector(s); const id=()=>crypto.randomUUID(); const today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(state));window.state=state;render()}
window.state=state;window.save=save;
function progress(b){return b.pages?Math.min(100,Math.round((b.current||0)/b.pages*100)):0}
function yearBooks(y=new Date().getFullYear()){return state.books.filter(b=>b.status==='Read'&&String(b.finishedAt||'').startsWith(String(y))).length}
function daySessions(d=today()){return state.sessions.filter(s=>s.date===d)}
function pagesToday(){return daySessions().reduce((n,s)=>n+(+s.pages||0),0)}
function minutesToday(){return daySessions().reduce((n,s)=>n+(+s.minutes||0),0)}
function applyTheme(){document.body.classList.remove('dark','light');if(state.theme!=='system')document.body.classList.add(state.theme)}
function render(){applyTheme();$('#todayMinutes').textContent=minutesToday()+' min';$('#todayPages').textContent=pagesToday()+' pages';const y=yearBooks(),goal=state.goals.year||0,pct=goal?Math.min(100,Math.round(y/goal*100)):0;$('#goalPct').textContent=pct+'%';$('#goalRing').style.setProperty('--p',pct);$('#yearProgress').textContent=y+' / '+goal;$('#paceText').textContent=goal?(goal>y?(goal-y)+' books to go':'Goal reached'):'Set a goal';document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===view));({dashboard,library,sessionsView,stats,goals}[view]||dashboard)()}
function dashboard(){const current=state.books.filter(b=>b.status==='Currently Reading'),queue=state.books.filter(b=>b.status==='Want to Read').slice(0,5);$('#view').innerHTML=`<div class="grid"><div class="card"><span class="label">CURRENTLY READING</span><div class="list">${current.map(bookCard).join('')||'<div class="empty">Nothing in progress yet.</div>'}</div></div><div class="card"><span class="label">UP NEXT</span><div class="list">${queue.map(bookCard).join('')||'<div class="empty">Your TBR is clear.</div>'}</div></div><div class="card"><span class="label">TODAY</span><div class="stat">${pagesToday()} pages</div><p class="muted">${minutesToday()} minutes logged today.</p><div class="row"><span>Library</span><b>${state.books.length}</b></div><div class="row"><span>Read this year</span><b>${yearBooks()}</b></div></div></div><div class="card" style="margin-top:14px"><div class="row"><h2>Recent sessions</h2><button onclick="view='sessions';render()">See all</button></div>${state.sessions.slice().reverse().slice(0,8).map(s=>`<div class="row session"><span><b>${esc(state.books.find(b=>b.id===s.bookId)?.title||'Unknown')}</b><small>${s.date}</small></span><span>${s.pages||0} pages · ${s.minutes||0} min</span></div>`).join('')||'<div class="empty">Log a session to build your reading history.</div>'}</div>`}
function bookCard(b){return `<article class="book"><div class="cover"></div><div class="bookmain"><h3>${esc(b.title)}</h3><div class="muted">${esc(b.author||'Unknown author')}</div><div class="meta"><span class="chip">${esc(b.status)}</span>${b.genre?`<span class="chip">${esc(b.genre)}</span>`:''}${b.rating?`<span class="chip">${b.rating}/5</span>`:''}</div>${b.status==='Currently Reading'?`<div class="bar"><i style="width:${progress(b)}%"></i></div><small class="muted">${b.current||0} / ${b.pages||'?'} pages · ${progress(b)}%</small>`:''}</div><button onclick="editBook('${b.id}')">Edit</button></article>`}
function library(){let q=($('#search').value||'').toLowerCase(),st=$('#status').value;const list=state.books.filter(b=>(st==='all'||b.status===st)&&(!q||JSON.stringify(b).toLowerCase().includes(q)));$('#view').innerHTML=`<div class="card"><div class="row"><h2>Library</h2><span class="muted">${list.length} books</span></div><div class="list">${list.map(bookCard).join('')||'<div class="empty">No books match your filters.</div>'}</div></div>`}
function sessionsView(){const list=state.sessions.slice().reverse();$('#view').innerHTML=`<div class="card"><div class="row"><h2>Reading sessions</h2><button class="primary" onclick="startSession()">+ Log session</button></div><div class="list">${list.map(s=>`<div class="row session"><span><b>${esc(state.books.find(b=>b.id===s.bookId)?.title||'Unknown')}</b><small>${s.date}${s.note?' · '+esc(s.note):''}</small></span><span>${s.pages||0} pages · ${s.minutes||0} min</span></div>`).join('')||'<div class="empty">No sessions yet.</div>'}</div></div>`}
function stats(){const done=state.books.filter(b=>b.status==='Read'),pages=state.sessions.reduce((n,s)=>n+(+s.pages||0),0),mins=state.sessions.reduce((n,s)=>n+(+s.minutes||0),0),genre={};done.forEach(b=>{const g=b.genre||'Uncategorized';genre[g]=(genre[g]||0)+1});const max=Math.max(1,...Object.values(genre));$('#view').innerHTML=`<div class="grid"><div class="card"><span class="label">BOOKS READ</span><div class="stat">${done.length}</div></div><div class="card"><span class="label">PAGES</span><div class="stat">${pages.toLocaleString()}</div></div><div class="card"><span class="label">READING TIME</span><div class="stat">${Math.round(mins/60)}h</div><p class="muted">${mins} minutes</p></div></div><div class="card" style="margin-top:14px"><h2>Genre profile</h2>${Object.entries(genre).map(([g,n])=>`<div class="metric"><div class="row"><span>${esc(g)}</span><b>${n}</b></div><div class="bar"><i style="width:${n/max*100}%"></i></div></div>`).join('')||'<div class="empty">Finish books to build your profile.</div>'}</div>`}
function goals(){const y=new Date().getFullYear();$('#view').innerHTML=`<div class="grid"><div class="card"><h2>${y} reading goal</h2><div class="stat">${yearBooks()} / ${state.goals.year||0}</div><div class="bar"><i style="width:${Math.min(100,yearBooks()/Math.max(1,state.goals.year||0)*100)}%"></i></div><button style="margin-top:12px" onclick="setGoals()">Edit goals</button></div><div class="card"><h2>Page target</h2><div class="stat">${state.goals.pages||0}</div><p class="muted">Optional total target.</p></div><div class="card"><h2>Minute target</h2><div class="stat">${state.goals.minutes||0}</div><p class="muted">Optional total target.</p></div></div>`}
function uiModal(html){$('#modalBody').innerHTML=`<div class="modal">${html}</div>`;$('#modal').showModal()} window.uiModal=uiModal;
function closeModal(){$('#modal').close()}
function addBook(){uiModal(`<h2>Add book</h2><form class="form" id="bookForm"><label>Title<input name="title" required autofocus></label><label>Author<input name="author"></label><div class="two"><label>Pages<input name="pages" type="number" min="1"></label><label>Current page<input name="current" type="number" min="0"></label></div><div class="two"><label>Status<select name="status"><option>Want to Read</option><option>Currently Reading</option><option>Read</option><option>DNF</option><option>Owned</option></select></label><label>Genre<input name="genre"></label></div><label>Tags<input name="tags" placeholder="fiction, history"></label><label>Notes<textarea name="notes" rows="4"></textarea></label><div class="row"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div></form>`);$('#bookForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.books.push({id:id(),title:f.get('title'),author:f.get('author'),pages:+f.get('pages')||0,current:+f.get('current')||0,status:f.get('status'),genre:f.get('genre'),tags:String(f.get('tags')).split(',').map(x=>x.trim()).filter(Boolean),notes:f.get('notes'),createdAt:new Date().toISOString(),finishedAt:f.get('status')==='Read'?new Date().toISOString():null});closeModal();save()}}
function editBook(bid){const b=state.books.find(x=>x.id===bid);if(!b)return;uiModal(`<h2>Edit book</h2><form class="form" id="editForm"><label>Title<input name="title" value="${esc(b.title)}" required></label><label>Author<input name="author" value="${esc(b.author)}"></label><div class="two"><label>Pages<input name="pages" type="number" value="${b.pages||''}"></label><label>Current page<input name="current" type="number" value="${b.current||0}"></label></div><div class="two"><label>Status<select name="status">${['Want to Read','Currently Reading','Read','DNF','Owned'].map(x=>`<option ${b.status===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Rating<input name="rating" type="number" min="0" max="5" step="0.5" value="${b.rating||''}"></label></div><label>Notes<textarea name="notes" rows="4">${esc(b.notes)}</textarea></label><div class="row"><button type="button" onclick="deleteBook('${b.id}')">Delete</button><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div></form>`);$('#editForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);Object.assign(b,{title:f.get('title'),author:f.get('author'),pages:+f.get('pages')||0,current:+f.get('current')||0,status:f.get('status'),rating:+f.get('rating')||0,notes:f.get('notes')});if(b.status==='Read'&&!b.finishedAt)b.finishedAt=new Date().toISOString();if(b.status!=='Read')b.finishedAt=null;closeModal();save()}}
function deleteBook(bid){if(confirm('Delete this book and its sessions?')){state.books=state.books.filter(b=>b.id!==bid);state.sessions=state.sessions.filter(s=>s.bookId!==bid);closeModal();save()}}
function startSession(){const current=state.books.filter(b=>b.status==='Currently Reading');if(!current.length){alert('Add a book and set it to Currently Reading first.');return}uiModal(`<h2>Log reading session</h2><form class="form" id="sessionForm"><label>Book<select name="book">${current.map(b=>`<option value="${b.id}">${esc(b.title)}</option>`).join('')}</select></label><div class="two"><label>Pages read<input name="pages" type="number" min="0" value="0"></label><label>Minutes<input name="minutes" type="number" min="0" value="20"></label></div><label>Date<input name="date" type="date" value="${today()}"></label><label>Session note<textarea name="note" rows="3"></textarea></label><div class="row"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Log session</button></div></form>`);$('#sessionForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),b=state.books.find(x=>x.id===f.get('book')),p=+f.get('pages')||0;state.sessions.push({id:id(),bookId:b.id,pages:p,minutes:+f.get('minutes')||0,date:f.get('date'),note:f.get('note')});b.current=Math.min(b.pages||Infinity,(b.current||0)+p);if(b.pages&&b.current>=b.pages){b.current=b.pages;b.status='Read';b.finishedAt=new Date().toISOString()}closeModal();save()}}
function setGoals(){uiModal(`<h2>Reading goals</h2><form class="form" id="goalForm"><label>Books this year<input name="year" type="number" min="0" value="${state.goals.year||0}"></label><label>Pages target<input name="pages" type="number" min="0" value="${state.goals.pages||0}"></label><label>Minutes target<input name="minutes" type="number" min="0" value="${state.goals.minutes||0}"></label><div class="row"><button type="button" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div></form>`);$('#goalForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.goals={year:+f.get('year')||0,pages:+f.get('pages')||0,minutes:+f.get('minutes')||0};closeModal();save()}}
function theme(){state.theme=state.theme==='system'?'dark':state.theme==='dark'?'light':'system';save()}
document.addEventListener('click',e=>{const t=e.target.closest('.tab');if(t){view=t.dataset.view;render()}});$('#addBook').onclick=addBook;$('#startSession').onclick=startSession;$('#themeBtn').onclick=theme;$('#studioBtn').onclick=()=>window.openStudio?.();$('#search').oninput=()=>{if(view!=='library')view='library';render()};$('#status').onchange=()=>{view='library';render()};render();