(() => {
  const KEY = 'reading-tracker:power:v2';
  const defaults = {
    shelves: ['Want to Read','Currently Reading','Read','DNF','Owned'], queue: [],
    ratings: {}, reviews: {}, quotes: [], annotations: [], plans: [], goals: [],
    dnfReasons: {}, snapshots: [], customFields: {}, preferences: {pageTarget:20, minuteTarget:20}
  };
  let power = JSON.parse(localStorage.getItem(KEY) || 'null') || defaults;
  power = Object.assign({}, defaults, power);
  const save = () => localStorage.setItem(KEY, JSON.stringify(power));
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const modal = html => { const d=document.querySelector('#modal'); if(!d) return; document.querySelector('#modalBody').innerHTML=html; d.showModal(); };
  const books = () => window.state?.books || [];
  const sessions = () => window.state?.sessions || [];
  const today = () => new Date().toISOString().slice(0,10);
  const book = id => books().find(b=>b.id===id);
  const days = n => Array.from({length:n},(_,i)=>{const d=new Date();d.setDate(d.getDate()-i);return d.toISOString().slice(0,10)});
  function sync(){ save(); if(window.state && window.save) window.save(); }
  function readDays(){ return new Set(sessions().map(s=>s.date)); }
  function streak(){ let set=readDays(), n=0; for(const d of days(366)){ if(set.has(d)) n++; else break; } return n; }
  function longestStreak(){ let set=readDays(), best=0, run=0; for(const d of [...set].sort()){ const prev=new Date(d); prev.setDate(prev.getDate()-1); const p=prev.toISOString().slice(0,10); run=set.has(p)?run+1:1; best=Math.max(best,run); } return best; }
  function monthMap(){ const map={}; sessions().forEach(s=>map[s.date]=(map[s.date]||0)+(Number(s.pages)||0)); return map; }
  function paceFor(id){ const xs=sessions().filter(s=>!id||s.bookId===id); const p=xs.reduce((n,s)=>n+(Number(s.pages)||0),0), m=xs.reduce((n,s)=>n+(Number(s.minutes)||0),0); return m?Math.round(p/m*60):0; }
  function totalPages(){ return sessions().reduce((n,s)=>n+(Number(s.pages)||0),0); }
  function totalMinutes(){ return sessions().reduce((n,s)=>n+(Number(s.minutes)||0),0); }
  function yearRead(y){ return books().filter(b=>b.status==='Read' && String(b.finishedAt||'').slice(0,4)===String(y)).length; }
  function injectButton(){ const host=document.querySelector('.actions'); if(host && !document.querySelector('#powerBtn')){ const b=document.createElement('button'); b.id='powerBtn'; b.textContent='Power Studio'; b.className='primary'; b.onclick=openPower; host.appendChild(b); } }
  function openPower(){
    const y=new Date().getFullYear(), avg=sessions().length?Math.round(totalMinutes()/sessions().length):0;
    modal(`<div class="modal"><div class="row"><div><span class="label">READING INTELLIGENCE</span><h2>Power Studio</h2></div><button onclick="document.querySelector('#modal').close()">Close</button></div>
      <div class="grid" style="margin-top:14px"><div class="card"><span class="label">BOOKS THIS YEAR</span><div class="stat">${yearRead(y)}</div></div><div class="card"><span class="label">PAGES</span><div class="stat">${totalPages()}</div></div><div class="card"><span class="label">READING STREAK</span><div class="stat">${streak()} days</div><small class="muted">Best: ${longestStreak()} days</small></div><div class="card"><span class="label">AVG SESSION</span><div class="stat">${avg} min</div></div><div class="card"><span class="label">PACE</span><div class="stat">${paceFor()} p/h</div></div><div class="card"><span class="label">TBR QUEUE</span><div class="stat">${power.queue.length}</div></div></div>
      <div class="card" style="margin-top:14px"><div class="row"><h3>Reading tools</h3><button onclick="window.rtQueue()">Up next</button></div><div class="list"><button onclick="window.rtBookStudio()">Book details, rating & review</button><button onclick="window.rtQuote()">Save quote / annotation</button><button onclick="window.rtPlan()">Create reading plan</button><button onclick="window.rtAnalytics()">Deep analytics & year comparison</button><button onclick="window.rtBackup()">Backup / restore / encrypted export</button><button onclick="window.rtPreferences()">Reading preferences</button></div></div>
      <div class="card" style="margin-top:14px"><h3>Recent insight</h3><p class="muted">${insight()}</p></div></div>`);
  }
  function insight(){ const map=monthMap(), top=Object.entries(map).sort((a,b)=>b[1]-a[1])[0]; if(!sessions().length) return 'Start a session to build your personal reading profile.'; if(top) return `Your strongest logged day is ${top[0]} with ${top[1]} pages. Your current pace is ${paceFor()} pages/hour.`; return 'Keep logging sessions to unlock richer trends.'; }
  function rtQueue(){ modal(`<div class="modal"><div class="row"><h2>Up next queue</h2><button onclick="window.openPower()">Back</button></div><p class="muted">Keep a deliberate next-five reading queue for your upcoming books.</p><div class="list">${power.queue.map((id,i)=>{const b=book(id);return b?`<div class="row"><span><b>${i+1}.</b> ${esc(b.title)}</span><button onclick="window.rtRemoveQueue('${id}')">Remove</button></div>`:''}).join('')||'<div class="empty">Queue a book from its Book Studio.</div>'}</div></div>`); }
  window.rtRemoveQueue=id=>{power.queue=power.queue.filter(x=>x!==id);save();rtQueue()};
  function rtBookStudio(){ const opts=books().map(b=>`<option value="${b.id}">${esc(b.title)}</option>`).join(''); modal(`<div class="modal"><h2>Book Studio</h2><form class="form" id="bookPower"><label>Book<select name="id" required>${opts}</select></label><div class="two"><label>Rating<input name="rating" type="number" min="0" max="5" step="0.5"></label><label>Format<select name="format"><option>Physical</option><option>eBook</option><option>Audiobook</option><option>PDF</option><option>Other</option></select></label></div><div class="two"><label>Series<input name="series"></label><label>ISBN<input name="isbn"></label></div><label>Review<textarea name="review" rows="5" placeholder="Your private review..."></textarea></label><label>DNF reason<input name="dnf" placeholder="Optional"></label><label><input name="queue" type="checkbox"> Add to Up Next queue</label><div class="row"><button type="button" onclick="window.openPower()">Cancel</button><button class="primary">Save</button></div></form></div>`); document.querySelector('#bookPower').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),id=f.get('id');const b=book(id);if(!b)return;power.ratings[id]=Number(f.get('rating')||0);power.reviews[id]=String(f.get('review')||'');b.format=f.get('format');b.series=f.get('series');b.isbn=f.get('isbn');if(f.get('dnf'))power.dnfReasons[id]=f.get('dnf');if(f.get('queue')&&!power.queue.includes(id)&&power.queue.length<5)power.queue.push(id);sync();openPower();}; }
  function rtQuote(){ const opts=books().map(b=>`<option value="${b.id}">${esc(b.title)}</option>`).join(''); modal(`<div class="modal"><h2>Quote & annotation</h2><form class="form" id="quoteForm"><label>Book<select name="id">${opts}</select></label><label>Quote<textarea name="quote" rows="4" required></textarea></label><label>Page / location<input name="loc"></label><label>Your annotation<textarea name="note" rows="4"></textarea></label><div class="row"><button type="button" onclick="window.openPower()">Cancel</button><button class="primary">Save</button></div></form></div>`); document.querySelector('#quoteForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);power.quotes.push({id:crypto.randomUUID(),bookId:f.get('id'),quote:f.get('quote'),location:f.get('loc'),note:f.get('note'),date:today()});sync();openPower();}; }
  function rtPlan(){ modal(`<div class="modal"><h2>Reading plan</h2><form class="form" id="planForm"><label>Name<input name="name" required placeholder="Finish my current book"></label><div class="two"><label>Pages target<input name="pages" type="number" min="0" value="100"></label><label>Minutes target<input name="minutes" type="number" min="0" value="60"></label></div><label>End date<input name="end" type="date"></label><label>Notes<textarea name="notes" rows="3"></textarea></label><div class="row"><button type="button" onclick="window.openPower()">Cancel</button><button class="primary">Create plan</button></div></form></div>`); document.querySelector('#planForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);power.plans.push({id:crypto.randomUUID(),name:f.get('name'),pages:+f.get('pages')||0,minutes:+f.get('minutes')||0,end:f.get('end'),notes:f.get('notes'),created:today()});sync();openPower();}; }
  function rtAnalytics(){ const now=new Date().getFullYear(), rows=[now,now-1,now-2].map(y=>`<div class="row"><span>${y}</span><b>${yearRead(y)} books · ${sessions().filter(s=>s.date.startsWith(String(y))).reduce((n,s)=>n+(+s.pages||0),0)} pages</b></div>`).join(''); const genres={};books().forEach(b=>{const g=b.genre||'Uncategorized';genres[g]=(genres[g]||0)+1});const top=Object.entries(genres).sort((a,b)=>b[1]-a[1]).slice(0,6); modal(`<div class="modal"><div class="row"><h2>Deep analytics</h2><button onclick="window.openPower()">Back</button></div><div class="card"><h3>Year comparison</h3><div class="list">${rows}</div></div><div class="card" style="margin-top:12px"><h3>Library profile</h3><div class="list">${top.map(x=>`<div class="row"><span>${esc(x[0])}</span><b>${x[1]} books</b></div>`).join('')||'<p class="muted">Add genres to books for richer analysis.</p>'}</div></div><div class="card" style="margin-top:12px"><h3>Session profile</h3><p>${sessions().length} sessions · ${totalMinutes()} minutes · ${totalPages()} pages · ${paceFor()} pages/hour · ${streak()} day current streak.</p></div></div>`); }
  async function rtBackup(){ modal(`<div class="modal"><h2>Data portability</h2><p class="muted">Back up your reading data locally. Encrypted export uses Web Crypto and never stores your password.</p><div class="list"><button onclick="window.rtPlainBackup()">Export complete JSON</button><button onclick="window.rtEncrypted()">Create encrypted backup</button><label>Import JSON <input id="rtImport" type="file" accept="application/json"></label><button onclick="window.rtRestore()">Restore local snapshot</button></div></div>`); const input=document.querySelector('#rtImport'); if(input) input.onchange=async()=>{const f=input.files[0];if(!f)return;try{const x=JSON.parse(await f.text());if(x.state) localStorage.setItem('reading-tracker:v1',JSON.stringify(x.state));if(x.power) localStorage.setItem(KEY,JSON.stringify(x.power));alert('Backup imported. Reload the app to apply it.')}catch{alert('That backup could not be read.')}}; }
  window.rtPlainBackup=()=>{download('reading-tracker-complete.json',JSON.stringify({version:2,exportedAt:new Date().toISOString(),state:window.state,power},null,2),'application/json');};
  window.rtEncrypted=async()=>{const password=prompt('Choose a backup password:');if(!password)return;const enc=new TextEncoder(),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));const base=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt']);const data=enc.encode(JSON.stringify({state:window.state,power}));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,data);const out={v:1,kdf:'PBKDF2-SHA-256',iterations:120000,algorithm:'AES-256-GCM',salt:Array.from(salt),iv:Array.from(iv),data:Array.from(new Uint8Array(cipher))};download('reading-tracker-encrypted.json',JSON.stringify(out),'application/json');};
  window.rtRestore=()=>{ if(!power.snapshots.length){alert('No local snapshots yet.');return;} const s=power.snapshots[power.snapshots.length-1]; if(s.state){localStorage.setItem('reading-tracker:v1',JSON.stringify(s.state));alert('Latest snapshot restored. Reload the app to apply it.');} };
  function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  function rtPreferences(){modal(`<div class="modal"><h2>Reading preferences</h2><form class="form" id="pref2"><label>Daily page target<input name="pages" type="number" min="0" value="${power.preferences.pageTarget}"></label><label>Daily minute target<input name="minutes" type="number" min="0" value="${power.preferences.minuteTarget}"></label><div class="row"><button type="button" onclick="window.openPower()">Cancel</button><button class="primary">Save</button></div></form></div>`);document.querySelector('#pref2').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);power.preferences.pageTarget=+f.get('pages')||0;power.preferences.minuteTarget=+f.get('minutes')||0;save();openPower();};}
  window.openPower=openPower;window.rtBookStudio=rtBookStudio;window.rtQuote=rtQuote;window.rtPlan=rtPlan;window.rtAnalytics=rtAnalytics;window.rtBackup=rtBackup;window.rtPreferences=rtPreferences;
  const originalRender=window.render; window.render=()=>{ try{window.state=state;}catch{} if(originalRender) originalRender(); injectButton(); };
  document.addEventListener('DOMContentLoaded',()=>setTimeout(injectButton,0));
})();
