(() => {
  const KEY='goalpath:v1';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
  const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
  const q=s=>document.querySelector(s), id=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36);
  function pct(g){if(g.target===g.startValue)return g.status==='Completed'?100:0;return Math.max(0,Math.min(100,((+g.current-(+g.startValue||0))/(+g.target-(+g.startValue||0)))*100))}
  function health(){const s=read(),active=(s.goals||[]).filter(g=>g.status!=='Completed'&&g.status!=='Paused'),now=new Date(),stale=active.filter(g=>!(s.checkins||[]).some(c=>c.goalId===g.id&&c.date>=new Date(Date.now()-14*864e5).toISOString().slice(0,10))),overdue=active.filter(g=>g.deadline&&new Date(g.deadline)<now),noMetric=active.filter(g=>!Number.isFinite(+g.target)||+g.target===0);return{active,stale,overdue,noMetric}}
  function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function inject(){const panel=document.createElement('div');panel.className='advanced-strip';panel.innerHTML='<div><b>Goalpath intelligence</b><span>rollups · health · templates · focus planning</span></div><div><button id="advHealth">Portfolio health</button><button id="advTemplate">Starter template</button><button id="advBackup">Quick backup</button></div>';const main=document.querySelector('main');if(main)main.prepend(panel);q('#advHealth').onclick=()=>{const h=health();alert(`Portfolio health\n\nActive goals: ${h.active.length}\nNeed a check-in: ${h.stale.length}\nPast deadline: ${h.overdue.length}\nMissing target: ${h.noMetric.length}`)};q('#advTemplate').onclick=()=>{const s=read(),today=new Date().toISOString().slice(0,10),goal={id:id(),title:'Quarterly personal growth',area:'Personal',type:'OKR',priority:'P1',startValue:0,current:0,target:100,unit:'%',deadline:new Date(Date.now()+90*864e5).toISOString().slice(0,10),parentId:'',status:'On track',why:'A focused outcome for the next 90 days.',notes:'Add measurable success measures or sub-goals.',created:today,updated:today};s.goals=[...(s.goals||[]),goal];write(s);location.reload()};q('#advBackup').onclick=()=>download('goalpath-quick-backup.json',JSON.stringify(read(),null,2),'application/json')}
  const style=document.createElement('style');style.textContent='.advanced-strip{display:flex;justify-content:space-between;gap:14px;align-items:center;margin:0 0 14px;padding:13px 16px;border:1px solid var(--line);border-radius:14px;background:var(--surface)}.advanced-strip span{display:block;color:var(--muted);font-size:11px;margin-top:3px}.advanced-strip button{background:var(--surface2);border:1px solid var(--line);border-radius:9px;padding:7px 9px;margin-left:6px;color:var(--text)}@media(max-width:700px){.advanced-strip{align-items:flex-start;flex-direction:column}.advanced-strip button{margin:6px 6px 0 0}}';document.head.appendChild(style);inject();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
