(() => {
  const KEY='goalpath:v1';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {goals:[],checkins:[],reviews:[],snapshots:[],settings:{}}}};
  const write=s=>{localStorage.setItem(KEY,JSON.stringify(s));return s};
  const $=s=>document.querySelector(s);
  const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
  const date=()=>new Date().toISOString().slice(0,10);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const days=(a,b)=>Math.ceil((new Date(b)-new Date(a))/86400000);
  const pct=(g)=>{const s=Number(g.startValue)||0,t=Number(g.target),c=Number(g.current);if(!Number.isFinite(t)||t===s)return g.status==='Completed'?100:0;return Math.max(0,Math.min(100,((c-s)/(t-s))*100))};
  const activeGoals=s=>(s.goals||[]).filter(g=>!['Completed','Paused','Archived'].includes(g.status));
  function ensure(s){s.goals=s.goals||[];s.checkins=s.checkins||[];s.reviews=s.reviews||[];s.snapshots=s.snapshots||[];s.advanced=s.advanced||{};s.advanced.measures=s.advanced.measures||{};s.advanced.milestones=s.advanced.milestones||{};s.advanced.actions=s.advanced.actions||{};s.advanced.habits=s.advanced.habits||{};s.advanced.risks=s.advanced.risks||{};s.advanced.journal=s.advanced.journal||{};s.advanced.tags=s.advanced.tags||{};return s}
  function goalData(s,gid,key){return (s.advanced[key][gid]||[])}
  function setGoalData(s,gid,key,value){s.advanced[key][gid]=value}
  function health(s){const gs=activeGoals(s),today=date(),cut=new Date(Date.now()-14*864e5).toISOString().slice(0,10);const stale=gs.filter(g=>!(s.checkins||[]).some(c=>c.goalId===g.id&&c.date>=cut));const overdue=gs.filter(g=>g.deadline&&g.deadline<today);const risky=gs.filter(g=>g.status==='At risk'||g.status==='Off track');const missing=gs.filter(g=>!Number.isFinite(Number(g.target))||Number(g.target)===0);return{gs,stale,overdue,risky,missing}}
  function trend(s,gid){const cs=(s.checkins||[]).filter(c=>c.goalId===gid).sort((a,b)=>a.date.localeCompare(b.date));if(cs.length<2)return{delta:0,days:0,rate:0};const first=cs[0],last=cs[cs.length-1],span=Math.max(1,days(first.date,last.date));return{delta:Number(last.value)-Number(first.value),days:span,rate:(Number(last.value)-Number(first.value))/span,latest:last.value,count:cs.length}}
  function projection(s,g){const t=trend(s,g.id),remaining=Number(g.target)-Number(g.current);if(!t.rate||!Number.isFinite(remaining))return null;const needed=remaining/t.rate;return Number.isFinite(needed)&&needed>=0?Math.ceil(needed):null}
  function quality(s,g){let score=0;const m=goalData(s,g.id,'measures'),a=goalData(s,g.id,'actions'),ms=goalData(s,g.id,'milestones');if(g.title?.length>=8)score+=15;if(g.why?.length>=20)score+=15;if(Number.isFinite(Number(g.target)))score+=15;if(g.deadline)score+=15;if(g.startValue!==undefined)score+=10;if(m.length)score+=10;if(a.length)score+=10;if(ms.length)score+=10;return score}
  function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function csv(s){const rows=[['Goal','Area','Status','Priority','Progress','Current','Target','Unit','Deadline','Quality','Trend/day','Projection days']];(s.goals||[]).forEach(g=>{const t=trend(s,g.id),p=projection(s,g);rows.push([g.title,g.area,g.status,g.priority,Math.round(pct(g)),g.current,g.target,g.unit,g.deadline||'',quality(s,g),t.rate||0,p??''])});return rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n')}
  function inject(){
    const main=document.querySelector('main');if(!main||document.querySelector('#goalpathAdvanced'))return;
    const strip=document.createElement('section');strip.id='goalpathAdvanced';strip.className='advanced-strip';strip.innerHTML=`<div><b>Goalpath Studio</b><span>measures · milestones · actions · habits · risks · pace</span></div><div class="adv-actions"><button id="studioOpen">Goal Studio</button><button id="portfolioOpen">Portfolio intelligence</button><button id="advancedCsv">Advanced CSV</button><button id="advancedBackup">Backup</button></div>`;main.prepend(strip);
    const modal=document.createElement('div');modal.id='studioModal';modal.className='modal';modal.setAttribute('aria-hidden','true');modal.innerHTML=`<div class="dialog wide studio-dialog"><div class="dialog-head"><div><p class="eyebrow">GOAL STUDIO</p><h2>Plan and understand a goal</h2></div><button class="close" id="studioClose">×</button></div><div class="studio-toolbar"><label>Goal<select id="studioGoal"></select></label><div id="studioSummary" class="studio-summary"></div></div><div class="studio-tabs"><button class="studio-tab active" data-panel="overview">Overview</button><button class="studio-tab" data-panel="measures">Success measures</button><button class="studio-tab" data-panel="milestones">Milestones</button><button class="studio-tab" data-panel="actions">Action plan</button><button class="studio-tab" data-panel="habits">Habits</button><button class="studio-tab" data-panel="risks">Risks</button><button class="studio-tab" data-panel="journal">Journal</button></div><div id="studioBody"></div></div>`;document.body.appendChild(modal);
    const pmodal=document.createElement('div');pmodal.id='portfolioModal';pmodal.className='modal';pmodal.setAttribute('aria-hidden','true');pmodal.innerHTML=`<div class="dialog wide"><div class="dialog-head"><div><p class="eyebrow">PORTFOLIO INTELLIGENCE</p><h2>See what deserves attention</h2></div><button class="close" id="portfolioClose">×</button></div><div id="portfolioBody"></div></div>`;document.body.appendChild(pmodal);
    wire();refreshGoalButtons();
  }
  function open(id){const el=$('#'+id);if(el){el.classList.add('open');el.setAttribute('aria-hidden','false')}}
  function close(id){const el=$('#'+id);if(el){el.classList.remove('open');el.setAttribute('aria-hidden','true')}}
  function refreshGoalSelect(selected){const s=ensure(read());const sel=$('#studioGoal');if(!sel)return;sel.innerHTML=(s.goals||[]).map(g=>`<option value="${g.id}">${esc(g.title)}</option>`).join('')||'<option value="">Create a goal first</option>';if(selected)sel.value=selected;if(!sel.value&&s.goals[0])sel.value=s.goals[0].id;renderStudio()}
  function summary(s,g){const p=Math.round(pct(g)),t=trend(s,g.id),q=quality(s,g),proj=projection(s,g),m=goalData(s,g.id,'measures').length,ms=goalData(s,g.id,'milestones').length,a=goalData(s,g.id,'actions').filter(x=>!x.done).length;return `<div class="summary-grid"><span><b>${p}%</b><small>progress</small></span><span><b>${q}%</b><small>goal quality</small></span><span><b>${m}</b><small>measures</small></span><span><b>${ms}</b><small>milestones</small></span><span><b>${a}</b><small>open actions</small></span><span><b>${proj===null?'—':proj+'d'}</b><small>projected</small></span></div>`}
  function renderStudio(){const s=ensure(read()),gid=$('#studioGoal')?.value,g=s.goals.find(x=>x.id===gid),body=$('#studioBody');if(!g||!body){if(body)body.innerHTML='<div class="empty">Create a goal first.</div>';return}$('#studioSummary').innerHTML=summary(s,g);const panel=document.querySelector('.studio-tab.active')?.dataset.panel||'overview';body.innerHTML=panelHtml(panel,s,g);bindPanel(panel,g.id)}
  function panelHtml(panel,s,g){
    if(panel==='overview')return `<div class="studio-grid"><article class="card"><h3>Goal quality</h3><div class="quality"><div><i style="width:${quality(s,g)}%"></i></div><strong>${quality(s,g)}%</strong></div><p class="muted">A lightweight completeness score based on clarity, measurement, timing and action planning.</p></article><article class="card"><h3>Pace & projection</h3><p>${trend(s,g.id).count||0} recorded check-ins.</p><strong>${trend(s,g.id).rate?Number(trend(s,g.id).rate.toFixed(2))+' '+esc(g.unit||'units')+'/day':'Not enough trend data yet.'}</strong><p class="muted">${projection(s,g)!==null?'At the current trend, about '+projection(s,g)+' days of movement are needed.':'Add at least two check-ins to estimate pace.'}</p></article><article class="card"><h3>Definition</h3><p><b>Why:</b> ${esc(g.why||'Add why this matters.')}</p><p><b>Notes:</b> ${esc(g.notes||'Add strategy, constraints and definition of done.')}</p></article><article class="card"><h3>Tags & planning</h3><label>Tags<input id="studioTags" value="${esc((g.tags||[]).join(', '))}" placeholder="learning, portfolio, 2026"></label><label>Review cadence<select id="studioCadence"><option>Weekly</option><option>Monthly</option><option>Quarterly</option></select></label><button class="primary" id="saveOverview">Save planning metadata</button></article></div>`;
    if(panel==='measures')return `<div class="panel-head"><div><h3>Success measures / key results</h3><p>Use measurable outcomes instead of only activity. This mirrors modern OKR/KPI goal practice.</p></div><button class="primary" id="addMeasure">+ Measure</button></div><div id="measureList">${goalData(s,g.id,'measures').map((m,i)=>`<div class="studio-row"><div><input data-m="title" data-i="${i}" value="${esc(m.title)}"><small>current ${esc(m.current)} · target ${esc(m.target)} ${esc(m.unit)}</small></div><input data-m="current" data-i="${i}" type="number" step="any" value="${m.current}"><input data-m="target" data-i="${i}" type="number" step="any" value="${m.target}"><input data-m="unit" data-i="${i}" value="${esc(m.unit||'')}" placeholder="unit"><button data-remove-measure="${i}">×</button></div>`).join('')||'<div class="empty">No success measures yet. Add 1–3 meaningful outcomes.</div>'}</div><button class="primary" id="saveMeasures">Save measures</button>`;
    if(panel==='milestones')return `<div class="panel-head"><div><h3>Milestones</h3><p>Turn a large outcome into visible checkpoints.</p></div><button class="primary" id="addMilestone">+ Milestone</button></div><div>${goalData(s,g.id,'milestones').map((m,i)=>`<div class="studio-row"><input data-ms="title" data-i="${i}" value="${esc(m.title)}"><input data-ms="due" data-i="${i}" type="date" value="${m.due||''}"><label class="check"><input data-ms="done" data-i="${i}" type="checkbox" ${m.done?'checked':''}> done</label><button data-remove-milestone="${i}">×</button></div>`).join('')||'<div class="empty">No milestones yet.</div>'}</div><button class="primary" id="saveMilestones">Save milestones</button>`;
    if(panel==='actions')return `<div class="panel-head"><div><h3>Action plan</h3><p>Define concrete next steps that can move the goal forward.</p></div><button class="primary" id="addAction">+ Action</button></div><div>${goalData(s,g.id,'actions').map((a,i)=>`<div class="studio-row"><label class="check"><input data-a="done" data-i="${i}" type="checkbox" ${a.done?'checked':''}></label><input data-a="title" data-i="${i}" value="${esc(a.title)}"><input data-a="due" data-i="${i}" type="date" value="${a.due||''}"><select data-a="repeat" data-i="${i}"><option value="none" ${a.repeat==='none'?'selected':''}>One-time</option><option value="daily" ${a.repeat==='daily'?'selected':''}>Daily</option><option value="weekly" ${a.repeat==='weekly'?'selected':''}>Weekly</option></select><button data-remove-action="${i}">×</button></div>`).join('')||'<div class="empty">No actions yet.</div>'}</div><button class="primary" id="saveActions">Save action plan</button>`;
    if(panel==='habits')return `<div class="panel-head"><div><h3>Supporting habits</h3><p>Habits can support a goal without pretending that every habit directly equals outcome progress.</p></div><button class="primary" id="addHabit">+ Habit</button></div><div>${goalData(s,g.id,'habits').map((h,i)=>`<div class="studio-row"><input data-h="name" data-i="${i}" value="${esc(h.name)}"><select data-h="cadence" data-i="${i}"><option ${h.cadence==='Daily'?'selected':''}>Daily</option><option ${h.cadence==='Weekdays'?'selected':''}>Weekdays</option><option ${h.cadence==='Weekly'?'selected':''}>Weekly</option></select><input data-h="target" data-i="${i}" type="number" min="1" value="${h.target||1}"><span class="muted">${(h.logs||[]).length} logs</span><button data-log-habit="${i}">Log today</button><button data-remove-habit="${i}">×</button></div>`).join('')||'<div class="empty">No supporting habits yet.</div>'}</div><button class="primary" id="saveHabits">Save habits</button>`;
    if(panel==='risks')return `<div class="panel-head"><div><h3>Risks & mitigations</h3><p>Capture obstacles before they become surprises.</p></div><button class="primary" id="addRisk">+ Risk</button></div><div>${goalData(s,g.id,'risks').map((r,i)=>`<div class="studio-row risk-row"><input data-r="risk" data-i="${i}" value="${esc(r.risk)}" placeholder="Risk"><select data-r="severity" data-i="${i}"><option ${r.severity==='Low'?'selected':''}>Low</option><option ${r.severity==='Medium'?'selected':''}>Medium</option><option ${r.severity==='High'?'selected':''}>High</option></select><input data-r="mitigation" data-i="${i}" value="${esc(r.mitigation)}" placeholder="Mitigation"><button data-remove-risk="${i}">×</button></div>`).join('')||'<div class="empty">No risks recorded.</div>'}</div><button class="primary" id="saveRisks">Save risks</button>`;
    return `<div class="panel-head"><div><h3>Goal journal</h3><p>Record context, lessons and small wins without changing the numeric metric.</p></div><button class="primary" id="addJournal">+ Entry</button></div><div>${goalData(s,g.id,'journal').slice().reverse().map((j,i)=>`<article class="journal-entry"><small>${esc(j.date)}</small><p>${esc(j.text)}</p></article>`).join('')||'<div class="empty">No journal entries yet.</div>'}</div>`;
  }
  function bindPanel(panel,gid){const s=ensure(read());const get=(key,fields)=>[...document.querySelectorAll(`[data-${key}]`)].reduce((arr,e)=>{const i=+e.dataset.i;if(!arr[i])arr[i]={};const f=e.dataset[key];arr[i][f]=e.type==='checkbox'?e.checked:e.value;return arr},[]);
    if(panel==='overview'){$('#saveOverview').onclick=()=>{const x=ensure(read()),g=x.goals.find(z=>z.id===gid);g.tags=($('#studioTags').value||'').split(',').map(v=>v.trim()).filter(Boolean);g.reviewCadence=$('#studioCadence').value;g.updated=date();write(x);toast('Goal planning saved');renderStudio()};$('#studioCadence').value=(s.goals.find(g=>g.id===gid).reviewCadence)||'Weekly'}
    if(panel==='measures'){$('#addMeasure').onclick=()=>{const x=ensure(read()),a=goalData(x,gid,'measures');a.push({id:id(),title:'New success measure',current:0,target:100,unit:'%'});setGoalData(x,gid,'measures',a);write(x);renderStudio()};document.querySelectorAll('[data-remove-measure]').forEach(b=>b.onclick=()=>removeItem('measures',gid,+b.dataset.removeMeasure));$('#saveMeasures').onclick=()=>{const x=ensure(read()),a=goalData(x,gid,'measures');document.querySelectorAll('[data-m]').forEach(e=>{const i=+e.dataset.i;a[i][e.dataset.m]=e.type==='number'?Number(e.value):e.value});setGoalData(x,gid,'measures',a);write(x);toast('Measures saved');renderStudio()}}
    if(panel==='milestones'){$('#addMilestone').onclick=()=>{const x=ensure(read()),a=goalData(x,gid,'milestones');a.push({id:id(),title:'New milestone',due:'',done:false});setGoalData(x,gid,'milestones',a);write(x);renderStudio()};document.querySelectorAll('[data-remove-milestone]').forEach(b=>b.onclick=()=>removeItem('milestones',gid,+b.dataset.removeMilestone));$('#saveMilestones').onclick=()=>{const x=ensure(read()),a=goalData(x,gid,'milestones');document.querySelectorAll('[data-ms]').forEach(e=>{const i=+e.dataset.i;a[i][e.dataset.ms]=e.type==='checkbox'?e.checked:e.value});setGoalData(x,gid,'milestones',a);write(x);toast('Milestones saved');renderStudio()}}
    if(panel==='actions'){$('#addAction').onclick=()=>{const x=ensure(read()),a=goalData(x,gid,'actions');a.push({id:id(),title:'Next action',due:'',repeat:'none',done:false});setGoalData(x,gid,'actions',a);write(x);renderStudio()};document.querySelectorAll('[data-remove-action]').forEach(b=>b.onclick=()=>removeItem('actions',gid,+b.dataset.removeAction));$('#saveActions').onclick=()=>{const x=ensure(read()),a=goalData(x,gid,'actions');document.querySelectorAll('[data-a]').forEach(e=>{const i=+e.dataset.i;a[i][e.dataset.a]=e.type==='checkbox'?e.checked:e.value});setGoalData(x,gid,'actions',a);write(x);toast('Action plan saved');renderStudio()}}
    if(panel==='habits'){$('#addHabit').onclick=()=>{const x=ensure(read()),a=goalData(x,gid,'habits');a.push({id:id(),name:'Supporting habit',cadence:'Daily',target:1,logs:[]});setGoalData(x,gid,'habits',a);write(x);renderStudio()};document.querySelectorAll('[data-remove-habit]').forEach(b=>b.onclick=()=>removeItem('habits',gid,+b.dataset.removeHabit));document.querySelectorAll('[data-log-habit]').forEach(b=>b.onclick=()=>{const x=ensure(read()),a=goalData(x,gid,'habits'),h=a[+b.dataset.logHabit];h.logs=h.logs||[];if(!h.logs.includes(date()))h.logs.push(date());setGoalData(x,gid,'habits',a);write(x);toast('Habit logged');renderStudio()});$('#saveHabits').onclick=()=>{const x=ensure(read()),a=goalData(x,gid,'habits');document.querySelectorAll('[data-h]').forEach(e=>{const i=+e.dataset.i;a[i][e.dataset.h]=e.type==='number'?Number(e.value):e.value});setGoalData(x,gid,'habits',a);write(x);toast('Habits saved');renderStudio()}}
    if(panel==='risks'){$('#addRisk').onclick=()=>{const x=ensure(read()),a=goalData(x,gid,'risks');a.push({id:id(),risk:'New risk',severity:'Medium',mitigation:''});setGoalData(x,gid,'risks',a);write(x);renderStudio()};document.querySelectorAll('[data-remove-risk]').forEach(b=>b.onclick=()=>removeItem('risks',gid,+b.dataset.removeRisk));$('#saveRisks').onclick=()=>{const x=ensure(read()),a=goalData(x,gid,'risks');document.querySelectorAll('[data-r]').forEach(e=>{const i=+e.dataset.i;a[i][e.dataset.r]=e.value});setGoalData(x,gid,'risks',a);write(x);toast('Risks saved');renderStudio()}}
    if(panel==='journal'){$('#addJournal').onclick=()=>{const text=prompt('Journal entry');if(!text?.trim())return;const x=ensure(read()),a=goalData(x,gid,'journal');a.push({id:id(),date:date(),text:text.trim()});setGoalData(x,gid,'journal',a);write(x);renderStudio()}}
  }
  function removeItem(key,gid,i){const s=ensure(read()),a=goalData(s,gid,key);a.splice(i,1);setGoalData(s,gid,key,a);write(s);renderStudio()}
  function portfolio(){const s=ensure(read()),h=health(s),gs=h.gs;const area={};gs.forEach(g=>area[g.area]=(area[g.area]||[]).concat(g));const rows=gs.map(g=>{const p=Math.round(pct(g)),t=trend(s,g.id),proj=projection(s,g),q=quality(s,g),d=g.deadline?days(date(),g.deadline):null;let signal='Healthy';if(h.overdue.includes(g)||h.risky.includes(g))signal='Needs attention';else if(h.stale.includes(g)||q<60)signal='Watch';return`<div class="portfolio-row"><div><strong>${esc(g.title)}</strong><small>${esc(g.area)} · ${esc(g.priority)} · ${signal}</small></div><div><b>${p}%</b><small>progress</small></div><div><b>${q}%</b><small>quality</small></div><div><b>${proj===null?'—':proj+'d'}</b><small>projection</small></div><div><b>${d===null?'—':d<0?Math.abs(d)+'d late':d+'d'}</b><small>deadline</small></div></div>`}).join('');$('#portfolioBody').innerHTML=`<div class="portfolio-metrics"><article class="card"><b>${gs.length}</b><span>active goals</span></article><article class="card"><b>${h.risky.length}</b><span>at risk/off track</span></article><article class="card"><b>${h.stale.length}</b><span>stale</span></article><article class="card"><b>${h.overdue.length}</b><span>overdue</span></article></div><article class="card"><h3>Attention queue</h3>${rows||'<div class="empty">No active goals yet.</div>'}</article><article class="card"><h3>Area balance</h3>${Object.entries(area).map(([a,v])=>`<div class="balance-row"><span>${esc(a)}</span><div><i style="width:${Math.round(v.length/Math.max(1,gs.length)*100)}%"></i></div><b>${v.length}</b></div>`).join('')||'<div class="empty">Create goals across the areas that matter to you.</div>'}</article>`}
  function refreshGoalButtons(){document.querySelectorAll('.goal-card').forEach(card=>{if(card.querySelector('[data-goal-studio]'))return;const b=card.querySelector('.goal-actions');const title=card.querySelector('h3')?.textContent;const s=ensure(read()),g=s.goals.find(x=>x.title===title);if(b&&g){const x=document.createElement('button');x.textContent='Studio';x.dataset.goalStudio=g.id;b.appendChild(x)}})}
  function wire(){
    $('#studioOpen').onclick=()=>{refreshGoalSelect();open('studioModal')};$('#portfolioOpen').onclick=()=>{portfolio();open('portfolioModal')};$('#advancedCsv').onclick=()=>download('goalpath-advanced.csv',csv(ensure(read())),'text/csv');$('#advancedBackup').onclick=()=>download('goalpath-advanced-backup.json',JSON.stringify(ensure(read()),null,2),'application/json');$('#studioClose').onclick=()=>close('studioModal');$('#portfolioClose').onclick=()=>close('portfolioModal');$('#studioGoal').onchange=renderStudio;
    document.addEventListener('click',e=>{const tab=e.target.closest('.studio-tab');if(tab){document.querySelectorAll('.studio-tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');renderStudio()}const b=e.target.closest('[data-goal-studio]');if(b){refreshGoalSelect(b.dataset.goalStudio);open('studioModal')}});
    const obs=new MutationObserver(refreshGoalButtons);obs.observe(document.querySelector('main'),{childList:true,subtree:true});
    document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();refreshGoalSelect();open('studioModal')}});
  }
  const style=document.createElement('style');style.textContent=`
  .advanced-strip{display:flex;justify-content:space-between;gap:14px;align-items:center;margin:0 0 14px;padding:14px 16px;border:1px solid var(--line);border-radius:14px;background:var(--surface)}.advanced-strip span{display:block;color:var(--muted);font-size:11px;margin-top:3px}.adv-actions button{background:var(--surface2);border:1px solid var(--line);border-radius:9px;padding:7px 10px;margin-left:6px;color:var(--text)}
  .studio-toolbar{display:flex;gap:14px;align-items:end;margin-bottom:14px}.studio-toolbar label{min-width:280px}.studio-summary{flex:1}.summary-grid{display:grid;grid-template-columns:repeat(6,1fr);gap:8px}.summary-grid span,.portfolio-metrics article{padding:10px;border:1px solid var(--line);border-radius:10px;background:var(--surface2);text-align:center}.summary-grid b,.summary-grid small{display:block}.summary-grid small{color:var(--muted);font-size:10px}.studio-tabs{display:flex;gap:6px;overflow:auto;border-bottom:1px solid var(--line);margin-bottom:14px}.studio-tab{white-space:nowrap;border:0;background:transparent;padding:9px 11px;color:var(--muted)}.studio-tab.active{color:var(--text);border-bottom:2px solid currentColor}.studio-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.studio-grid .card{margin:0}.quality{display:flex;align-items:center;gap:10px}.quality>div{height:10px;flex:1;background:var(--surface2);border-radius:99px;overflow:hidden}.quality i{display:block;height:100%;background:var(--accent,#5b5bd6)}.panel-head{display:flex;justify-content:space-between;align-items:start;gap:12px;margin-bottom:12px}.studio-row{display:grid;grid-template-columns:minmax(150px,2fr) 110px 110px 110px auto;gap:8px;align-items:center;padding:8px 0;border-bottom:1px solid var(--line)}.studio-row input,.studio-row select{min-width:0}.studio-row small{display:block;color:var(--muted);margin-top:3px}.check{display:flex;align-items:center;gap:5px}.risk-row{grid-template-columns:1.2fr 100px 1.5fr auto}.journal-entry{padding:12px;border:1px solid var(--line);border-radius:10px;margin-bottom:8px;background:var(--surface2)}.journal-entry small{color:var(--muted)}.portfolio-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:12px}.portfolio-metrics b,.portfolio-metrics span{display:block}.portfolio-row{display:grid;grid-template-columns:2fr repeat(4,100px);gap:10px;align-items:center;padding:10px 0;border-bottom:1px solid var(--line)}.portfolio-row small{display:block;color:var(--muted);font-size:10px}.balance-row{display:flex;gap:8px;align-items:center;margin:8px 0}.balance-row span{width:120px}.balance-row div{flex:1;height:8px;background:var(--surface2);border-radius:99px;overflow:hidden}.balance-row i{display:block;height:100%;background:var(--accent,#5b5bd6)}
  @media(max-width:850px){.advanced-strip,.studio-toolbar,.panel-head{align-items:stretch;flex-direction:column}.adv-actions button{margin:5px 5px 0 0}.summary-grid{grid-template-columns:repeat(3,1fr)}.studio-grid{grid-template-columns:1fr}.studio-row,.risk-row{grid-template-columns:1fr 1fr}.portfolio-metrics{grid-template-columns:repeat(2,1fr)}.portfolio-row{grid-template-columns:1fr 1fr}.studio-toolbar label{min-width:0}}
  `;document.head.appendChild(style);
  inject();
  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
