const STORAGE_KEY='focus.tasks.v3';
const PREF_KEY='focus.prefs.v3';
const BACKUP_VERSION=3;
const DEFAULT_CATEGORIES=['Personal','Work','Study'];
const PRIORITIES=['low','medium','high'];
const RECURRENCES=['','daily','weekdays','weekly','monthly','yearly','custom'];
let tasks=loadTasks(),prefs=loadPrefs(),currentView='all',editingId=null,selected=new Set(),undoState=null,undoTimer=null,calendarCursor=new Date();
const $=id=>document.getElementById(id);
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const pad=n=>String(n).padStart(2,'0');
const localDate=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const today=()=>localDate(new Date());
const dateObj=v=>new Date(`${v}T12:00:00`);
const shiftDate=(v,n)=>{const d=dateObj(v);d.setDate(d.getDate()+n);return localDate(d)};
const isDate=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(dateObj(v).getTime());
const isTime=v=>typeof v==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(v);
const escapeHTML=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const linkify=s=>escapeHTML(s).replace(/(https?:\/\/[^\s<]+)/g,'<a href="$1" target="_blank" rel="noopener noreferrer">$1</a>');
const formatDate=v=>isDate(v)?dateObj(v).toLocaleDateString(undefined,{month:'short',day:'numeric'}):'';
const priorityRank=p=>({high:0,medium:1,low:2}[p]??1);
const normalizeSubtask=s=>s&&typeof s==='object'&&typeof s.title==='string'&&s.title.trim()?{id:String(s.id||uid()),title:s.title.trim().slice(0,120),completed:Boolean(s.completed)}:null;
function normalizeTask(t){
 if(!t||typeof t!=='object'||!t.id||typeof t.title!=='string'||!t.title.trim())return null;
 const now=Date.now(),r=t.recurrence&&typeof t.recurrence==='object'?t.recurrence:{type:typeof t.recurrence==='string'?t.recurrence:'',every:t.repeatEvery||1,unit:t.repeatUnit||'days'};
 return {id:String(t.id),title:t.title.trim().slice(0,160),notes:typeof t.notes==='string'?t.notes.slice(0,4000):'',priority:PRIORITIES.includes(t.priority)?t.priority:'medium',due:isDate(t.due)?t.due:'',dueTime:isTime(t.dueTime)?t.dueTime:'',category:typeof t.category==='string'?t.category.trim().slice(0,40):'',tags:Array.isArray(t.tags)?[...new Set(t.tags.map(String).map(x=>x.trim().toLowerCase()).filter(Boolean).slice(0,15))]:[],subtasks:Array.isArray(t.subtasks)?t.subtasks.map(normalizeSubtask).filter(Boolean).slice(0,50):[],completed:Boolean(t.completed),archived:Boolean(t.archived),recurrence:RECURRENCES.includes(r.type)?r.type:'',repeatEvery:Math.max(1,Math.min(99,Number(r.every)||1)),repeatUnit:['days','weeks','months','years'].includes(r.unit)?r.unit:'days',reminder:isTime(t.reminder)?t.reminder:'',createdAt:Number.isFinite(Number(t.createdAt))?Number(t.createdAt):now,updatedAt:Number.isFinite(Number(t.updatedAt))?Number(t.updatedAt):now,completedAt:Number.isFinite(Number(t.completedAt))?Number(t.completedAt):null};
}
function loadTasks(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY)||localStorage.getItem('focus.tasks.v2')||localStorage.getItem('focus.tasks.v1')||'[]');return Array.isArray(raw)?raw.map(normalizeTask).filter(Boolean):[]}catch{return[]}}
function loadPrefs(){try{const raw=JSON.parse(localStorage.getItem(PREF_KEY)||localStorage.getItem('focus.prefs.v2')||localStorage.getItem('focus.prefs.v1')||'{}');const cats=Array.isArray(raw.categories)?raw.categories.map(String).map(x=>x.trim()).filter(Boolean):[];return{categories:[...new Set([...DEFAULT_CATEGORIES,...cats])].slice(0,50),theme:['light','dark','system'].includes(raw.theme)?raw.theme:'system',compact:Boolean(raw.compact),notifications:raw.notifications!==false,sort:['due','priority','created','title'].includes(raw.sort)?raw.sort:'due'}}catch{return{categories:DEFAULT_CATEGORIES,theme:'system',compact:false,notifications:true,sort:'due'}}}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(tasks));localStorage.setItem(PREF_KEY,JSON.stringify(prefs));return true}catch{toast('Could not save changes in this browser');return false}}
function isOverdue(t){if(t.completed||t.archived||!t.due)return false;const d=t.due<today();return d||t.due===today()&&t.dueTime&&t.dueTime<`${pad(new Date().getHours())}:${pad(new Date().getMinutes())}`}
function isDueToday(t){return!t.completed&&!t.archived&&t.due===today()}
function isUpcoming(t){return!t.completed&&!t.archived&&t.due>today()}
function addMonths(v,n){const d=dateObj(v),day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+n);const last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();d.setDate(Math.min(day,last));return localDate(d)}
function nextRecurringDate(t){if(!t.due||!t.recurrence)return'';if(t.recurrence==='daily')return shiftDate(t.due,1);if(t.recurrence==='weekdays'){let n=shiftDate(t.due,1);while([0,6].includes(dateObj(n).getDay()))n=shiftDate(n,1);return n}if(t.recurrence==='weekly')return shiftDate(t.due,7);if(t.recurrence==='monthly')return addMonths(t.due,1);if(t.recurrence==='yearly')return addMonths(t.due,12);if(t.recurrence==='custom'){const n=Number(t.repeatEvery)||1;return t.repeatUnit==='weeks'?shiftDate(t.due,n*7):t.repeatUnit==='months'?addMonths(t.due,n):t.repeatUnit==='years'?addMonths(t.due,n*12):shiftDate(t.due,n)}return''}
function completeTask(id,checked=true){const t=tasks.find(x=>x.id===id);if(!t)return;if(checked&&t.recurrence&&t.due)tasks.unshift({...structuredClone(t),id:uid(),due:nextRecurringDate(t),completed:false,completedAt:null,createdAt:Date.now(),updatedAt:Date.now()});t.completed=checked;t.completedAt=checked?Date.now():null;t.updatedAt=Date.now();save();render();toast(checked?'Task completed':'Task reopened')}
function parseQuickAdd(text){let title=text,due='',dueTime='';const low=text.toLowerCase();if(/\btomorrow\b/.test(low)){due=shiftDate(today(),1);title=title.replace(/\btomorrow\b/i,'')}else if(/\btoday\b/.test(low)){due=today();title=title.replace(/\btoday\b/i,'')}else if(/\bnext week\b/.test(low)){due=shiftDate(today(),7);title=title.replace(/\bnext week\b/i,'')}else{const m=low.match(/\b20\d{2}-\d{2}-\d{2}\b/);if(m&&isDate(m[0])){due=m[0];title=title.replace(m[0],'')}}const tm=title.match(/\b(?:at\s*)?([01]?\d|2[0-3]):([0-5]\d)\b/);if(tm){dueTime=`${pad(Number(tm[1]))}:${tm[2]}`;title=title.replace(tm[0],'')}else{const am=title.match(/\b(?:at\s*)?(1[0-2]|[1-9])\s*(am|pm)\b/i);if(am){let h=Number(am[1]);if(am[2].toLowerCase()==='pm'&&h<12)h+=12;if(am[2].toLowerCase()==='am'&&h===12)h=0;dueTime=`${pad(h)}:00`;title=title.replace(am[0],'')}}let priority='';const pm=title.match(/(?:^|\s)!p([1-3])\b/i);if(pm){priority=['high','medium','low'][Number(pm[1])-1];title=title.replace(pm[0],' ')}const tags=[...title.matchAll(/#([a-z0-9_-]+)/gi)].map(m=>m[1].toLowerCase());title=title.replace(/#[a-z0-9_-]+/gi,'').replace(/\s{2,}/g,' ').trim();return{title:title||'Untitled task',due,dueTime,tags,priority}}
function addTask(e){e.preventDefault();const raw=$('taskTitle').value.trim();if(!raw)return;const p=parseQuickAdd(raw),t={id:uid(),title:p.title.slice(0,160),notes:'',priority:p.priority||$('taskPriority').value,due:isDate($('taskDue').value)?$('taskDue').value:p.due,dueTime:isTime($('taskDueTime').value)?$('taskDueTime').value:p.dueTime,category:$('taskCategory').value,tags:p.tags,subtasks:[],completed:false,archived:false,recurrence:'',repeatEvery:1,repeatUnit:'days',reminder:'',createdAt:Date.now(),updatedAt:Date.now(),completedAt:null};tasks.unshift(t);if(save()){$('taskForm').reset();$('taskPriority').value='medium';render();toast('Task added');$('taskTitle').focus()}}
function getVisibleTasks(){const q=$('search').value.trim().toLowerCase(),status=$('statusFilter').value,priority=$('priorityFilter').value,category=$('categoryFilter').value,tag=$('tagFilter').value,sort=$('sortBy').value;let list=tasks.filter(t=>{if(currentView==='archived')return t.archived;if(t.archived)return false;if(currentView==='today'&&!isDueToday(t))return false;if(currentView==='upcoming'&&!isUpcoming(t))return false;if(currentView==='overdue'&&!isOverdue(t))return false;if(currentView==='completed'&&!t.completed)return false;if(currentView.startsWith('cat:')&&t.category!==currentView.slice(4))return false;if(status==='active'&&t.completed)return false;if(status==='completed'&&!t.completed)return false;if(priority!=='all'&&t.priority!==priority)return false;if(category!=='all'&&t.category!==category)return false;if(tag!=='all'&&!t.tags.includes(tag))return false;const hay=[t.title,t.notes,t.category,t.tags.join(' '),t.subtasks.map(s=>s.title).join(' ')].join(' ').toLowerCase();return!q||hay.includes(q)});list.sort((a,b)=>{if(sort==='priority')return priorityRank(a.priority)-priorityRank(b.priority)||b.createdAt-a.createdAt;if(sort==='created')return b.createdAt-a.createdAt;if(sort==='title')return a.title.localeCompare(b.title);if(!a.due&&!b.due)return b.createdAt-a.createdAt;if(!a.due)return 1;if(!b.due)return-1;return a.due.localeCompare(b.due)||(a.dueTime||'').localeCompare(b.dueTime||'')||priorityRank(a.priority)-priorityRank(b.priority)});return list}
function taskHTML(t){const done=t.subtasks.filter(s=>s.completed).length,total=t.subtasks.length;const meta=[t.due?`<span class="${isOverdue(t)?'overdue':''}">${isOverdue(t)?'Overdue · ':''}${formatDate(t.due)}${t.dueTime?' · '+escapeHTML(t.dueTime):''}</span>`:'',t.category?`<span class="pill">${escapeHTML(t.category)}</span>`:'',...t.tags.slice(0,4).map(x=>`<span class="pill tag">#${escapeHTML(x)}</span>`),t.recurrence?`<span class="pill repeat">↻ ${escapeHTML(t.recurrence==='custom'?`every ${t.repeatEvery} ${t.repeatUnit}`:t.recurrence)}</span>`:'',total?`<span class="pill">✓ ${done}/${total} steps</span>`:'',t.reminder?`<span class="pill">◷ ${escapeHTML(t.reminder)}</span>`:'',`<span class="pill priority-${t.priority}">${t.priority}</span>`].filter(Boolean).join('');return`<article class="task ${t.completed?'completed':''} ${isOverdue(t)?'task-overdue':''}" data-id="${escapeHTML(t.id)}"><input class="check select-check" type="checkbox" aria-label="Select ${escapeHTML(t.title)}" ${selected.has(t.id)?'checked':''}><input class="check complete-check" type="checkbox" aria-label="${t.completed?'Reopen':'Complete'} ${escapeHTML(t.title)}" ${t.completed?'checked':''}><div class="task-main"><button class="task-open" type="button" data-action="edit">${escapeHTML(t.title)}</button><div class="meta">${meta}</div>${t.notes?`<div class="task-notes">${linkify(t.notes)}</div>`:''}</div><div class="task-actions"><button data-action="edit" title="Edit task">Edit</button><button data-action="duplicate" title="Duplicate task">Copy</button><button data-action="archive" title="${t.archived?'Restore':'Archive'} task">${t.archived?'Restore':'Archive'}</button><button data-action="delete" title="Delete task">Delete</button></div></article>`}
function emptyHTML(){const map={completed:['Nothing completed yet','Completed tasks will appear here.'],today:['Nothing due today','Add a task or schedule one for today.'],upcoming:['No upcoming tasks','Schedule a future date to see it here.'],overdue:['No overdue tasks','You are all caught up.'],archived:['Archive is empty','Archived tasks will appear here.'],all:['No tasks found','Add a task above to get started.']};const x=map[currentView]||map.all;return`<div class="empty"><div class="empty-icon">✓</div><strong>${x[0]}</strong><span>${x[1]}</span></div>`}
function renderNav(){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));const title={all:'Inbox',today:'Today',upcoming:'Upcoming',overdue:'Overdue',calendar:'Calendar',completed:'Completed',archived:'Archived'}[currentView]||(currentView.startsWith('cat:')?currentView.slice(4):'Inbox');$('viewTitle').textContent=title;$('dateLabel').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});}
function renderCategories(){const nav=prefs.categories.map(c=>`<button class="category-item ${currentView==='cat:'+c?'active':''}" data-category="${escapeHTML(c)}"><span>${escapeHTML(c)}</span><span>${tasks.filter(t=>t.category===c&&!t.completed&&!t.archived).length}</span></button>`).join('');$('categoryNav').innerHTML=nav;const opts='<option value="">No category</option>'+prefs.categories.map(c=>`<option value="${escapeHTML(c)}">${escapeHTML(c)}</option>`).join('');$('taskCategory').innerHTML=opts;$('editCategory').innerHTML=opts}
function renderFilters(){const cats='<option value="all">All categories</option>'+prefs.categories.map(c=>`<option value="${escapeHTML(c)}">${escapeHTML(c)}</option>`).join('');const tags=[...new Set(tasks.flatMap(t=>t.tags))].sort();$('categoryFilter').innerHTML=cats;$('tagFilter').innerHTML='<option value="all">All tags</option>'+tags.map(t=>`<option value="${escapeHTML(t)}">#${escapeHTML(t)}</option>`).join('');$('sortBy').value=prefs.sort}
function renderCalendar(){const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),start=first.getDay(),cells=[];for(let i=0;i<start;i++)cells.push('<div class="calendar-cell muted-cell"></div>');for(let day=1;day<=days;day++){const d=`${y}-${pad(m+1)}-${pad(day)}`,items=tasks.filter(t=>!t.archived&&t.due===d).sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority));cells.push(`<div class="calendar-cell ${d===today()?'is-today':''}"><div class="calendar-date"><strong>${day}</strong><span>${items.length||''}</span></div>${items.slice(0,4).map(t=>`<button class="calendar-task ${t.completed?'done':''}" data-calendar-id="${escapeHTML(t.id)}"><span class="dot priority-${t.priority}"></span>${escapeHTML(t.title)}</button>`).join('')}${items.length>4?`<small>+${items.length-4} more</small>`:''}</div>`)}return`<div class="calendar-head"><button class="btn ghost" id="prevMonth">←</button><strong>${first.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</strong><button class="btn ghost" id="nextMonth">→</button><button class="btn ghost" id="calendarToday">Today</button></div><div class="calendar-weekdays">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-month">${cells.join('')}</div>`}
function render(){renderNav();renderCategories();renderFilters();$('taskList').innerHTML=currentView==='calendar'?renderCalendar():(getVisibleTasks().length?getVisibleTasks().map(taskHTML).join(''):emptyHTML());const active=tasks.filter(t=>!t.completed&&!t.archived).length,done=tasks.filter(t=>t.completed&&!t.archived).length,total=tasks.filter(t=>!t.archived).length;Object.assign($('allCount'),{textContent:active});$('todayCount').textContent=tasks.filter(isDueToday).length;$('overdueCount').textContent=tasks.filter(isOverdue).length;$('completedCount').textContent=done;$('archivedCount').textContent=tasks.filter(t=>t.archived).length;$('progressText').textContent=total?`${done} of ${total} completed`:'0 tasks';$('progressBar').style.width=total?`${done/total*100}%`:'0%';$('selectedText').textContent=`${selected.size} selected`;$('bulkbar').classList.toggle('hidden',!selected.size);$('clearCompleted').classList.toggle('hidden',done===0);const dark=prefs.theme==='dark'||prefs.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches;document.body.classList.toggle('dark',dark);document.body.classList.toggle('compact',prefs.compact);$('themeBtn').textContent=prefs.theme==='system'?'◐':dark?'☀':'☾';$('installBtn').classList.toggle('hidden',!deferredInstallPrompt)}
function openEdit(id){const t=tasks.find(x=>x.id===id);if(!t)return;editingId=id;$('editTitle').value=t.title;$('editNotes').value=t.notes;$('editPriority').value=t.priority;$('editDue').value=t.due;$('editDueTime').value=t.dueTime;$('editCategory').value=t.category;$('editTags').value=t.tags.join(', ');$('editRecurrence').value=t.recurrence;$('editRepeatEvery').value=t.repeatEvery;$('editRepeatUnit').value=t.repeatUnit;$('editReminder').value=t.reminder;renderSubtasks(t);$('editDialog').showModal();$('editTitle').focus()}
function renderSubtasks(t){$('subtaskList').innerHTML=t.subtasks.map(s=>`<label class="subtask-row"><input type="checkbox" data-subtask="${escapeHTML(s.id)}" ${s.completed?'checked':''}><span class="${s.completed?'done':''}">${escapeHTML(s.title)}</span><button type="button" data-remove-subtask="${escapeHTML(s.id)}">×</button></label>`).join('')||'<p class="muted">No steps yet.</p>'}
function saveEdited(e){e.preventDefault();const t=tasks.find(x=>x.id===editingId);if(!t)return;const title=$('editTitle').value.trim();if(!title)return;t.title=title.slice(0,160);t.notes=$('editNotes').value.slice(0,4000);t.priority=$('editPriority').value;t.due=isDate($('editDue').value)?$('editDue').value:'';t.dueTime=isTime($('editDueTime').value)?$('editDueTime').value:'';t.category=$('editCategory').value;t.tags=[...new Set($('editTags').value.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean))].slice(0,15);t.recurrence=$('editRecurrence').value;t.repeatEvery=Math.max(1,Math.min(99,Number($('editRepeatEvery').value)||1));t.repeatUnit=$('editRepeatUnit').value;t.reminder=isTime($('editReminder').value)?$('editReminder').value:'';t.updatedAt=Date.now();if(save()){$('editDialog').close();render();toast('Task updated')}}
function deleteTask(id){const i=tasks.findIndex(t=>t.id===id);if(i<0||!confirm(`Delete “${tasks[i].title}”?`))return;undoState={tasks:structuredClone(tasks),message:`“${tasks[i].title}” deleted`};tasks.splice(i,1);selected.delete(id);save();render();showUndo()}
function archiveTask(id){const t=tasks.find(x=>x.id===id);if(!t)return;t.archived=!t.archived;t.updatedAt=Date.now();save();render();toast(t.archived?'Task archived':'Task restored')}
function duplicateTask(id){const t=tasks.find(x=>x.id===id);if(!t)return;tasks.unshift({...structuredClone(t),id:uid(),title:`${t.title} (copy)`,completed:false,archived:false,completedAt:null,createdAt:Date.now(),updatedAt:Date.now()});save();render();toast('Task duplicated')}
function showUndo(){const el=$('undo');el.classList.add('show');el.innerHTML=`<span>${escapeHTML(undoState.message)}</span><button type="button" id="undoBtn">Undo</button>`;$('undoBtn').onclick=()=>{tasks=undoState.tasks;undoState=null;save();render();el.classList.remove('show');toast('Restored')};clearTimeout(undoTimer);undoTimer=setTimeout(()=>{undoState=null;el.classList.remove('show')},5000)}
function deleteSelected(){if(!selected.size||!confirm(`Delete ${selected.size} selected tasks?`))return;undoState={tasks:structuredClone(tasks),message:`${selected.size} tasks deleted`};tasks=tasks.filter(t=>!selected.has(t.id));selected.clear();save();render();showUndo()}
function completeSelected(){tasks.forEach(t=>{if(selected.has(t.id)&&!t.completed){t.completed=true;t.completedAt=Date.now();t.updatedAt=Date.now()}});selected.clear();save();render();toast('Selected tasks completed')}
function clearCompleted(){if(!confirm('Remove all completed tasks? This can be undone for a few seconds.'))return;undoState={tasks:structuredClone(tasks),message:'Completed tasks removed'};tasks=tasks.filter(t=>!t.completed);save();render();showUndo()}
function addSubtask(){if(!editingId)return;const t=tasks.find(x=>x.id===editingId),input=$('newSubtask'),title=input.value.trim();if(!title)return;t.subtasks.push({id:uid(),title:title.slice(0,120),completed:false});input.value='';t.updatedAt=Date.now();save();renderSubtasks(t)}
function handleSubtaskClick(e){const t=tasks.find(x=>x.id===editingId);if(!t)return;const remove=e.target.closest('[data-remove-subtask]');if(remove){t.subtasks=t.subtasks.filter(s=>s.id!==remove.dataset.removeSubtask);save();renderSubtasks(t);return}if(e.target.matches('[data-subtask]')){const s=t.subtasks.find(x=>x.id===e.target.dataset.subtask);if(s)s.completed=e.target.checked;t.updatedAt=Date.now();save();renderSubtasks(t)}}
function manageCategory(){const name=prompt('New category name');if(!name)return;const n=name.trim().slice(0,40);if(!n)return;if(prefs.categories.some(c=>c.toLowerCase()===n.toLowerCase()))return toast('Category already exists');prefs.categories.push(n);save();render();toast('Category created')}
function manageCategories(){const list=prefs.categories.map((c,i)=>`${i+1}. ${c}`).join('\n');const choice=prompt(`Category manager\n\n${list}\n\nType a category name to rename it, or leave blank to cancel.`);if(!choice)return;const old=prefs.categories.find(c=>c.toLowerCase()===choice.trim().toLowerCase());if(!old)return toast('Category not found');const next=prompt(`Rename “${old}” to:`);if(!next)return;const n=next.trim().slice(0,40);if(!n||prefs.categories.some(c=>c.toLowerCase()===n.toLowerCase()))return toast('Category already exists');prefs.categories=prefs.categories.map(c=>c===old?n:c);tasks.forEach(t=>{if(t.category===old)t.category=n});save();render();toast('Category renamed')}
function deleteCategory(){const name=prompt(`Delete which category?\n\n${prefs.categories.join('\n')}`);if(!name)return;const c=prefs.categories.find(x=>x.toLowerCase()===name.trim().toLowerCase());if(!c)return toast('Category not found');if(!confirm(`Delete category “${c}”? Tasks will become uncategorized.`))return;prefs.categories=prefs.categories.filter(x=>x!==c);tasks.forEach(t=>{if(t.category===c)t.category=''});save();render();toast('Category deleted')}
function exportData(){const data={version:BACKUP_VERSION,app:'Focus',exportedAt:new Date().toISOString(),tasks,categories:prefs.categories,preferences:{theme:prefs.theme,compact:prefs.compact,notifications:prefs.notifications,sort:prefs.sort}};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`focus-backup-${today()}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),0);toast('Backup exported')}
function importData(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.tasks))throw Error();const incoming=d.tasks.map(normalizeTask).filter(Boolean);const replace=confirm(`Import ${incoming.length} valid tasks. OK = replace current tasks; Cancel = merge.`);if(replace)tasks=incoming;else{const ids=new Set(tasks.map(t=>t.id));tasks=[...incoming.filter(t=>!ids.has(t.id)),...tasks]}if(Array.isArray(d.categories))prefs.categories=[...new Set([...DEFAULT_CATEGORIES,...d.categories.map(String).map(x=>x.trim()).filter(Boolean)])].slice(0,50);save();selected.clear();render();toast('Backup imported')}catch{toast('Invalid backup file')}};r.readAsText(file)}
async function requestNotifications(){if(!('Notification'in window))return toast('Notifications are not supported here');const p=await Notification.requestPermission();prefs.notifications=p==='granted';save();render();toast(p==='granted'?'Reminders enabled':'Reminders disabled')}
function checkReminders(){if(!prefs.notifications||!('Notification'in window)||Notification.permission!=='granted')return;const now=new Date(),tm=`${pad(now.getHours())}:${pad(now.getMinutes())}`;tasks.filter(t=>!t.completed&&!t.archived&&t.due===today()&&t.reminder===tm).forEach(t=>{const k=`focus.reminded.${t.id}.${today()}.${tm}`;if(!sessionStorage.getItem(k)){new Notification('Focus reminder',{body:t.title});sessionStorage.setItem(k,'1')}})}
function installPWA(){if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();deferredInstallPrompt.userChoice.finally(()=>{deferredInstallPrompt=null;render()})}
function openSettings(){const active=tasks.filter(t=>!t.completed&&!t.archived).length,done=tasks.filter(t=>t.completed&&!t.archived).length,over=tasks.filter(isOverdue).length;const dark=prefs.theme==='dark';$('settingsTheme').value=prefs.theme;$('compactToggle').checked=prefs.compact;$('notificationToggle').checked=prefs.notifications;$('settingsStats').textContent=`${active} active · ${over} overdue · ${done} completed · ${tasks.length} total`;$('settingsDialog').showModal()}
function saveSettings(){prefs.theme=$('settingsTheme').value;prefs.compact=$('compactToggle').checked;prefs.notifications=$('notificationToggle').checked;save();$('settingsDialog').close();render();toast('Settings saved')}
let deferredInstallPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;render()});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;render();toast('Focus installed')});
window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY||e.key===PREF_KEY){tasks=loadTasks();prefs=loadPrefs();render()}});
window.matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(prefs.theme==='system')render()});
document.addEventListener('click',e=>{const nav=e.target.closest('.nav-item');if(nav){currentView=nav.dataset.view;selected.clear();render();return}const cat=e.target.closest('[data-category]');if(cat){currentView='cat:'+cat.dataset.category;selected.clear();render();return}if(e.target.id==='prevMonth'){calendarCursor.setMonth(calendarCursor.getMonth()-1);render();return}if(e.target.id==='nextMonth'){calendarCursor.setMonth(calendarCursor.getMonth()+1);render();return}if(e.target.id==='calendarToday'){calendarCursor=new Date();render();return}const action=e.target.closest('[data-action]');if(action){const a=action.closest('.task');if(a){const id=a.dataset.id;if(action.dataset.action==='edit')openEdit(id);if(action.dataset.action==='delete')deleteTask(id);if(action.dataset.action==='duplicate')duplicateTask(id);if(action.dataset.action==='archive')archiveTask(id)}return}const cal=e.target.closest('[data-calendar-id]');if(cal)openEdit(cal.dataset.calendarId)});
$('taskForm').addEventListener('submit',addTask);$('editForm').addEventListener('submit',saveEdited);$('addSubtaskBtn').addEventListener('click',addSubtask);$('newSubtask').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addSubtask()}});$('subtaskList').addEventListener('click',handleSubtaskClick);$('subtaskList').addEventListener('change',handleSubtaskClick);
$('taskList').addEventListener('change',e=>{const article=e.target.closest('.task');if(!article)return;const id=article.dataset.id;if(e.target.classList.contains('complete-check'))completeTask(id,e.target.checked);if(e.target.classList.contains('select-check')){e.target.checked?selected.add(id):selected.delete(id);render()}});
$('deleteSelected').addEventListener('click',deleteSelected);$('completeSelected').addEventListener('click',completeSelected);$('clearSelection').addEventListener('click',()=>{selected.clear();render()});$('clearCompleted').addEventListener('click',clearCompleted);$('exportBtn').addEventListener('click',exportData);$('importInput').addEventListener('change',e=>{if(e.target.files[0])importData(e.target.files[0]);e.target.value=''});$('themeBtn').addEventListener('click',()=>{prefs.theme=prefs.theme==='system'?'dark':prefs.theme==='dark'?'light':'system';save();render()});$('installBtn').addEventListener('click',installPWA);$('notifyBtn').addEventListener('click',requestNotifications);$('settingsBtn').addEventListener('click',openSettings);$('saveSettings').addEventListener('click',saveSettings);$('addCategoryBtn').addEventListener('click',manageCategory);$('manageCategoriesBtn').addEventListener('click',manageCategories);$('deleteCategoryBtn').addEventListener('click',deleteCategory);
['search','statusFilter','priorityFilter','categoryFilter','tagFilter','sortBy'].forEach(id=>$(id).addEventListener('input',()=>{if(id==='sortBy'){prefs.sort=$(id).value;save()}render()}));$('editDialog').addEventListener('close',()=>editingId=null);
document.addEventListener('keydown',e=>{const typing=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('search').focus()}if(!typing&&e.key.toLowerCase()==='n'){e.preventDefault();$('taskTitle').focus()}if(!typing&&e.key.toLowerCase()==='c'){e.preventDefault();manageCategory()}if(e.key==='Escape'&&!$('editDialog').open&&!$('settingsDialog').open){selected.clear();render()}});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));setInterval(checkReminders,30000);setTimeout(checkReminders,1000);render();