/* Movie Watchlist Power Suite v1
   Local-first advanced tools: smart lists, calendar analytics, taste profile,
   watchlist aging, decision engine, group picker, duplicate audit, imports,
   exports, encrypted backups, snapshots, data health, and year review cards. */
(()=>{
'use strict';
const KEY='movie-watchlist:v4', PKEY='movie-watchlist:power:v1';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{"movies":[],"lists":[],"settings":{}}')}catch{return {movies:[],lists:[],settings:{}}}};
const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
const movies=()=>read().movies||[];
const watched=()=>movies().filter(m=>m.status==='Watched');
const queue=()=>movies().filter(m=>m.status==='Watchlist');
const genres=m=>String(m.genres||'').split(',').map(x=>x.trim()).filter(Boolean);
const tags=m=>String(m.tags||'').split(',').map(x=>x.trim()).filter(Boolean);
const csvCell=v=>`"${String(v??'').replace(/"/g,'""')}"`;
const download=(name,text,type='application/json')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
const modal=(title,body)=>{let d=$('#powerModal');if(!d){d=document.createElement('dialog');d.id='powerModal';d.innerHTML='<div id="powerBody"></div>';document.body.append(d)}$('#powerBody').innerHTML=`<div class="powerHead"><div><span class="eyebrow">POWER SUITE</span><h2>${esc(title)}</h2></div><button onclick="document.getElementById('powerModal').close()">Close</button></div>${body}`;d.showModal()};
const countBy=(arr,keyFn)=>arr.reduce((o,x)=>{const k=keyFn(x);if(k)o[k]=(o[k]||0)+1;return o},{});
function openPower(){modal('Advanced tools',`<div class="powerGrid">
<button onclick="MoviePower.smartLists()"><b>Smart Lists</b><span>Auto-filter collections by rules</span></button>
<button onclick="MoviePower.calendar()"><b>Viewing Calendar</b><span>Heatmap, streaks and monthly rhythm</span></button>
<button onclick="MoviePower.taste()"><b>Taste Profile</b><span>Genres, decades, directors, languages and ratings</span></button>
<button onclick="MoviePower.decision()"><b>Decision Engine</b><span>Explainable weighted picks from your queue</span></button>
<button onclick="MoviePower.group()"><b>Group Picker</b><span>Find films everyone can agree on</span></button>
<button onclick="MoviePower.audit()"><b>Library Audit</b><span>Duplicates, missing data and watchlist aging</span></button>
<button onclick="MoviePower.data()"><b>Data Center</b><span>JSON/CSV export, import and encrypted backup</span></button>
<button onclick="MoviePower.year()"><b>Year Review</b><span>Deep annual summary and shareable text</span></button>
</div>`)}
function smartLists(){const ms=movies();const body=`<div class="powerNote">Smart lists are calculated locally from your current library. Nothing is uploaded.</div><div class="ruleRow"><select id="slField"><option value="status">Status</option><option value="rating">Rating</option><option value="year">Release year</option><option value="runtime">Runtime</option><option value="priority">Priority</option><option value="favorite">Favorite</option><option value="rewatch">Rewatch</option><option value="owned">Owned</option><option value="genre">Genre contains</option><option value="tag">Tag contains</option><option value="service">Service contains</option></select><select id="slOp"><option value="eq">is</option><option value="gte">≥</option><option value="lte">≤</option><option value="contains">contains</option></select><input id="slVal" placeholder="Value"><button class="primary" onclick="MoviePower.runSmartList()">Run</button></div><div id="slResult" class="powerResults"><div class="empty">Choose a rule to preview matching films.</div></div>`;modal('Smart Lists',body);}
function runSmartList(){const f=$('#slField').value,o=$('#slOp').value,v=$('#slVal').value.trim().toLowerCase();const ms=movies().filter(m=>{let x=f==='genre'?genres(m).join(' '):f==='tag'?tags(m).join(' '):m[f];if(f==='favorite'||f==='rewatch'||f==='owned')x=!!x;const n=Number(x),nv=Number(v);if(o==='gte')return Number.isFinite(n)&&n>=nv;if(o==='lte')return Number.isFinite(n)&&n<=nv;if(o==='contains')return String(x??'').toLowerCase().includes(v);return String(x??'').toLowerCase()===v});$('#slResult').innerHTML=`<div class="powerResultHead"><b>${ms.length} matches</b><button onclick="MoviePower.saveSmartList()">Save as list</button></div>${ms.slice(0,100).map(m=>`<div class="powerItem"><span>${esc(m.title)}</span><small>${esc(m.year||'')} ${m.rating?`· ★ ${m.rating}`:''}</small></div>`).join('')||'<div class="empty">No matches.</div>'}`;window._smartResult=ms;}
function saveSmartList(){const name=prompt('List name');if(!name||!window._smartResult)return;const s=read();s.lists=s.lists||[];s.lists.push({id:crypto.randomUUID(),name,private:true,movieIds:window._smartResult.map(m=>m.id)});write(s);modal('Smart Lists',`<div class="successBox">Saved “${esc(name)}” with ${window._smartResult.length} films.</div><button class="primary" onclick="location.reload()">Refresh library</button>`)}
function calendar(){const ws=watched(),days=countBy(ws,m=>m.watchedAt||'');const year=new Date().getFullYear();let best=0,cur=0,last='';Object.keys(days).sort().forEach(d=>{const dt=new Date(d),prev=last?new Date(last):null;if(prev&&dt-prev===86400000)cur++;else cur=1;best=Math.max(best,cur);last=d});const months=Array.from({length:12},(_,i)=>{const k=`${year}-${String(i+1).padStart(2,'0')}`;return[k,ws.filter(m=>(m.watchedAt||'').startsWith(k)).length]});modal('Viewing Calendar',`<div class="statGrid"><div class="card"><span class="label">VIEWINGS</span><div class="stat">${ws.length}</div></div><div class="card"><span class="label">ACTIVE DAYS</span><div class="stat">${Object.keys(days).length}</div></div><div class="card"><span class="label">LONGEST STREAK</span><div class="stat">${best} days</div></div><div class="card"><span class="label">THIS MONTH</span><div class="stat">${months[new Date().getMonth()][1]}</div></div></div><div class="powerCalendar">${months.map(([k,n])=>`<div><span>${k.slice(5)}</span><i class="level${Math.min(4,Math.ceil(n/2))}"></i><b>${n}</b></div>`).join('')}</div><h3>Daily activity</h3><div class="heatmap">${Object.entries(days).sort((a,b)=>a[0].localeCompare(b[0])).slice(-140).map(([d,n])=>`<span title="${esc(d)} · ${n} film${n===1?'':'s'}" class="level${Math.min(4,n)}"></span>`).join('')||'<div class="empty">Log viewing dates to build your calendar.</div>'}</div>`)}
function taste(){const ws=watched(),gs=countBy(ws,m=>genres(m)),ds=countBy(ws,m=>String(m.director||'').trim()),ls=countBy(ws,m=>String(m.language||'').trim()),dec=countBy(ws,m=>m.year?`${Math.floor(m.year/10)*10}s`:'Unknown'),ratings=countBy(ws,m=>m.rating?String(m.rating):'Unrated');const top=o=>Object.entries(o).filter(([k])=>k).sort((a,b)=>b[1]-a[1]).slice(0,8);modal('Taste Profile',`<div class="grid"><div class="card"><h3>Genres</h3>${top(gs).map(([k,n])=>`<div class="powerLine"><span>${esc(k)}</span><b>${n}</b></div>`).join('')||'<div class="empty">No genre data.</div>'}</div><div class="card"><h3>Directors</h3>${top(ds).map(([k,n])=>`<div class="powerLine"><span>${esc(k)}</span><b>${n}</b></div>`).join('')||'<div class="empty">No director data.</div>'}</div><div class="card"><h3>Decades</h3>${top(dec).map(([k,n])=>`<div class="powerLine"><span>${esc(k)}</span><b>${n}</b></div>`).join('')}</div><div class="card"><h3>Languages</h3>${top(ls).map(([k,n])=>`<div class="powerLine"><span>${esc(k)}</span><b>${n}</b></div>`).join('')||'<div class="empty">No language data.</div>'}</div></div><div class="card"><h3>Rating distribution</h3><div class="ratingScale">${Object.entries(ratings).sort((a,b)=>Number(a[0])-Number(b[0])).map(([k,n])=>`<span><b>${esc(k)}</b><i style="width:${Math.min(100,n/ws.length*100)}%"></i><small>${n}</small></span>`).join('')}</div></div>`)}
function decision(){const q=queue();const mood=prompt('Optional mood (e.g. cozy, intense, funny). Leave blank for any.','');if(mood===null)return;const m=mood.trim().toLowerCase();const pool=q.filter(x=>!m||`${x.mood} ${x.tags} ${x.genres}`.toLowerCase().includes(m));const scored=pool.map(x=>{let score=(+x.priority||3)*20+(+x.rating||0)*8;score+=Math.max(0,5-(new Date()-new Date(x.addedAt))/86400000/60);if(m&&`${x.mood} ${x.tags} ${x.genres}`.toLowerCase().includes(m))score+=40;return{x,score}}).sort((a,b)=>b.score-a.score).slice(0,8);modal('Decision Engine',`<div class="powerNote">Picks are explainable and based only on your own queue: priority, rating, freshness and optional mood match.</div>${scored.map((r,i)=>`<div class="decisionCard"><b>#${i+1} ${esc(r.x.title)}</b><span>${esc(r.x.year||'')} · priority ${r.x.priority||3}${r.x.rating?` · ★ ${r.x.rating}`:''}</span><small>${m&&`${r.x.mood} ${r.x.tags} ${r.x.genres}`.toLowerCase().includes(m)?'Mood match · ':''}${r.x.rewatch?'Rewatch candidate · ':''}weighted score ${Math.round(r.score)}</small></div>`).join('')||'<div class="empty">Add films to your watchlist first.</div>'}`)}
function group(){const q=queue();if(!q.length){modal('Group Picker','<div class="empty">Add watchlist films first.</div>');return}const count=Math.min(8,Number(prompt('How many options should the group choose from?','5'))||5);const shuffled=q.slice().sort(()=>Math.random()-.5).slice(0,count);modal('Group Picker',`<div class="powerNote">A neutral shortlist for a shared decision. Each person can vote privately on this screen.</div><div id="votes">${shuffled.map(m=>`<label class="vote"><input type="checkbox" value="${esc(m.id)}"><span><b>${esc(m.title)}</b><small>${esc(m.year||'')} · ${esc(m.genres||'No genre')}</small></span></label>`).join('')}</div><button class="primary" onclick="MoviePower.tally()">Tally shortlist</button>`)}
function tally(){const ids=[...document.querySelectorAll('#votes input:checked')].map(x=>x.value);const ms=movies().filter(m=>ids.includes(m.id));modal('Group Result',`<h3>${ms.length} film${ms.length===1?'':'s'} selected</h3>${ms.map(m=>`<div class="decisionCard"><b>${esc(m.title)}</b><span>${esc(m.year||'')} · ${esc(m.genres||'')}</span></div>`).join('')||'<div class="empty">No selections yet.</div>'}`)}
function audit(){const ms=movies(),dups=countBy(ms,m=>(m.title||'').trim().toLowerCase()),dup=[...Object.entries(dups)].filter(([,n])=>n>1);const missing=ms.filter(m=>!m.year||!m.genres||!m.runtime||!m.poster);const aged=queue().filter(m=>Date.now()-new Date(m.addedAt||Date.now())>90*86400000);modal('Library Audit',`<div class="statGrid"><div class="card"><span class="label">TOTAL</span><div class="stat">${ms.length}</div></div><div class="card"><span class="label">DUPLICATE TITLES</span><div class="stat">${dup.length}</div></div><div class="card"><span class="label">INCOMPLETE</span><div class="stat">${missing.length}</div></div><div class="card"><span class="label">90+ DAY QUEUE</span><div class="stat">${aged.length}</div></div></div><div class="grid"><div class="card"><h3>Possible duplicates</h3>${dup.map(([k,n])=>`<div class="powerLine"><span>${esc(k)}</span><b>${n}</b></div>`).join('')||'<div class="successBox">No duplicate titles detected.</div>'}</div><div class="card"><h3>Metadata health</h3><p>${missing.length} film${missing.length===1?'':'s'} are missing at least one of year, genre, runtime or poster.</p>${missing.slice(0,20).map(m=>`<div class="powerItem"><span>${esc(m.title)}</span><small>${[!m.year&&'year',!m.genres&&'genre',!m.runtime&&'runtime',!m.poster&&'poster'].filter(Boolean).join(', ')}</small></div>`).join('')}</div></div>`)}
function data(){modal('Data Center',`<div class="dataActions"><button onclick="MoviePower.exportJSON()">Export full JSON</button><button onclick="MoviePower.exportCSV()">Export CSV</button><button onclick="MoviePower.importJSON()">Import JSON</button><button onclick="MoviePower.encryptedBackup()">Encrypted backup</button><button onclick="MoviePower.restoreEncrypted()">Restore encrypted backup</button><button onclick="MoviePower.snapshot()">Create snapshot</button><button onclick="MoviePower.restoreSnapshot()">Restore latest snapshot</button></div><div class="powerNote">Exports contain your local library only. Encrypted backups use AES-GCM in your browser and never send the password or backup to a server.</div>`)}
function exportJSON(){download(`movie-watchlist-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(read(),null,2))}
function exportCSV(){const ms=movies(),cols=['title','year','releaseDate','runtime','director','cast','genres','country','language','tags','status','rating','review','notes','favorite','rewatch','rewatchCount','priority','mood','watchedAt','watchDates','owned','format','service','where','poster','backdrop','trailer','source','spoiler','liked'];download(`movie-watchlist-${new Date().toISOString().slice(0,10)}.csv`,[cols.join(','),...ms.map(m=>cols.map(k=>csvCell(Array.isArray(m[k])?m[k].join('|'):m[k])).join(','))].join('\n'),'text/csv')}
function importJSON(){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=()=>{const f=i.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const incoming=JSON.parse(r.result);if(!Array.isArray(incoming.movies))throw Error('Invalid library');if(!confirm(`Replace your current library with ${incoming.movies.length} films?`))return;write({...incoming,movies:incoming.movies});location.reload()}catch(e){alert('Import failed: '+e.message)}};r.readAsText(f)};i.click()}
async function encryptedBackup(){const pass=prompt('Create a backup password (do not forget it):');if(!pass)return;const enc=new TextEncoder(),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',enc.encode(pass)),'AES-GCM',false,['encrypt','decrypt']);const data=enc.encode(JSON.stringify(read()));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,data);const payload={version:1,algorithm:'AES-GCM',salt:[...salt],iv:[...iv],data:[...new Uint8Array(cipher)]};download(`movie-watchlist-encrypted-${Date.now()}.mwbackup`,JSON.stringify(payload), 'application/json')}
async function restoreEncrypted(){const pass=prompt('Enter the backup password:');if(!pass)return;const i=document.createElement('input');i.type='file';i.accept='.mwbackup,.json';i.onchange=()=>{const f=i.files[0];if(!f)return;const r=new FileReader();r.onload=async()=>{try{const p=JSON.parse(r.result),enc=new TextEncoder(),key=await crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',enc.encode(pass)),'AES-GCM',false,['decrypt']);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(p.iv)},key,new Uint8Array(p.data));const s=JSON.parse(new TextDecoder().decode(plain));if(!Array.isArray(s.movies))throw Error('Invalid backup');if(confirm(`Restore ${s.movies.length} films?`)){write(s);location.reload()}}catch(e){alert('Restore failed. Check the password and backup file.')}};r.readAsText(f)};i.click()}
function snapshot(){const s=JSON.parse(localStorage.getItem(PKEY)||'{"snapshots":[]}');s.snapshots=s.snapshots||[];s.snapshots.unshift({at:new Date().toISOString(),data:read()});s.snapshots=s.snapshots.slice(0,5);localStorage.setItem(PKEY,JSON.stringify(s));modal('Snapshot created','<div class="successBox">A local restore point was saved. Up to five recent snapshots are retained.</div>')}
function restoreSnapshot(){const s=JSON.parse(localStorage.getItem(PKEY)||'{"snapshots":[]}');const x=s.snapshots?.[0];if(!x){modal('Snapshot','<div class="empty">No snapshot exists yet.</div>');return}if(confirm(`Restore snapshot from ${x.at}?`)){write(x.data);location.reload()}}
function year(){const y=Number(prompt('Year to review',String(new Date().getFullYear())));if(!y)return;const ms=watched().filter(m=>String(m.watchedAt||'').startsWith(String(y))),rated=ms.filter(m=>m.rating),avg=rated.length?(rated.reduce((a,m)=>a+m.rating,0)/rated.length).toFixed(2):'—',mins=ms.reduce((a,m)=>a+(+m.runtime||0),0),topG=Object.entries(countBy(ms,m=>genres(m)[0])).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—',best=ms.slice().sort((a,b)=>(b.rating||0)-(a.rating||0))[0];const text=`${y} Movie Year Review\n\n${ms.length} films watched\n${Math.floor(mins/60)}h ${mins%60}m watch time\nAverage rating: ${avg}/5\nTop genre: ${topG}\nTop rated: ${best?.title||'—'}\nRewatches: ${ms.filter(m=>m.rewatch).length}`;modal(`${y} Year Review`,`<div class="yearHero"><div class="stat">${ms.length}</div><span>films watched</span></div><div class="metaGrid"><span><b>Watch time</b>${Math.floor(mins/60)}h ${mins%60}m</span><span><b>Average rating</b>${avg}/5</span><span><b>Top genre</b>${esc(topG)}</span><span><b>Top rated</b>${esc(best?.title||'—')}</span><span><b>Rewatches</b>${ms.filter(m=>m.rewatch).length}</span><span><b>Favorites</b>${ms.filter(m=>m.favorite).length}</span></div><button class="primary" onclick="MoviePower.copyYear(${JSON.stringify(text)})">Copy text summary</button>`);window._yearText=text}
async function copyYear(t){await navigator.clipboard?.writeText(t);alert('Year review copied.')}
window.MoviePower={open:openPower,smartLists,runSmartList,saveSmartList,calendar,taste,decision,group,tally,audit,data,exportJSON,exportCSV,importJSON,encryptedBackup,restoreEncrypted,snapshot,restoreSnapshot,year,copyYear};
function boot(){const studio=$('#studio');if(studio){studio.textContent='Power tools';studio.onclick=openPower}const tabs=$('.tabs');if(tabs&&!tabs.querySelector('[data-view="power"]')){const b=document.createElement('button');b.type='button';b.dataset.view='power';b.textContent='Power';tabs.append(b);b.onclick=openPower}if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
