import db from "./db";
import { randomUUID } from "node:crypto";
import { afterStudy, afterQuiz } from "./learning-events";

const tables = { subjects:"subjects", topics:"topics", notes:"notes", flashcards:"flashcards", flashcard_reviews:"flashcard_reviews", quizzes:"quizzes", study_sessions:"study_sessions", quiz_attempts:"quiz_attempts", study_goals:"study_goals" } as const;
export type Resource = keyof typeof tables;
export function listResource(userId:string,r:Resource){const t=tables[r];return r==="topics"?db.prepare("SELECT t.* FROM topics t JOIN subjects s ON s.id=t.subject_id WHERE s.user_id=? ORDER BY t.position").all(userId):db.prepare(`SELECT * FROM ${t} WHERE user_id=? ORDER BY rowid DESC`).all(userId)}
export function getResource(userId:string,r:Resource,id:string){if(r==="topics")return db.prepare("SELECT t.* FROM topics t JOIN subjects s ON s.id=t.subject_id WHERE t.id=? AND s.user_id=?").get(id,userId);return db.prepare(`SELECT * FROM ${tables[r]} WHERE id=? AND user_id=?`).get(id,userId)}
function ownsSubject(userId:string,id:string){return !!db.prepare("SELECT 1 FROM subjects WHERE id=? AND user_id=?").get(id,userId)}
function ownsCard(userId:string,id:string){return !!db.prepare("SELECT 1 FROM flashcards WHERE id=? AND user_id=?").get(id,userId)}
export function createResource(userId:string,r:Resource,b:any){const id=String(b.id||randomUUID()),now=new Date().toISOString();if(r==="subjects")db.prepare("INSERT INTO subjects(id,user_id,name,description,created_at) VALUES(?,?,?,?,?)").run(id,userId,String(b.name||""),String(b.description||""),now);else if(r==="topics"){if(!ownsSubject(userId,b.subject_id))throw Error("Invalid subject");db.prepare("INSERT INTO topics(id,subject_id,name,completed,position) VALUES(?,?,?,?,?)").run(id,b.subject_id,String(b.name||""),b.completed?1:0,Number(b.position||0))}else if(r==="notes")db.prepare("INSERT INTO notes(id,user_id,subject_id,topic_id,title,content,tags_json,pinned,archived,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(id,userId,b.subject_id||null,b.topic_id||null,String(b.title||""),String(b.content||""),JSON.stringify(b.tags||[]),b.pinned?1:0,b.archived?1:0,now,now);else if(r==="flashcards")db.prepare("INSERT INTO flashcards(id,user_id,subject_id,topic_id,front,back,interval,ease,due_at,reviews,state,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run(id,userId,b.subject_id||null,b.topic_id||null,String(b.front||""),String(b.back||""),1,2.5,b.due_at||now,0,String(b.state||"new"),now);else if(r==="flashcard_reviews"){if(!ownsCard(userId,String(b.flashcard_id)))throw Error("Invalid flashcard");db.prepare("INSERT INTO flashcard_reviews(id,user_id,flashcard_id,rating,interval,state,reviewed_at) VALUES(?,?,?,?,?,?,?)").run(id,userId,b.flashcard_id,String(b.rating||"good"),Number(b.interval||1),String(b.state||"learning"),now)}else if(r==="quizzes")db.prepare("INSERT INTO quizzes(id,user_id,subject_id,topic_id,title,difficulty,questions_json,created_at) VALUES(?,?,?,?,?,?,?,?)").run(id,userId,b.subject_id||null,b.topic_id||null,String(b.title||"Untitled quiz"),String(b.difficulty||"medium"),JSON.stringify(b.questions||[]),now);else if(r==="study_goals")db.prepare("INSERT INTO study_goals(id,user_id,minutes,updated_at) VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET minutes=excluded.minutes,updated_at=excluded.updated_at").run(id,userId,Math.max(1,Number(b.minutes||25)),now);else if(r==="study_sessions")db.prepare("INSERT INTO study_sessions(id,user_id,subject_id,topic_id,activity,minutes,started_at,ended_at) VALUES(?,?,?,?,?,?,?,?)").run(id,userId,b.subject_id||null,b.topic_id||null,String(b.activity||"study"),Math.max(0,Number(b.minutes||0)),String(b.started_at||now),b.ended_at||now);else db.prepare("INSERT INTO quiz_attempts(id,user_id,quiz_id,title,score,total,percent,completed_at) VALUES(?,?,?,?,?,?,?,?)").run(id,userId,b.quiz_id||null,String(b.title||"Quiz"),Number(b.score||0),Number(b.total||0),Number(b.percent||0),now);if(r==="study_sessions")afterStudy(userId);if(r==="quiz_attempts")afterQuiz(userId);return id}
export function updateResource(userId:string,r:Resource,id:string,b:any){if(r==="topics")return db.prepare("UPDATE topics SET name=?,completed=?,position=? WHERE id=? AND subject_id IN (SELECT id FROM subjects WHERE user_id=?)").run(String(b.name||""),b.completed?1:0,Number(b.position||0),id,userId);if(r==="subjects")return db.prepare("UPDATE subjects SET name=?,description=? WHERE id=? AND user_id=?").run(String(b.name||""),String(b.description||""),id,userId);if(r==="notes")return db.prepare("UPDATE notes SET title=?,content=?,tags_json=?,pinned=?,archived=?,subject_id=?,topic_id=?,updated_at=? WHERE id=? AND user_id=?").run(String(b.title||""),String(b.content||""),JSON.stringify(b.tags||[]),b.pinned?1:0,b.archived?1:0,b.subject_id||null,b.topic_id||null,new Date().toISOString(),id,userId);if(r==="flashcards")return db.prepare("UPDATE flashcards SET front=?,back=?,subject_id=?,topic_id=?,due_at=?,interval=?,ease=?,reviews=?,state=? WHERE id=? AND user_id=?").run(String(b.front||""),String(b.back||""),b.subject_id||null,b.topic_id||null,b.due_at||new Date().toISOString(),Number(b.interval||1),Number(b.ease||2.5),Number(b.reviews||0),String(b.state||"new"),id,userId);if(r==="quizzes")return db.prepare("UPDATE quizzes SET title=?,difficulty=?,questions_json=?,subject_id=?,topic_id=? WHERE id=? AND user_id=?").run(String(b.title||"Untitled quiz"),String(b.difficulty||"medium"),JSON.stringify(b.questions||[]),b.subject_id||null,b.topic_id||null,id,userId);if(r==="quiz_attempts")return db.prepare("UPDATE quiz_attempts SET title=?,score=?,total=?,percent=? WHERE id=? AND user_id=?").run(String(b.title||"Quiz"),Number(b.score||0),Number(b.total||0),Number(b.percent||0),id,userId);if(r==="study_goals")return db.prepare("UPDATE study_goals SET minutes=?,updated_at=? WHERE id=? AND user_id=?").run(Math.max(1,Number(b.minutes||25)),new Date().toISOString(),id,userId);return db.prepare(`UPDATE ${tables[r]} SET minutes=?,ended_at=? WHERE id=? AND user_id=?`).run(Math.max(0,Number(b.minutes||0)),b.ended_at||new Date().toISOString(),id,userId)}
export function deleteResource(userId:string,r:Resource,id:string){if(r==="topics")return db.prepare("DELETE FROM topics WHERE id=? AND subject_id IN (SELECT id FROM subjects WHERE user_id=?)").run(id,userId);return db.prepare(`DELETE FROM ${tables[r]} WHERE id=? AND user_id=?`).run(id,userId)}
