import db from "./db";
type Achievement={code:string;title:string;body:string;xp:number;target:number;metric:"minutes"|"quizzes"|"cards"|"streak"};
export const catalog:Achievement[]=[
 {code:"first-session",title:"First Study Session",body:"Complete your first focused study session.",xp:25,target:1,metric:"minutes"},
 {code:"first-quiz",title:"Quiz Starter",body:"Complete your first quiz.",xp:25,target:1,metric:"quizzes"},
 {code:"first-card",title:"Card Starter",body:"Review your first flashcard.",xp:20,target:1,metric:"cards"},
 {code:"study-60",title:"Focused Hour",body:"Study for 60 total minutes.",xp:50,target:60,metric:"minutes"},
 {code:"study-300",title:"Deep Practice",body:"Study for 5 total hours.",xp:100,target:300,metric:"minutes"},
 {code:"study-1000",title:"Study Veteran",body:"Study for 1,000 total minutes.",xp:250,target:1000,metric:"minutes"},
 {code:"quiz-5",title:"Quiz Builder",body:"Complete 5 quiz attempts.",xp:75,target:5,metric:"quizzes"},
 {code:"quiz-25",title:"Quiz Regular",body:"Complete 25 quiz attempts.",xp:150,target:25,metric:"quizzes"},
 {code:"cards-25",title:"Recall Builder",body:"Review 25 flashcards.",xp:75,target:25,metric:"cards"},
 {code:"cards-100",title:"Recall Pro",body:"Review 100 flashcards.",xp:150,target:100,metric:"cards"},
 {code:"seven-day-streak",title:"Seven Day Streak",body:"Study on seven consecutive days.",xp:100,target:7,metric:"streak"},
 {code:"fourteen-day-streak",title:"Two Week Streak",body:"Study on fourteen consecutive days.",xp:175,target:14,metric:"streak"},
 {code:"thirty-day-streak",title:"Month of Momentum",body:"Study on 30 consecutive days.",xp:300,target:30,metric:"streak"}
];
function progress(userId:string){const sessions=db.prepare("SELECT minutes,started_at FROM study_sessions WHERE user_id=?").all(userId) as any[];const quizzes=db.prepare("SELECT 1 FROM quiz_attempts WHERE user_id=?").all(userId).length;const cards=db.prepare("SELECT 1 FROM flashcard_reviews WHERE user_id=?").all(userId).length;const days=new Set(sessions.map(x=>new Date(x.started_at).toISOString().slice(0,10)));let streak=0,d=new Date();while(days.has(d.toISOString().slice(0,10))){streak++;d.setDate(d.getDate()-1)}return {minutes:sessions.reduce((n,x)=>n+Number(x.minutes||0),0),quizzes,cards,streak};}
function grantXp(userId:string,xp:number,source:string){const now=new Date().toISOString();db.prepare("INSERT INTO xp_transactions(id,user_id,amount,source,created_at) VALUES(?,?,?,?,?)").run(crypto.randomUUID(),userId,xp,source,now);db.prepare("INSERT INTO user_progress(user_id,xp,level,longest_streak) VALUES(?,?,1,0) ON CONFLICT(user_id) DO UPDATE SET xp=xp+excluded.xp").run(userId,xp);const row=db.prepare("SELECT xp,level FROM user_progress WHERE user_id=?").get(userId) as any;const level=Math.max(1,Math.floor(Number(row.xp)/250)+1);if(level!==row.level)db.prepare("UPDATE user_progress SET level=? WHERE user_id=?").run(level,userId);}
export function unlock(userId:string,code:string){const item=catalog.find(x=>x.code===code);if(!item)return false;if(db.prepare("SELECT 1 FROM achievements WHERE user_id=? AND code=?").get(userId,code))return false;const now=new Date().toISOString();db.prepare("INSERT INTO achievements(id,user_id,code,unlocked_at) VALUES(?,?,?,?)").run(crypto.randomUUID(),userId,code,now);grantXp(userId,item.xp,`achievement:${code}`);const prefs=db.prepare("SELECT achievement_alerts FROM notification_preferences WHERE user_id=?").get(userId) as any;if(prefs?.achievement_alerts!==0)db.prepare("INSERT INTO notifications(id,user_id,type,title,body,created_at) VALUES(?,?,?,?,?,?)").run(crypto.randomUUID(),userId,"achievement",`Achievement unlocked: ${item.title}`,`${item.body} +${item.xp} XP`,now);return true;}
export function evaluate(userId:string){const p=progress(userId);for(const item of catalog){if(p[item.metric]>=item.target)unlock(userId,item.code)}db.prepare("INSERT INTO user_progress(user_id,longest_streak) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET longest_streak=MAX(longest_streak,excluded.longest_streak)").run(userId,p.streak);return p;}
export function afterStudy(userId:string){const p=evaluate(userId);createStudyNotifications(userId);return p}export function afterQuiz(userId:string){return evaluate(userId)}export function afterCard(userId:string){const p=evaluate(userId);createDueNotification(userId);return p}
export function createDueNotification(userId:string){const r=db.prepare("SELECT COUNT(*) n FROM flashcards WHERE user_id=? AND due_at<=?").get(userId,new Date().toISOString()) as {n:number};const prefs=db.prepare("SELECT review_alerts FROM notification_preferences WHERE user_id=?").get(userId) as any;if(r.n&&prefs?.review_alerts!==0){const day=new Date().toISOString().slice(0,10);if(!db.prepare("SELECT 1 FROM notifications WHERE user_id=? AND type='review' AND created_at LIKE ?").get(userId,`${day}%`))db.prepare("INSERT INTO notifications(id,user_id,type,title,body,created_at) VALUES(?,?,?,?,?,?)").run(crypto.randomUUID(),userId,"review","Flashcards due",`${r.n} card${r.n===1?"":"s"} ready for review.`,new Date().toISOString())}}
export function createStudyNotifications(userId:string){const day=new Date().toISOString().slice(0,10);const s=db.prepare("SELECT COALESCE(SUM(minutes),0) n FROM study_sessions WHERE user_id=? AND started_at LIKE ?").get(userId,`${day}%`) as {n:number};const g=db.prepare("SELECT minutes FROM study_goals WHERE user_id=?").get(userId) as {minutes:number}|undefined;const prefs=db.prepare("SELECT goal_alerts FROM notification_preferences WHERE user_id=?").get(userId) as any;if(g&&s.n>=g.minutes&&prefs?.goal_alerts!==0&&!db.prepare("SELECT 1 FROM notifications WHERE user_id=? AND type='goal' AND created_at LIKE ?").get(userId,`${day}%`))db.prepare("INSERT INTO notifications(id,user_id,type,title,body,created_at) VALUES(?,?,?,?,?,?)").run(crypto.randomUUID(),userId,"goal","Daily goal complete",`You reached ${g.minutes} minutes today.`,new Date().toISOString())}
