import db from "./db";
type Achievement={code:string;title:string;body:string;xp:number;target:number};
export const catalog:Achievement[]=[{code:"first-session",title:"First Study Session",body:"Complete your first focused study session.",xp:25,target:1},{code:"first-quiz",title:"Quiz Starter",body:"Complete your first quiz.",xp:25,target:1},{code:"first-card",title:"Card Starter",body:"Review your first flashcard.",xp:20,target:1},{code:"study-60",title:"Focused Hour",body:"Study for 60 total minutes.",xp:50,target:60},{code:"quiz-5",title:"Quiz Builder",body:"Complete 5 quiz attempts.",xp:75,target:5},{code:"cards-25",title:"Recall Builder",body:"Review 25 flashcards.",xp:75,target:25},{code:"seven-day-streak",title:"Seven Day Streak",body:"Study on seven consecutive days.",xp:100,target:7},{code:"thirty-day-streak",title:"Month of Momentum",body:"Study on 30 consecutive days.",xp:300,target:30}];
function progress(userId:string){const sessions=db.prepare("SELECT minutes,started_at FROM study_sessions WHERE user_id=?").all(userId) as any[];const quizzes=db.prepare("SELECT 1 FROM quiz_attempts WHERE user_id=?").all(userId).length;const cards=db.prepare("SELECT 1 FROM flashcard_reviews WHERE user_id=?").all(userId).length;const days=new Set(sessions.map(x=>new Date(x.started_at).toISOString().slice(0,10)));let streak=0,d=new Date();while(days.has(d.toISOString().slice(0,10))){streak++;d.setDate(d.getDate()-1)}return {minutes:sessions.reduce((n,x)=>n+Number(x.minutes||0),0),quizzes,cards,streak};}
function grantXp(userId:string,xp:number){db.prepare("INSERT INTO user_progress(user_id,xp,level,longest_streak) VALUES(?,?,1,0) ON CONFLICT(user_id) DO UPDATE SET xp=xp+excluded.xp").run(userId,xp);const row=db.prepare("SELECT xp,level FROM user_progress WHERE user_id=?").get(userId) as any;const level=Math.max(1,Math.floor(Number(row.xp)/250)+1);if(level!==row.level)db.prepare("UPDATE user_progress SET level=? WHERE user_id=?").run(level,userId);}
export function unlock(userId:string,code:string){const item=catalog.find(x=>x.code===code);if(!item)return false;if(db.prepare("SELECT 1 FROM achievements WHERE user_id=? AND code=?").get(userId,code))return false;const now=new Date().toISOString();db.prepare("INSERT INTO achievements(id,user_id,code,unlocked_at) VALUES(?,?,?,?)").run(crypto.randomUUID(),userId,code,now);grantXp(userId,item.xp);db.prepare("INSERT INTO notifications(id,user_id,type,title,body,created_at) VALUES(?,?,?,?,?,?)").run(crypto.randomUUID(),userId,"achievement",`Achievement unlocked: ${item.title}`,`${item.body} +${item.xp} XP`,now);return true;}
export function evaluate(userId:string){const p=progress(userId);if(p.minutes>=1)unlock(userId,"first-session");if(p.quizzes>=1)unlock(userId,"first-quiz");if(p.cards>=1)unlock(userId,"first-card");if(p.minutes>=60)unlock(userId,"study-60");if(p.quizzes>=5)unlock(userId,"quiz-5");if(p.cards>=25)unlock(userId,"cards-25");if(p.streak>=7)unlock(userId,"seven-day-streak");if(p.streak>=30)unlock(userId,"thirty-day-streak");db.prepare("INSERT INTO user_progress(user_id,longest_streak) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET longest_streak=MAX(longest_streak,excluded.longest_streak)").run(userId,p.streak);return p;}
export function afterStudy(userId:string){return evaluate(userId)}export function afterQuiz(userId:string){return evaluate(userId)}export function afterCard(userId:string){return evaluate(userId)}
export function createDueNotification(userId:string){const r=db.prepare("SELECT COUNT(*) n FROM flashcards WHERE user_id=? AND due_at<=?").get(userId,new Date().toISOString()) as {n:number};if(r.n){const day=new Date().toISOString().slice(0,10);if(!db.prepare("SELECT 1 FROM notifications WHERE user_id=? AND type='review' AND created_at LIKE ?").get(userId,`${day}%`))db.prepare("INSERT INTO notifications(id,user_id,type,title,body,created_at) VALUES(?,?,?,?,?,?)").run(crypto.randomUUID(),userId,"review","Flashcards due",`${r.n} card${r.n===1?"":"s"} ready for review.`,new Date().toISOString())}}
export function createStudyNotifications(userId:string){const day=new Date().toISOString().slice(0,10);const s=db.prepare("SELECT COALESCE(SUM(minutes),0) n FROM study_sessions WHERE user_id=? AND started_at LIKE ?").get(userId,`${day}%`) as {n:number};const g=db.prepare("SELECT minutes FROM study_goals WHERE user_id=?").get(userId) as {minutes:number}|undefined;if(g&&s.n>=g.minutes&&!db.prepare("SELECT 1 FROM notifications WHERE user_id=? AND type='goal' AND created_at LIKE ?").get(userId,`${day}%`))db.prepare("INSERT INTO notifications(id,user_id,type,title,body,created_at) VALUES(?,?,?,?,?,?)").run(crypto.randomUUID(),userId,"goal","Daily goal complete",`You reached ${g.minutes} minutes today.`,new Date().toISOString())}
