/* Local-only card attachments for Flowboard */
const FLOW_ATTACH_DB='flowboard-attachments-v1';
function faOpen(){return new Promise((res,rej)=>{const r=indexedDB.open(FLOW_ATTACH_DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('files',{keyPath:'id'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function faList(cardId){const db=await faOpen();return new Promise((res,rej)=>{const q=db.transaction('files').objectStore('files').getAll();q.onsuccess=()=>res(q.result.filter(x=>x.cardId===cardId));q.onerror=()=>rej(q.error)})}
async function faPut(cardId,file){const db=await faOpen();const item={id:uid('file'),cardId,name:file.name,type:file.type||'application/octet-stream',size:file.size,blob:file,created:Date.now()};return new Promise((res,rej)=>{const q=db.transaction('files','readwrite').objectStore('files').put(item);q.onsuccess=()=>res(item);q.onerror=()=>rej(q.error)})}
async function faDelete(id){const db=await faOpen();return new Promise((res,rej)=>{const q=db.transaction('files','readwrite').objectStore('files').delete(id);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)})}
async function faRender(cardId,host){const files=await faList(cardId);host.innerHTML=`<div class="attachment-head"><b>Attachments</b><span class="muted">${files.length} local file${files.length===1?'':'s'}</span></div>${files.map(f=>`<div class="attachment-row"><button class="link-btn" data-fa-open="${f.id}">${esc(f.name)}</button><span class="muted">${Math.ceil(f.size/1024)} KB</span><button class="text-btn" data-fa-delete="${f.id}">Delete</button></div>`).join('')||'<p class="muted">No attachments. Files stay in this browser and are never uploaded.</p>'}`;host.querySelectorAll('[data-fa-open]').forEach(b=>b.onclick=async()=>{const db=await faOpen();const q=db.transaction('files').objectStore('files').get(b.dataset.faOpen);q.onsuccess=()=>{if(!q.result)return;const u=URL.createObjectURL(q.result.blob);window.open(u,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(u),60000)}});host.querySelectorAll('[data-fa-delete]').forEach(b=>b.onclick=async()=>{await faDelete(b.dataset.faDelete);faRender(cardId,host)})}
function faAttachUI(){const d=document.getElementById('cardDialog');if(!d||d.querySelector('#faBox'))return;const box=document.createElement('div');box.id='faBox';box.className='attachment-box';box.innerHTML='<div class="attachment-head"><b>Attachments</b><span class="muted">Local-only IndexedDB storage</span></div><input id="faInput" type="file" multiple><div id="faList"></div>';d.querySelector('.modal-actions').parentNode.insertBefore(box,d.querySelector('.modal-actions'));d.querySelector('#faInput').onchange=async e=>{const id=d.dataset.advCardId;if(!id){toast('Save the card before attaching files');e.target.value='';return}for(const f of e.target.files)await faPut(id,f);e.target.value='';faRender(id,d.querySelector('#faList'))}}
function faBoot(){faAttachUI();const o=new MutationObserver(()=>faAttachUI());o.observe(document.body,{childList:true,subtree:true})}
faBoot();
