(()=>{
const KEY='monthflow:v1';const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};const write=s=>{localStorage.setItem(KEY,JSON.stringify(s));location.reload()};const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function current(){const s=read();return s.month||new Date().toISOString().slice(0,7)}
function csv(){const s=read(),rows=[['Title','Date','Start','Duration','Priority','Energy','Deadline','Project','Goal','Tags','Completed','Notes']].concat((s.tasks||[]).map(t=>[t.title,t.date,t.start,t.duration,t.priority,t.energy,t.deadline,t.project,(s.goals||[]).find(g=>g.id===t.goalId)?.title||'',(t.tags||[]).join('|'),t.completed?'Yes':'No',t.notes]));const text=rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');download(text,`monthflow-${current()}.csv`,'text/csv')}
function ics(){const s=read(),events=(s.tasks||[]).filter(t=>t.date&&t.date.startsWith(current())&&!t.completed).map(t=>{const start=(t.start||'09:00').replace(':','')+'00';const end=new Date(`${t.date}T${t.start||'09:00'}:00`);end.setMinutes(end.getMinutes()+(Number(t.duration)||30));const e=end.toTimeString().slice(0,5).replace(':','')+'00';return `BEGIN:VEVENT\nUID:${t.id}@monthflow\nDTSTART:${t.date.replaceAll('-','')}T${start}\nDTEND:${t.date.replaceAll('-','')}T${e}\nSUMMARY:${String(t.title).replace(/[\\,;]/g,' ')}\nDESCRIPTION:${String(t.notes||'').replace(/[\\,;]/g,' ')}\nEND:VEVENT`}).join('\n');download(`BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Monthflow//Monthly Planner//EN\n${events}\nEND:VCALENDAR`,`monthflow-${current()}.ics`,'text/calendar')}
function download(text,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function template(){const s=read(),key=current(),tasks=(s.tasks||[]).filter(t=>t.date?.startsWith(key));const tpl={id:uid(),name:`${key} template`,createdAt:new Date().toISOString(),tasks:tasks.map(t=>({...t,id:undefined,date:'',completed:false,completedAt:null,source:undefined}))};s.templates=[...(s.templates||[]),tpl];write(s)}
function applyTemplate(){const s=read(),tpl=(s.templates||[]).at(-1);if(!tpl){alert('No saved monthly template yet.');return}const day=prompt('Apply template starting on date (YYYY-MM-DD):',`${current()}-01`);if(!day)return;tpl.tasks.forEach((x,i)=>{const t={...x,id:uid(),date:'',completed:false,createdAt:new Date().toISOString()};if(x.date){const base=new Date(`${current()}-01T00:00:00`),old=new Date(x.date+'T00:00:00');const offset=Math.round((old-base)/86400000);const d=new Date(day+'T00:00:00');d.setDate(d.getDate()+offset);t.date=d.toISOString().slice(0,10)}s.tasks.push(t)});write(s)}
function natural(){const raw=prompt('Quick capture. Examples: “Submit report Friday 90m p1”, “Review budget next month 60m”, “Plan study 2026-10-12 45m”.');if(!raw)return;const s=read(),now=new Date(),key=current();let date='';const isoMatch=raw.match(/\b(20\d{2}-\d{2}-\d{2})\b/);if(isoMatch)date=isoMatch[1];else if(/tomorrow/i.test(raw)){const d=new Date(now);d.setDate(d.getDate()+1);date=d.toISOString().slice(0,10)}else if(/today/i.test(raw))date=now.toISOString().slice(0,10);else {const names=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];const m=names.findIndex(n=>new RegExp('\\b'+n+'\\b','i').test(raw));if(m>=0){const d=new Date(now),delta=(m-d.getDay()+7)%7||7;d.setDate(d.getDate()+delta);date=d.toISOString().slice(0,10)}}if(!date&&/next month/i.test(raw))date='';const duration=Number((raw.match(/(\d+)\s*(?:m|min|mins|minutes)\b/i)||[])[1])||30;const p=/\bp1\b/i.test(raw)?'p1':/\bp2\b/i.test(raw)?'p2':/\bp4\b/i.test(raw)?'p4':'p3';const clean=raw.replace(/\b(?:today|tomorrow|next month|monday|tuesday|wednesday|thursday|friday|saturday|sunday|20\d{2}-\d{2}-\d{2}|\d+\s*(?:m|min|mins|minutes)|p[1-4])\b/gi,'').replace(/\s+/g,' ').trim();s.tasks=[...(s.tasks||[]),{id:uid(),title:clean||raw,date,start:'',duration,priority:p,energy:'medium',deadline:'',repeat:'none',project:'',tags:[],dependsOn:[],goalId:'',notes:'Captured with Monthflow quick capture',completed:false,createdAt:new Date().toISOString()}];write(s)}
function panel(){const p=document.createElement('aside');p.id='advancedTools';p.innerHTML=`<div class="adv-head"><strong>Advanced tools</strong><button id="advClose">×</button></div><button id="quickCapture">Quick capture</button><button id="exportIcs">Export ICS</button><button id="exportCsv">Export CSV</button><button id="saveTpl">Save month template</button><button id="applyTpl">Apply latest template</button><small>All tools stay local to this browser.</small>`;document.body.append(p);const st=document.createElement('style');st.textContent='#advancedTools{position:fixed;right:18px;bottom:18px;z-index:45;width:230px;padding:14px;background:var(--panel);border:1px solid var(--line);border-radius:16px;box-shadow:0 20px 50px #0004;display:grid;gap:8px}#advancedTools button{padding:9px;border:1px solid var(--line);background:var(--panel2);border-radius:9px;text-align:left;color:var(--text)}#advancedTools small{color:var(--muted)}.adv-head{display:flex;justify-content:space-between}.adv-head button{background:transparent!important;border:0!important;font-size:20px!important;padding:0!important}';document.head.append(st);p.querySelector('#quickCapture').onclick=natural;p.querySelector('#exportIcs').onclick=ics;p.querySelector('#exportCsv').onclick=csv;p.querySelector('#saveTpl').onclick=template;p.querySelector('#applyTpl').onclick=applyTemplate;p.querySelector('#advClose').onclick=()=>p.remove()}
window.addEventListener('DOMContentLoaded',panel)
})();