const KEY='monthflow:v1';
const defaults={tasks:[],goals:[],reviews:{},templates:[],settings:{capacity:9600,dailyCapacity:420,buffer:15,start:'08:00',end:'18:00',peakStart:'09:00',peakEnd:'12:00',theme:'system',weekStart:1,weekend:false,notifications:false},month:monthKey(new Date())};
let state=load(); let selectedMonth=state.month;
const $=id=>document.getElementById(id); const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function monthKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function parseDate(s){const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function firstDay(key){return new Date(Number(key.slice(0,4)),Number(key.slice(5,7))-1,1)}
function daysIn(key){const d=firstDay(key);return new Date(d.getFullYear(),d.getMonth()+1,0).getDate()}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function load(){try{return {...structuredClone(defaults),...JSON.parse(localStorage.getItem(KEY)||'{}'),settings:{...defaults.settings,...(JSON.parse(localStorage.getItem(KEY)||'{}').settings||{})}}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state)); render()}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function inMonth(t,key=selectedMonth){return t.date&&t.date.startsWith(key)}
function tasksForDate(date){return state.tasks.filter(t=>t.date===date).sort((a,b)=>(a.start||'99:99').localeCompare(b.start||'99:99')||b.priority.localeCompare(a.priority))}
function taskMinutes(t){return Number(t.duration)||30}
function monthTasks(){return state.tasks.filter(t=>inMonth(t))}
function monthGoals(){return state.goals.filter(g=>g.month===selectedMonth)}
function capacityDays(){const n=daysIn(selectedMonth),start=firstDay(selectedMonth).getDay();let weekend=0;for(let i=0;i<n;i++){const dow=(start+i)%7;if(dow===0||dow===6)weekend++}return n-(state.settings.weekend?0:weekend)}
function monthCapacity(){return Math.min(state.settings.capacity,Math.max(1,capacityDays())*state.settings.dailyCapacity*(1-state.settings.buffer/100))}
function goalProgress(g){const linked=monthTasks().filter(t=>t.goalId===g.id);const done=linked.filter(t=>t.completed).length;return g.target?Math.min(100,Math.round((done/g.target)*100)):0}
function fmtHours(min){return `${(min/60).toFixed(min%60?'1':'0')}h`}
function applyTheme(){const t=state.settings.theme;document.body.classList.toggle('dark',t==='dark'||(t==='system'&&matchMedia('(prefers-color-scheme: dark)').matches))}
function render(){applyTheme();renderHeader();renderMetrics();renderCalendar();renderGoals();renderBacklog();renderAnalytics();loadReview()}
function renderHeader(){const d=firstDay(selectedMonth);$('monthTitle').textContent=d.toLocaleDateString(undefined,{month:'long',year:'numeric'});$('monthSubtitle').textContent=`${monthTasks().filter(t=>t.completed).length} completed · ${fmtHours(monthTasks().filter(t=>!t.completed).reduce((s,t)=>s+taskMinutes(t),0))} remaining · ${monthGoals().length} goals`}
function renderMetrics(){const ts=monthTasks(),done=ts.filter(t=>t.completed),planned=ts.filter(t=>t.date),mins=ts.reduce((s,t)=>s+taskMinutes(t),0),doneMin=done.reduce((s,t)=>s+taskMinutes(t),0),cap=monthCapacity(),pct=cap?Math.round(mins/cap*100):0,goals=monthGoals(),goalAvg=goals.length?Math.round(goals.reduce((s,g)=>s+goalProgress(g),0)/goals.length):0;$('metrics').innerHTML=[['Tasks',`${done.length}/${ts.length}`,'completion',ts.length?Math.round(done.length/ts.length*100):0],['Planned',`${planned.length}/${ts.length}`,'scheduled',ts.length?Math.round(planned.length/ts.length*100):0],['Workload',fmtHours(mins),'capacity',Math.min(100,pct)],['Focus time',fmtHours(doneMin),'done',done.length?Math.round(doneMin/Math.max(1,mins)*100):0],['Goals',`${goalAvg}%`,'goal',goalAvg]].map(x=>`<div class="metric"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="progress"><i style="width:${x[3]}%"></i></div><div class="label">${x[2]} · ${x[3]}%</div></div>`).join('')}
function renderCalendar(){const head=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];$('weekdayHead').innerHTML=head.map(x=>`<div>${x}</div>`).join('');const first=firstDay(selectedMonth),offset=first.getDay(),total=daysIn(selectedMonth),prevDays=new Date(first.getFullYear(),first.getMonth(),0).getDate(),cells=[];for(let i=0;i<42;i++){const n=i-offset+1;let d=new Date(first);d.setDate(n);const current=n>=1&&n<=total;const date=iso(d);const ts=tasksForDate(date);const mins=ts.reduce((s,t)=>s+taskMinutes(t),0);const cls=`day ${current?'':'muted'} ${date===iso(new Date())?'today':''} ${mins>state.settings.dailyCapacity?'over':''}`;cells.push(`<div class="${cls}" data-date="${date}"><div class="dayhead"><span class="daynum">${d.getDate()}</span><span class="capacity-dot">${fmtHours(mins)} / ${fmtHours(state.settings.dailyCapacity)}</span></div><div class="dropzone" data-drop="${date}">${ts.map(taskCard).join('')}</div><button class="mini" data-add-date="${date}">+ add</button></div>`)}$('monthGrid').innerHTML=cells.join('');bindCalendar()}
function taskCard(t){return `<article class="task-card ${t.priority} ${t.completed?'done':''}" draggable="true" data-task="${t.id}"><div class="taskline"><input type="checkbox" data-complete="${t.id}" ${t.completed?'checked':''}><span>${esc(t.title)}</span></div><div class="taskmeta">${t.start?esc(t.start)+' · ':''}${taskMinutes(t)}m${t.energy?` · ${esc(t.energy)}`:''}${t.deadline?` · due ${esc(t.deadline)}`:''}</div></article>`}
function bindCalendar(){$('[id="monthGrid"]').querySelectorAll('[data-complete]').forEach(x=>x.onchange=()=>{const t=state.tasks.find(t=>t.id===x.dataset.complete);if(t){t.completed=x.checked;t.completedAt=x.checked?new Date().toISOString():null;save();toast(x.checked?'Task completed':'Task reopened')}});$('monthGrid').querySelectorAll('[data-task]').forEach(x=>{x.ondblclick=()=>openTask(x.dataset.task);x.ondragstart=e=>e.dataTransfer.setData('text/plain',x.dataset.task)});$('monthGrid').querySelectorAll('[data-drop]').forEach(x=>{x.ondragover=e=>e.preventDefault();x.ondrop=e=>{const id=e.dataTransfer.getData('text/plain'),t=state.tasks.find(t=>t.id===id);if(t){t.date=x.dataset.drop;save();toast('Task moved')}}});$('monthGrid').querySelectorAll('[data-add-date]').forEach(x=>x.onclick=()=>openTask(null,x.dataset.addDate))}
function renderGoals(){const gs=monthGoals();$('goalsList').innerHTML=gs.length?gs.map(g=>{const p=goalProgress(g),linked=monthTasks().filter(t=>t.goalId===g.id);return `<article class="goal"><div class="goal-top"><div><h3>${esc(g.title)}</h3><div class="goal-meta">${linked.filter(t=>t.completed).length}/${linked.length} linked tasks · target ${g.target} ${esc(g.unit)}</div></div><div class="goal-actions"><button class="mini" data-edit-goal="${g.id}">Edit</button></div></div><div class="goal-progress"><div class="progress"><i style="width:${p}%"></i></div><strong>${p}%</strong></div><p class="goal-meta">${esc(g.notes||'')}</p></article>`}).join(''):'<div class="empty">No monthly goals yet. Add 1–3 outcome-focused goals to anchor the month.</div>';$('goalsList').querySelectorAll('[data-edit-goal]').forEach(x=>x.onclick=()=>openGoal(x.dataset.editGoal))}
function renderBacklog(){const q=($('search').value||'').toLowerCase(),p=$('priorityFilter').value;const ts=state.tasks.filter(t=>(!t.date||!inMonth(t))&&!t.completed&&(!q||`${t.title} ${t.notes||''} ${t.project||''}`.toLowerCase().includes(q))&&(p==='all'||t.priority===p));$('backlogList').innerHTML=ts.length?ts.map(t=>`<div class="backlog-item"><div><strong>${esc(t.title)}</strong><div class="taskmeta">${t.priority} · ${taskMinutes(t)}m${t.deadline?' · due '+t.deadline:''}${t.project?' · '+esc(t.project):''}</div></div><button class="mini" data-plan="${t.id}">Plan</button><button class="mini" data-edit-task="${t.id}">Edit</button></div>`).join(''):'<div class="empty">Your backlog is clear.</div>';$('backlogList').querySelectorAll('[data-edit-task]').forEach(x=>x.onclick=()=>openTask(x.dataset.editTask));$('backlogList').querySelectorAll('[data-plan]').forEach(x=>x.onclick=()=>openTask(x.dataset.plan))}
function renderAnalytics(){const ts=monthTasks(),days=daysIn(selectedMonth),done=ts.filter(t=>t.completed),mins=ts.reduce((s,t)=>s+taskMinutes(t),0),p1=ts.filter(t=>t.priority==='p1').length,over=[];for(let i=1;i<=days;i++){const d=iso(new Date(firstDay(selectedMonth).getFullYear(),firstDay(selectedMonth).getMonth(),i)),m=tasksForDate(d).reduce((s,t)=>s+taskMinutes(t),0);if(m>state.settings.dailyCapacity)over.push({d,m})}const byProject={};ts.forEach(t=>{const k=t.project||'Unassigned';byProject[k]=(byProject[k]||0)+taskMinutes(t)});$('analytics').innerHTML=`<div class="analytics-card"><h3>Completion</h3><div class="big">${ts.length?Math.round(done.length/ts.length*100):0}%</div><p>${done.length} of ${ts.length} tasks complete.</p></div><div class="analytics-card"><h3>Capacity</h3><div class="big">${Math.round(mins/Math.max(1,monthCapacity())*100)}%</div><p>${fmtHours(mins)} planned against ${fmtHours(monthCapacity())} usable capacity.</p></div><div class="analytics-card"><h3>Risk</h3><div class="big">${over.length}</div><p>${over.length?'days exceed daily capacity':'No overloaded days detected.'}</p></div><div class="analytics-card"><h3>Priority mix</h3>${['p1','p2','p3','p4'].map(p=>{const n=ts.filter(t=>t.priority===p).length;return `<div class="bar-row"><span>${p.toUpperCase()}</span><div class="bar"><i style="width:${ts.length?n/ts.length*100:0}%"></i></div><span>${n}</span></div>`}).join('')}</div><div class="analytics-card"><h3>Project load</h3>${Object.entries(byProject).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=>`<div class="bar-row"><span>${esc(k)}</span><div class="bar"><i style="width:${mins?v/mins*100:0}%"></i></div><span>${fmtHours(v)}</span></div>`).join('')||'<p>No project data yet.</p>'}</div><div class="analytics-card"><h3>Deadline radar</h3>${ts.filter(t=>t.deadline&&!t.completed).sort((a,b)=>a.deadline.localeCompare(b.deadline)).slice(0,8).map(t=>`<div class="bar-row"><span>${esc(t.title).slice(0,16)}</span><div class="bar"><i style="width:${Math.min(100,Math.max(5,(parseDate(t.deadline)-new Date())/86400000/30*100))}%"></i></div><span>${t.deadline}</span></div>`).join('')||'<p>No open deadlines.</p>'}</div>`}
function openTask(id=null,date=''){const t=id?state.tasks.find(x=>x.id===id):null;$('taskDialogTitle').textContent=t?'Edit task':'New task';$('taskId').value=t?.id||'';$('taskTitle').value=t?.title||'';$('taskDate').value=t?.date||date;$('taskStart').value=t?.start||'';$('taskDuration').value=t?.duration||30;$('taskPriority').value=t?.priority||'p3';$('taskEnergy').value=t?.energy||'medium';$('taskDeadline').value=t?.deadline||'';$('taskRepeat').value=t?.repeat||'none';$('taskProject').value=t?.project||'';$('taskTags').value=(t?.tags||[]).join(', ');$('taskDepends').value=(t?.dependsOn||[]).join(', ');$('taskNotes').value=t?.notes||'';$('taskGoal').innerHTML='<option value="">No goal</option>'+monthGoals().map(g=>`<option value="${g.id}">${esc(g.title)}</option>`).join('');$('taskGoal').value=t?.goalId||'';$('deleteTaskBtn').style.display=t?'block':'none';$('taskDialog').showModal()}
function saveTask(){const id=$('taskId').value||uid(),old=state.tasks.find(t=>t.id===id);const date=$('taskDate').value||'';const t={id,title:$('taskTitle').value.trim(),date,start:$('taskStart').value,duration:Number($('taskDuration').value)||30,priority:$('taskPriority').value,energy:$('taskEnergy').value,deadline:$('taskDeadline').value,repeat:$('taskRepeat').value,project:$('taskProject').value.trim(),tags:$('taskTags').value.split(',').map(x=>x.trim()).filter(Boolean),dependsOn:$('taskDepends').value.split(',').map(x=>x.trim()).filter(Boolean),goalId:$('taskGoal').value,notes:$('taskNotes').value.trim(),completed:old?.completed||false,completedAt:old?.completedAt||null,createdAt:old?.createdAt||new Date().toISOString()};if(!t.title)return;if(old)Object.assign(old,t);else state.tasks.push(t);expandRecurrence(t);save();$('taskDialog').close();toast('Task saved')}
function expandRecurrence(t){if(!t.repeat||t.repeat==='none'||!t.date)return;const base=parseDate(t.date);for(let i=1;i<=12;i++){let d=new Date(base);if(t.repeat==='daily')d.setDate(base.getDate()+i);if(t.repeat==='weekdays'){d.setDate(base.getDate()+i);while([0,6].includes(d.getDay()))d.setDate(d.getDate()+1)}if(t.repeat==='weekly')d.setDate(base.getDate()+i*7);if(t.repeat==='monthly')d.setMonth(base.getMonth()+i);if(d.getMonth()!==base.getMonth()&&t.repeat==='daily')break;const date=iso(d);if(!state.tasks.some(x=>x.source===t.id&&x.date===date))state.tasks.push({...t,id:uid(),date,source:t.id,completed:false,completedAt:null})}}
function openGoal(id=null){const g=id?state.goals.find(x=>x.id===id):null;$('goalId').value=g?.id||'';$('goalTitle').value=g?.title||'';$('goalTarget').value=g?.target||100;$('goalUnit').value=g?.unit||'%';$('goalNotes').value=g?.notes||'';$('deleteGoalBtn').style.display=g?'block':'none';$('goalDialog').showModal()}
function saveGoal(){const id=$('goalId').value||uid(),old=state.goals.find(g=>g.id===id),g={id,title:$('goalTitle').value.trim(),target:Number($('goalTarget').value)||100,unit:$('goalUnit').value.trim()||'%',notes:$('goalNotes').value.trim(),month:selectedMonth};if(!g.title)return;if(old)Object.assign(old,g);else state.goals.push(g);save();$('goalDialog').close();toast('Goal saved')}
function autoPlan(){const key=selectedMonth,capacity=state.settings.dailyCapacity*(1-state.settings.buffer/100),ts=state.tasks.filter(t=>!t.completed&&(!t.date||!inMonth(t,key)));const eligible=ts.filter(t=>{if(t.dependsOn?.some(id=>state.tasks.some(x=>x.id===id&&!x.completed)))return false;return true}).sort((a,b)=>(a.deadline||'9999').localeCompare(b.deadline||'9999')||b.priority.localeCompare(a.priority)||taskMinutes(b)-taskMinutes(a));const loads={};for(let i=1;i<=daysIn(key);i++){const d=iso(new Date(firstDay(key).getFullYear(),firstDay(key).getMonth(),i));const dow=parseDate(d).getDay();if(!state.settings.weekend&&[0,6].includes(dow))continue;loads[d]=tasksForDate(d).reduce((s,t)=>s+taskMinutes(t),0)}for(const t of eligible){const candidates=Object.keys(loads).filter(d=>loads[d]+taskMinutes(t)<=capacity);if(t.deadline){const before=candidates.filter(d=>d<=t.deadline);if(before.length)candidates.splice(0,candidates.length,...before)}if(!candidates.length)continue;const best=candidates.sort((a,b)=>loads[a]-loads[b])[0];t.date=best;loads[best]+=taskMinutes(t)}save();toast('Month auto-planned around capacity')}
function shiftMonth(delta){const d=firstDay(selectedMonth);d.setMonth(d.getMonth()+delta);selectedMonth=monthKey(d);state.month=selectedMonth;save()}
function exportData(){const payload={schema:'monthflow/v1',exportedAt:new Date().toISOString(),state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`monthflow-${selectedMonth}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.state?.tasks||!x.state?.settings)throw Error('Invalid backup');state={...structuredClone(defaults),...x.state,settings:{...defaults.settings,...x.state.settings}};selectedMonth=state.month||selectedMonth;save();toast('Backup restored')}catch{toast('Import failed')}};r.readAsText(file)}
function loadReview(){const r=state.reviews[selectedMonth]||{};$('reviewWins').value=r.wins||'';$('reviewBlockers').value=r.blockers||'';$('reviewChanges').value=r.changes||'';$('reviewFocus').value=r.focus||''}
function saveReview(){state.reviews[selectedMonth]={wins:$('reviewWins').value,blockers:$('reviewBlockers').value,changes:$('reviewChanges').value,focus:$('reviewFocus').value,savedAt:new Date().toISOString()};save();toast('Review saved')}
function openReview(){const ts=monthTasks(),done=ts.filter(t=>t.completed),gs=monthGoals();$('reviewSummary').innerHTML=`<div class="review-card"><strong>${done.length}/${ts.length} tasks completed</strong><span>${fmtHours(ts.reduce((s,t)=>s+taskMinutes(t),0))} planned · ${gs.length} goals · ${gs.filter(g=>goalProgress(g)>=100).length} goals complete</span><span>${monthCapacity()>=ts.reduce((s,t)=>s+taskMinutes(t),0)?'Capacity looks realistic.':'The month is over capacity — consider cutting, moving or splitting work.'}</span></div>`;$('reviewDialog').showModal()}
function openSettings(){const s=state.settings;$('settingCapacity').value=s.capacity;$('settingDailyCapacity').value=s.dailyCapacity;$('settingBuffer').value=s.buffer;$('settingStart').value=s.start;$('settingEnd').value=s.end;$('settingPeakStart').value=s.peakStart;$('settingPeakEnd').value=s.peakEnd;$('settingTheme').value=s.theme;$('settingWeekStart').value=s.weekStart;$('settingWeekend').checked=s.weekend;$('settingNotifications').checked=s.notifications;$('settingsDialog').showModal()}
function saveSettings(){Object.assign(state.settings,{capacity:Number($('settingCapacity').value)||9600,dailyCapacity:Number($('settingDailyCapacity').value)||420,buffer:Number($('settingBuffer').value)||0,start:$('settingStart').value,end:$('settingEnd').value,peakStart:$('settingPeakStart').value,peakEnd:$('settingPeakEnd').value,theme:$('settingTheme').value,weekStart:Number($('settingWeekStart').value),weekend:$('settingWeekend').checked,notifications:$('settingNotifications').checked});if(state.settings.notifications&&'Notification'in window&&Notification.permission==='default')Notification.requestPermission();save();$('settingsDialog').close();toast('Settings saved')}
function resetAll(){if(confirm('Reset all Monthflow data? This cannot be undone unless you have an export.')){localStorage.removeItem(KEY);state=structuredClone(defaults);selectedMonth=state.month;save();$('settingsDialog').close();toast('Data reset')}}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(b.dataset.view+'View').classList.add('active')});
$('prevMonth').onclick=()=>shiftMonth(-1);$('nextMonth').onclick=()=>shiftMonth(1);$('todayBtn').onclick=()=>{selectedMonth=monthKey(new Date());state.month=selectedMonth;save()};$('newTaskBtn').onclick=()=>openTask();$('backlogAdd').onclick=()=>openTask();$('newGoalBtn').onclick=()=>openGoal();$('goalViewAdd').onclick=()=>openGoal();$('autoPlanBtn').onclick=autoPlan;$('reviewBtn').onclick=openReview;$('settingsBtn').onclick=openSettings;$('exportBtn').onclick=exportData;$('importBtn').onclick=()=>$('importFile').click();$('importFile').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$('search').oninput=renderBacklog;$('priorityFilter').onchange=renderBacklog;$('taskForm').onsubmit=e=>{e.preventDefault();saveTask()};$('goalForm').onsubmit=e=>{e.preventDefault();saveGoal()};$('settingsForm').onsubmit=e=>{e.preventDefault();saveSettings()};$('reviewModalForm').onsubmit=e=>{e.preventDefault();$('reviewDialog').close();document.querySelector('[data-view="review"]').click()};$('saveReviewBtn').onclick=saveReview;$('deleteTaskBtn').onclick=()=>{const id=$('taskId').value;state.tasks=state.tasks.filter(t=>t.id!==id&&t.source!==id);save();$('taskDialog').close();toast('Task deleted')};$('deleteGoalBtn').onclick=()=>{const id=$('goalId').value;state.goals=state.goals.filter(g=>g.id!==id);state.tasks.forEach(t=>{if(t.goalId===id)t.goalId=''});save();$('goalDialog').close();toast('Goal deleted')};$('resetBtn').onclick=resetAll;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());window.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();$('search').focus()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('search').focus()}if(e.key.toLowerCase()==='n'&&!e.ctrlKey&&!e.metaKey&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName))openTask()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});window.addEventListener('storage',e=>{if(e.key===KEY){state=load();selectedMonth=state.month;render()}});render();
