"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

type Q={type:"multiple_choice"|"true_false"|"short_answer";question:string;options?:string[];answer:string};
const blank=():Q=>({type:"multiple_choice",question:"",options:["","","",""],answer:""});

export default function QuizEditor({quizId}:{quizId?:string}){
 const [title,setTitle]=useState("New quiz"),[difficulty,setDifficulty]=useState("medium"),[questions,setQuestions]=useState<Q[]>([blank()]),[loading,setLoading]=useState(!!quizId),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null),[done,setDone]=useState(false);
 useEffect(()=>{if(!quizId)return; (async()=>{try{const r=await fetch("/api/data?resource=quizzes");if(!r.ok)throw Error("Could not load quiz.");const q=(await r.json()).data?.find((x:any)=>x.id===quizId);if(!q)throw Error("Quiz not found.");setTitle(q.title);setDifficulty(q.difficulty);setQuestions(JSON.parse(q.questions_json||"[]"));}catch(e){setError(e instanceof Error?e.message:"Could not load quiz.")}finally{setLoading(false)}})()},[quizId]);
 function patch(i:number,p:Partial<Q>){setQuestions(q=>q.map((x,n)=>n===i?{...x,...p}:x))}
 function save(){setSaving(true);setError(null);fetch("/api/data",{method:quizId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource:"quizzes",...(quizId?{id:quizId}:{}),title,difficulty,questions})}).then(async r=>{if(!r.ok)throw Error((await r.json()).error||"Could not save quiz.");setDone(true)}).catch(e=>setError(e.message)).finally(()=>setSaving(false))}
 async function remove(){if(!quizId||!confirm("Delete this quiz?"))return;const r=await fetch(`/api/data?resource=quizzes&id=${encodeURIComponent(quizId)}`,{method:"DELETE"});if(r.ok)location.href="/quizzes";else setError("Could not delete quiz.")}
 if(loading)return <p className="text-slate-400">Loading quiz…</p>;
 return <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6 sm:p-8"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm text-slate-400">Title<input value={title} onChange={e=>setTitle(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-white"/></label><label className="text-sm text-slate-400">Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 px-4 py-3 text-white"><option>easy</option><option>medium</option><option>hard</option></select></label></div>
 <div className="mt-8 space-y-5">{questions.map((q,i)=><article key={i} className="rounded-2xl border border-slate-800 p-5"><div className="flex justify-between"><h2 className="font-semibold">Question {i+1}</h2><button onClick={()=>setQuestions(xs=>xs.filter((_,n)=>n!==i))} disabled={questions.length===1} className="text-sm text-red-300 disabled:opacity-30">Remove</button></div><div className="mt-4 grid gap-3"><select value={q.type} onChange={e=>{const type=e.target.value as Q["type"];patch(i,{type,options:type==="multiple_choice"?["","","",""]:type==="true_false"?["True","False"]:undefined,answer:type==="true_false"?"True":""})}} className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3"><option value="multiple_choice">Multiple choice</option><option value="true_false">True / false</option><option value="short_answer">Short answer</option></select><input value={q.question} onChange={e=>patch(i,{question:e.target.value})} placeholder="Question" className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3"/>{q.options?.map((o,n)=><input key={n} value={o} onChange={e=>{const opts=[...(q.options||[])];opts[n]=e.target.value;patch(i,{options:opts})}} placeholder={`Option ${n+1}`} className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3"/>)}<input value={q.answer} onChange={e=>patch(i,{answer:e.target.value})} placeholder="Correct answer" className="rounded-xl border border-slate-700 bg-slate-950 px-4 py-3"/></div></article>)}<button onClick={()=>setQuestions(q=>[...q,blank()])} className="rounded-xl border border-slate-700 px-4 py-3 text-sm font-semibold">+ Add question</button></div>
 {error&&<p className="mt-5 text-sm text-red-300">{error}</p>}{done&&<p className="mt-5 text-sm text-emerald-300">Quiz saved.</p>}<div className="mt-7 flex flex-wrap gap-3"><button onClick={save} disabled={saving||!title.trim()||questions.some(q=>!q.question.trim()||!q.answer.trim())} className="rounded-xl bg-white px-5 py-3 text-sm font-semibold text-slate-950 disabled:opacity-40">{saving?"Saving…":"Save quiz"}</button><Link href="/quizzes" className="rounded-xl border border-slate-700 px-5 py-3 text-sm font-semibold">Cancel</Link>{quizId&&<button onClick={remove} className="ml-auto rounded-xl border border-red-900/60 px-5 py-3 text-sm font-semibold text-red-300">Delete quiz</button>}</div></section>;
}
