"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

export default function QuizCatalog(){
 const [quizzes,setQuizzes]=useState<any[]>([]),[subject,setSubject]=useState("All"),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 async function load(){setLoading(true);setError(null);try{const r=await fetch("/api/data?resource=quizzes");if(!r.ok)throw Error("Sign in to manage quizzes.");setQuizzes((await r.json()).data||[])}catch(e){setError(e instanceof Error?e.message:"Could not load quizzes.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const subjects=useMemo(()=>["All",...Array.from(new Set(quizzes.map(q=>q.subject||"General")))],[quizzes]);
 const filtered=subject==="All"?quizzes:quizzes.filter(q=>(q.subject||"General")===subject);
 async function remove(id:string){if(!confirm("Delete this quiz?"))return;const r=await fetch(`/api/data?resource=quizzes&id=${encodeURIComponent(id)}`,{method:"DELETE"});if(r.ok)setQuizzes(xs=>xs.filter(q=>q.id!==id));else setError("Could not delete quiz.")}
 if(loading)return <div className="rounded-2xl border border-slate-800 p-8 text-slate-400">Loading quizzes…</div>;
 if(error)return <div className="rounded-2xl border border-red-900/50 bg-red-950/20 p-6"><p className="text-red-300">{error}</p><button onClick={()=>void load()} className="mt-4 rounded-xl bg-white px-4 py-2 text-sm font-semibold text-slate-950">Retry</button></div>;
 return <div><div className="flex flex-wrap gap-2">{subjects.map(item=><button key={item} onClick={()=>setSubject(item)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${subject===item?"bg-white text-slate-950":"border border-slate-800 text-slate-400 hover:border-slate-600"}`}>{item}</button>)}<Link href="/quizzes/new" className="ml-auto rounded-xl bg-white px-4 py-2 text-sm font-semibold text-slate-950">Create quiz</Link></div>{!filtered.length?<div className="mt-6 rounded-2xl border border-dashed border-slate-800 p-10 text-center"><p className="font-semibold">No quizzes yet</p><p className="mt-2 text-sm text-slate-500">Create your first quiz to start practicing.</p><Link href="/quizzes/new" className="mt-5 inline-block rounded-xl bg-white px-4 py-2 text-sm font-semibold text-slate-950">Create quiz</Link></div>:<div className="mt-6 grid gap-4 md:grid-cols-2">{filtered.map(q=>{let questions=[];try{questions=JSON.parse(q.questions_json||"[]")}catch{}return <article key={q.id} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-slate-500">{q.subject||"General"} · {q.topic||"Practice"}</p><h2 className="mt-1 text-xl font-bold">{q.title}</h2></div><span className="rounded-lg border border-slate-800 px-2.5 py-1 text-xs text-slate-500">{q.difficulty}</span></div><p className="mt-4 text-sm text-slate-400">{questions.length} questions</p><div className="mt-6 flex gap-2"><Link href={`/quizzes/${q.id}`} className="flex-1 rounded-xl bg-white px-4 py-3 text-center text-sm font-semibold text-slate-950">Start</Link><Link href={`/quizzes/${q.id}/edit`} className="rounded-xl border border-slate-700 px-4 py-3 text-sm font-semibold">Edit</Link><button onClick={()=>void remove(q.id)} className="rounded-xl border border-red-900/60 px-3 py-3 text-sm text-red-300">Delete</button></div></article>})}</div>}</div>;
}
