const KEY='mood-journal:v1';
const defaults={version:1,theme:'system',entries:[],goals:[],settings:{period:30}};
let state=load(); let view='today'; let query='';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const day=d=>new Date(d).toLocaleDateString('en-CA');
const today=()=>day(new Date());
const moodList=[['Great','5'],['Good','4'],['Okay','3'],['Low','2'],['Hard','1']];
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return {...defaults,...x,settings:{...defaults.settings,...(x?.settings||{})}}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));window.state=state;render()}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),1800)}
function entries(){return [...state.entries].sort((a,b)=>new Date(b.date)-new Date(a.date))}
function moodName(v){return moodList.find(x=>x[1]===String(v))?.[0]||'Okay'}
function moodIcon(v){return ({Great:'☺',Good:'◕',Okay:'•',Low:'◔',Hard:'○'})[moodName(v)]||'•'}
function rangeEntries(){const p=state.settings.period;if(p==='all')return entries();const cut=Date.now()-Number(p)*86400000;return entries().filter(e=>new Date(e.date).getTime()>=cut)}
function render(){document.body.classList.toggle('dark',state.theme==='dark'||(state.theme==='system'&&matchMedia('(prefers-color-scheme:dark)').matches));$('#dateLabel').textContent=new Intl.DateTimeFormat(undefined,{weekday:'long',month:'long',day:'numeric'}).format(new Date()).toUpperCase();const t=entries().find(e=>day(e.date)===today());$('#todayMood').textContent=t?moodIcon(t.mood):'—';$('#heroTitle').textContent=t?`Today feels ${moodName(t.mood).toLowerCase()}.`:'How are you feeling today?';renderView();renderStats()}
function filtered(){let es=rangeEntries();if(query){const q=query.toLowerCase();es=es.filter(e=>[e.note,e.moodName,e.emotions,e.factors,e.tags?.join(' ')].join(' ').toLowerCase().includes(q))}return es}
function renderView(){syncTabs();if(view==='calendar')return calendar();if(view==='insights')return window.renderInsights?.();const es=view==='today'?filtered().filter(e=>day(e.date)===today()):filtered();$('#view').innerHTML=es.length?es.map(card).join(''):`<div class="empty"><div class="empty-icon">◎</div><h3>${view==='today'?'No check-in yet':'No matching check-ins'}</h3><p>${view==='today'?'A quick mood check-in is enough. You can always add more detail later.':'Try another search or period.'}</p><button class="primary" id="emptyNew">+ Check in</button></div>`;$('#emptyNew')?.addEventListener('click',()=>openEntry());$$('[data-edit]').forEach(b=>b.onclick=()=>openEntry(b.dataset.edit));$$('[data-fav]').forEach(b=>b.onclick=()=>{const e=find(b.dataset.fav);e.favorite=!e.favorite;save()})}
function card(e){return `<article class="entry-card"><div class="entry-head"><div class="mood-dot mood-${e.mood}">${moodIcon(e.mood)}</div><div class="entry-main"><div class="entry-date">${new Date(e.date).toLocaleString([], {weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</div><h3>${esc(e.moodName||moodName(e.mood))} <span>${e.intensity}/10</span></h3><p>${esc(e.note||'No note — just a check-in.')}</p></div><div class="entry-actions"><button data-fav="${e.id}" title="Important">${e.favorite?'★':'☆'}</button><button data-edit="${e.id}">Edit</button></div></div><div class="metric-row"><span>Energy ${e.energy}/10</span><span>Stress ${e.stress}/10</span><span>Sleep ${e.sleep}/10</span>${e.factors?`<span>Factors: ${esc(e.factors)}</span>`:''}</div><div class="tag-row">${(e.emotions||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}${(e.tags||[]).map(x=>`<span class="tag">#${esc(x)}</span>`).join('')}</div></article>`}
function calendar(){const now=new Date();const y=window.calMonth?.getFullYear()??now.getFullYear(),m=window.calMonth?.getMonth()??now.getMonth();window.calMonth=new Date(y,m,1);const start=(new Date(y,m,1).getDay()+6)%7,last=new Date(y,m+1,0).getDate();let h=`<div class="calendar-wrap"><div class="cal-nav"><button id="calPrev">←</button><strong>${new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(window.calMonth)}</strong><button id="calNext">→</button></div><div class="cal-grid">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="cal-head">${x}</div>`).join('')}`;for(let i=0;i<42;i++){const n=i-start+1,d=new Date(y,m,n),k=day(d),es=state.entries.filter(e=>day(e.date)===k),avg=es.length?Math.round(es.reduce((a,e)=>a+Number(e.mood),0)/es.length):0;h+=`<button class="cal-day ${n<1||n>last?'muted':''} ${k===today()?'today':''} mood-bg-${avg}" data-day="${k}"><span>${d.getDate()}</span>${es.length?`<small>${es.length} · ${moodIcon(avg)}</small>`:''}</button>`}h+='</div></div>';$('#view').innerHTML=h;$('#calPrev').onclick=()=>{window.calMonth.setMonth(m-1);render()};$('#calNext').onclick=()=>{window.calMonth.setMonth(m+1);render()};$$('[data-day]').forEach(b=>b.onclick=()=>{const d=b.dataset.day;const es=state.entries.filter(e=>day(e.date)===d);if(es.length){view='timeline';query='';render()}else openEntry(null,d)})}
function renderStats(){const es=rangeEntries(),avg=es.length?(es.reduce((a,e)=>a+Number(e.mood),0)/es.length).toFixed(1):'—',best=es.length?Math.max(...es.map(e=>e.mood)):'—';$('#stats').innerHTML=`<div><b>${es.length}</b><small>check-ins</small></div><div><b>${avg}</b><small>average mood</small></div><div><b>${best==='—'?'—':moodName(best)}</b><small>best mood</small></div><div><b>${window.moodStreak?.()??streak()}</b><small>day streak</small></div>`}
function streak(){let n=0,d=new Date();while(state.entries.some(e=>day(e.date)===day(d))){n++;d.setDate(d.getDate()-1)}return n}
function find(id){return state.entries.find(e=>e.id===id)}
function localISO(d){const x=new Date(d),p=n=>String(n).padStart(2,'0');return `${x.getFullYear()}-${p(x.getMonth()+1)}-${p(x.getDate())}T${p(x.getHours())}:${p(x.getMinutes())}`}
function openEntry(id=null,date=null,preset=null){const e=id?find(id):null;$('#entryForm').reset();$('#entryId').value=e?.id||'';$('#modalTitle').textContent=e?'Edit check-in':'New check-in';$('#entryDate').value=localISO(e?.date||(date?new Date(date+'T12:00'):new Date()));buildMoods(e?.mood||preset?.mood||'3');setVal('intensity',e?.intensity||preset?.intensity||5);setVal('energy',e?.energy||preset?.energy||5);setVal('stress',e?.stress??preset?.stress??5);setVal('sleep',e?.sleep??preset?.sleep??5);$('#emotions').value=(e?.emotions||preset?.emotions||[]).join(', ');$('#note').value=e?.note||preset?.note||'';$('#factors').value=e?.factors||preset?.factors||'';$('#tags').value=(e?.tags||preset?.tags||[]).join(', ');$('#favorite').checked=!!e?.favorite;$('#deleteEntry').style.display=e?'block':'none';$('#entryDialog').showModal()}
function setVal(id,v){$('#'+id).value=v;$('#'+id+'Value').textContent=v+'/10'}
function buildMoods(selected){$('#moodPicker').innerHTML=moodList.map(([name,v])=>`<button type="button" class="mood-choice ${String(selected)===v?'selected':''}" data-mood="${v}"><span>${moodIcon(v)}</span><small>${name}</small></button>`).join('');$$('[data-mood]').forEach(b=>b.onclick=()=>{buildMoods(b.dataset.mood)})}
function formData(){const id=$('#entryId').value||uid(),e=find(id);const mood=document.querySelector('.mood-choice.selected')?.dataset.mood||e?.mood||'3';return {id,date:new Date($('#entryDate').value).toISOString(),mood,moodName:moodName(mood),intensity:+$('#intensity').value,energy:+$('#energy').value,stress:+$('#stress').value,sleep:+$('#sleep').value,emotions:$('#emotions').value.split(',').map(x=>x.trim()).filter(Boolean),note:$('#note').value.trim(),factors:$('#factors').value.trim(),tags:$('#tags').value.split(',').map(x=>x.trim()).filter(Boolean),favorite:$('#favorite').checked,createdAt:e?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()}}
$('#entryForm').onsubmit=e=>{e.preventDefault();const d=formData(),old=find(d.id);if(old)Object.assign(old,d);else state.entries.push(d);save();$('#entryDialog').close();toast(old?'Check-in updated':'Check-in saved')};$('#deleteEntry').onclick=()=>{const id=$('#entryId').value;if(id&&confirm('Delete this check-in?')){state.entries=state.entries.filter(e=>e.id!==id);save();$('#entryDialog').close();toast('Check-in deleted')}};
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#newBtn').onclick=()=>openEntry();$('#studioBtn').onclick=()=>window.openStudio?.();$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':state.theme==='light'?'system':'dark';save()};$('#search').oninput=e=>{query=e.target.value;renderView()};$('#period').value=state.settings.period;$('#period').onchange=e=>{state.settings.period=e.target.value;save()};$$('#tabs button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});['intensity','energy','stress','sleep'].forEach(id=>$('#'+id).oninput=e=>$('#'+id+'Value').textContent=e.target.value+'/10');$$('.quick').forEach(b=>b.onclick=()=>quick(b.dataset.quick));
function quick(type){const p={mood:{},reflection:{note:'What am I feeling right now?\n\nWhat might be influencing it?\n\nWhat do I need next?',emotions:['reflect']},gratitude:{note:'I am grateful for…',emotions:['grateful']},trigger:{note:'What was happening around this moment?',emotions:['notice']}}[type]||{};openEntry(null,null,p)}
function syncTabs(){$$('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
window.moodState={get:()=>state,save,render,openEntry,exportData:()=>exportJSON(),importData:importJSON};window.state=state;render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});