/* Mood Journal — deep feature layer
   Local-only enhancements: custom trackers, experiments, prompts, gratitude,
   reminders, check-in templates, wellness review, and attachment storage.
*/
const MJX='mood-journal:enhancements:v3';
let mjx=JSON.parse(localStorage.getItem(MJX)||'null')||{trackers:[],logs:{},experiments:[],prompts:[],gratitude:[],reminders:[],templates:[],intentions:[],settings:{compact:false}};
const X$=s=>document.querySelector(s),X$$=s=>[...document.querySelectorAll(s)];
function xsave(){localStorage.setItem(MJX,JSON.stringify(mjx));}
function xtoast(t){window.toast?.(t);}
function xdownload(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function xesc(s){return String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function xday(d){return new Date(d).toLocaleDateString('en-CA')}
function xentries(){return window.moodState.get().entries||[]}
function xavg(es){return es.length?es.reduce((a,e)=>a+Number(e.mood),0)/es.length:0}
function xmonthDays(n=30){const out=[];for(let i=n-1;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);out.push(xday(d))}return out}

function openEnhancementStudio(){
  const dlg=X$('#studioDialog');if(!dlg?.open)dlg?.showModal();
  let tab=X$('.studio-tabs [data-studio="wellness"]');
  if(!tab){const nav=X$('.studio-tabs');tab=document.createElement('button');tab.dataset.studio='wellness';tab.textContent='Wellness';nav?.appendChild(tab);tab.onclick=()=>renderXStudio('wellness')}
  renderXStudio('wellness');
}
function renderXStudio(tab='wellness'){
  const host=X$('#studioContent');if(!host)return;
  X$$('.studio-tabs [data-studio]').forEach(b=>b.classList.toggle('active',b.dataset.studio===tab));
  const e=xentries();
  if(tab==='wellness')host.innerHTML=`<div class="panel"><div class="panel-head"><h3>Wellness workspace</h3><span>local-only</span></div><div class="studio-grid"><div class="studio-card"><span>Tracked factors</span><b>${mjx.trackers.length}</b></div><div class="studio-card"><span>Experiments</span><b>${mjx.experiments.length}</b></div><div class="studio-card"><span>Reflections</span><b>${(window.moodState.get().entries||[]).filter(x=>x.note).length}</b></div><div class="studio-card"><span>Custom logs</span><b>${Object.values(mjx.logs).flat().length}</b></div></div><p class="muted">Add the context you care about, compare it with mood, and keep the conclusions modest: these are personal associations, not medical diagnoses.</p><div class="data-buttons"><button class="secondary" data-x="tracker">+ Custom tracker</button><button class="secondary" data-x="experiment">+ Experiment</button><button class="secondary" data-x="prompt">+ Prompt</button><button class="secondary" data-x="template">+ Check-in template</button></div></div><div class="panel"><div class="panel-head"><h3>Custom trackers</h3><span>sleep, focus, hydration, etc.</span></div>${trackerHTML()}</div><div class="panel"><div class="panel-head"><h3>Personal experiments</h3><span>compare periods</span></div>${experimentHTML()}</div><div class="panel"><div class="panel-head"><h3>Prompts & templates</h3><span>${mjx.prompts.length} prompts · ${mjx.templates.length} templates</span></div>${promptHTML()}${templateHTML()}</div>`;
  if(tab==='goals'){};
  bindX();
}
function trackerHTML(){if(!mjx.trackers.length)return '<p class="muted">No custom trackers yet.</p>';return mjx.trackers.map(t=>{const logs=(mjx.logs[t.id]||[]);const last=logs.at(-1);return `<div class="factor"><div><b>${xesc(t.name)}</b><small>${xesc(t.type)} · ${logs.length} logs${last?' · last '+xesc(last.value):''}</small></div><button class="secondary" data-log-tracker="${t.id}">Log</button><button class="danger" data-del-tracker="${t.id}">×</button></div>`}).join('')}
function experimentHTML(){if(!mjx.experiments.length)return '<p class="muted">Create an experiment to compare a factor against your logged mood over time.</p>';return mjx.experiments.map(x=>{const es=e=xentries().filter(z=>new Date(z.date)>=new Date(x.start));const yes=es.filter(z=>(z.factors||'').toLowerCase().split(',').map(s=>s.trim()).includes(x.factor.toLowerCase()));const no=es.filter(z=>!((z.factors||'').toLowerCase().split(',').map(s=>s.trim()).includes(x.factor.toLowerCase())));const delta=yes.length&&no.length?(xavg(yes)-xavg(no)).toFixed(2):'—';return `<div class="factor"><div><b>${xesc(x.name)}</b><small>${xesc(x.factor)} · ${yes.length} with / ${no.length} without</small></div><strong>${delta==='—'?'—':(delta>0?'+':'')+delta}</strong><button class="danger" data-del-exp="${x.id}">×</button></div>`}).join('')}
function promptHTML(){if(!mjx.prompts.length)return '<p class="muted">Add prompts you actually like. Built-in quick reflections remain available.</p>';return `<div class="tag-row">${mjx.prompts.map((p,i)=>`<button class="tag" data-use-prompt="${i}">${xesc(p)}</button>`).join('')}</div>`}
function templateHTML(){if(!mjx.templates.length)return '';return `<div class="tag-row">${mjx.templates.map((t,i)=>`<button class="tag" data-use-template="${i}">${xesc(t.name)}</button>`).join('')}</div>`}
function bindX(){X$$('[data-x]').forEach(b=>b.onclick=()=>{if(b.dataset.x==='tracker')newTracker();if(b.dataset.x==='experiment')newExperiment();if(b.dataset.x==='prompt')newPrompt();if(b.dataset.x==='template')newTemplate()});X$$('[data-log-tracker]').forEach(b=>b.onclick=()=>logTracker(b.dataset.logTracker));X$$('[data-del-tracker]').forEach(b=>b.onclick=()=>{mjx.trackers=mjx.trackers.filter(t=>t.id!==b.dataset.delTracker);xsave();renderXStudio()});X$$('[data-del-exp]').forEach(b=>b.onclick=()=>{mjx.experiments=mjx.experiments.filter(t=>t.id!==b.dataset.delExp);xsave();renderXStudio()});X$$('[data-use-prompt]').forEach(b=>b.onclick=()=>{const p=mjx.prompts[+b.dataset.usePrompt];window.moodState.openEntry(null,null,{note:p})});X$$('[data-use-template]').forEach(b=>b.onclick=()=>{const t=mjx.templates[+b.dataset.useTemplate];window.moodState.openEntry(null,null,t.preset||{})})}
function newTracker(){const name=prompt('Tracker name','Focus');if(!name)return;const type=prompt('Type: number, yes/no, or rating','rating')||'rating';mjx.trackers.push({id:crypto.randomUUID(),name,type,createdAt:new Date().toISOString()});xsave();renderXStudio();xtoast('Tracker added')}
function logTracker(id){const t=mjx.trackers.find(x=>x.id===id);if(!t)return;let v=prompt(`Log ${t.name}`,t.type==='yes/no'?'yes':'5');if(v===null)return;if(t.type==='number'||t.type==='rating'){const n=Number(v);if(!Number.isFinite(n))return xtoast('Enter a number')} (mjx.logs[id]??=[]).push({date:new Date().toISOString(),value:v});xsave();renderXStudio();xtoast('Tracker logged')}
function newExperiment(){const name=prompt('Experiment name','Earlier bedtime');if(!name)return;const factor=prompt('Factor to compare','sleep');if(!factor)return;const start=prompt('Start date (YYYY-MM-DD)',xday(new Date()));if(!start)return;mjx.experiments.push({id:crypto.randomUUID(),name,factor,start});xsave();renderXStudio();xtoast('Experiment created')}
function newPrompt(){const p=prompt('Write your reflection prompt');if(!p)return;mjx.prompts.push(p);xsave();renderXStudio();xtoast('Prompt saved')}
function newTemplate(){const name=prompt('Template name','Evening check-in');if(!name)return;const note=prompt('Starter note','What stood out today?')||'';const mood=prompt('Starting mood 1–5','3')||'3';mjx.templates.push({id:crypto.randomUUID(),name,preset:{note,mood,intensity:5,energy:5,stress:5,sleep:5}});xsave();renderXStudio();xtoast('Template saved')}

function addQuickWellness(){
  const row=document.createElement('div');row.className='wellness-strip';row.innerHTML=`<button class="quick" data-wx="gratitude"><b>♡</b><span>Gratitude</span><small>one good thing</small></button><button class="quick" data-wx="intention"><b>→</b><span>Intention</span><small>set today's focus</small></button><button class="quick" data-wx="coping"><b>✦</b><span>Coping note</span><small>what helped</small></button>`;X$('.quick-grid')?.after(row);X$$('[data-wx]').forEach(b=>b.onclick=()=>quickWellness(b.dataset.wx));
}
function quickWellness(type){const prompts={gratitude:'I am grateful for…',intention:'Today I want to pay attention to…',coping:'Something that helped me today was…'};const text=prompt(prompts[type]);if(!text)return;const now=new Date().toISOString();if(type==='gratitude')mjx.gratitude.push({date:now,text});if(type==='intention')mjx.intentions.push({date:xday(now),text});if(type==='coping')mjx.logs.coping=(mjx.logs.coping||[]).concat({date:now,value:text});xsave();xtoast(type[0].toUpperCase()+type.slice(1)+' saved')}

function reminderSetup(){const time=prompt('Reminder time (HH:MM)','20:00');if(!time||!/^[0-2]\d:[0-5]\d$/.test(time))return xtoast('Use HH:MM');mjx.reminders=[{time,enabled:true}];xsave();if('Notification'in window&&Notification.permission==='default')Notification.requestPermission();xtoast('Daily reminder preference saved')}
function checkReminder(){const r=mjx.reminders.find(x=>x.enabled);if(!r)return;const now=new Date(),hh=String(now.getHours()).padStart(2,'0'),mm=String(now.getMinutes()).padStart(2,'0');const stamp=xday(now)+' '+hh+mm;if(hh+':'+mm===r.time&&localStorage.getItem('mood-journal:last-reminder')!==stamp){localStorage.setItem('mood-journal:last-reminder',stamp);if(Notification.permission==='granted')new Notification('Mood Journal',{body:'Take a gentle moment to check in.'});}}
function renderWellnessSummary(){const s=window.moodState.get();const host=document.createElement('div');host.className='panel wellness-summary';const recent=s.entries.filter(e=>new Date(e.date)>=new Date(Date.now()-7*864e5));const avg7=xavg(recent);host.innerHTML=`<div class="panel-head"><h3>7-day reflection</h3><span>${recent.length} check-ins</span></div><p>${recent.length?`Your logged mood averaged ${avg7.toFixed(1)}/5 this week. Notice what was present on your easier and harder days.`:'A few small check-ins can make the trend more useful.'}</p><div class="data-buttons"><button class="secondary" id="setReminder">Daily reminder</button><button class="secondary" id="manageWellness">Wellness Studio</button></div>`;X$('#stats')?.after(host);X$('#setReminder').onclick=reminderSetup;X$('#manageWellness').onclick=openEnhancementStudio}

addQuickWellness();renderWellnessSummary();
const oldOpen=window.openStudio;window.openStudio=()=>{oldOpen?.();setTimeout(()=>{let nav=X$('.studio-tabs');if(nav&&!nav.querySelector('[data-studio="wellness"]')){const b=document.createElement('button');b.dataset.studio='wellness';b.textContent='Wellness';nav.appendChild(b);b.onclick=()=>renderXStudio('wellness')}},0)};
setInterval(checkReminder,30000);
