(()=>{
'use strict';
const KEY='activity-logger:v5';
const CATS=['Work','Study','Exercise','Personal','Creative','Social','Chores','Errand','Other'];
const $=id=>document.getElementById(id), today=()=>new Date().toISOString().slice(0,10), uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2), pad=n=>String(n).padStart(2,'0');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtMin=n=>{n=Math.max(0,Math.round(Number(n)||0));return n>=60?`${Math.floor(n/60)}h ${n%60?`${n%60}m`:''}`.trim():`${n}m`};
const fmtDate=d=>new Date(`${d}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});
const shift=(d,n)=>{const x=new Date(`${d}T12:00:00`);x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
const monthKey=d=>d.slice(0,7);
let state={entries:[],goals:[],view:'today',selectedDate:today(),range:7,query:'',category:'all',status:'active',calendarMonth:monthKey(today()),timer:null,settings:{defaultCategory:'Work',confirmArchive:true,notifications:false,weekStartsMonday:true}};
try{const old=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('activity-logger:v4')||'null');if(old)state={...state,...old,settings:{...state.settings,...(old.settings||{})}}}catch{}
function save(){localStorage.setItem(KEY,JSON.stringify({entries:state.entries,goals:state.goals,view:state.view,selectedDate:state.selectedDate,range:state.range,settings:state.settings}))}
function toast(t){const x=$('toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),2400)}
function notify(t,b){if(state.settings.notifications&&'Notification'in window&&Notification.permission==='granted')new Notification(t,{body:b})}
function minutes(e){return Math.max(0,Number(e.duration)||0)}
function activeOn(d){return state.entries.filter(e=>!e.archived&&!e.deleted&&e.date===d)}
function total(d=state.selectedDate,cat='all'){return activeOn(d).filter(e=>cat==='all'||e.category===cat).reduce((a,e)=>a+minutes(e),0)}
function dates(n=state.range){return Array.from({length:n},(_,i)=>shift(state.selectedDate,-(n-1-i)))}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function startOfMonth(m){return new Date(`${m}-01T12:00:00`)}
function iso(x){return x.toISOString().slice(0,10)}
function daysInMonth(m){const x=startOfMonth(m);x.setMonth(x.getMonth()+1);x.setDate(0);return x.getDate()}
function monthCells(m){const first=startOfMonth(m),offset=(first.getDay()+(state.settings.weekStartsMonday?6:0))%7;const n=daysInMonth(m);const out=[];for(let i=0;i<offset;i++)out.push(null);for(let d=1;d<=n;d++)out.push(`${m}-${pad(d)}`);while(out.length%7)out.push(null);return out}
function openEntry(id=null,defaults={}){const e=id?state.entries.find(x=>x.id===id):null;$('entryTitle').textContent=e?'Edit activity':'Log activity';$('entryId').value=e?.id||'';$('activity').value=e?.activity||defaults.activity||'';$('category').value=e?.category||defaults.category||state.settings.defaultCategory;$('date').value=e?.date||defaults.date||state.selectedDate;$('start').value=e?.start||defaults.start||new Date().toTimeString().slice(0,5);$('end').value=e?.end||defaults.end||'';$('duration').value=e?.duration??defaults.duration??30;$('context').value=e?.context||defaults.context||'';$('tags').value=(e?.tags||defaults.tags||[]).join(', ');$('notes').value=e?.notes||defaults.notes||'';$('favorite').checked=!!(e?.favorite||defaults.favorite);$('entryDialog').showModal();setTimeout(()=>$('activity').focus(),40)}
function saveEntry(ev){ev.preventDefault();const id=$('entryId').value,old=id&&state.entries.find(e=>e.id===id);const e=old||{id:uid(),createdAt:new Date().toISOString()};Object.assign(e,{activity:$('activity').value.trim(),category:$('category').value,date:$('date').value,start:$('start').value,end:$('end').value,duration:Math.max(1,Math.min(1440,Number($('duration').value)||1)),context:$('context').value.trim(),tags:$('tags').value.split(',').map(x=>x.trim()).filter(Boolean),notes:$('notes').value.trim(),favorite:$('favorite').checked,archived:false,deleted:false,updatedAt:new Date().toISOString()});if(!old)state.entries.unshift(e);save();$('entryDialog').close();render();toast(old?'Activity updated':'Activity logged');checkGoals(e.date,e.category)}
function archive(id){const e=state.entries.find(x=>x.id===id);if(!e)return;if(state.settings.confirmArchive&&!confirm('Archive this activity?'))return;e.archived=true;e.updatedAt=new Date().toISOString();save();render();toast('Activity archived — restore it from Archived')}
function restore(id){const e=state.entries.find(x=>x.id===id);if(e){e.archived=false;e.deleted=false;e.updatedAt=new Date().toISOString();save();render();toast('Activity restored')}}
function removeForever(id){if(!confirm('Permanently delete this activity? This cannot be undone.'))return;state.entries=state.entries.filter(e=>e.id!==id);save();render();toast('Activity permanently deleted')}
function toggleFavorite(id){const e=state.entries.find(x=>x.id===id);if(e){e.favorite=!e.favorite;save();render();toast(e.favorite?'Added to favorites':'Removed from favorites')}}
function timerSeconds(){if(!state.timer)return 0;return Math.max(0,Math.floor(((state.timer.accumulatedMs||0)+(state.timer.running?Date.now()-(state.timer.startedAt||Date.now()):0))/1000))}
function timerStart(){if(state.timer?.running)return;state.timer=state.timer||{activity:$('timerActivity')?.value||'',category:$('timerCategory')?.value||state.settings.defaultCategory,accumulatedMs:0};state.timer.activity=state.timer.activity||$('timerActivity')?.value||'Tracked activity';state.timer.category=state.timer.category||$('timerCategory')?.value||state.settings.defaultCategory;state.timer.running=true;state.timer.startedAt=Date.now();save();render()}
function timerPause(){if(!state.timer?.running)return;state.timer.accumulatedMs=(state.timer.accumulatedMs||0)+(Date.now()-state.timer.startedAt);state.timer.startedAt=null;state.timer.running=false;save();render();toast('Timer paused')}
function timerReset(){if(!state.timer)return;state.timer=null;save();render();toast('Timer reset')}
function timerStop(){if(!state.timer)return;const t={...state.timer},sec=timerSeconds();state.timer=null;save();openEntry(null,{activity:t.activity||'Tracked activity',category:t.category||state.settings.defaultCategory,date:today(),start:t.startedAt?new Date(t.startedAt).toTimeString().slice(0,5):new Date().toTimeString().slice(0,5),duration:Math.max(1,Math.round(sec/60))});toast('Timer stopped — review and save the entry')}
function timerCard(){const s=timerSeconds(),h=pad(Math.floor(s/3600)),m=pad(Math.floor(s/60)%60),sec=pad(s%60);return `<section class="timer-card"><div><span class="eyebrow">LIVE TIMER</span><div class="timer-clock">${h}:${m}:${sec}</div><div class="timer-fields"><input id="timerActivity" value="${esc(state.timer?.activity||'')}" placeholder="What are you doing?" ${state.timer?.running?'disabled':''}><select id="timerCategory" ${state.timer?.running?'disabled':''}>${CATS.map(c=>`<option ${c===(state.timer?.category||state.settings.defaultCategory)?'selected':''}>${c}</option>`).join('')}</select></div></div><div class="timer-actions">${state.timer?.running?`<button class="btn" id="pauseTimer">Pause</button><button class="btn primary" id="stopTimer">Stop & log</button>`:state.timer?`<button class="btn primary" id="resumeTimer">Resume</button><button class="btn" id="stopTimer">Stop & log</button><button class="btn" id="resetTimer">Reset</button>`:`<button class="btn primary" id="startTimer">Start timer</button>`}<button class="btn" id="manualTimer">Manual entry</button></div></section>`}
function activityList(items,archiveMode=false){if(!items.length)return `<div class="empty"><strong>${archiveMode?'Archive is empty.':'No activity logged.'}</strong><span>${archiveMode?'Archived records will appear here.':'Start a timer or log a manual activity to build your history.'}</span>${!archiveMode?'<button class="btn primary" id="emptyAdd">Log your first activity</button>':''}</div>`;return `<div class="entry-list">${items.map(e=>`<article class="entry"><div class="entry-time"><strong>${esc(e.start||'—')}</strong><span>${fmtMin(e.duration)}</span></div><div class="entry-main"><div class="entry-title"><strong>${esc(e.activity||'Untitled')}</strong>${e.favorite?'<span class="pill">★ Favorite</span>':''}<span class="pill">${esc(e.category)}</span></div><div class="entry-meta">${e.end?`${esc(e.start)}–${esc(e.end)} · `:''}${esc(e.context||'')}${e.tags?.length?` · ${e.tags.map(esc).join(' · ')}`:''}</div>${e.notes?`<p>${esc(e.notes)}</p>`:''}</div><div class="entry-actions">${archiveMode?`<button class="icon-btn" data-restore="${e.id}" title="Restore">↶</button><button class="icon-btn danger" data-delete="${e.id}" title="Delete permanently">×</button>`:`<button class="icon-btn" data-fav="${e.id}" title="Favorite">${e.favorite?'★':'☆'}</button><button class="icon-btn" data-edit="${e.id}" title="Edit">✎</button><button class="icon-btn danger" data-archive="${e.id}" title="Archive">×</button>`}</div></article>`).join('')}</div>`}
function quickStarts(){const fav=state.entries.filter(e=>!e.archived&&!e.deleted&&e.favorite).slice(0,6);if(!fav.length)return '';const seen=new Set(),list=fav.filter(e=>{const k=`${e.activity}|${e.category}`;if(seen.has(k))return false;seen.add(k);return true});return `<section class="panel"><div class="section-head"><div><h3>Quick starts</h3><p>Reuse your favorite activity labels without retyping.</p></div></div><div class="quick-grid">${list.map(e=>`<button class="quick" data-quick="${e.id}"><strong>${esc(e.activity)}</strong><span>${esc(e.category)}</span></button>`).join('')}</div></section>`}
function todayView(){const d=state.selectedDate,items=activeOn(d),t=total(d),goalRows=state.goals.filter(g=>g.active!==false).map(g=>{const n=total(d,g.category||'all'),p=Math.min(100,n/g.minutes*100);return `<div class="goal-mini"><div><strong>${esc(g.name)}</strong><span>${fmtMin(n)} / ${fmtMin(g.minutes)}</span></div><div class="progress"><i style="width:${p}%"></i></div></div>`}).join('');const cats={};items.forEach(e=>cats[e.category]=(cats[e.category]||0)+minutes(e));const top=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';return `<div class="hero-row"><div><span class="eyebrow">${d===today()?'TODAY':'SELECTED DAY'}</span><h2>${fmtDate(d)}</h2><p>${fmtMin(t)} tracked across ${items.length} activities.</p></div><div class="date-nav"><button class="icon-btn" id="prevDay">←</button><button class="btn" id="todayBtn">Today</button><button class="icon-btn" id="nextDay">→</button></div></div>${timerCard()}<div class="metric-grid"><div class="metric"><span>Total tracked</span><strong>${fmtMin(t)}</strong></div><div class="metric"><span>Activities</span><strong>${items.length}</strong></div><div class="metric"><span>Top category</span><strong>${top}</strong></div><div class="metric"><span>Longest session</span><strong>${fmtMin(Math.max(0,...items.map(minutes),0))}</strong></div></div>${quickStarts()}${goalRows?`<section class="panel"><div class="section-head"><div><h3>Daily goals</h3><p>Progress for ${fmtDate(d)}.</p></div><button class="btn" id="goalsLink">Manage goals</button></div>${goalRows}</section>`:''}<section class="panel"><div class="section-head"><div><h3>Activity</h3><p>Detailed records for the selected day.</p></div><button class="btn primary" id="newEntry">+ Log activity</button></div>${activityList(items)}</section>`}
function calendar(){const m=state.calendarMonth,cells=monthCells(m),names=state.settings.weekStartsMonday?['Mon','Tue','Wed','Thu','Fri','Sat','Sun']:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];return `<div class="page-head"><div><span class="eyebrow">CALENDAR</span><h2>${startOfMonth(m).toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><p>See activity density by day and jump directly into a date.</p></div><div class="filters"><button class="btn" id="prevMonth">←</button><button class="btn" id="calendarToday">Today</button><button class="btn" id="nextMonth">→</button></div></div><section class="panel calendar-panel"><div class="calendar-head">${names.map(n=>`<span>${n}</span>`).join('')}</div><div class="calendar-grid">${cells.map(d=>{if(!d)return '<div class="calendar-cell blank"></div>';const n=total(d),count=activeOn(d).length,sel=d===state.selectedDate;return `<button class="calendar-cell ${sel?'selected':''}" data-day="${d}"><span>${Number(d.slice(-2))}</span><strong>${n?fmtMin(n):'—'}</strong><small>${count?`${count} ${count===1?'entry':'entries'}`:' '}</small></button>`}).join('')}</div></section>`}
function timeline(){const ds=dates(Number(state.range)).reverse();return `<div class="page-head"><div><span class="eyebrow">TIMELINE</span><h2>Chronological history</h2><p>Review the last ${state.range} days around the selected date.</p></div><div class="filters"><select id="range"><option value="7" ${state.range==7?'selected':''}>7 days</option><option value="14" ${state.range==14?'selected':''}>14 days</option><option value="30" ${state.range==30?'selected':''}>30 days</option></select><button class="btn primary" id="timelineAdd">+ Log activity</button></div></div><div class="timeline">${ds.map(d=>`<section class="timeline-day"><div class="timeline-date"><strong>${fmtDate(d)}</strong><span>${fmtMin(total(d))}</span></div>${activityList(activeOn(d))}</section>`).join('')}</div>`}
function reports(){const ds=dates(Number(state.range)),items=state.entries.filter(e=>!e.archived&&!e.deleted&&ds.includes(e.date)),tm=items.reduce((a,e)=>a+minutes(e),0),cats={};items.forEach(e=>cats[e.category]=(cats[e.category]||0)+minutes(e));const max=Math.max(1,...ds.map(d=>total(d)));const active=ds.filter(d=>total(d)>0).length;const avg=tm/Math.max(1,active);const peak=Object.entries(Array.from({length:24},(_,h)=>[h,items.filter(e=>Number((e.start||'00:00').split(':')[0])===h).reduce((a,e)=>a+minutes(e),0)])).sort((a,b)=>b[1][1]-a[1][1])[0];return `<div class="page-head"><div><span class="eyebrow">REPORTS</span><h2>Time insights</h2><p>${state.range}-day analysis ending ${fmtDate(state.selectedDate)}.</p></div><div class="filters"><select id="reportRange"><option value="7" ${state.range==7?'selected':''}>7 days</option><option value="14" ${state.range==14?'selected':''}>14 days</option><option value="30" ${state.range==30?'selected':''}>30 days</option></select><button class="btn" id="exportCsv">Export CSV</button></div></div><div class="metric-grid"><div class="metric"><span>Tracked time</span><strong>${fmtMin(tm)}</strong></div><div class="metric"><span>Average active day</span><strong>${fmtMin(avg)}</strong></div><div class="metric"><span>Active days</span><strong>${active}/${ds.length}</strong></div><div class="metric"><span>Peak hour</span><strong>${peak&&peak[1]?`${pad(peak[0])}:00`:'—'}</strong></div></div><div class="report-grid"><section class="panel"><h3>Daily volume</h3><div class="bars">${ds.map(d=>`<div class="bar-item"><span>${new Date(`${d}T12:00:00`).toLocaleDateString(undefined,{weekday:'short'})}</span><i><b style="height:${Math.max(3,total(d)/max*100)}%"></b></i><strong>${fmtMin(total(d))}</strong></div>`).join('')}</div></section><section class="panel"><h3>Time by category</h3><div class="category-bars">${Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([c,n])=>`<div><div class="cat-label"><span>${esc(c)}</span><strong>${fmtMin(n)}</strong></div><div class="progress"><i style="width:${tm?Math.min(100,n/tm*100):0}%"></i></div></div>`).join('')||'<div class="empty">No data in this range.</div>'}</div></section></div><section class="panel"><h3>Hourly rhythm</h3><div class="hour-grid">${Array.from({length:24},(_,h)=>{const n=items.filter(e=>Number((e.start||'00:00').split(':')[0])===h).reduce((a,e)=>a+minutes(e),0);return `<div title="${h}:00 · ${fmtMin(n)}"><span>${h}</span><i style="height:${Math.min(100,Math.max(4,n/Math.max(1,tm/8)*100))}%"></i></div>`}).join('')}</div></section>`}
function goals(){return `<div class="page-head"><div><span class="eyebrow">GOALS</span><h2>Daily time targets</h2><p>Set total or category-specific targets and see progress for the selected day.</p></div><button class="btn primary" id="newGoal">+ New goal</button></div><div class="goal-grid">${state.goals.map(g=>{const n=total(state.selectedDate,g.category||'all'),p=Math.min(100,n/g.minutes*100);return `<article class="goal-card"><div class="goal-card-head"><div><h3>${esc(g.name)}</h3><span>${g.category==='all'?'All activities':esc(g.category)}</span></div><button class="icon-btn danger" data-goal-delete="${g.id}">×</button></div><div class="goal-number"><strong>${fmtMin(n)}</strong><span>of ${fmtMin(g.minutes)}</span></div><div class="progress large"><i style="width:${p}%"></i></div><p>${p>=100?'Goal reached':`${Math.round(p)}% complete`} · ${fmtMin(Math.max(0,g.minutes-n))} remaining</p></article>`}).join('')||'<div class="empty"><strong>No goals yet.</strong><span>Create a daily target for focused work, study, exercise, or total activity.</span><button class="btn primary" id="emptyGoal">Create goal</button></div>'}</div>`}
function activities(){let items=state.entries.filter(e=>state.status==='archived'?e.archived:!e.archived&&!e.deleted);if(state.query)items=items.filter(e=>JSON.stringify(e).toLowerCase().includes(state.query.toLowerCase()));if(state.category!=='all')items=items.filter(e=>e.category===state.category);items.sort((a,b)=>`${b.date}${b.start}`.localeCompare(`${a.date}${a.start}`));return `<div class="page-head"><div><span class="eyebrow">ACTIVITY LIBRARY</span><h2>${state.status==='archived'?'Archived activities':'All activities'}</h2><p>Search, filter, favorite, edit, archive, restore and permanently remove records.</p></div><button class="btn primary" id="libraryAdd">+ Log activity</button></div><section class="panel"><div class="search-row"><input id="activitySearch" value="${esc(state.query)}" placeholder="Search activities, notes, context and tags…"><select id="activityCategory"><option value="all">All categories</option>${CATS.map(c=>`<option ${state.category===c?'selected':''}>${c}</option>`).join('')}</select><select id="activityStatus"><option value="active" ${state.status==='active'?'selected':''}>Active</option><option value="archived" ${state.status==='archived'?'selected':''}>Archived</option></select><span class="result-count">${items.length} results</span></div>${activityList(items,state.status==='archived')}</section>`}
function checkGoals(d,cat){for(const g of state.goals){if(g.active===false)continue;const n=total(d,g.category||'all');if(n>=g.minutes&&!g.lastNotified||g.lastNotified!==d){g.lastNotified=d;notify('Activity goal reached',`${g.name}: ${fmtMin(n)} tracked today.`)}}save()}
function goalDialog(){ $('goalName').value='';$('goalCategory').value='all';$('goalMinutes').value=60;$('goalDialog').showModal() }
function render(){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===state.view));let html=state.view==='today'?todayView():state.view==='calendar'?calendar():state.view==='timeline'?timeline():state.view==='reports'?reports():state.view==='goals'?goals():activities();$('main').innerHTML=html;bind();if(state.timer?.running){clearTimeout(render.tick);render.tick=setTimeout(render,1000)}}
function bind(){
$('prevDay')?.addEventListener('click',()=>{state.selectedDate=shift(state.selectedDate,-1);save();render()});$('nextDay')?.addEventListener('click',()=>{state.selectedDate=shift(state.selectedDate,1);save();render()});$('todayBtn')?.addEventListener('click',()=>{state.selectedDate=today();save();render()});
$('startTimer')?.addEventListener('click',()=>{state.timer={running:false,activity:$('timerActivity').value.trim()||'Tracked activity',category:$('timerCategory').value,accumulatedMs:0};timerStart()});$('resumeTimer')?.addEventListener('click',timerStart);$('pauseTimer')?.addEventListener('click',timerPause);$('stopTimer')?.addEventListener('click',timerStop);$('resetTimer')?.addEventListener('click',timerReset);$('manualTimer')?.addEventListener('click',()=>openEntry());
$('newEntry')?.addEventListener('click',()=>openEntry());$('emptyAdd')?.addEventListener('click',()=>openEntry());$('timelineAdd')?.addEventListener('click',()=>openEntry());$('libraryAdd')?.addEventListener('click',()=>openEntry());$('goalsLink')?.addEventListener('click',()=>{state.view='goals';render()});$('emptyGoal')?.addEventListener('click',goalDialog);$('newGoal')?.addEventListener('click',goalDialog);
$('range')?.addEventListener('change',e=>{state.range=Number(e.target.value);render()});$('reportRange')?.addEventListener('change',e=>{state.range=Number(e.target.value);render()});
$('activitySearch')?.addEventListener('input',e=>{state.query=e.target.value;render()});$('activityCategory')?.addEventListener('change',e=>{state.category=e.target.value;render()});$('activityStatus')?.addEventListener('change',e=>{state.status=e.target.value;render()});
$('prevMonth')?.addEventListener('click',()=>{const d=startOfMonth(state.calendarMonth);d.setMonth(d.getMonth()-1);state.calendarMonth=monthKey(iso(d));render()});$('nextMonth')?.addEventListener('click',()=>{const d=startOfMonth(state.calendarMonth);d.setMonth(d.getMonth()+1);state.calendarMonth=monthKey(iso(d));render()});$('calendarToday')?.addEventListener('click',()=>{state.calendarMonth=monthKey(today());state.selectedDate=today();render()});document.querySelectorAll('[data-day]').forEach(b=>b.addEventListener('click',()=>{state.selectedDate=b.dataset.day;state.calendarMonth=monthKey(b.dataset.day);state.view='today';save();render()}));
$('exportCsv')?.addEventListener('click',()=>{const rows=[['date','start','end','duration_minutes','activity','category','context','tags','notes','favorite','archived'],...state.entries.map(e=>[e.date,e.start,e.end,e.duration,e.activity,e.category,e.context,(e.tags||[]).join('|'),e.notes,e.favorite?'yes':'no',e.archived?'yes':'no'])];download(`activity-log-${today()}.csv`,rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n'),'text/csv')});
$('exportBtn')?.addEventListener('click',()=>download(`activity-logger-backup-${today()}.json`,JSON.stringify({schema:5,exportedAt:new Date().toISOString(),entries:state.entries,goals:state.goals,settings:state.settings},null,2),'application/json'));
}
document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit]');if(edit)openEntry(edit.dataset.edit);const arch=e.target.closest('[data-archive]');if(arch)archive(arch.dataset.archive);const fav=e.target.closest('[data-fav]');if(fav)toggleFavorite(fav.dataset.fav);const restoreBtn=e.target.closest('[data-restore]');if(restoreBtn)restore(restoreBtn.dataset.restore);const del=e.target.closest('[data-delete]');if(del)removeForever(del.dataset.delete);const quick=e.target.closest('[data-quick]');if(quick){const x=state.entries.find(a=>a.id===quick.dataset.quick);if(x)openEntry(null,{activity:x.activity,category:x.category,context:x.context,tags:x.tags,favorite:true,duration:x.duration})}const gd=e.target.closest('[data-goal-delete]');if(gd&&confirm('Delete this goal?')){state.goals=state.goals.filter(g=>g.id!==gd.dataset.goalDelete);save();render();toast('Goal deleted')}});
document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{state.view=t.dataset.view;save();render()}));
$('entryForm').addEventListener('submit',saveEntry);$('goalForm').addEventListener('submit',e=>{e.preventDefault();const g={id:uid(),name:$('goalName').value.trim(),category:$('goalCategory').value,minutes:Math.max(1,Math.min(1440,Number($('goalMinutes').value)||60)),active:true};state.goals.push(g);save();$('goalDialog').close();render();toast('Goal created')});
$('themeBtn').addEventListener('click',()=>{document.documentElement.classList.toggle('dark');localStorage.setItem('activity-logger:theme',document.documentElement.classList.contains('dark')?'dark':'light')});$('settingsBtn').addEventListener('click',()=>{ $('defaultCategory').value=state.settings.defaultCategory;$('confirmArchive').checked=state.settings.confirmArchive;$('notifications').checked=state.settings.notifications;$('storageInfo').textContent=`${new Blob([localStorage.getItem(KEY)||'']).size.toLocaleString()} bytes used`; $('settingsDialog').showModal()});$('settingsForm').addEventListener('submit',e=>{e.preventDefault();state.settings.defaultCategory=$('defaultCategory').value;state.settings.confirmArchive=$('confirmArchive').checked;state.settings.notifications=$('notifications').checked;save();$('settingsDialog').close();toast('Settings saved');render()});$('clearDataBtn').addEventListener('click',()=>{if(confirm('Delete all Activity Logger data from this browser?')){localStorage.removeItem(KEY);localStorage.removeItem('activity-logger:v4');localStorage.removeItem('activity-logger:theme');location.reload()}});$('importInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!Array.isArray(x.entries))throw Error('Invalid backup');if(!confirm('Replace current Activity Logger data with this backup?'))return;state.entries=x.entries;state.goals=Array.isArray(x.goals)?x.goals:[];state.settings={...state.settings,...(x.settings||{})};save();render();toast('Backup imported')}catch{alert('Could not import this file. Choose an Activity Logger JSON backup.')}e.target.value='' });
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(localStorage.getItem('activity-logger:theme')==='dark')document.documentElement.classList.add('dark');
render();
})();