(()=>{'use strict';
const KEY='activity-logger:v4',SET='activity-logger:settings:v2';
const CATS=['Work','Study','Exercise','Personal','Creative','Social','Chores','Errand','Other'];
const $=id=>document.getElementById(id),uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2),today=()=>new Date().toISOString().slice(0,10),pad=n=>String(n).padStart(2,'0'),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let state={entries:[],goals:[],view:'today',range:'7',query:'',category:'all',selectedDate:today(),timer:null,settings:{defaultCategory:'Work',confirmArchive:true,notifications:false}};
try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s)state={...state,...s,settings:{...state.settings,...(s.settings||{})}}}catch{}
function save(){localStorage.setItem(KEY,JSON.stringify({entries:state.entries,goals:state.goals,settings:state.settings}))}
function fmtMin(n){n=Math.max(0,Math.round(Number(n)||0));return n>=60?`${Math.floor(n/60)}h ${n%60?`${n%60}m`:''}`.trim():`${n}m`}
function fmtDate(d){return new Date(`${d}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}
function dateShift(d,n){const x=new Date(`${d}T12:00:00`);x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)}
function minutesFor(e){return Number(e.duration)||0}
function entriesForDate(d){return state.entries.filter(e=>!e.archived&&e.date===d).sort((a,b)=>`${a.start||''}`.localeCompare(`${b.start||''}`))}
function total(d=state.selectedDate){return entriesForDate(d).reduce((a,e)=>a+minutesFor(e),0)}
function rangeDates(n=7){return Array.from({length:n},(_,i)=>dateShift(state.selectedDate,-(n-1-i)))}
function showToast(t){const x=$('toast');x.textContent=t;x.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>x.classList.remove('show'),2200)}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function openEntry(id=null,defaults={}){const e=id?state.entries.find(x=>x.id===id):null;$('entryTitle').textContent=e?'Edit activity':'Log activity';$('entryId').value=e?.id||'';$('activity').value=e?.activity||defaults.activity||'';$('category').value=e?.category||defaults.category||state.settings.defaultCategory;$('date').value=e?.date||defaults.date||state.selectedDate;$('start').value=e?.start||defaults.start||new Date().toTimeString().slice(0,5);$('end').value=e?.end||defaults.end||'';$('duration').value=e?.duration??defaults.duration??30;$('context').value=e?.context||'';$('tags').value=(e?.tags||[]).join(', ');$('notes').value=e?.notes||'';$('entryDialog').showModal();setTimeout(()=>$('activity').focus(),50)}
function addElapsed(start){const [h,m]=start.split(':').map(Number),now=new Date();let mins=now.getHours()*60+now.getMinutes()-(h*60+m);if(mins<0)mins+=1440;return Math.max(1,mins)}
function saveEntry(ev){ev.preventDefault();const id=$('entryId').value,old=id&&state.entries.find(x=>x.id===id);const e=old||{id:uid(),createdAt:new Date().toISOString()};Object.assign(e,{activity:$('activity').value.trim(),category:$('category').value,date:$('date').value,start:$('start').value,end:$('end').value,duration:Number($('duration').value)||1,context:$('context').value.trim(),tags:$('tags').value.split(',').map(x=>x.trim()).filter(Boolean),notes:$('notes').value.trim(),updatedAt:new Date().toISOString(),archived:false});if(!old)state.entries.unshift(e);save();$('entryDialog').close();render();showToast(old?'Activity updated':'Activity logged')}
function archive(id){if(state.settings.confirmArchive&&!confirm('Archive this activity?'))return;const e=state.entries.find(x=>x.id===id);if(e){e.archived=true;e.updatedAt=new Date().toISOString();save();render();showToast('Activity archived')}}
function timerStart(){if(state.timer?.running)return;state.timer={running:true,startedAt:Date.now(),activity:state.timer?.activity||'',category:state.timer?.category||state.settings.defaultCategory};save();render()}
function timerStop(){if(!state.timer?.running)return;const mins=Math.max(1,Math.round((Date.now()-state.timer.startedAt)/60000));const t={...state.timer};state.timer=null;save();openEntry(null,{activity:t.activity||'Tracked activity',category:t.category||state.settings.defaultCategory,date:today(),start:new Date(t.startedAt).toTimeString().slice(0,5),duration:mins});}
function timerElapsed(){return state.timer?.running?Math.max(0,Math.floor((Date.now()-state.timer.startedAt)/1000)):0}
function timerBox(){const s=timerElapsed(),hh=pad(Math.floor(s/3600)),mm=pad(Math.floor(s/60)%60),ss=pad(s%60);return`<section class="timer-card"><div><span class="eyebrow">LIVE TIMER</span><div class="timer-clock">${hh}:${mm}:${ss}</div><div class="timer-fields"><input id="timerActivity" value="${esc(state.timer?.activity||'')}" placeholder="What are you doing?" ${state.timer?.running?'disabled':''}><select id="timerCategory" ${state.timer?.running?'disabled':''}>${CATS.map(c=>`<option ${c===(state.timer?.category||state.settings.defaultCategory)?'selected':''}>${c}</option>`).join('')}</select></div></div><div class="timer-actions">${state.timer?.running?`<button class="btn primary" id="stopTimer">Stop & log</button>`:`<button class="btn primary" id="startTimer">Start timer</button>`}<button class="btn" id="manualTimer">Manual entry</button></div></section>`}
function todayView(){const d=state.selectedDate,items=entriesForDate(d),t=total(d),goal=state.goals.filter(g=>g.active!==false),goalRows=goal.map(g=>{const n=g.category==='all'?t:items.filter(e=>e.category===g.category).reduce((a,e)=>a+minutesFor(e),0);return`<div class="goal-mini"><div><strong>${esc(g.name)}</strong><span>${fmtMin(n)} / ${fmtMin(g.minutes)}</span></div><div class="progress"><i style="width:${Math.min(100,n/g.minutes*100)}%"></i></div></div>`}).join('');return`<div class="hero-row"><div><span class="eyebrow">${d===today()?'TODAY':'SELECTED DAY'}</span><h2>${fmtDate(d)}</h2><p>${fmtMin(t)} tracked across ${items.length} activities.</p></div><div class="date-nav"><button class="icon-btn" id="prevDay">←</button><button class="btn" id="todayBtn">Today</button><button class="icon-btn" id="nextDay">→</button></div></div>${timerBox()}<section class="metric-grid"><div class="metric"><span>Total tracked</span><strong>${fmtMin(t)}</strong></div><div class="metric"><span>Activities</span><strong>${items.length}</strong></div><div class="metric"><span>Top category</span><strong>${topCategory(items)||'—'}</strong></div><div class="metric"><span>Longest session</span><strong>${fmtMin(Math.max(0,...items.map(minutesFor),0))}</strong></div></section>${goalRows?`<section class="panel"><div class="section-head"><div><h3>Today's goals</h3><p>Progress toward your daily targets.</p></div><button class="btn" id="goalsLink">View goals</button></div>${goalRows}</section>`:''}<section class="panel"><div class="section-head"><div><h3>Today's activity</h3><p>Newest records are ready to edit.</p></div><button class="btn primary" id="newEntry">+ Log activity</button></div>${activityList(items)}</section>`}
function topCategory(items){const m={};items.forEach(e=>m[e.category]=(m[e.category]||0)+minutesFor(e));return Object.entries(m).sort((a,b)=>b[1]-a[1])[0]?.[0]}
function activityList(items){if(!items.length)return`<div class="empty"><strong>No activity logged.</strong><span>Start a timer or add a manual entry to build your timeline.</span><button class="btn primary" id="emptyAdd">Log your first activity</button></div>`;return`<div class="entry-list">${items.map(e=>`<article class="entry"><div class="entry-time"><strong>${esc(e.start||'—')}</strong><span>${fmtMin(e.duration)}</span></div><div class="entry-main"><div class="entry-title"><strong>${esc(e.activity)}</strong><span class="pill">${esc(e.category)}</span></div><div class="entry-meta">${e.end?`${esc(e.start)}–${esc(e.end)} · `:''}${esc(e.context||'')}${e.tags?.length?` · ${e.tags.map(esc).join(' · ')}`:''}</div>${e.notes?`<p>${esc(e.notes)}</p>`:''}</div><div class="entry-actions"><button class="icon-btn" data-edit="${e.id}" title="Edit">✎</button><button class="icon-btn danger" data-archive="${e.id}" title="Archive">×</button></div></article>`).join('')}</div>`}
function timeline(){const dates=rangeDates(Number(state.range));return`<div class="page-head"><div><span class="eyebrow">TIMELINE</span><h2>Where your time went</h2><p>Review activity chronologically without losing the day-level context.</p></div><div class="filters"><select id="range"><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option></select><button class="btn primary" id="timelineAdd">+ Log activity</button></div></div><div class="timeline">${dates.reverse().map(d=>`<section class="timeline-day"><div class="timeline-date"><strong>${fmtDate(d)}</strong><span>${fmtMin(total(d))}</span></div>${activityList(entriesForDate(d))}</section>`).join('')}</div>`}
function reports(){const days=Number(state.range),dates=rangeDates(days),items=state.entries.filter(e=>!e.archived&&dates.includes(e.date)),totalM=items.reduce((a,e)=>a+minutesFor(e),0),cats={};items.forEach(e=>cats[e.category]=(cats[e.category]||0)+minutesFor(e));const max=Math.max(1,...dates.map(total));return`<div class="page-head"><div><span class="eyebrow">REPORTS</span><h2>Patterns & trends</h2><p>${days}-day view ending ${fmtDate(state.selectedDate)}.</p></div><div class="filters"><select id="reportRange"><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option></select><button class="btn" id="exportCsv">Export CSV</button></div></div><section class="metric-grid"><div class="metric"><span>Tracked time</span><strong>${fmtMin(totalM)}</strong></div><div class="metric"><span>Daily average</span><strong>${fmtMin(totalM/days)}</strong></div><div class="metric"><span>Active days</span><strong>${dates.filter(d=>total(d)>0).length}/${days}</strong></div><div class="metric"><span>Entries</span><strong>${items.length}</strong></div></section><div class="report-grid"><section class="panel"><h3>Daily volume</h3><div class="bars">${dates.map(d=>`<div class="bar-item"><span>${new Date(`${d}T12:00:00`).toLocaleDateString(undefined,{weekday:'short'})}</span><i><b style="height:${Math.max(3,total(d)/max*100)}%"></b></i><strong>${fmtMin(total(d))}</strong></div>`).join('')}</div></section><section class="panel"><h3>Time by category</h3><div class="category-bars">${Object.entries(cats).sort((a,b)=>b[1]-a[1]).map(([c,n])=>`<div><div class="cat-label"><span>${esc(c)}</span><strong>${fmtMin(n)}</strong></div><div class="progress"><i style="width:${n/totalM*100}%"></i></div></div>`).join('')||'<div class="empty">No data in this range.</div>'}</div></section></div><section class="panel"><h3>Productivity rhythm</h3><div class="hour-grid">${Array.from({length:24},(_,h)=>{const n=items.filter(e=>Number((e.start||'0:0').split(':')[0])===h).reduce((a,e)=>a+minutesFor(e),0);return`<div title="${h}:00 · ${fmtMin(n)}"><span>${h}</span><i style="height:${Math.min(100,Math.max(4,n/Math.max(1,totalM/8)*100))}%"></i></div>`}).join('')}</div></section>`}
function goals(){return`<div class="page-head"><div><span class="eyebrow">GOALS</span><h2>Daily time targets</h2><p>Use goals to build time on activities that matter.</p></div><button class="btn primary" id="newGoal">+ New goal</button></div><div class="goal-grid">${state.goals.map(g=>{const n=g.category==='all'?total():entriesForDate(state.selectedDate).filter(e=>e.category===g.category).reduce((a,e)=>a+minutesFor(e),0),pct=Math.min(100,n/g.minutes*100);return`<article class="goal-card"><div class="goal-card-head"><div><h3>${esc(g.name)}</h3><span>${g.category==='all'?'All activities':esc(g.category)}</span></div><button class="icon-btn danger" data-goal-delete="${g.id}">×</button></div><div class="goal-number"><strong>${fmtMin(n)}</strong><span>of ${fmtMin(g.minutes)}</span></div><div class="progress large"><i style="width:${pct}%"></i></div><p>${pct>=100?'Goal reached':`${Math.round(pct)}% complete`} · ${fmtMin(Math.max(0,g.minutes-n))} remaining</p></article>`}).join('')||'<div class="empty"><strong>No goals yet.</strong><span>Create a daily target for study, exercise, work, or total activity.</span><button class="btn primary" id="emptyGoal">Create goal</button></div>'}</div>`}
function activities(){let items=state.entries.filter(e=>!e.archived);if(state.query)items=items.filter(e=>JSON.stringify(e).toLowerCase().includes(state.query.toLowerCase()));if(state.category!=='all')items=items.filter(e=>e.category===state.category);items.sort((a,b)=>`${b.date}${b.start}`.localeCompare(`${a.date}${a.start}`));return`<div class="page-head"><div><span class="eyebrow">ACTIVITY LIBRARY</span><h2>All activities</h2><p>Search, filter and maintain your complete local history.</p></div><button class="btn primary" id="libraryAdd">+ Log activity</button></div><section class="panel"><div class="search-row"><input id="activitySearch" value="${esc(state.query)}" placeholder="Search activities, notes, context and tags…"><select id="activityCategory"><option value="all">All categories</option>${CATS.map(c=>`<option ${state.category===c?'selected':''}>${c}</option>`).join('')}</select><span class="result-count">${items.length} results</span></div>${activityList(items)}</section>`}
function render(){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===state.view));const m=state.view==='today'?todayView():state.view==='timeline'?timeline():state.view==='reports'?reports():state.view==='goals'?goals():activities();$('main').innerHTML=m;bind();if(state.timer?.running){clearTimeout(render.tick);render.tick=setTimeout(render,1000)}}
function bind(){document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('newEntry')?.addEventListener('click',()=>openEntry());$('emptyAdd')?.addEventListener('click',()=>openEntry());$('timelineAdd')?.addEventListener('click',()=>openEntry());$('libraryAdd')?.addEventListener('click',()=>openEntry());$('goalsLink')?.addEventListener('click',()=>{state.view='goals';render()});$('prevDay')?.addEventListener('click',()=>{state.selectedDate=dateShift(state.selectedDate,-1);render()});$('nextDay')?.addEventListener('click',()=>{state.selectedDate=dateShift(state.selectedDate,1);render()});$('todayBtn')?.addEventListener('click',()=>{state.selectedDate=today();render()});$('startTimer')?.addEventListener('click',()=>{const activity=$('timerActivity').value.trim(),category=$('timerCategory').value;if(!activity){$('timerActivity').focus();return}state.timer={running:true,startedAt:Date.now(),activity,category};save();render();showToast('Timer started')});$('stopTimer')?.addEventListener('click',timerStop);$('manualTimer')?.addEventListener('click',()=>openEntry());$('range')?.addEventListener('change',e=>{state.range=e.target.value;render()});$('reportRange')?.addEventListener('change',e=>{state.range=e.target.value;render()});$('newGoal')?.addEventListener('click',()=>{$('goalName').value='';$('goalCategory').value='all';$('goalMinutes').value=60;$('goalDialog').showModal()});$('emptyGoal')?.addEventListener('click',()=>{$('goalName').value='';$('goalCategory').value='all';$('goalMinutes').value=60;$('goalDialog').showModal()});$('activitySearch')?.addEventListener('input',e=>{state.query=e.target.value;render()});$('activityCategory')?.addEventListener('change',e=>{state.category=e.target.value;render()});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEntry(b.dataset.edit));document.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>archive(b.dataset.archive));document.querySelectorAll('[data-goal-delete]').forEach(b=>b.onclick=()=>{if(confirm('Delete this goal?')){state.goals=state.goals.filter(g=>g.id!==b.dataset.goalDelete);save();render()}});$('exportCsv')?.addEventListener('click',exportCsv)}
function exportCsv(){const fields=['activity','category','date','start','end','duration','context','tags','notes'];const rows=state.entries.map(e=>fields.map(k=>`"${String(Array.isArray(e[k])?e[k].join('|'):e[k]??'').replaceAll('"','""')}"`).join(','));download('activity-logger.csv',[fields.join(','),...rows].join('\n'),'text/csv')}
$('entryForm').addEventListener('submit',saveEntry);$('goalForm').addEventListener('submit',e=>{e.preventDefault();state.goals.push({id:uid(),name:$('goalName').value.trim(),category:$('goalCategory').value,minutes:Number($('goalMinutes').value),createdAt:new Date().toISOString(),active:true});save();$('goalDialog').close();state.view='goals';render();showToast('Goal created')});
$('themeBtn').onclick=()=>{document.documentElement.classList.toggle('dark');localStorage.setItem(SET,JSON.stringify(state.settings));document.documentElement.classList.contains('dark')&&showToast('Dark mode')};$('exportBtn').onclick=()=>download('activity-logger-backup.json',JSON.stringify({version:4,exportedAt:new Date().toISOString(),entries:state.entries,goals:state.goals,settings:state.settings},null,2),'application/json');$('importInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!Array.isArray(p.entries))throw 0;state.entries=p.entries;state.goals=Array.isArray(p.goals)?p.goals:[];state.settings={...state.settings,...(p.settings||{})};save();render();showToast('Backup imported')}catch{showToast('Invalid backup file')}};r.readAsText(f);e.target.value=''};$('settingsBtn').onclick=()=>{$('defaultCategory').value=state.settings.defaultCategory;$('confirmArchive').checked=state.settings.confirmArchive;$('notifications').checked=state.settings.notifications;$('storageInfo').textContent=`${state.entries.length} activities · ${state.goals.length} goals · ${(new Blob([localStorage.getItem(KEY)||'']).size/1024).toFixed(1)} KB`;$('settingsDialog').showModal()};$('settingsForm').onsubmit=e=>{e.preventDefault();state.settings.defaultCategory=$('defaultCategory').value;state.settings.confirmArchive=$('confirmArchive').checked;state.settings.notifications=$('notifications').checked;save();$('settingsDialog').close();showToast('Settings saved')};$('clearDataBtn').onclick=()=>{if(confirm('Delete every locally stored activity, goal and setting? This cannot be undone unless you have an export.')){localStorage.removeItem(KEY);state.entries=[];state.goals=[];save();$('settingsDialog').close();render();showToast('Local data deleted')}};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});
if(localStorage.getItem(SET)==='dark')document.documentElement.classList.add('dark');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
})();