const AK='digital-diary:advanced:v6';
let adv=JSON.parse(localStorage.getItem(AK)||'null')||{annual:100,prompts:[],reflections:{},goals:[],reminders:[],snapshots:[],versions:{},trash:[],settings:{compact:false,confirmDelete:true,rememberFilters:true}};
adv.prompts ||= []; adv.reflections ||= {}; adv.goals ||= []; adv.reminders ||= []; adv.snapshots ||= []; adv.versions ||= {}; adv.trash ||= []; adv.settings ||= {};
const A=s=>document.querySelector(s), $$A=s=>[...document.querySelectorAll(s)];
const diary=()=>window.state||state, Akey=d=>new Date(d).toLocaleDateString('en-CA'), Aesc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function advSave(){localStorage.setItem(AK,JSON.stringify(adv))} function syncCore(){const s=diary();window.state=s;localStorage.setItem('digital-diary:v1',JSON.stringify(s));localStorage.setItem('digital-diary:v2',JSON.stringify(s))}
function adl(name,data,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),700)}
function astats(){const s=diary(),m={},days={};s.entries.forEach(e=>{if(e.mood)m[e.mood]=(m[e.mood]||0)+1;days[Akey(e.date)]=(days[Akey(e.date)]||0)+1});return{m,days,words:s.entries.reduce((n,e)=>n+(e.body||'').split(/\s+/).filter(Boolean).length,0)}}
function astreak(days){let n=0,d=new Date();while(days[Akey(d)]){n++;d.setDate(d.getDate()-1)}return n}
function ensureFilterBar(){if(A('#advancedFilters'))return;const toolbar=A('.toolbar');if(!toolbar)return;toolbar.insertAdjacentHTML('afterend',`<section id="advancedFilters" class="advanced-filters"><select id="journalFilter"><option value="all">All journals</option></select><select id="moodFilter"><option value="all">All moods</option></select><label class="check-filter"><input id="privateFilter" type="checkbox"> Private only</label><button class="ghost" id="clearFilters">Clear filters</button></section>`);const syncFilters=()=>{const s=diary(),j=A('#journalFilter'),m=A('#moodFilter');j.innerHTML='<option value="all">All journals</option>'+s.journals.map(x=>`<option value="${Aesc(x.id)}">${Aesc(x.name)}</option>`).join('');m.innerHTML='<option value="all">All moods</option>'+[...new Set(s.entries.map(e=>e.mood).filter(Boolean))].map(x=>`<option>${Aesc(x)}</option>`).join('');j.value=adv.settings.journal||'all';m.value=adv.settings.mood||'all';A('#privateFilter').checked=!!adv.settings.privateOnly};syncFilters();A('#journalFilter').onchange=e=>{adv.settings.journal=e.target.value;advSave();renderView()};A('#moodFilter').onchange=e=>{adv.settings.mood=e.target.value;advSave();renderView()};A('#privateFilter').onchange=e=>{adv.settings.privateOnly=e.target.checked;advSave();renderView()};A('#clearFilters').onclick=()=>{adv.settings.journal='all';adv.settings.mood='all';adv.settings.privateOnly=false;syncFilters();renderView()};window.refreshDiaryFilters=syncFilters}
function wrapRender(){if(window.__diaryAdvancedRender)return;window.__diaryAdvancedRender=true;const base=renderView;renderView=function(){ensureFilterBar();if(view==='trash'){renderTrash();return}base()}}
function renderTrash(){const s=diary(),items=adv.trash.length?adv.trash.map((t,i)=>`<div class="media-item"><div><strong>${Aesc(t.entry.title||'Untitled entry')}</strong><small>Deleted ${new Date(t.deletedAt).toLocaleString()}</small></div><button class="ghost" data-restore-trash="${i}">Restore</button><button class="danger ghost" data-delete-trash="${i}">Delete forever</button></div>`).join(''):'<div class="empty"><h3>Trash is empty</h3><p>Deleted entries remain recoverable until permanently removed.</p></div>';A('#view').innerHTML=`<div class="studio-card"><p class="eyebrow">RECOVERY BIN</p><p class="hero-copy">Keep deleted entries recoverable instead of losing them immediately.</p>${items}</div>`;$$A('[data-restore-trash]').forEach(b=>b.onclick=()=>{const t=adv.trash.splice(+b.dataset.restoreTrash,1)[0];if(!t)return;s.entries.push(t.entry);advSave();syncCore();render();toast('Entry restored')});$$A('[data-delete-trash]').forEach(b=>b.onclick=()=>{if(!confirm('Delete this entry permanently?'))return;adv.trash.splice(+b.dataset.deleteTrash,1);advSave();renderTrash();toast('Entry deleted permanently')})}
function installTrashTab(){const tabs=A('#tabs');if(!tabs||A('#trashTab'))return;const b=document.createElement('button');b.id='trashTab';b.dataset.view='trash';b.textContent='Trash';tabs.appendChild(b);b.onclick=()=>{view='trash';$$A('#tabs button').forEach(x=>x.classList.toggle('active',x===b));render()}}
function captureVersions(){const form=A('#entryForm');if(!form||form.__versionsInstalled)return;form.__versionsInstalled=true;form.addEventListener('submit',()=>{const id=A('#entryId').value;if(!id)return;const before=diary().entries.find(e=>e.id===id);if(!before)return;const snap={at:new Date().toISOString(),title:before.title||'',body:before.body||'',mood:before.mood||'',energy:before.energy||5};adv.versions[id]=[...(adv.versions[id]||[]),snap].slice(-20);advSave()},true)}
function captureTrash(){const del=A('#deleteEntry');if(!del||del.__trashInstalled)return;del.__trashInstalled=true;del.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();const id=A('#entryId').value,s=diary(),i=s.entries.findIndex(x=>x.id===id);if(i<0)return;const entry=s.entries.splice(i,1)[0];adv.trash.unshift({entry,deletedAt:new Date().toISOString()});adv.trash=adv.trash.slice(0,100);advSave();syncCore();window.deleteMedia?.(id);A('#entryDialog').close();render();toast('Entry moved to trash')},true)}
function restoreVersion(id,index){const s=diary(),e=s.entries.find(x=>x.id===id),v=(adv.versions[id]||[])[index];if(!e||!v)return;if(!confirm('Restore this older version?'))return;e.title=v.title;e.body=v.body;e.mood=v.mood;e.energy=v.energy;e.updatedAt=new Date().toISOString();syncCore();advSave();render();toast('Older version restored')}
function journalManager(){const s=diary(),name=prompt('New journal name');if(!name?.trim())return;s.journals.push({id:crypto.randomUUID(),name:name.trim(),createdAt:new Date().toISOString()});syncCore();advSave();render();toast('Journal created')}
function renameJournal(id){const s=diary(),j=s.journals.find(x=>x.id===id);if(!j)return;const n=prompt('Rename journal',j.name);if(!n?.trim())return;j.name=n.trim();syncCore();advSave();studio('journals')}
function deleteJournal(id){const s=diary();if(s.journals.length<=1)return toast('Keep at least one journal');const j=s.journals.find(x=>x.id===id);if(!j||!confirm(`Delete "${j.name}"? Entries will move to the first journal.`))return;const target=s.journals.find(x=>x.id!==id);s.entries.forEach(e=>{if(e.journalId===id)e.journalId=target.id});s.journals=s.journals.filter(x=>x.id!==id);syncCore();advSave();studio('journals');toast('Journal removed')}
function promptAdd(){const p=prompt('Write a reusable journal prompt');if(p?.trim()){adv.prompts.push(p.trim());advSave();studio('prompts')}}
function addGoal(){const title=prompt('Goal name');if(!title?.trim())return;const target=Math.max(1,+prompt('Target entries',String(adv.annual))||adv.annual);adv.goals.push({id:crypto.randomUUID(),title:title.trim(),target,done:0,createdAt:new Date().toISOString()});advSave();studio('goals')}
function addReminder(){const time=prompt('Daily reminder time (HH:MM)','20:00');if(!/^\d{2}:\d{2}$/.test(time||''))return toast('Use HH:MM');adv.reminders.push({id:crypto.randomUUID(),time,enabled:true});advSave();studio('data');toast('Reminder saved')}
function checkReminders(){const now=new Date(),hh=String(now.getHours()).padStart(2,'0'),mm=String(now.getMinutes()).padStart(2,'0'),stamp=Akey(now)+' '+hh+':'+mm;if(adv.settings.lastReminder===stamp)return;const due=adv.reminders.filter(r=>r.enabled&&r.time===`${hh}:${mm}`);if(!due.length)return;adv.settings.lastReminder=stamp;advSave();if('Notification'in window&&Notification.permission==='granted')new Notification('Digital Diary',{body:'A quiet moment to write is waiting for you.'});else toast('Diary reminder: take a quiet moment to write')}
function requestNotifications(){if(!('Notification'in window))return toast('Notifications are not supported here');Notification.requestPermission().then(x=>toast(x==='granted'?'Notifications enabled':'Notifications not enabled'))}
async function storageHealth(){const e=navigator.storage?.estimate?await navigator.storage.estimate():{};const used=e.usage||0,quota=e.quota||0,pct=quota?Math.round(used/quota*100):0;return `${(used/1048576).toFixed(1)} MB used · ${(quota/1048576).toFixed(0)} MB available · ${pct}%`}
async function persistStorage(){if(!navigator.storage?.persist)return toast('Persistent storage is not supported');const ok=await navigator.storage.persist();toast(ok?'Persistent storage requested successfully':'Browser kept best-effort storage')}
function snapshot(){adv.snapshots.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),core:JSON.parse(JSON.stringify(diary()))});adv.snapshots=adv.snapshots.slice(0,15);advSave();toast('Restore point created')}
function restoreSnapshot(i){const x=adv.snapshots[i];if(!x||!confirm('Restore this restore point?'))return;state=JSON.parse(JSON.stringify(x.core));window.state=state;syncCore();location.reload()}
async function derive(password,salt){return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:150000,hash:'SHA-256'},await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']),{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptedExport(){const p=prompt('Create a password for this encrypted backup');if(!p)return;const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),k=await derive(p,salt),data=new TextEncoder().encode(JSON.stringify({core:diary(),advanced:adv})),ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},k,data);adl('digital-diary-encrypted-backup.json',JSON.stringify({v:2,kdf:'PBKDF2-SHA256',iterations:150000,cipher:'AES-256-GCM',salt:[...salt],iv:[...iv],data:[...new Uint8Array(ct)]},null,2))}
async function encryptedImport(){const i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=()=>{const r=new FileReader();r.onload=async()=>{try{const x=JSON.parse(r.result),p=prompt('Enter backup password');if(!p||!x.salt||!x.iv||!x.data)throw 0;const k=await derive(p,new Uint8Array(x.salt)),pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(x.iv)},k,new Uint8Array(x.data)),z=JSON.parse(new TextDecoder().decode(pt));if(!z.core?.entries)throw 0;state=z.core;window.state=state;adv=z.advanced||adv;syncCore();advSave();location.reload()}catch{toast('Could not decrypt or validate backup')}};r.readAsText(i.files[0])};i.click()}
function exportCSV(){const s=diary(),rows=[['date','title','body','mood','energy','weather','location','tags','journal','favorite','memory']].concat(s.entries.map(e=>[e.date,e.title,e.body,e.mood,e.energy,e.weather,e.location,(e.tags||[]).join('|'),s.journals.find(j=>j.id===e.journalId)?.name||'',e.favorite,e.memory]));adl('digital-diary.csv',rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n'),'text/csv')}
function exportHTML(){const s=diary(),body=s.entries.slice().sort((a,b)=>new Date(a.date)-new Date(b.date)).map(e=>`<article><h2>${Aesc(e.title||'Untitled')}</h2><small>${new Date(e.date).toLocaleString()}</small><p>${Aesc(e.body||'').replace(/\n/g,'<br>')}</p></article>`).join('');adl('digital-diary-archive.html',`<!doctype html><meta charset="utf-8"><title>Digital Diary Archive</title><style>body{font:16px system-ui;max-width:850px;margin:40px auto;padding:20px}article{padding:20px 0;border-bottom:1px solid #ddd}</style><h1>Digital Diary Archive</h1>${body}`,'text/html')}
function exportMarkdown(){const s=diary();const out=s.entries.slice().sort((a,b)=>new Date(a.date)-new Date(b.date)).map(e=>`# ${e.title||'Untitled'}\n\n- Date: ${e.date}\n- Mood: ${e.mood||'—'}\n- Energy: ${e.energy||'—'}/10\n- Tags: ${(e.tags||[]).join(', ')}\n\n${e.body||''}\n`).join('\n---\n\n');adl('digital-diary.md',out,'text/markdown')}
function studio(tab='overview'){
  if(A('#diaryStudio'))A('#diaryStudio').remove();const s=diary(),z=astats(),past=s.entries.filter(e=>{const d=new Date(e.date),t=new Date();return d.getMonth()===t.getMonth()&&d.getDate()===t.getDate()&&d.getFullYear()!==t.getFullYear()}).slice(0,10);
  document.body.insertAdjacentHTML('beforeend',`<div class="studio" id="diaryStudio"><div class="studio-inner"><div class="studio-head"><div><p class="eyebrow">DIGITAL DIARY STUDIO</p><h1>Your story, understood.</h1><p class="hero-copy">Insights, journals, goals, recovery, privacy and data tools.</p></div><button class="primary" id="closeStudio">Close</button></div><div class="studio-tabs">${['overview','insights','prompts','journals','goals','versions','data'].map(x=>`<button data-tab="${x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</div><div id="studioBody"></div></div></div>`);
  const body=A('#studioBody');$$A('#diaryStudio [data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));let h='';
  if(tab==='overview')h=`<div class="studio-grid"><div class="studio-card"><p class="eyebrow">WRITING</p><h2>${s.entries.length}</h2><p>${z.words.toLocaleString()} words · ${astreak(z.days)} day streak</p></div><div class="studio-card"><p class="eyebrow">ANNUAL TARGET</p><input id="annual" type="number" min="1" value="${adv.annual}"><p>${s.entries.length}/${adv.annual} entries</p><div class="progress"><i style="width:${Math.min(100,s.entries.length/adv.annual*100)}%"></i></div></div><div class="studio-card"><p class="eyebrow">ON THIS DAY</p>${past.length?past.map(e=>`<p><strong>${new Date(e.date).getFullYear()}</strong> — ${Aesc(e.title||'Untitled')}</p>`).join(''):'<p>No past memories for this date yet.</p>'}</div><div class="studio-card"><p class="eyebrow">TODAY REFLECTION</p><textarea id="reflection" rows="6" placeholder="What are you noticing?">${Aesc(adv.reflections[Akey(new Date())]||'')}</textarea><button class="primary" id="saveReflection">Save reflection</button></div></div>`;
  if(tab==='insights'){const recent=s.entries.filter(e=>Date.now()-new Date(e.date)<30*864e5),energy=recent.length?(recent.reduce((n,e)=>n+(Number(e.energy)||0),0)/recent.length).toFixed(1):'—';h=`<div class="studio-grid"><div class="studio-card"><p class="eyebrow">30-DAY ENERGY</p><h2>${energy}/10</h2></div><div class="studio-card"><p class="eyebrow">TOP MOOD</p><h2>${Aesc(Object.entries(z.m).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—')}</h2></div><div class="studio-card"><p class="eyebrow">12-WEEK RHYTHM</p><div class="heatmap">${Array.from({length:84},(_,i)=>{const d=new Date();d.setDate(d.getDate()-83+i);const c=z.days[Akey(d)]||0;return `<span title="${Akey(d)}: ${c}" style="opacity:${c?Math.min(1,.25+c*.18):.08}"></span>`}).join('')}</div></div><div class="studio-card"><p class="eyebrow">STORAGE</p><p id="storageHealth">Checking…</p><button class="ghost" id="persistStorage">Protect local storage</button></div></div>`}
  if(tab==='prompts')h=`<div class="studio-card"><p class="eyebrow">PROMPT LIBRARY</p><div class="prompt-list">${adv.prompts.map((p,i)=>`<button class="ghost" data-use-prompt="${i}">${Aesc(p)}</button>`).join('')||'<p>No custom prompts yet.</p>'}</div><button class="primary" id="addPrompt">+ Add prompt</button>`;
  if(tab==='journals')h=`<div class="studio-card"><p class="eyebrow">JOURNAL LIBRARY</p>${s.journals.map(j=>`<div class="media-item"><div><strong>${Aesc(j.name)}</strong><small>${s.entries.filter(e=>e.journalId===j.id).length} entries</small></div><button class="ghost" data-rename-journal="${j.id}">Rename</button><button class="danger ghost" data-delete-journal="${j.id}">Delete</button></div>`).join('')}<button class="primary" id="newJournal">+ New journal</button></div>`;
  if(tab==='goals')h=`<div class="studio-grid">${adv.goals.map(g=>`<div class="studio-card"><p class="eyebrow">GOAL</p><h2>${Aesc(g.title)}</h2><p>${s.entries.length}/${g.target} entries in portfolio</p></div>`).join('')}<div class="studio-card"><p class="eyebrow">CONSISTENCY</p><h2>${astreak(z.days)}</h2><p>current writing-day streak</p></div></div><button class="primary" id="addGoal">+ Add writing goal</button>`;
  if(tab==='versions')h=`<div class="studio-card"><p class="eyebrow">ENTRY VERSION HISTORY</p>${Object.entries(adv.versions).map(([id,vs])=>{const e=s.entries.find(x=>x.id===id);return e?`<div class="media-item"><div><strong>${Aesc(e.title||'Untitled')}</strong><small>${vs.length} saved versions</small></div><button class="ghost" data-history-entry="${id}">View history</button></div>`:''}).join('')||'<p>No previous versions yet. Edit an entry to start its history.</p>'}</div>`;
  if(tab==='data')h=`<div class="studio-grid"><div class="studio-card"><p class="eyebrow">EXPORT</p><button class="ghost" id="jsonExport">JSON backup</button><button class="ghost" id="csvExport">CSV export</button><button class="ghost" id="mdExport">Markdown archive</button><button class="ghost" id="htmlExport">HTML archive</button></div><div class="studio-card"><p class="eyebrow">ENCRYPTED BACKUP</p><button class="ghost" id="encExport">Encrypt & export</button><button class="ghost" id="encImport">Decrypt & restore</button><small>AES-256-GCM + PBKDF2-SHA256. Password is never stored.</small></div><div class="studio-card"><p class="eyebrow">RECOVERY</p><button class="ghost" id="snap">Create restore point</button>${adv.snapshots.slice(0,5).map((x,i)=>`<button class="ghost" data-restore-snap="${i}">${new Date(x.at).toLocaleString()}</button>`).join('')}</div><div class="studio-card"><p class="eyebrow">REMINDERS</p>${adv.reminders.map(r=>`<p>${r.time} · ${r.enabled?'enabled':'paused'}</p>`).join('')}<button class="ghost" id="addReminder">+ Add reminder</button><button class="ghost" id="notify">Enable notifications</button><small>Browser reminders are best-effort and require notification support.</small></div><div class="studio-card"><p class="eyebrow">MEDIA</p><button class="ghost" id="mediaGallery">Open media gallery</button><p>Attachments remain in this browser's IndexedDB storage.</p></div><div class="studio-card"><p class="eyebrow">FOCUS</p><button class="ghost" id="focus">Zen focus mode</button><button class="ghost" id="random">Random prompt</button></div></div>`;
  body.innerHTML=h;
  A('#annual')?.addEventListener('change',e=>{adv.annual=Math.max(1,+e.target.value||100);advSave();studio('overview')});A('#saveReflection')?.addEventListener('click',()=>{adv.reflections[Akey(new Date())]=A('#reflection').value.trim();advSave();toast('Reflection saved')});A('#addPrompt')?.addEventListener('click',promptAdd);A('#newJournal')?.addEventListener('click',journalManager);A('#addGoal')?.addEventListener('click',addGoal);A('#addReminder')?.addEventListener('click',addReminder);A('#notify')?.addEventListener('click',requestNotifications);A('#persistStorage')?.addEventListener('click',persistStorage);A('#storageHealth')&&storageHealth().then(x=>A('#storageHealth').textContent=x);
  $$A('[data-use-prompt]').forEach(b=>b.onclick=()=>{const p=adv.prompts[+b.dataset.usePrompt];A('#diaryStudio')?.remove();openEntry(null,null,{title:'Journal prompt',body:p+'\n\n'})});$$A('[data-rename-journal]').forEach(b=>b.onclick=()=>renameJournal(b.dataset.renameJournal));$$A('[data-delete-journal]').forEach(b=>b.onclick=()=>deleteJournal(b.dataset.deleteJournal));$$A('[data-restore-snap]').forEach(b=>b.onclick=()=>restoreSnapshot(+b.dataset.restoreSnap));
  $$A('[data-history-entry]').forEach(b=>b.onclick=()=>{const id=b.dataset.historyEntry,vs=adv.versions[id]||[];body.innerHTML=`<div class="studio-card"><p class="eyebrow">VERSION HISTORY</p>${vs.map((v,i)=>`<div class="media-item"><div><strong>${Aesc(v.title||'Untitled')}</strong><small>${new Date(v.at).toLocaleString()}</small></div><button class="ghost" data-restore-version="${i}">Restore</button></div>`).join('')}</div>`;$$A('[data-restore-version]').forEach(x=>x.onclick=()=>restoreVersion(id,+x.dataset.restoreVersion))});
  A('#jsonExport')?.addEventListener('click',()=>adl('digital-diary-backup.json',JSON.stringify({core:diary(),advanced:adv},null,2)));A('#csvExport')?.addEventListener('click',exportCSV);A('#mdExport')?.addEventListener('click',exportMarkdown);A('#htmlExport')?.addEventListener('click',exportHTML);A('#encExport')?.addEventListener('click',encryptedExport);A('#encImport')?.addEventListener('click',encryptedImport);A('#snap')?.addEventListener('click',snapshot);A('#mediaGallery')?.addEventListener('click',()=>{A('#diaryStudio')?.remove();window.openMediaGallery?.()});A('#focus')?.addEventListener('click',()=>{document.body.classList.toggle('focus-mode');A('#diaryStudio')?.remove()});A('#random')?.addEventListener('click',()=>{const p=['What do you want to remember from today?','What surprised you recently?','What are you grateful for?','What did you learn today?','What would your future self like to know?'][Math.floor(Math.random()*5)];A('#diaryStudio')?.remove();openEntry(null,null,{title:'Journal prompt',body:p+'\n\n'})});
  A('#closeStudio').onclick=()=>A('#diaryStudio').remove();$$A('#diaryStudio [data-tab]').forEach(b=>b.onclick=()=>studio(b.dataset.tab));
}
window.openStudio=studio;window.advancedDiaryState=()=>adv;ensureFilterBar();installTrashTab();wrapRender();captureVersions();captureTrash();setInterval(checkReminders,30000);advSave();
