const MEDIA_DB='digital-diary-media-v2';
function mediaDB(){return new Promise((ok,no)=>{let r=indexedDB.open(MEDIA_DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('media',{keyPath:'id'});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function mediaFor(entryId){let d=await mediaDB();return new Promise((ok,no)=>{let a=[],r=d.transaction('media').objectStore('media').openCursor();r.onsuccess=()=>{let c=r.result;if(!c)return ok(a);if(c.value.entryId===entryId)a.push(c.value);c.continue()};r.onerror=()=>no(r.error)})}
async function allMedia(){let d=await mediaDB();return new Promise(ok=>{let a=[],r=d.transaction('media').objectStore('media').openCursor();r.onsuccess=()=>{let c=r.result;if(!c)return ok(a);a.push(c.value);c.continue()}})}
function mediaURL(m){return URL.createObjectURL(m.blob)}
window.handleFiles=async id=>{let fs=document.querySelector('#entryFiles')?.files;if(!fs?.length)return;let d=await mediaDB();for(const f of fs){let tx=d.transaction('media','readwrite');tx.objectStore('media').put({id:crypto.randomUUID(),entryId:id,name:f.name,type:f.type||'application/octet-stream',size:f.size,blob:f,createdAt:new Date().toISOString()});await new Promise((ok,no)=>{tx.oncomplete=ok;tx.onerror=()=>no(tx.error)})}let e=(window.state||state).entries.find(x=>x.id===id);if(e)e.mediaCount=(await mediaFor(id)).length;localStorage.setItem('digital-diary:v1',JSON.stringify(window.state||state));renderMedia(id);document.querySelector('#entryFiles').value='';toast('Attachment saved locally')};
window.renderMedia=async id=>{let b=document.querySelector('#existingMedia');if(!b)return;if(!id){b.innerHTML='';return}let ms=await mediaFor(id);b.innerHTML=ms.map(m=>{let u=mediaURL(m),visual=m.type.startsWith('image/')?`<img src="${u}" alt="${m.name}">`:m.type.startsWith('video/')?`<video src="${u}" controls></video>`:m.type.startsWith('audio/')?`<audio src="${u}" controls></audio>`:`<span class="file-icon">FILE</span>`;return `<div class="media-item">${visual}<div><strong>${m.name}</strong><small>${Math.max(1,Math.ceil(m.size/1024))} KB</small></div><button class="ghost" data-media-download="${m.id}">Open</button><button class="danger ghost" data-media-delete="${m.id}">Delete</button></div>`}).join('')||'<small>No attachments yet.</small>';$$('#existingMedia [data-media-download]').forEach(b=>b.onclick=async()=>{let m=(await allMedia()).find(x=>x.id===b.dataset.mediaDownload);if(m){let a=document.createElement('a');a.href=mediaURL(m);a.download=m.name;a.target='_blank';a.click()}});$$('#existingMedia [data-media-delete]').forEach(b=>b.onclick=async()=>{let d=await mediaDB(),tx=d.transaction('media','readwrite');tx.objectStore('media').delete(b.dataset.mediaDelete);tx.oncomplete=()=>renderMedia(id)})};
window.deleteMedia=async id=>{let d=await mediaDB(),ms=await mediaFor(id),tx=d.transaction('media','readwrite');ms.forEach(m=>tx.objectStore('media').delete(m.id))};
window.openMediaGallery=async()=>{let ms=await allMedia();let b=document.querySelector('#mediaGallery');if(!b)return;b.innerHTML=ms.map(m=>`<div class="media-gallery-card"><strong>${m.name}</strong><small>${Math.ceil(m.size/1024)} KB · ${m.type||'file'}</small></div>`).join('')||'<p>No attachments saved yet.</p>'};
