(() => {
  'use strict';
  const KEY='calm-calendar:v1', SET='calm-calendar:settings:v1', TMP='calm-calendar:templates:v1';
  const COLORS=['#5b5bd6','#168a6a','#c77700','#c44862','#5b62a5','#8b5cc7'];
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const pad=n=>String(n).padStart(2,'0'), iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
  const parseDate=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}, today=new Date();
  const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
  const clone=x=>JSON.parse(JSON.stringify(x));
  const defaultState=()=>({calendars:[{id:'personal',name:'Personal',color:'#5b5bd6',description:'Personal events',visible:true}],events:[]});
  let state=load(KEY,defaultState), settings=load(SET,{weekStarts:1,timeFormat:'24',dayStart:'07:00',dayEnd:'22:00',slotMinutes:30,theme:'system',notifications:false}), templates=load(TMP,[]);
  let view='month', cursor=new Date(today.getFullYear(),today.getMonth(),today.getDate()), selected=iso(today), editingId=null, search='';
  function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
  function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
  function saveSettings(){localStorage.setItem(SET,JSON.stringify(settings));applyTheme();renderAll()}
  function dateFrom(s){return s?parseDate(s):new Date()}
  function cal(id){return state.calendars.find(c=>c.id===id)||state.calendars[0]}
  function visibleEvents(){return expandEvents(state.events.filter(e=>cal(e.calendarId)?.visible!==false));}
  function eventMatches(e){const q=search.trim().toLowerCase();return !q||[e.title,e.location,e.notes,e.attendees,e.calendarId].join(' ').toLowerCase().includes(q)}
  function mins(t){if(!t)return 0;const [h,m]=t.split(':').map(Number);return h*60+m}
  function fmtTime(t){if(!t)return '';if(settings.timeFormat==='24')return t;let [h,m]=t.split(':').map(Number),ap=h>=12?'PM':'AM';h=h%12||12;return `${h}:${pad(m)} ${ap}`}
  function dayStart(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
  function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
  function startOfWeek(d){const x=dayStart(d), target=Number(settings.weekStarts);let diff=(x.getDay()-target+7)%7;return addDays(x,-diff)}
  function daysInMonth(y,m){return new Date(y,m+1,0).getDate()}
  function monthName(d){return d.toLocaleDateString(undefined,{month:'long',year:'numeric'})}
  function dayName(d,short=true){return d.toLocaleDateString(undefined,{weekday:short?'short':'long'})}
  function eventDuration(e){if(e.allDay)return 1440;if(!e.start||!e.end)return 60;let x=mins(e.end)-mins(e.start);return x>0?x:60}
  function expandEvents(base){const out=[];const rangeStart=addDays(cursor,-45), rangeEnd=addDays(cursor,400);for(const e of base){if(!e.date)continue;const until=e.repeatUntil?parseDate(e.repeatUntil):rangeEnd;const start=parseDate(e.date);const repeat=e.repeat||'none';if(repeat==='none'){if(start>=rangeStart&&start<=rangeEnd)out.push({...e,instanceDate:e.date,instanceId:e.id});continue}for(let d=new Date(start),guard=0;d<=until&&d<=rangeEnd&&guard<1200;guard++,d=nextRepeat(d,repeat)){if(d<rangeStart)continue;const ds=iso(d);if((e.exdates||[]).includes(ds))continue;out.push({...e,instanceDate:ds,instanceId:`${e.id}@${ds}`});}}return out}
  function nextRepeat(d,r){const x=new Date(d);if(r==='daily')x.setDate(x.getDate()+1);else if(r==='weekdays'){do{x.setDate(x.getDate()+1)}while(x.getDay()===0||x.getDay()===6)}else if(r==='weekly')x.setDate(x.getDate()+7);else if(r==='biweekly')x.setDate(x.getDate()+14);else if(r==='monthly')x.setMonth(x.getMonth()+1);else if(r==='yearly')x.setFullYear(x.getFullYear()+1);return x}
  function dayEvents(ds){return visibleEvents().filter(e=>e.instanceDate===ds&&eventMatches(e)&&filterMatch(e)).sort((a,b)=>(a.allDay?0:1)-(b.allDay?0:1)||mins(a.start)-mins(b.start))}
  function filterMatch(e){const f=$('#quickFilter')?.value||'all', d=dateFrom(e.instanceDate), td=dayStart(today);if(f==='today')return e.instanceDate===iso(td);if(f==='upcoming')return d>=td;if(f==='conflicts')return hasConflict(e);return true}
  function hasConflict(e){if(e.allDay)return false;return dayEventsRaw(e.instanceDate).some(x=>x.instanceId!==e.instanceId&&!x.allDay&&overlap(e,x))}
  function dayEventsRaw(ds){return visibleEvents().filter(e=>e.instanceDate===ds)}
  function overlap(a,b){return mins(a.start)<mins(b.end||a.start)+eventDuration(b)&&mins(b.start)<mins(a.end||b.start)+eventDuration(a)}
  function color(e){return e.color&&e.color!=='auto'?e.color:cal(e.calendarId)?.color||COLORS[0]}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function renderAll(){applyTheme();renderMini();renderCalendars();renderView();fillSettings();scheduleReminders()}
  function applyTheme(){document.body.classList.toggle('dark',settings.theme==='dark'||(settings.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches))}
  function renderMini(){const d=cursor, first=new Date(d.getFullYear(),d.getMonth(),1), start=startOfWeek(first), title=$('#miniTitle');title.textContent=first.toLocaleDateString(undefined,{month:'short',year:'numeric'});let html=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class="dow">${x.slice(0,2)}</div>`).join('');for(let i=0;i<42;i++){const x=addDays(start,i), ds=iso(x), muted=x.getMonth()!==d.getMonth(), cls=['mini-day',muted?'muted':'',ds===iso(today)?'today':'',ds===selected?'selected':'',dayEventsRaw(ds).length?'has':''].join(' ');html+=`<button class="${cls}" data-mini-date="${ds}">${x.getDate()}</button>`}$('#miniCalendar').innerHTML=html}
  function renderCalendars(){const box=$('#calendarList');box.innerHTML=state.calendars.map(c=>`<label class="calendar-item"><input type="checkbox" data-cal-vis="${c.id}" ${c.visible!==false?'checked':''}><span class="cal-dot" style="background:${c.color}"></span><span class="calendar-name">${esc(c.name)}</span><span class="calendar-count">${state.events.filter(e=>e.calendarId===c.id).length}</span></label>`).join('')}
  function renderView(){
    const title=$('#periodTitle');if(view==='month')title.textContent=monthName(cursor);else if(view==='week'){const s=startOfWeek(cursor),e=addDays(s,6);title.textContent=s.getMonth()===e.getMonth()?`${s.toLocaleDateString(undefined,{month:'long'})} ${s.getDate()}–${e.getDate()}, ${e.getFullYear()}`:`${s.toLocaleDateString(undefined,{month:'short',day:'numeric'})} – ${e.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}`}else if(view==='day')title.textContent=cursor.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});else title.textContent='Agenda';
    $$('.view-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#calendarView').innerHTML=view==='month'?monthView():view==='week'?weekView():view==='day'?dayView():agendaView();$('#emptyState').classList.toggle('hidden',!visibleEvents().some(eventMatches));
  }
  function monthView(){const first=new Date(cursor.getFullYear(),cursor.getMonth(),1), start=startOfWeek(first), cols=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];let h='<div class="month-grid">'+cols.map(x=>`<div class="month-dow">${x}</div>`).join('');for(let i=0;i<42;i++){const d=addDays(start,i),ds=iso(d),ev=dayEvents(ds),muted=d.getMonth()!==cursor.getMonth();h+=`<div class="month-cell ${muted?'muted-day':''}" data-date="${ds}"><div class="day-number ${ds===iso(today)?'today':''} ${ds===selected?'selected':''}">${d.getDate()}</div>${ev.slice(0,5).map(e=>eventChip(e)).join('')}${ev.length>5?`<div class="more-events" data-date="${ds}">+${ev.length-5} more</div>`:''}</div>`}return h+'</div>'}
  function eventChip(e){const c=color(e);return `<div class="month-event ${e.allDay?'allday':''}" style="--primary:${c};background:${c}18" data-event="${e.instanceId}" title="${esc(e.title)}">${e.allDay?'':fmtTime(e.start)+' · '}${esc(e.title)}${hasConflict(e)?'<span class="conflict-dot"></span>':''}</div>`}
  function weekView(){const s=startOfWeek(cursor),days=Array.from({length:7},(_,i)=>addDays(s,i)),startM=mins(settings.dayStart),endM=Math.max(startM+60,mins(settings.dayEnd)),slots=Math.ceil((endM-startM)/30),px=30;let heads=days.map(d=>`<div class="week-head ${iso(d)===iso(today)?'today':''}">${dayName(d)}<strong>${d.getDate()}</strong></div>`).join('');let cols=days.map(d=>`<div class="week-column" data-date="${iso(d)}" style="height:${slots*px}px">${dayEvents(iso(d)).filter(e=>!e.allDay).map(e=>timeEvent(e,startM,px)).join('')}</div>`).join('');let axis=Array.from({length:slots},(_,i)=>{const m=startM+i*30;return `<div class="time-label" style="height:${px*2}px">${fmtTime(pad(Math.floor(m/60))+':'+pad(m%60))}</div>`}).join('');return `<div class="week-grid"><div class="time-axis">${axis}</div><div><div class="week-days">${heads}</div><div class="week-columns">${cols}</div></div></div>`}
  function timeEvent(e,startM,px){const top=Math.max(0,(mins(e.start)-startM)/30*px), height=Math.max(25,eventDuration(e)/30*px),c=color(e);return `<div class="time-event" data-event="${e.instanceId}" style="top:${top}px;height:${height}px;--primary:${c};background:${c}18"><strong>${esc(e.title)}</strong><small>${fmtTime(e.start)}–${fmtTime(e.end||'')}</small></div>`}
  function dayView(){const ds=iso(cursor),startM=mins(settings.dayStart),endM=Math.max(startM+60,mins(settings.dayEnd)),slots=Math.ceil((endM-startM)/30),px=30;let axis=Array.from({length:slots},(_,i)=>{const m=startM+i*30;return `<div class="time-label" style="height:${px*2}px">${fmtTime(pad(Math.floor(m/60))+':'+pad(m%60))}</div>`}).join('');let ev=dayEvents(ds);return `<div class="day-grid"><div class="time-axis">${axis}</div><div><div class="week-head ${ds===iso(today)?'today':''}">${dayName(cursor,false)}<strong>${cursor.getDate()}</strong></div><div class="day-column" data-date="${ds}" style="height:${slots*px}px">${ev.filter(e=>!e.allDay).map(e=>timeEvent(e,startM,px)).join('')}</div></div></div>`}
  function agendaView(){const start=dayStart(cursor),end=addDays(start,30), groups=[];for(let d=new Date(start);d<end;d=addDays(d,1)){const ev=dayEvents(iso(d));if(ev.length)groups.push(`<section class="agenda-day"><h3>${d.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</h3>${ev.map(e=>`<div class="agenda-event" data-event="${e.instanceId}"><div class="agenda-time">${e.allDay?'All day':fmtTime(e.start)}</div><div class="agenda-bar" style="background:${color(e)}"></div><div><div class="agenda-title">${esc(e.title)}${hasConflict(e)?'<span class="conflict-dot"></span>':''}</div><div class="agenda-meta">${esc([e.location,e.notes].filter(Boolean).join(' · '))}</div></div></div>`).join('')}</section>`)}return `<div class="agenda">${groups.join('')||'<div class="empty-state" style="position:static;transform:none;margin:60px auto">No upcoming events in the next 30 days.</div>'}</div>`}
  function openEvent(id=null,date=selected){editingId=id;const e=id?state.events.find(x=>x.id===id):null;$('#eventMode').textContent=e?'EDIT EVENT':'NEW EVENT';$('#eventDialogTitle').textContent=e?'Edit event':'Create event';$('#eventTitle').value=e?.title||'';$('#eventDate').value=e?.date||date;$('#eventCalendar').innerHTML=state.calendars.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('#eventCalendar').value=e?.calendarId||state.calendars[0].id;$('#eventStart').value=e?.start||'09:00';$('#eventEnd').value=e?.end||'10:00';$('#eventAllDay').checked=!!e?.allDay;$('#eventColor').value=e?.color||'auto';$('#eventRepeat').value=e?.repeat||'none';$('#eventRepeatUntil').value=e?.repeatUntil||'';$('#eventLocation').value=e?.location||'';$('#eventReminder').value=String(e?.reminder??15);$('#eventAttendees').value=e?.attendees||'';$('#eventNotes').value=e?.notes||'';$('#deleteEventBtn').classList.toggle('hidden',!e);toggleAllDay();checkFormConflict();$('#eventDialog').showModal()}
  function readEvent(){return {id:editingId||uid(),title:$('#eventTitle').value.trim(),date:$('#eventDate').value,calendarId:$('#eventCalendar').value,start:$('#eventAllDay').checked?'':$('#eventStart').value,end:$('#eventAllDay').checked?'':$('#eventEnd').value,allDay:$('#eventAllDay').checked,color:$('#eventColor').value,repeat:$('#eventRepeat').value,repeatUntil:$('#eventRepeatUntil').value,location:$('#eventLocation').value.trim(),reminder:Number($('#eventReminder').value),attendees:$('#eventAttendees').value.trim(),notes:$('#eventNotes').value.trim(),exdates:editingId?(state.events.find(e=>e.id===editingId)?.exdates||[]):[]}}
  function toggleAllDay(){const on=$('#eventAllDay').checked;$('#eventStart').disabled=on;$('#eventEnd').disabled=on}
  function checkFormConflict(){const e=readEvent(),notice=$('#conflictNotice');if(!e.date||e.allDay||!e.start){notice.classList.add('hidden');return}const conflict=state.events.some(x=>x.id!==editingId&&x.date===e.date&&!x.allDay&&x.calendarId!==''&&overlap(e,x));notice.textContent=conflict?'This time overlaps another event on the same date. You can still save it.':'No conflict detected for this date/time.';notice.classList.remove('hidden')}
  function deleteEvent(){if(!editingId)return;const e=state.events.find(x=>x.id===editingId);if(!e)return;if(e.repeat&&e.repeat!=='none'){const action=prompt('Type SERIES to delete the whole recurring series, or INSTANCE to remove only this occurrence.','INSTANCE');if(action==='SERIES')state.events=state.events.filter(x=>x.id!==e.id);else if(action==='INSTANCE'){const ds=$('#eventDate').value;e.exdates=[...(e.exdates||[]),ds];save();$('#eventDialog').close();toast('Occurrence removed');}return}else{state.events=state.events.filter(x=>x.id!==editingId);save();$('#eventDialog').close();toast('Event deleted')}}
  function submitEvent(ev){ev.preventDefault();const e=readEvent();if(!e.title||!e.date){toast('Add a title and date');return}if(e.start&&e.end&&mins(e.end)<=mins(e.start)){toast('End time must be after start time');return}if(editingId){const i=state.events.findIndex(x=>x.id===editingId);if(i>=0)state.events[i]=e}else state.events.push(e);save();$('#eventDialog').close();toast(editingId?'Event updated':'Event created')}
  function createCalendar(ev){ev.preventDefault();const name=$('#calendarName').value.trim();if(!name)return;state.calendars.push({id:uid(),name,color:$('#calendarColor').value,description:$('#calendarDescription').value.trim(),visible:true});save();$('#calendarDialog').close();$('#calendarForm').reset();toast('Calendar created')}
  function navigate(delta){if(view==='month')cursor=new Date(cursor.getFullYear(),cursor.getMonth()+delta,1);else if(view==='week')cursor=addDays(cursor,delta*7);else cursor=addDays(cursor,delta);selected=iso(cursor);renderAll()}
  function setView(v){view=v;renderView()}
  function quickDate(kind){let d=dayStart(today);if(kind==='tomorrow')d=addDays(d,1);if(kind==='nextweek')d=addDays(startOfWeek(d),7);$('#eventDate').value=iso(d);if(kind==='allday'){$('#eventAllDay').checked=true;toggleAllDay()}}
  function exportJSON(){download('calm-calendar-backup.json',JSON.stringify({version:1,exportedAt:new Date().toISOString(),state,settings,templates},null,2),'application/json')}
  function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function escapeICS(s=''){return String(s).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}
  function icsDate(e,end=false){const ds=end&&e.end?e.date:e.date,t=end?(e.end||'00:00'):e.start;if(e.allDay)return ds.replaceAll('-','');return `${ds.replaceAll('-','')}T${(t||'00:00').replace(':','')}00`}
  function exportICS(){let lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Calm Personal Calendar//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH'];for(const e of state.events){lines.push('BEGIN:VEVENT',`UID:${e.id}@calm-calendar`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART${e.allDay?';VALUE=DATE':''}:${icsDate(e)}`);if(e.allDay){const n=addDays(parseDate(e.date),1);lines.push(`DTEND;VALUE=DATE:${iso(n).replaceAll('-','')}`)}else lines.push(`DTEND:${icsDate(e,true)}`);lines.push(`SUMMARY:${escapeICS(e.title)}`);if(e.location)lines.push(`LOCATION:${escapeICS(e.location)}`);if(e.notes)lines.push(`DESCRIPTION:${escapeICS(e.notes)}`);if(e.repeat&&e.repeat!=='none')lines.push(`RRULE:${rrule(e)}`);lines.push('END:VEVENT')}lines.push('END:VCALENDAR');download('calm-calendar.ics',lines.join('\r\n')+'\r\n','text/calendar')}
  function rrule(e){const until=e.repeatUntil?`;UNTIL=${e.repeatUntil.replaceAll('-','')}T235959`:'';return ({daily:'FREQ=DAILY',weekdays:'FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR',weekly:'FREQ=WEEKLY',biweekly:'FREQ=WEEKLY;INTERVAL=2',monthly:'FREQ=MONTHLY',yearly:'FREQ=YEARLY'}[e.repeat]||'')+until}
  function importICS(text){const blocks=text.split(/BEGIN:VEVENT/i).slice(1), imported=[];for(const block of blocks){const get=k=>{const re=new RegExp('(?:^|\\n)'+k+'(?:;[^:]*)?:([^\\n\\r]*)','i');const m=block.match(re);return m?m[1].trim():''};const dt=get('DTSTART'),de=get('DTEND'),title=unescapeICS(get('SUMMARY'))||'Imported event';if(!dt)continue;const allDay=!dt.includes('T'),date=allDay?`${dt.slice(0,4)}-${dt.slice(4,6)}-${dt.slice(6,8)}`:`${dt.slice(0,4)}-${dt.slice(4,6)}-${dt.slice(6,8)}`,start=allDay?'':`${dt.slice(9,11)}:${dt.slice(11,13)}`,end=allDay?'':de.includes('T')?`${de.slice(9,11)}:${de.slice(11,13)}`:'';const rr=get('RRULE');imported.push({id:uid(),title,date,start,end,allDay,calendarId:state.calendars[0].id,color:'auto',repeat:parseRR(rr),repeatUntil:rr.match(/UNTIL=(\d{8})/) ? `${rr.match(/UNTIL=(\d{8})/)[1].slice(0,4)}-${rr.match(/UNTIL=(\d{8})/)[1].slice(4,6)}-${rr.match(/UNTIL=(\d{8})/)[1].slice(6,8)}`:'',location:unescapeICS(get('LOCATION')),notes:unescapeICS(get('DESCRIPTION')),reminder:15,exdates:[]})}state.events.push(...imported);save();toast(`${imported.length} event${imported.length===1?'':'s'} imported`)}
  function unescapeICS(s){return s.replace(/\\n/gi,'\n').replace(/\\,/g,',').replace(/\\;/g,';').replace(/\\\\/g,'\\')}
  function parseRR(r){if(!r)return'none';if(r.includes('BYDAY=MO,TU,WE,TH,FR'))return'weekdays';if(r.includes('INTERVAL=2'))return'biweekly';if(r.includes('FREQ=DAILY'))return'daily';if(r.includes('FREQ=WEEKLY'))return'weekly';if(r.includes('FREQ=MONTHLY'))return'monthly';if(r.includes('FREQ=YEARLY'))return'yearly';return'none'}
  function handleImport(file){const r=new FileReader();r.onload=()=>{try{if(file.name.toLowerCase().endsWith('.json')){const data=JSON.parse(r.result);if(data.state){state=data.state;settings=data.settings||settings;templates=data.templates||templates;saveSettings();save();toast('Backup restored')}}else importICS(r.result)}catch(err){console.error(err);toast('Could not import that file')}};r.readAsText(file)}
  function showFreeTime(){const d=$('#freeDate');d.value=selected;$('#freeTimeDialog').showModal();findFree()}
  function findFree(){const ds=$('#freeDate').value||selected,dur=Number($('#freeDuration').value),start=mins($('#freeStart').value),end=mins($('#freeEnd').value);const ev=dayEventsRaw(ds).filter(e=>!e.allDay&&e.start).sort((a,b)=>mins(a.start)-mins(b.start));let slots=[];for(let m=start;m+dur<=end;m+=15){const a={start:`${pad(Math.floor(m/60))}:${pad(m%60)}`,end:`${pad(Math.floor((m+dur)/60))}:${pad((m+dur)%60)}`};if(!ev.some(e=>overlap(a,e)))slots.push(a);if(slots.length>=8)break}$('#freeResults').innerHTML=slots.length?slots.map(s=>`<div class="free-slot" data-free="${s.start}"><strong>${fmtTime(s.start)}–${fmtTime(s.end)}</strong><small>Free for ${dur} minutes</small></div>`).join(''):'<div class="notice">No matching free slot in this window.</div>'}
  function saveTemplate(){const e=readEvent();if(!e.title){toast('Add an event title first');return}templates.push({id:uid(),name:e.title,start:e.start,end:e.end,allDay:e.allDay,color:e.color,repeat:e.repeat,reminder:e.reminder,location:e.location,notes:e.notes});localStorage.setItem(TMP,JSON.stringify(templates));renderTemplates();toast('Template saved')}
  function renderTemplates(){const box=$('#templateList');box.innerHTML=templates.length?templates.map(t=>`<div class="template-item"><span class="cal-dot" style="background:${t.color==='auto'?COLORS[0]:t.color}"></span><div><strong>${esc(t.name)}</strong><small>${t.allDay?'All day':`${fmtTime(t.start)}–${fmtTime(t.end)}`} · ${esc(t.location||'No location')}</small></div><button data-use-template="${t.id}" class="primary">Use</button><button data-delete-template="${t.id}" class="danger">×</button></div>`).join(''):'<div class="notice">Save an event as a reusable template to get started.</div>'}
  function useTemplate(id){const t=templates.find(x=>x.id===id);if(!t)return;openEvent(null,selected);$('#eventTitle').value=t.name;$('#eventStart').value=t.start||'';$('#eventEnd').value=t.end||'';$('#eventAllDay').checked=!!t.allDay;$('#eventColor').value=t.color||'auto';$('#eventRepeat').value=t.repeat||'none';$('#eventReminder').value=String(t.reminder??15);$('#eventLocation').value=t.location||'';$('#eventNotes').value=t.notes||'';toggleAllDay()}
  function monthStats(){const s=visibleEvents(),month=cursor.getMonth(),year=cursor.getFullYear(),ev=s.filter(e=>{const d=dateFrom(e.instanceDate);return d.getMonth()===month&&d.getFullYear()===year});return {count:ev.length,hours:Math.round(ev.reduce((n,e)=>n+eventDuration(e),0)/60),conflicts:ev.filter(hasConflict).length,days:new Set(ev.map(e=>e.instanceDate)).size}}
  function notify(e){if(!settings.notifications||!('Notification'in window)||Notification.permission!=='granted')return;new Notification(e.title,{body:[e.location,e.start?fmtTime(e.start):'All day'].filter(Boolean).join(' · '),tag:e.instanceId})}
  let reminderTimers=[];function scheduleReminders(){reminderTimers.forEach(clearTimeout);reminderTimers=[];if(!settings.notifications||!('Notification'in window)||Notification.permission!=='granted')return;const now=Date.now();for(const e of visibleEvents()){if(e.allDay||!e.start||e.reminder==null)continue;const when=new Date(`${e.instanceDate}T${e.start}:00`).getTime()-e.reminder*60000-now;if(when>0&&when<2147483647)reminderTimers.push(setTimeout(()=>notify(e),when))}}
  function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2200)}
  function bind(){
    $$('.view-btn').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#todayBtn').onclick=()=>{cursor=dayStart(today);selected=iso(today);renderAll()};$('#prevBtn').onclick=()=>navigate(-1);$('#nextBtn').onclick=()=>navigate(1);$('#prevMini').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1);renderAll()};$('#nextMini').onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);renderAll()};$('#newBtn').onclick=()=>openEvent();$('#emptyNewBtn').onclick=()=>openEvent();$('#settingsBtn').onclick=()=>{$('#settingsDialog').showModal();fillSettings()};$('#addCalendarBtn').onclick=()=>$('#calendarDialog').showModal();$('#freeTimeBtn').onclick=showFreeTime;$('#templatesBtn').onclick=()=>{$('#templatesDialog').showModal();renderTemplates()};$('#exportBtn').onclick=exportICS;$('#importBtn').onclick=()=>$('#fileInput').click();$('#printBtn').onclick=()=>window.print();$('#fileInput').onchange=e=>{if(e.target.files[0])handleImport(e.target.files[0]);e.target.value=''};$('#searchInput').oninput=e=>{search=e.target.value;renderView()};$('#quickFilter').onchange=renderView;
    $('#eventForm').onsubmit=submitEvent;$('#deleteEventBtn').onclick=deleteEvent;$('#eventAllDay').onchange=toggleAllDay;['eventDate','eventStart','eventEnd','eventCalendar'].forEach(id=>$('#'+id).addEventListener('input',checkFormConflict));$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('[data-quick]').forEach(b=>b.onclick=()=>quickDate(b.dataset.quick));$('#calendarForm').onsubmit=createCalendar;
    $('#settingsForm').onsubmit=e=>{e.preventDefault();settings.weekStarts=Number($('#weekStarts').value);settings.timeFormat=$('#timeFormat').value;settings.dayStart=$('#dayStart').value;settings.dayEnd=$('#dayEnd').value;settings.slotMinutes=Number($('#slotMinutes').value);settings.theme=$('#theme').value;settings.notifications=$('#notifications').checked;if(settings.notifications&&'Notification'in window&&Notification.permission==='default')Notification.requestPermission().then(()=>saveSettings());else saveSettings();$('#settingsDialog').close();toast('Settings saved')};$('#resetBtn').onclick=()=>{if(confirm('Delete all calendars and events from this browser?')){state=defaultState();templates=[];localStorage.removeItem(TMP);save();toast('Calendar reset')}};
    $('#freeDate').oninput=findFree;$('#freeDuration').onchange=findFree;$('#freeStart').oninput=findFree;$('#freeEnd').oninput=findFree;$('#saveTemplateBtn').onclick=saveTemplate;
    $('#calendarView').addEventListener('click',e=>{const eventEl=e.target.closest('[data-event]');if(eventEl){const inst=visibleEvents().find(x=>x.instanceId===eventEl.dataset.event);if(inst){selected=inst.instanceDate;openEvent(inst.id,inst.instanceDate)}return}const more=e.target.closest('.more-events');if(more){selected=more.dataset.date;cursor=parseDate(selected);setView('agenda');return}const cell=e.target.closest('[data-date]');if(cell&&!e.target.closest('.time-event')){selected=cell.dataset.date;cursor=parseDate(selected);if(view==='month')openEvent(null,selected)}});
    $('#calendarView').addEventListener('dblclick',e=>{const col=e.target.closest('[data-date]');if(col&&!e.target.closest('[data-event]'))openEvent(null,col.dataset.date)});
    $('#miniCalendar').addEventListener('click',e=>{const b=e.target.closest('[data-mini-date]');if(!b)return;selected=b.dataset.miniDate;cursor=parseDate(selected);renderAll()});$('#calendarList').addEventListener('change',e=>{const id=e.target.dataset.calVis;if(id){cal(id).visible=e.target.checked;save()}});
    $('#freeResults').addEventListener('click',e=>{const b=e.target.closest('[data-free]');if(!b)return;openEvent(null,$('#freeDate').value);$('#eventStart').value=b.dataset.free;$('#eventEnd').value=`${pad(Math.floor((mins(b.dataset.free)+Number($('#freeDuration').value))/60))}:${pad((mins(b.dataset.free)+Number($('#freeDuration').value))%60)}`;checkFormConflict()});$('#templateList').addEventListener('click',e=>{const u=e.target.closest('[data-use-template]'),d=e.target.closest('[data-delete-template]');if(u)useTemplate(u.dataset.useTemplate);if(d){templates=templates.filter(t=>t.id!==d.dataset.deleteTemplate);localStorage.setItem(TMP,JSON.stringify(templates));renderTemplates()}});
    document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('dialog[open]').forEach(d=>d.close());if(e.key==='/'&&!/input|textarea|select/i.test(document.activeElement.tagName)){e.preventDefault();$('#searchInput').focus()}if((e.metaKey||e.ctrlKey)&&e.key==='n'){e.preventDefault();openEvent()}if(e.key.toLowerCase()==='m'&&!e.metaKey&&!e.ctrlKey)setView('month');if(e.key.toLowerCase()==='w'&&!e.metaKey&&!e.ctrlKey)setView('week');if(e.key.toLowerCase()==='d'&&!e.metaKey&&!e.ctrlKey)setView('day');if(e.key.toLowerCase()==='a'&&!e.metaKey&&!e.ctrlKey)setView('agenda')});
    window.addEventListener('online',()=>toast('Back online'));window.addEventListener('offline',()=>toast('Offline — your local calendar still works'));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn);
  }
  function fillSettings(){$('#weekStarts').value=settings.weekStarts;$('#timeFormat').value=settings.timeFormat;$('#dayStart').value=settings.dayStart;$('#dayEnd').value=settings.dayEnd;$('#slotMinutes').value=settings.slotMinutes;$('#theme').value=settings.theme;$('#notifications').checked=settings.notifications}
  bind();renderAll();
})();
